{"metadata":{"roleHeading":"Class","title":"TMPrePurchaseViewController","navigatorTitle":[{"text":"TMPrePurchaseViewController","kind":"identifier"}],"modules":[{"name":"TicketmasterPrePurchase"}],"externalID":"c:@M@TicketmasterPrePurchase@objc(cs)TMPrePurchaseViewController","role":"symbol","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TMPrePurchaseViewController","kind":"identifier"}]},"abstract":[{"text":"Class used to display UI flow for discovering attractions and venues leading up to purchase flow.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMPrePurchaseViewController"}]}],"kind":"declarations"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(cs)UIViewController"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)ASWebAuthenticationPresentationContextProviding","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)NSCoding","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)NSObject","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)SFSafariViewControllerDelegate","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/s7CVarArgP","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/s8CopyableP","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/s28CustomDebugStringConvertibleP","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/s23CustomStringConvertibleP","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/SQ","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/SH","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/@M@TicketmasterFoundation@objc(pl)UALWebViewMessageHandlerDelegate","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/22TicketmasterFoundation32UFCWebViewMessageHandlerDelegateP","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)UIAppearanceContainer","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)UIContentContainer","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)UIFocusEnvironment","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)UIStateRestoring","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/5UIKit23UITraitChangeObservableP","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)UITraitEnvironment","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)UIUserActivityRestoring","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)WKNavigationDelegate","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)WKScriptMessageHandler","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)WKUIDelegate"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller"]}],"topicSections":[{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/init(initialPage:marketDomain:marketLocation:queryParameters:enclosingEnvironment:allowJavaScriptToBringUpKeyboard:internalTestingKeys:customFont:customBoldFont:incomingURL:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/analyticsDelegate","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/locationDelegate","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/navigationDelegate","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/preferredStatusBarStyle","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/queryParameters"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/backButtonAction()","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/changeLocation(coordinate:)","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/communicateLocationFetchError()","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/didMove(toParent:)","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/handleAttractionResponse(response:)","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/imageForCategory(url:)","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/runWhenNotShowingLoadingView(_:)","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/viewDidDisappear(_:)","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/viewDidLoad()","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/viewWillAppear(_:)","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/viewWillDisappear(_:)"],"generated":true,"title":"Instance Methods"},{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/attractionDetailsViewController(attractionIdentifier:marketDomain:enclosingEnvironment:customFont:customBoldFont:)","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/venueDetailsViewController(venueIdentifier:marketDomain:enclosingEnvironment:customFont:customBoldFont:)"],"anchor":"Type-Methods","generated":true,"title":"Type Methods"},{"title":"Enumerations","generated":true,"anchor":"Enumerations","identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/EnclosingEnvironment","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/FavoriteType","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/PrePurchasePage"]},{"anchor":"Default-Implementations","title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/SFSafariViewControllerDelegate-Implementations","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/UALWebViewMessageHandlerDelegate-Implementations","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/UFCWebViewMessageHandlerDelegate-Implementations","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/WKNavigationDelegate-Implementations","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/WKScriptMessageHandler-Implementations","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/WKUIDelegate-Implementations"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase"]]},"references":{"doc://com.ticketmaster.TicketmasterPrePurchase/s7CVarArgP":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/SFSafariViewControllerDelegate-Implementations":{"type":"topic","title":"SFSafariViewControllerDelegate Implementations","role":"collectionGroup","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/sfsafariviewcontrollerdelegate-implementations","abstract":[],"kind":"article","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/SFSafariViewControllerDelegate-Implementations"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase":{"title":"TicketmasterPrePurchase","url":"\/documentation\/ticketmasterprepurchase","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","abstract":[],"role":"collection","kind":"symbol"},"doc://com.ticketmaster.TicketmasterPrePurchase/objc(cs)UIViewController":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(cs)UIViewController","type":"unresolvable","title":"UIViewController"},"doc://com.ticketmaster.TicketmasterPrePurchase/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://com.ticketmaster.TicketmasterPrePurchase/objc(pl)NSObject":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.ticketmaster.TicketmasterPrePurchase/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/analyticsDelegate":{"title":"analyticsDelegate","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"analyticsDelegate"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:23TicketmasterPrePurchase05TMPreC17AnalyticsDelegateP","text":"TMPrePurchaseAnalyticsDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/analyticsdelegate","abstract":[{"type":"text","text":"A delegate to call analytics methods on (optional)"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/analyticsDelegate","type":"topic"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/PrePurchasePage":{"role":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/prepurchasepage","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/PrePurchasePage","navigatorTitle":[{"text":"PrePurchasePage","kind":"identifier"}],"type":"topic","abstract":[{"text":"An enum that represents the type of the Discovery page","type":"text"}],"title":"TMPrePurchaseViewController.PrePurchasePage","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PrePurchasePage","kind":"identifier"}],"kind":"symbol"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/imageForCategory(url:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"imageForCategory","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"title":"imageForCategory(url:)","role":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/imageforcategory(url:)","abstract":[{"type":"text","text":"Return a header image for the supplied URL"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/imageForCategory(url:)"},"doc://com.ticketmaster.TicketmasterPrePurchase/objc(pl)SFSafariViewControllerDelegate":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)SFSafariViewControllerDelegate","type":"unresolvable","title":"SFSafariViewControllerDelegate"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/FavoriteType":{"kind":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/favoritetype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"FavoriteType","kind":"identifier"}],"title":"TMPrePurchaseViewController.FavoriteType","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/FavoriteType","navigatorTitle":[{"kind":"identifier","text":"FavoriteType"}]},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController":{"kind":"symbol","navigatorTitle":[{"text":"TMPrePurchaseViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"Class used to display UI flow for discovering attractions and venues leading up to purchase flow."}],"title":"TMPrePurchaseViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMPrePurchaseViewController"}],"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController","type":"topic","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/communicateLocationFetchError()":{"navigatorTitle":[{"text":"communicateLocationFetchError","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"communicateLocationFetchError"},{"kind":"text","text":"()"}],"title":"communicateLocationFetchError()","role":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/communicatelocationfetcherror()","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/communicateLocationFetchError()"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/preferredStatusBarStyle":{"title":"preferredStatusBarStyle","role":"symbol","navigatorTitle":[{"text":"preferredStatusBarStyle","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredStatusBarStyle"},{"kind":"text","text":": "},{"text":"UIStatusBarStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIStatusBarStyle"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/preferredstatusbarstyle","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/preferredStatusBarStyle"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/locationDelegate":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationDelegate"},{"kind":"text","text":": "},{"text":"TMPrePurchaseLocationDelegate","preciseIdentifier":"s:23TicketmasterPrePurchase05TMPreC16LocationDelegateP","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"locationDelegate","role":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/locationdelegate","abstract":[{"type":"text","text":"A delegate to call location methods on"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/locationDelegate"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/handleAttractionResponse(response:)":{"title":"handleAttractionResponse(response:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"handleAttractionResponse","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"response"},{"kind":"text","text":": "},{"preciseIdentifier":"s:22TicketmasterFoundation14NetworkServiceC","kind":"typeIdentifier","text":"NetworkService"},{"kind":"text","text":"."},{"preciseIdentifier":"s:22TicketmasterFoundation14NetworkServiceC11APIResponseO","text":"APIResponse","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:24TicketmasterDiscoveryAPI0B10AttractionV","text":"DiscoveryAttraction"},{"text":">)","kind":"text"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/handleattractionresponse(response:)","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/handleAttractionResponse(response:)"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/viewDidDisappear(_:)":{"navigatorTitle":[{"kind":"identifier","text":"viewDidDisappear:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/viewdiddisappear(_:)","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/viewDidDisappear(_:)","type":"topic","abstract":[],"kind":"symbol","title":"viewDidDisappear(_:)","role":"symbol"},"doc://com.ticketmaster.TicketmasterPrePurchase/objc(pl)NSCoding":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/didMove(toParent:)":{"navigatorTitle":[{"kind":"identifier","text":"didMoveToParentViewController:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"didMove","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"toParent"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":"?)"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/didmove(toparent:)","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/didMove(toParent:)","type":"topic","abstract":[],"kind":"symbol","title":"didMove(toParent:)","role":"symbol"},"doc://com.ticketmaster.TicketmasterPrePurchase/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/EnclosingEnvironment":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EnclosingEnvironment","kind":"identifier"}],"role":"symbol","title":"TMPrePurchaseViewController.EnclosingEnvironment","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/EnclosingEnvironment","navigatorTitle":[{"text":"EnclosingEnvironment","kind":"identifier"}],"abstract":[{"text":"The environment that the ","type":"text"},{"type":"codeVoice","code":"TMPrePurchaseViewController"},{"type":"text","text":" is expected to be displayed in."}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/enclosingenvironment","type":"topic"},"doc://com.ticketmaster.TicketmasterPrePurchase/SH":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterPrePurchase/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterPrePurchase/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/WKUIDelegate-Implementations":{"title":"WKUIDelegate Implementations","role":"collectionGroup","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/wkuidelegate-implementations","abstract":[],"kind":"article","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/WKUIDelegate-Implementations","type":"topic"},"doc://com.ticketmaster.TicketmasterPrePurchase/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/backButtonAction()":{"title":"backButtonAction()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"backButtonAction","kind":"identifier"},{"kind":"text","text":"()"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/backbuttonaction()","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/backButtonAction()","type":"topic"},"doc://com.ticketmaster.TicketmasterPrePurchase/@M@TicketmasterFoundation@objc(pl)UALWebViewMessageHandlerDelegate":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/@M@TicketmasterFoundation@objc(pl)UALWebViewMessageHandlerDelegate","title":"UALWebViewMessageHandlerDelegate","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterPrePurchase/objc(pl)UIContentContainer":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/WKScriptMessageHandler-Implementations":{"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/wkscriptmessagehandler-implementations","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/WKScriptMessageHandler-Implementations","type":"topic","abstract":[],"kind":"article","title":"WKScriptMessageHandler Implementations","role":"collectionGroup"},"doc://com.ticketmaster.TicketmasterPrePurchase/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/viewWillDisappear(_:)":{"abstract":[],"navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewWillDisappear","kind":"identifier"},{"kind":"text","text":"("},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"viewWillDisappear(_:)","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/viewWillDisappear(_:)","role":"symbol","kind":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/viewwilldisappear(_:)","type":"topic"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/UALWebViewMessageHandlerDelegate-Implementations":{"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/ualwebviewmessagehandlerdelegate-implementations","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/UALWebViewMessageHandlerDelegate-Implementations","kind":"article","abstract":[],"role":"collectionGroup","title":"UALWebViewMessageHandlerDelegate Implementations","type":"topic"},"doc://com.ticketmaster.TicketmasterPrePurchase/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/SQ"},"doc://com.ticketmaster.TicketmasterPrePurchase/s8CopyableP":{"title":"Swift.Copyable","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/s8CopyableP"},"doc://com.ticketmaster.TicketmasterPrePurchase/objc(pl)WKUIDelegate":{"title":"WKUIDelegate","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)WKUIDelegate"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/navigationDelegate":{"kind":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/navigationdelegate","abstract":[{"type":"text","text":"A delegate to call required methods on"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/navigationDelegate","title":"navigationDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"navigationDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:23TicketmasterPrePurchase05TMPreC18NavigationDelegateP","kind":"typeIdentifier","text":"TMPrePurchaseNavigationDelegate"},{"kind":"text","text":"?"}]},"doc://com.ticketmaster.TicketmasterPrePurchase/22TicketmasterFoundation32UFCWebViewMessageHandlerDelegateP":{"title":"TicketmasterFoundation.UFCWebViewMessageHandlerDelegate","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/22TicketmasterFoundation32UFCWebViewMessageHandlerDelegateP"},"doc://com.ticketmaster.TicketmasterPrePurchase/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)UIFocusEnvironment"},"doc://com.ticketmaster.TicketmasterPrePurchase/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/s28CustomDebugStringConvertibleP"},"doc://com.ticketmaster.TicketmasterPrePurchase/objc(pl)ASWebAuthenticationPresentationContextProviding":{"title":"AuthenticationServices.ASWebAuthenticationPresentationContextProviding","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)ASWebAuthenticationPresentationContextProviding"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/venueDetailsViewController(venueIdentifier:marketDomain:enclosingEnvironment:customFont:customBoldFont:)":{"kind":"symbol","role":"symbol","type":"topic","title":"venueDetailsViewController(venueIdentifier:marketDomain:enclosingEnvironment:customFont:customBoldFont:)","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/venueDetailsViewController(venueIdentifier:marketDomain:enclosingEnvironment:customFont:customBoldFont:)","abstract":[{"type":"text","text":"Convenience function for creating a Venue Details Page for a specific identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"venueDetailsViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"venueIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"marketDomain"},{"text":": ","kind":"text"},{"text":"MarketDomain","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterFoundation@E@MarketDomain"},{"text":", ","kind":"text"},{"text":"enclosingEnvironment","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:23TicketmasterPrePurchase05TMPreC14ViewControllerC20EnclosingEnvironmentO","text":"EnclosingEnvironment","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"customFont","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"customBoldFont"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIFont","kind":"typeIdentifier","text":"UIFont"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"TMPrePurchaseViewController","preciseIdentifier":"c:@M@TicketmasterPrePurchase@objc(cs)TMPrePurchaseViewController"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/venuedetailsviewcontroller(venueidentifier:marketdomain:enclosingenvironment:customfont:customboldfont:)"},"doc://com.ticketmaster.TicketmasterPrePurchase/objc(pl)WKNavigationDelegate":{"title":"WKNavigationDelegate","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)WKNavigationDelegate"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/runWhenNotShowingLoadingView(_:)":{"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"runWhenNotShowingLoadingView"},{"text":"((() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":"))"}],"kind":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/runwhennotshowingloadingview(_:)","title":"runWhenNotShowingLoadingView(_:)","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/runWhenNotShowingLoadingView(_:)","role":"symbol","type":"topic"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/UFCWebViewMessageHandlerDelegate-Implementations":{"role":"collectionGroup","type":"topic","title":"UFCWebViewMessageHandlerDelegate Implementations","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/UFCWebViewMessageHandlerDelegate-Implementations","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/ufcwebviewmessagehandlerdelegate-implementations","kind":"article","abstract":[]},"doc://com.ticketmaster.TicketmasterPrePurchase/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/viewWillAppear(_:)":{"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/viewWillAppear(_:)","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/viewwillappear(_:)","title":"viewWillAppear(_:)","navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewWillAppear","kind":"identifier"},{"kind":"text","text":"("},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"kind":"symbol"},"doc://com.ticketmaster.TicketmasterPrePurchase/objc(pl)NSExtensionRequestHandling":{"title":"Foundation.NSExtensionRequestHandling","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)NSExtensionRequestHandling"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/queryParameters":{"type":"topic","title":"queryParameters","abstract":[],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/queryparameters","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/queryParameters","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"queryParameters","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}]},"doc://com.ticketmaster.TicketmasterPrePurchase/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)UIAppearanceContainer"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/init(initialPage:marketDomain:marketLocation:queryParameters:enclosingEnvironment:allowJavaScriptToBringUpKeyboard:internalTestingKeys:customFont:customBoldFont:incomingURL:)":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/init(initialPage:marketDomain:marketLocation:queryParameters:enclosingEnvironment:allowJavaScriptToBringUpKeyboard:internalTestingKeys:customFont:customBoldFont:incomingURL:)","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/init(initialpage:marketdomain:marketlocation:queryparameters:enclosingenvironment:allowjavascripttobringupkeyboard:internaltestingkeys:customfont:customboldfont:incomingurl:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"initialPage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PrePurchasePage","preciseIdentifier":"s:23TicketmasterPrePurchase05TMPreC14ViewControllerC0bC4PageO"},{"text":", ","kind":"text"},{"text":"marketDomain","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MarketDomain","preciseIdentifier":"c:@M@TicketmasterFoundation@E@MarketDomain"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"marketLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)MarketLocation","text":"MarketLocation"},{"text":"?, ","kind":"text"},{"text":"queryParameters","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"enclosingEnvironment"},{"kind":"text","text":": "},{"text":"EnclosingEnvironment","kind":"typeIdentifier","preciseIdentifier":"s:23TicketmasterPrePurchase05TMPreC14ViewControllerC20EnclosingEnvironmentO"},{"text":", ","kind":"text"},{"text":"allowJavaScriptToBringUpKeyboard","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"internalTestingKeys"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"text":"customFont","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"customBoldFont","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":"?, "},{"text":"incomingURL","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?)","kind":"text"}],"title":"init(initialPage:marketDomain:marketLocation:queryParameters:enclosingEnvironment:allowJavaScriptToBringUpKeyboard:internalTestingKeys:customFont:customBoldFont:incomingURL:)","abstract":[{"type":"text","text":"The initializer for creating a PrePurchase page."}]},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/changeLocation(coordinate:)":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/changeLocation(coordinate:)","navigatorTitle":[{"text":"changeLocationWithCoordinate:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/changelocation(coordinate:)","type":"topic","abstract":[],"title":"changeLocation(coordinate:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"changeLocation"},{"kind":"text","text":"("},{"text":"coordinate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/WKNavigationDelegate-Implementations":{"kind":"article","type":"topic","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/wknavigationdelegate-implementations","title":"WKNavigationDelegate Implementations","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/WKNavigationDelegate-Implementations"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/attractionDetailsViewController(attractionIdentifier:marketDomain:enclosingEnvironment:customFont:customBoldFont:)":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"attractionDetailsViewController"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"attractionIdentifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"marketDomain","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TicketmasterFoundation@E@MarketDomain","kind":"typeIdentifier","text":"MarketDomain"},{"kind":"text","text":", "},{"kind":"externalParam","text":"enclosingEnvironment"},{"text":": ","kind":"text"},{"text":"EnclosingEnvironment","kind":"typeIdentifier","preciseIdentifier":"s:23TicketmasterPrePurchase05TMPreC14ViewControllerC20EnclosingEnvironmentO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"customFont"},{"text":": ","kind":"text"},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"},{"text":"?, ","kind":"text"},{"text":"customBoldFont","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"TMPrePurchaseViewController","preciseIdentifier":"c:@M@TicketmasterPrePurchase@objc(cs)TMPrePurchaseViewController"}],"abstract":[{"type":"text","text":"Convenience function for creating an Attraction Details Page for a specific identifier"}],"type":"topic","title":"attractionDetailsViewController(attractionIdentifier:marketDomain:enclosingEnvironment:customFont:customBoldFont:)","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/attractiondetailsviewcontroller(attractionidentifier:marketdomain:enclosingenvironment:customfont:customboldfont:)","role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/attractionDetailsViewController(attractionIdentifier:marketDomain:enclosingEnvironment:customFont:customBoldFont:)"},"doc://com.ticketmaster.TicketmasterPrePurchase/objc(pl)WKScriptMessageHandler":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)WKScriptMessageHandler","title":"WKScriptMessageHandler"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/viewDidLoad()":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/viewDidLoad()","title":"viewDidLoad()","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/viewdidload()","abstract":[],"navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"TMPrePurchaseViewController"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"TMPrePurchaseViewController","kind":"identifier"}],"op":"replace"},{"value":[{"text":"TMPrePurchaseViewController","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/preferredStatusBarStyle"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/changeLocation(coordinate:)","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/communicateLocationFetchError()","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/didMove(toParent:)","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/viewDidDisappear(_:)","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/viewDidLoad()","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/viewWillAppear(_:)","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/viewWillDisappear(_:)"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/SFSafariViewControllerDelegate-Implementations","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/UALWebViewMessageHandlerDelegate-Implementations","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/WKNavigationDelegate-Implementations","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/WKScriptMessageHandler-Implementations","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/WKUIDelegate-Implementations"],"anchor":"Default-Implementations"}],"op":"replace"},{"value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(cs)UIViewController"]},{"title":"Conforms To","identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)SFSafariViewControllerDelegate","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/@M@TicketmasterFoundation@objc(pl)UALWebViewMessageHandlerDelegate","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)WKNavigationDelegate","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)WKScriptMessageHandler","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)WKUIDelegate"],"kind":"relationships","type":"conformsTo"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPrePurchaseViewController"},{"kind":"text","text":" : "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/title","value":"TMPrePurchaseViewController"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/fragments","value":[{"text":"TMPrePurchaseViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/navigatorTitle","value":[{"kind":"identifier","text":"TMPrePurchaseViewController"}]},{"value":"communicateLocationFetchError","op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1communicateLocationFetchError()\/title"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1communicateLocationFetchError()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"communicateLocationFetchError"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1preferredStatusBarStyle\/title","op":"replace","value":"preferredStatusBarStyle"},{"op":"replace","value":[{"text":"preferredStatusBarStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1preferredStatusBarStyle\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1viewDidDisappear(_:)\/title","value":"viewDidDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1viewDidDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidDisappear:"}]},{"op":"replace","value":"didMoveToParentViewController:","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1didMove(toParent:)\/title"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1didMove(toParent:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didMoveToParentViewController:"}],"op":"replace"},{"value":"viewWillDisappear:","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1viewWillDisappear(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillDisappear:"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1viewWillDisappear(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewWillAppear:"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1viewWillAppear(_:)\/fragments","op":"replace"},{"op":"replace","value":"changeLocationWithCoordinate:","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1changeLocation(coordinate:)\/title"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1changeLocation(coordinate:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"changeLocationWithCoordinate:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"viewDidLoad","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1viewDidLoad()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}