{"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TMPrePurchase","kind":"identifier"}],"modules":[{"name":"TicketmasterPrePurchase"}],"title":"TMPrePurchase","externalID":"c:@M@TicketmasterPrePurchase@objc(cs)TMPrePurchase","role":"symbol","navigatorTitle":[{"text":"TMPrePurchase","kind":"identifier"}],"symbolKind":"class"},"kind":"symbol","sections":[],"abstract":[{"text":"A class that stores the global configuration for the TicketmasterPrePurchase SDK.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchase"]},{"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchase"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/apiKey","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/brandColor","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/domain","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/environment-swift.property","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/marketDomain","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/sdkBuildInfo","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/useDebugAnalytics","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/version"]},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/configure(apiKey:region:completion:)","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/configure(tmxSettings:completion:)"],"generated":true},{"title":"Type Properties","anchor":"Type-Properties","generated":true,"identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/shared"]},{"title":"Enumerations","generated":true,"anchor":"Enumerations","identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/Environment-swift.enum"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TMPrePurchase","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)NSObject","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/s7CVarArgP","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/s28CustomDebugStringConvertibleP","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/s23CustomStringConvertibleP","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/SQ","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/SH"]}],"references":{"doc://com.ticketmaster.TicketmasterPrePurchase/SH":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.ticketmaster.TicketmasterPrePurchase/objc(pl)NSObject":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchase/domain":{"type":"topic","abstract":[{"type":"text","text":"Note that .US also includes .CA markets"}],"role":"symbol","title":"domain","kind":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchase\/domain","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/domain","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"domain","kind":"identifier"},{"kind":"text","text":": "},{"text":"MarketDomain","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterFoundation@E@MarketDomain"}],"deprecated":true},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchase/shared":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TicketmasterPrePurchase@objc(cs)TMPrePurchase","text":"TMPrePurchase","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/shared","type":"topic","kind":"symbol","title":"shared","role":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchase\/shared","abstract":[{"text":"Shared instance for TicketmasterPrePurchase","type":"text"}]},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchase/configure(apiKey:region:completion:)":{"type":"topic","abstract":[{"text":"configure Ticketmaster PrePurchase with your API key","type":"text"}],"role":"symbol","title":"configure(apiKey:region:completion:)","kind":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchase\/configure(apikey:region:completion:)","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/configure(apiKey:region:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"apiKey","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"region","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterAuthentication@objc(cs)TMAuthentication","text":"TMAuthentication"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:26TicketmasterAuthentication16TMAuthenticationC19TMXDeploymentRegionO","text":"TMXDeploymentRegion"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"didSetMarketDomain","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]},"doc://com.ticketmaster.TicketmasterPrePurchase/SQ":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchase/Environment-swift.enum":{"title":"TMPrePurchase.Environment","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Environment","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/Environment-swift.enum","kind":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchase\/environment-swift.enum","role":"symbol","abstract":[],"navigatorTitle":[{"text":"Environment","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchase/brandColor":{"type":"topic","abstract":[{"type":"text","text":"A color that can be set to customize certain parts of the UI."}],"role":"symbol","title":"brandColor","kind":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchase\/brandcolor","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/brandColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"brandColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}]},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase":{"kind":"symbol","abstract":[],"title":"TicketmasterPrePurchase","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","role":"collection","url":"\/documentation\/ticketmasterprepurchase"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchase/useDebugAnalytics":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/useDebugAnalytics","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"useDebugAnalytics","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchase\/usedebuganalytics","title":"useDebugAnalytics","type":"topic","kind":"symbol","abstract":[{"text":"A flag that indicates whether the PrePurchase SDK should put analytics into a debug bucket","type":"text"}],"role":"symbol"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchase/environment-swift.property":{"type":"topic","abstract":[{"text":"The Ticketmaster Host Environment marching the API key provided","type":"text"}],"role":"symbol","title":"environment","kind":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchase\/environment-swift.property","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/environment-swift.property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"environment","kind":"identifier"},{"kind":"text","text":": "},{"text":"Environment","preciseIdentifier":"s:23TicketmasterPrePurchase05TMPreC0C11EnvironmentO","kind":"typeIdentifier"}]},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchase":{"title":"TMPrePurchase","kind":"symbol","abstract":[{"text":"A class that stores the global configuration for the TicketmasterPrePurchase SDK.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchase","navigatorTitle":[{"text":"TMPrePurchase","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMPrePurchase"}]},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchase/version":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/version","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"version","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchase\/version","title":"version","type":"topic","kind":"symbol","abstract":[{"text":"build version of TicketmasterPrePurchase","type":"text"}],"role":"symbol"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchase/apiKey":{"type":"topic","abstract":[{"text":"Your Discovery API key","type":"text"}],"role":"symbol","title":"apiKey","kind":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchase\/apikey","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/apiKey","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apiKey","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"deprecated":true},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchase/marketDomain":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/marketDomain","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"marketDomain","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MarketDomain","preciseIdentifier":"c:@M@TicketmasterFoundation@E@MarketDomain"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchase\/marketdomain","title":"marketDomain","kind":"symbol","abstract":[{"text":"which ","type":"text"},{"code":"MarketDomain","type":"codeVoice"},{"text":" to discovery Events in","type":"text"}],"type":"topic","role":"symbol"},"doc://com.ticketmaster.TicketmasterPrePurchase/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(cs)NSObject"},"doc://com.ticketmaster.TicketmasterPrePurchase/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/s23CustomStringConvertibleP"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchase/init":{"type":"topic","abstract":[],"role":"symbol","title":"init","kind":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchase\/init","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterPrePurchase/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchase/configure(tmxSettings:completion:)":{"type":"topic","abstract":[{"text":"configure Ticketmaster PrePurchase with your API key","type":"text"}],"role":"symbol","title":"configure(tmxSettings:completion:)","kind":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchase\/configure(tmxsettings:completion:)","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/configure(tmxSettings:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configure"},{"text":"(","kind":"text"},{"text":"tmxSettings","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TMAuthentication","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterAuthentication@objc(cs)TMAuthentication"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:26TicketmasterAuthentication16TMAuthenticationC11TMXSettingsV","text":"TMXSettings"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"didSetMarketDomain"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchase/sdkBuildInfo":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/sdkBuildInfo","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdkBuildInfo"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchase\/sdkbuildinfo","title":"sdkBuildInfo","kind":"symbol","abstract":[],"type":"topic","role":"symbol"},"doc://com.ticketmaster.TicketmasterPrePurchase/s7CVarArgP":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"TMPrePurchase","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","value":[{"kind":"identifier","text":"TMPrePurchase"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TMPrePurchase"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/init"]}]},{"op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/objc(cs)NSObject"],"kind":"relationships"}],"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMPrePurchase","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}]}},{"op":"replace","value":"TMPrePurchase","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchase\/title"},{"value":[{"text":"TMPrePurchase","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchase\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchase\/navigatorTitle","value":[{"text":"TMPrePurchase","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}