{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebAnalyticsDelegate\/purchaseNavigationController(_:webPageDidErrorFor:errorString:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"abstract":[{"text":"Indicates an error occured while interacting with a page, usually surfaced by JavaScript with an error string","type":"text"}],"metadata":{"symbolKind":"method","role":"symbol","title":"purchaseNavigationController(_:webPageDidErrorFor:errorString:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"purchaseNavigationController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterPurchase@objc(cs)TMPurchaseNavigationController","text":"TMPurchaseNavigationController"},{"kind":"text","text":", "},{"text":"webPageDidErrorFor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"errorString","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"externalID":"s:20TicketmasterPurchase30TMPurchaseWebAnalyticsDelegateP28purchaseNavigationController_18webPageDidErrorFor11errorStringyAA0chI0C_10Foundation3URLVSStF","required":true,"modules":[{"name":"TicketmasterPurchase"}],"roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"purchaseNavigationController"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"purchaseNavigationController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController","text":"TMPurchaseNavigationController","preciseIdentifier":"c:@M@TicketmasterPurchase@objc(cs)TMPurchaseNavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"webPageDidErrorFor"},{"text":" ","kind":"text"},{"text":"url","kind":"internalParam"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"errorString","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebAnalyticsDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterpurchase\/tmpurchasewebanalyticsdelegate\/purchasenavigationcontroller(_:webpagediderrorfor:errorstring:)"]}],"references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebAnalyticsDelegate/purchaseNavigationController(_:webPageDidErrorFor:errorString:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"purchaseNavigationController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TMPurchaseNavigationController","preciseIdentifier":"c:@M@TicketmasterPurchase@objc(cs)TMPurchaseNavigationController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"webPageDidErrorFor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":", ","kind":"text"},{"text":"errorString","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"required":true,"title":"purchaseNavigationController(_:webPageDidErrorFor:errorString:)","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebAnalyticsDelegate\/purchaseNavigationController(_:webPageDidErrorFor:errorString:)","url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebanalyticsdelegate\/purchasenavigationcontroller(_:webpagediderrorfor:errorstring:)","kind":"symbol","abstract":[{"type":"text","text":"Indicates an error occured while interacting with a page, usually surfaced by JavaScript with an error string"}],"type":"topic","role":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController":{"abstract":[{"type":"text","text":"A navigation controller (view controller) that allows users to select and purchase tickets to a Ticketmaster Event."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMPurchaseNavigationController"}],"url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller","title":"TMPurchaseNavigationController","navigatorTitle":[{"kind":"identifier","text":"TMPurchaseNavigationController"}]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"role":"collection","type":"topic","title":"TicketmasterPurchase","kind":"symbol","url":"\/documentation\/ticketmasterpurchase","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","abstract":[]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebAnalyticsDelegate":{"role":"symbol","kind":"symbol","title":"TMPurchaseWebAnalyticsDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMPurchaseWebAnalyticsDelegate","kind":"identifier"}],"type":"topic","abstract":[{"text":"The detailed anayltics delegate of a ","type":"text"},{"type":"codeVoice","code":"TMPurchaseNavigationController"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebAnalyticsDelegate","navigatorTitle":[{"text":"TMPurchaseWebAnalyticsDelegate","kind":"identifier"}],"url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebanalyticsdelegate"}},"variantOverrides":[{"patch":[{"value":"TMPurchaseNavigationController","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"TMPurchaseNavigationController"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/navigatorTitle","value":[{"text":"TMPurchaseNavigationController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}