{"metadata":{"modules":[{"name":"TicketmasterDiscoveryAPI"}],"roleHeading":"Instance Property","role":"symbol","platforms":[],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"externalID":"s:24TicketmasterDiscoveryAPI011TMDiscoveryC0C6apiKeySSSgvp","title":"apiKey"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"style":"important","name":"Important","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Deprecated use method configure(apiKey:region:completion:) instead"}]}]}]}],"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/apiKey","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI"]]},"kind":"symbol","deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use method configure(apiKey:region:completion:) instead"}]}],"variants":[{"paths":["\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi\/apikey"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Your Discovery API key"}],"references":{"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI","kind":"symbol","title":"TicketmasterDiscoveryAPI","abstract":[],"url":"\/documentation\/ticketmasterdiscoveryapi","type":"topic","role":"collection"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TMDiscoveryAPI":{"navigatorTitle":[{"text":"TMDiscoveryAPI","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"A class that stores the global configuration for the TicketmasterDiscoveryAPI SDK","type":"text"}],"title":"TMDiscoveryAPI","url":"\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMDiscoveryAPI","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TMDiscoveryAPI/apiKey":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/apiKey","deprecated":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiKey"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"title":"apiKey","abstract":[{"type":"text","text":"Your Discovery API key"}],"type":"topic","url":"\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi\/apikey"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TMDiscoveryAPI","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterDiscoveryAPI~1documentation~1TicketmasterDiscoveryAPI~1TMDiscoveryAPI\/title","op":"replace"},{"value":[{"kind":"identifier","text":"TMDiscoveryAPI"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterDiscoveryAPI~1documentation~1TicketmasterDiscoveryAPI~1TMDiscoveryAPI\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"TMDiscoveryAPI"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterDiscoveryAPI~1documentation~1TicketmasterDiscoveryAPI~1TMDiscoveryAPI\/navigatorTitle","op":"replace"}]}]}