{"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets"]]},"kind":"article","sections":[],"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/CustomModules","interfaceLanguage":"swift"},"metadata":{"role":"article","title":"Custom Module","roleHeading":"Article","modules":[{"name":"TicketmasterTickets"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"A "},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","isActive":true},{"type":"text","text":" is defined by three values:"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmastertickets\/custommodules"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ticketmastertickets\/custommodules"]}],"primaryContentSections":[{"kind":"content","content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A unique identifier string","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"An optional Header View","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"0 to 3 Buttons"}]}]}],"type":"orderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"See: "},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/init(identifier:headerDisplay:actionButtons:)","type":"reference","isActive":true}]},{"inlineContent":[{"text":"Modules are built and returned in ","type":"text"},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleDelegate\/addCustomModules(event:completion:)","type":"reference","isActive":true}],"type":"paragraph"},{"type":"codeListing","syntax":null,"code":["extension MyClass: TMTicketsModuleDelegate {    ","","    func addCustomModules(event: TMPurchasedEvent, completion: @escaping ([TMTicketsModule]?) -> Void) {","        \/\/ build a UIView","        let view = UIView()","        view.backgroundColor = .red","    ","        \/\/ build Header with UIView","        let header = TMTicketsModule.HeaderDisplay(view: view)","    ","        \/\/ build buttons","        let button1 = TMTicketsModule.ActionButton(title: \"One\")","        let button2 = TMTicketsModule.ActionButton(title: \"Two\")","        let button3 = TMTicketsModule.ActionButton(title: \"Three\")","","        \/\/ build module with header and buttons","        let module = TMTicketsModule(identifier: \"com.myDemoApp.demoModule\",","                                    headerDisplay: header,","                                    actionButtons: [button1, button2, button3])","    ","        \/\/ return modules in display order","        completion([module])","    }","}"]},{"inlineContent":[{"type":"text","text":"Output:"},{"text":" ","type":"text"},{"type":"image","identifier":"Module_DefaultAspect.jpg"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Let’s examine each of these three values in detail."}]},{"level":2,"text":"Identifier","anchor":"Identifier","type":"heading"},{"inlineContent":[{"text":"A globally unique indentifier is best to avoid conflicts with any internal or pre-built module names.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"We recommend using a reverse URL style."}]},{"inlineContent":[{"text":"Unique examples:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"“com.ticketmaster.seatUpgrades”"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"“com.nfl.broncosSeating”"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"“com.myDemoApp.demoModule”"}]}]}],"type":"unorderedList"},{"type":"heading","text":"Header","level":2,"anchor":"Header"},{"inlineContent":[{"text":"While optional, the Header is the most easily visible component of a Module.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"A Header (","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/HeaderDisplay-swift.class"},{"type":"text","text":") is simply a wrapper around a UIView."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Note that a Module can contain a Header with no Buttons, or Buttons with no Header."}],"type":"paragraph"},{"type":"heading","level":3,"text":"Size","anchor":"Size"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The Header is automatically resized to the width of the user’s phone, so you can only really control the height. This is done by setting an aspect ratio."}]},{"inlineContent":[{"type":"text","text":"The default aspect ratio (3x2) is recommended for visual consistancy."}],"type":"paragraph"},{"type":"heading","level":2,"text":"Header Default Aspect Ratio","anchor":"Header-Default-Aspect-Ratio"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Build a module with a Red header, using the default aspect ratio (3x2).","type":"text"}]}]}]},{"syntax":null,"code":["func addCustomModules(event: TMPurchasedEvent, completion: @escaping ([TMTicketsModule]?) -> Void) {","    \/\/ build a UIView (with default aspect ratio 3x2)","    let view = UIView()","    view.backgroundColor = .red","    ","    \/\/ build header with UIView","    let header = TMTicketsModule.HeaderDisplay(view: view)","    ","    \/\/ build buttons","    let button1 = TMTicketsModule.ActionButton(title: \"One\")","    let button2 = TMTicketsModule.ActionButton(title: \"Two\")","    let button3 = TMTicketsModule.ActionButton(title: \"Three\")","","    \/\/ build module with header and buttons","    let module = TMTicketsModule(identifier: \"com.myDemoApp.demoModule\",","                                 headerDisplay: header,","                                 actionButtons: [button1, button2, button3])","    ","    \/\/ return module","    completion([module])","}"],"type":"codeListing"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Output:"}],"type":"paragraph"}]}]},{"type":"paragraph","inlineContent":[{"identifier":"Module_DefaultAspect.jpg","type":"image"}]},{"text":"Header Custom Aspect Ratio","type":"heading","anchor":"Header-Custom-Aspect-Ratio","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The Header inherits it’s aspect ratio from the provided UIView, so by setting the size of the UIView you can alter the aspect ratio of the Header."}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Build a module with a Red header, using a custom defined aspect ratio (1x1).","type":"text"}],"type":"paragraph"}]}]},{"syntax":null,"code":["func addCustomModules(event: TMPurchasedEvent, completion: @escaping ([TMTicketsModule]?) -> Void) {","    \/\/ build a UIView (with a defined aspect ratio)","    let view = UIView(frame: CGRect(x: 0, y: 0, width: 1, height: 1))","    view.backgroundColor = .red","    ","    \/\/ build header with UIView","    let header = TMTicketsModule.HeaderDisplay(view: view)","    ","    \/\/ build buttons","    let button1 = TMTicketsModule.ActionButton(title: \"One\")","    let button2 = TMTicketsModule.ActionButton(title: \"Two\")","    let button3 = TMTicketsModule.ActionButton(title: \"Three\")","","    \/\/ build module with header and buttons","    let module = TMTicketsModule(identifier: \"com.myDemoApp.demoModule\",","                                 headerDisplay: header,","                                 actionButtons: [button1, button2, button3])","    ","    \/\/ return module","    completion([module])","}"],"type":"codeListing"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Output:","type":"text"}],"type":"paragraph"}]}]},{"inlineContent":[{"type":"image","identifier":"Module_DefinedAspect.jpg"}],"type":"paragraph"},{"level":2,"anchor":"Custom-Header-Image","text":"Custom Header Image","type":"heading"},{"inlineContent":[{"text":"Headers can also be created with a UIImage (as a convenience). The aspect ratio of the Header is inherited from the size of the UIImage.","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"text":"Build a module with an Image header, aspect ratio is defined by Image size:","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"syntax":null,"type":"codeListing","code":["func addCustomModules(event: TMPurchasedEvent, completion: @escaping ([TMTicketsModule]?) -> Void) {","    \/\/ load UIImage","    let image = UIImage(imageLiteralResourceName: \"HotDogs.jpg\")","    ","    \/\/ build header with UIImage","    let header = TMTicketsModule.HeaderDisplay(image: image)","    ","    \/\/ build buttons","    let button1 = TMTicketsModule.ActionButton(title: \"One\")","    let button2 = TMTicketsModule.ActionButton(title: \"Two\")","    let button3 = TMTicketsModule.ActionButton(title: \"Three\")","","    \/\/ build module with header and buttons","    let module = TMTicketsModule(identifier: \"com.myDemoApp.demoModule\",","                                 headerDisplay: header,","                                 actionButtons: [button1, button2, button3])","    ","    \/\/ return module","    completion([module])","}"]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Output:","type":"text"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"Module_Image.jpg"}]},{"type":"heading","text":"HeaderView Builder","level":2,"anchor":"HeaderView-Builder"},{"inlineContent":[{"type":"text","text":"While you are welcome to build a Header using any UIView, a helpful Header builder has been provided."}],"type":"paragraph"},{"inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView"},{"type":"text","text":" can help you quickly build a UIView for presentation."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The header builder supports:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Three lines of custom Text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Gradient overlay (from top-left and bottom-right corners)","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"UIColor background","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/configure(topLabelText:topLabelTextAlignment:centerLabelText:centerLabelTextAlignment:bottomLabelText:bottomLabelTextAlignment:gradientAlpha:backgroundColor:)","type":"reference","isActive":true}]}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"UIImage background","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"TMTicketsModuleHeaderView\/configure(topLabelText:topLabelTextAlignment:centerLabelText:centerLabelTextAlignment:bottomLabelText:bottomLabelTextAlignment:gradientAlpha:backgroundImage:)"}]}]}],"type":"unorderedList"}]},{"content":[{"inlineContent":[{"type":"text","text":"MKCoordinateRegion map"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/configure(topLabelText:topLabelTextAlignment:centerLabelText:centerLabelTextAlignment:bottomLabelText:bottomLabelTextAlignment:gradientAlpha:mapCoordinateRegion:mapAnnotation:)","type":"reference","isActive":true}]}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"QR Code","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"TMTicketsModuleHeaderView\/configure(topLabelText:topLabelTextAlignment:centerLabelText:centerLabelTextAlignment:bottomLabelText:bottomLabelTextAlignment:gradientAlpha:backgroundImage:qrCodeValue:)"}]}]}],"type":"unorderedList"}]},{"content":[{"inlineContent":[{"type":"text","text":"2D Barcode"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"code":"TMTicketsModuleHeaderView\/configure(topLabelText:topLabelTextAlignment:centerLabelText:centerLabelTextAlignment:bottomLabelText:bottomLabelTextAlignment:gradientAlpha:backgroundImage:barcode2DValue:)","type":"codeVoice"}]}]}],"type":"unorderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Audio\/Video Content"}]},{"items":[{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/configure(topLabelText:topLabelTextAlignment:centerLabelText:centerLabelTextAlignment:bottomLabelText:bottomLabelTextAlignment:gradientAlpha:avContentURL:disableLoopingContent:disableAVAudio:)","isActive":true}],"type":"paragraph"}]}],"type":"unorderedList"}]}]},{"type":"heading","anchor":"HeaderView-Builder-Color","text":"HeaderView Builder: Color","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Build a module with a Red header, using the Header View builder:"}],"type":"paragraph"}]}]},{"type":"codeListing","syntax":null,"code":["func addCustomModules(event: TMPurchasedEvent, completion: @escaping ([TMTicketsModule]?) -> Void) {","    \/\/ build a UIView (with default aspect ratio 3x2)","    let headerView = TMTicketsModuleHeaderView.build()","    headerView.configure(backgroundColor: .red)","    ","    \/\/ build header with HeaderView (a UIView)","    let header = TMTicketsModule.HeaderDisplay(view: headerView)","    ","    \/\/ build buttons","    let button1 = TMTicketsModule.ActionButton(title: \"One\")","    let button2 = TMTicketsModule.ActionButton(title: \"Two\")","    let button3 = TMTicketsModule.ActionButton(title: \"Three\")","","    \/\/ build module with header and buttons","    let module = TMTicketsModule(identifier: \"com.myDemoApp.demoModule\",","                                 headerDisplay: header,","                                 actionButtons: [button1, button2, button3])","    ","    \/\/ return module","    completion([module])","}"]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Output:"}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"identifier":"Module_DefaultAspect.jpg","type":"image"}]},{"anchor":"HeaderView-Builder-Image-+-Text-+-Gradient","type":"heading","level":2,"text":"HeaderView Builder: Image + Text + Gradient"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Build a module with an Image, Text, and Gradient:"}]}]}]},{"code":["func addCustomModules(event: TMPurchasedEvent, completion: @escaping ([TMTicketsModule]?) -> Void) {","    \/\/ load UIImage","    let image = UIImage(imageLiteralResourceName: \"HotDogs.jpg\")","    ","    \/\/ build a UIView with a text, gradient, and image","    let headerView = TMTicketsModuleHeaderView.build()","    headerView.configure(topLabelText: \"Food\",","                         topLabelTextAlignment: .left,","                         centerLabelText: \"Drinks\",","                         centerLabelTextAlignment: .center,","                         bottomLabelText: \"Fun\",","                         bottomLabelTextAlignment: .right,","                         gradientAlpha: 1.0,","                         backgroundImage: image)","    ","    \/\/ build header with HeaderView (a UIView)","    let header = TMTicketsModule.HeaderDisplay(view: headerView)","    ","    \/\/ build buttons","    let button1 = TMTicketsModule.ActionButton(title: \"One\")","    let button2 = TMTicketsModule.ActionButton(title: \"Two\")","    let button3 = TMTicketsModule.ActionButton(title: \"Three\")","","    \/\/ build module with header and buttons","    let module = TMTicketsModule(identifier: \"com.myDemoApp.demoModule\",","                                 headerDisplay: header,","                                 actionButtons: [button1, button2, button3])","    ","    \/\/ return module","    completion([module])","}"],"syntax":null,"type":"codeListing"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Output:","type":"text"}]}]}]},{"inlineContent":[{"identifier":"Module_ImageText.jpg","type":"image"}],"type":"paragraph"},{"type":"heading","anchor":"HeaderView-Builder-Map","text":"HeaderView Builder: Map","level":2},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Build a module with a Map and Text:"}]}]}],"type":"unorderedList"},{"syntax":null,"type":"codeListing","code":["func addCustomModules(event: TMPurchasedEvent, completion: @escaping ([TMTicketsModule]?) -> Void) {","    \/\/ define map region and zoom (span)","    let mapRegion = MKCoordinateRegion(","        center: CLLocationCoordinate2D(latitude: 34.0734, longitude: -118.2402),","        span: MKCoordinateSpan(latitudeDelta: 0.02, longitudeDelta: 0.02))","    ","    \/\/ define map point of interest","    let mapAnnotation = TMTicketsModuleHeaderView.MapAnnotation(","        coordinate: CLLocationCoordinate2D(latitude: 34.0735, longitude: -118.2456),","        title: \"Lot 1\")","    ","    \/\/ build a UIView with a text, gradient, and image","    let headerView = TMTicketsModuleHeaderView.build()","    headerView.configure(topLabelText: \"Parking: Lot 1\",","                         mapCoordinateRegion: mapRegion,","                         mapAnnotation: mapAnnotation)","    ","    \/\/ build header with HeaderView (a UIView)","    let header = TMTicketsModule.HeaderDisplay(view: headerView)","    ","    \/\/ build buttons","    let button1 = TMTicketsModule.ActionButton(title: \"One\")","    let button2 = TMTicketsModule.ActionButton(title: \"Two\")","    let button3 = TMTicketsModule.ActionButton(title: \"Three\")","","    \/\/ build module with header and buttons","    let module = TMTicketsModule(identifier: \"com.myDemoApp.demoModule\",","                                 headerDisplay: header,","                                 actionButtons: [button1, button2, button3])","    ","    \/\/ return module","    completion([module])","}"]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Output:","type":"text"}]}]}],"type":"unorderedList"},{"inlineContent":[{"type":"image","identifier":"Module_MapText.jpg"}],"type":"paragraph"},{"level":2,"type":"heading","anchor":"HeaderView-Builder-QR-Code","text":"HeaderView Builder: QR Code"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Build a module with a QR Code, Image, Gradient and Text:"}],"type":"paragraph"}]}],"type":"unorderedList"},{"type":"codeListing","syntax":null,"code":["func addCustomModules(event: TMPurchasedEvent, completion: @escaping ([TMTicketsModule]?) -> Void) {","    \/\/ build a UIView with a text, QR code, gradient, and image","    let headerView = TMTicketsModuleHeaderView.build()","    headerView.configure(topLabelText: \"Broncos Fan Voucher\",","                         bottomLabelText: \"Stored Value: $58.90\",","                         gradientAlpha: 1.0,","                         backgroundImage: UIImage(named: \"BroncosPlay.jpg\"),","                         qrCodeValue: \"1234567890ABCDEF\")","","    \/\/ build header with HeaderView (a UIView)","    let header = TMTicketsModule.HeaderDisplay(view: headerView)","","    \/\/ build module with header, but no buttons","    let module = TMTicketsModule(identifier: \"com.myDemoApp.demoModule\",","                                 headerDisplay: header,","                                 actionButtons: nil) \/\/ no buttons","    ","    \/\/ return module","    completion([module])","}"]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Output:","type":"text"}]}]}],"type":"unorderedList"},{"inlineContent":[{"type":"image","identifier":"Module_QRText.jpg"}],"type":"paragraph"},{"text":"HeaderView Builder: Video","type":"heading","anchor":"HeaderView-Builder-Video","level":2},{"type":"paragraph","inlineContent":[{"text":"The video will start playing as soon as the user scrolls down to the module.","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Build a module with a Video and Text:"}],"type":"paragraph"}]}]},{"type":"codeListing","syntax":null,"code":["func addCustomModules(event: TMPurchasedEvent, completion: @escaping ([TMTicketsModule]?) -> Void) {","    \/\/ load video from local file or web URL","    let ticketsMovieURL = Bundle.main.url(forResource: \"BroncosMobileTickets\", withExtension: \"mp4\")!","    ","    \/\/ build a UIView with a text, QR code, and image","    let headerView = TMTicketsModuleHeaderView.build()","    headerView.configure(topLabelText: \"Entry Demo\",","                         avContentURL: ticketsMovieURL)","    ","    \/\/ build header with HeaderView (a UIView)","    let header = TMTicketsModule.HeaderDisplay(view: headerView)","","    \/\/ build buttons","    let button1 = TMTicketsModule.ActionButton(title: \"One\")","    let button2 = TMTicketsModule.ActionButton(title: \"Two\")","    let button3 = TMTicketsModule.ActionButton(title: \"Three\")","","    \/\/ build module with header and buttons","    let module = TMTicketsModule(identifier: \"com.myDemoApp.demoModule\",","                                 headerDisplay: header,","                                 actionButtons: [button1, button2, button3])","    ","    \/\/ return module","    completion([module])","}"]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Output:"}],"type":"paragraph"}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"Module_VideoText.jpg"}]},{"anchor":"Buttons","type":"heading","level":2,"text":"Buttons"},{"type":"paragraph","inlineContent":[{"text":"Buttons (","type":"text"},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/ActionButton","isActive":true},{"type":"text","text":") are assigned Actions that occur when the button is pressed."}]},{"inlineContent":[{"type":"text","text":"Currently, only two Actions are supported:"}],"type":"paragraph"},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"open a given webpage inside Tickets SDK (in a webview)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"callback to module delegate (inside your app)"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note that a Module can contain a Header with no Buttons, or Buttons with no Header."}]},{"level":2,"type":"heading","text":"Button Action: Callback","anchor":"Button-Action-Callback"},{"type":"paragraph","inlineContent":[{"text":"If webpage settings are not defined on the ","type":"text"},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/ActionButton","isActive":true,"type":"reference"},{"type":"text","text":", then when the user presses the button, the callback method on the module delegate will be called: "},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleDelegate\/handleModuleActionButton(event:module:button:completion:)","type":"reference","isActive":true}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Build three buttons (with no header):","type":"text"}]}]}]},{"type":"codeListing","code":["extension MyClass: TMTicketsModuleDelegate {","    ","    func addCustomModules(event: TMPurchasedEvent, completion: @escaping ([TMTicketsModule]?) -> Void) {","        \/\/ build buttons","        let button1 = TMTicketsModule.ActionButton(title: \"One\")","        let button2 = TMTicketsModule.ActionButton(title: \"Two\")","        let button3 = TMTicketsModule.ActionButton(title: \"Three\")","","        \/\/ build module with header and buttons","        let module = TMTicketsModule(identifier: \"com.myDemoApp.demoModule\",","                                     headerDisplay: nil, \/\/ no header","                                     actionButtons: [button1, button2, button3])","        ","        \/\/ return module","        completion([module])","    }","    ","    func handleModuleActionButton(","        event: TMPurchasedEvent,","        module: TMTicketsModule,","        button: TMTicketsModule.ActionButton,","        completion: @escaping (TMTicketsModule.WebpageSettings?) -> Void) {","","        \/\/ this is not called if webpage settings are already defined","        if module.identifier == \"com.myDemoApp.demoModule\" {","            if button.callbackValue == \"One\" {","                print(\"Action: One\")","                \/\/ handle in your own code, do not close modal Tickets Listing page ","                \/\/ do not call completion","                handle(button: button)","                ","            } else if button.callbackValue == \"Two\" {","                print(\"Action: Two\")","                \/\/ handle in your own code, but first close modal Tickets Listing page","                \/\/ call completion with nil","                completion(nil)","                handle(button: button)","","            } else if button.callbackValue == \"Three\" {","                print(\"Action: Three\")","                \/\/ open a webpage inside Tickets SDK (webview)","                let request = URLRequest(url: URL(string: \"https:\/\/www.mlb.com\")!)","                let settings = TMTicketsModule.WebpageSettings(pageTitle: \"MLB Homepage\",","                                                               urlRequest: request)","                \/\/ call completion with webpage settings","                completion(settings)","            }","        }","    }","}"],"syntax":null},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Output:","type":"text"}]}]}],"type":"unorderedList"},{"inlineContent":[{"type":"image","identifier":"Button_Three.jpg"}],"type":"paragraph"},{"type":"heading","text":"Button Action: Callback Completion","level":2,"anchor":"Button-Action-Callback-Completion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Notice that the handleModuleActionButton delegate method has a completion closure."}]},{"inlineContent":[{"type":"text","text":"This is used to inform Tickets SDK of which behavior you would like when the user presses a Module Button."}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Do not close modal Tickets Listing page and handle button in your own code:","type":"text"}]}]}],"type":"unorderedList"},{"type":"codeListing","syntax":null,"code":["if button.callbackValue == \"One\" {","    print(\"Action: One\")","    \/\/ handle in your own code, do not close modal Tickets Listing page ","    \/\/ do not call completion","    handle(button: button)"]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Close modal Tickets Listing page first, then handle button in your own code:","type":"text"}]}]}],"type":"unorderedList"},{"type":"codeListing","syntax":null,"code":["} else if button.callbackValue == \"Two\" {","    print(\"Action: Two\")","    \/\/ handle in your own code, but first close modal Tickets Listing page","    \/\/ call completion with nil","    completion(nil)","    handle(button: button)"]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Do not close modal Tickets Listing page, have Tickets SDK open a webpage for you:"}],"type":"paragraph"}]}],"type":"unorderedList"},{"syntax":null,"code":["} else if button.callbackValue == \"Three\" {","    print(\"Action: Three\")","    \/\/ open a webpage inside Tickets SDK (webview)","    let request = URLRequest(url: URL(string: \"https:\/\/www.mlb.com\")!)","    let settings = TMTicketsModule.WebpageSettings(pageTitle: \"MLB Homepage\",","                                                   urlRequest: request)","    \/\/ call completion with webpage settings","    completion(settings)"],"type":"codeListing"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Output:","type":"text"}],"type":"paragraph"}]}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"Button_MLBWebpage.jpg"}]},{"level":2,"type":"heading","anchor":"Button-Action-Webpage-Settings","text":"Button Action: Webpage Settings"},{"type":"paragraph","inlineContent":[{"text":"You can provide the Button webpage settings ahead of time instead of waiting for the callback.","type":"text"}]},{"inlineContent":[{"text":"Note that is this case, the handleModuleActionButton delegate method will not be called.","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"text":"Build one button with pre-defined webpage settings (with no header):","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"syntax":null,"type":"codeListing","code":["func addCustomModules(event: TMPurchasedEvent, completion: @escaping ([TMTicketsModule]?) -> Void) {","    \/\/ build webpage settings","    let request = URLRequest(url: URL(string: \"https:\/\/www.mlb.com\")!)","    let settings = TMTicketsModule.WebpageSettings(pageTitle: \"MLB Homepage\",","                                                   urlRequest: request)","    ","    \/\/ build buttons","    let button1 = TMTicketsModule.ActionButton(title: \"One\",","                                               webpageSettings: settings)","    ","    \/\/ build module with header and buttons","    let module = TMTicketsModule(identifier: \"com.myDemoApp.demoModule\",","                                 headerDisplay: nil, \/\/ no header","                                 actionButtons: [button1])","    ","    \/\/ return module","    completion([module])","}"]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Output:","type":"text"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"Button_MLBWebpage.jpg"}]},{"level":2,"type":"heading","anchor":"Button-Action-Webpage-Settings-+-State","text":"Button Action: Webpage Settings + State"},{"inlineContent":[{"text":"Typically you will want to pass in some state variables to the webpage. For example, maybe which event the user is viewing.","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This can be done with URL parameters."}]}]}],"type":"unorderedList"},{"inlineContent":[{"text":"You may also want to pass values securely. For example, the user’s login state (oauth token).","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"text":"This can be done with ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/OAuthCookieSettings","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]}],"type":"unorderedList"},{"inlineContent":[{"type":"text","text":"Example:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Build button with pre-defined webpage settings including eventID and user OAuthToken:"}],"type":"paragraph"}]}]},{"type":"codeListing","syntax":null,"code":["func addCustomModules(event: TMPurchasedEvent, completion: @escaping ([TMTicketsModule]?) -> Void) {","    \/\/ build cookie settings","    let cookie = TMTicketsModule.OAuthCookieSettings(name: \"userAuth\",","                                                     value: \"oauthToken1234\",","                                                     webDomains: [\".mlb.com\"])","    ","    \/\/ build webpage settings with parameters","    let request = URLRequest(url: URL(string: \"https:\/\/www.mlb.com?event=\\(event.info.identifier)\")!)","    let settings = TMTicketsModule.WebpageSettings(pageTitle: \"MLB Homepage\",","                                                   urlRequest: request,","                                                   oauthCookieSettings: cookie)","    ","    \/\/ build buttons","    let button1 = TMTicketsModule.ActionButton(title: \"One\",","                                               webpageSettings: settings)","    ","    \/\/ build module with header and buttons","    let module = TMTicketsModule(identifier: \"com.myDemoApp.demoModule\",","                                 headerDisplay: nil, \/\/ no header","                                 actionButtons: [button1])","    ","    \/\/ return module","    completion([module])","}"]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You can also easily attach Ticketmaster OAuth Tokens this way:"}]}]}],"type":"unorderedList"},{"type":"codeListing","syntax":null,"code":["func addCustomModules(event: TMPurchasedEvent, completion: @escaping ([TMTicketsModule]?) -> Void) {","    \/\/ build cookie settings (attaching Ticketmaster Archtics Modern Accounts token)","    let cookie = TMTicketsModule.OAuthCookieSettings(name: \"tmOAuth\",","                                                     webDomains: [\".mlb.com\"],","                                                     backend: .TeamModernAccounts)","    ","    \/\/ build webpage settings with parameters","    let request = URLRequest(url: URL(string: \"https:\/\/www.mlb.com?event=\\(event.info.identifier)\")!)","    let settings = TMTicketsModule.WebpageSettings(pageTitle: \"MLB Homepage\",","                                                   urlRequest: request,","                                                   oauthCookieSettings: cookie)","    ","    \/\/ build buttons","    let button1 = TMTicketsModule.ActionButton(title: \"One\",","                                               webpageSettings: settings)","    ","    \/\/ build module with header and buttons","    let module = TMTicketsModule(identifier: \"com.myDemoApp.demoModule\",","                                 headerDisplay: nil, \/\/ no header","                                 actionButtons: [button1])","    ","    \/\/ return module","    completion([module])","}"]},{"type":"heading","level":2,"text":"Pre-Built Modules","anchor":"Pre-Built-Modules"},{"inlineContent":[{"type":"text","text":"A few basic modules have already been created for you, see: "},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule","isActive":true}],"type":"paragraph"},{"type":"heading","text":"API Documentation","anchor":"API-Documentation","level":2},{"inlineContent":[{"text":"For more options see: ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule"}],"type":"paragraph"}]}],"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule/init(identifier:headerDisplay:actionButtons:)":{"abstract":[{"text":"create a module with the given identifier, header, and action buttons","type":"text"}],"title":"init(identifier:headerDisplay:actionButtons:)","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/init(identifier:headerDisplay:actionButtons:)","role":"symbol","kind":"symbol","url":"\/documentation\/ticketmastertickets\/tmticketsmodule\/init(identifier:headerdisplay:actionbuttons:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"headerDisplay","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HeaderDisplay","preciseIdentifier":"s:19TicketmasterTickets15TMTicketsModuleC13HeaderDisplayC"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"actionButtons"},{"kind":"text","text":": ["},{"text":"ActionButton","kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets15TMTicketsModuleC12ActionButtonC"},{"text":"]?)","kind":"text"}],"type":"topic"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView/configure(topLabelText:topLabelTextAlignment:centerLabelText:centerLabelTextAlignment:bottomLabelText:bottomLabelTextAlignment:gradientAlpha:avContentURL:disableLoopingContent:disableAVAudio:)":{"kind":"symbol","title":"configure(topLabelText:topLabelTextAlignment:centerLabelText:centerLabelTextAlignment:bottomLabelText:bottomLabelTextAlignment:gradientAlpha:avContentURL:disableLoopingContent:disableAVAudio:)","role":"symbol","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/configure(topLabelText:topLabelTextAlignment:centerLabelText:centerLabelTextAlignment:bottomLabelText:bottomLabelTextAlignment:gradientAlpha:avContentURL:disableLoopingContent:disableAVAudio:)","abstract":[{"type":"text","text":"configure with Audio\/Video content (typically a movie file)"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"configure","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"topLabelText"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"topLabelTextAlignment"},{"kind":"text","text":": "},{"text":"NSTextAlignment","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTextAlignment"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"centerLabelText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"centerLabelTextAlignment","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@NSTextAlignment","text":"NSTextAlignment","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"bottomLabelText","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"bottomLabelTextAlignment","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSTextAlignment","preciseIdentifier":"c:@E@NSTextAlignment"},{"text":"?, ","kind":"text"},{"text":"gradientAlpha","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"avContentURL","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":", ","kind":"text"},{"text":"disableLoopingContent","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"disableAVAudio","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview\/configure(toplabeltext:toplabeltextalignment:centerlabeltext:centerlabeltextalignment:bottomlabeltext:bottomlabeltextalignment:gradientalpha:avcontenturl:disableloopingcontent:disableavaudio:)"},"Module_QRText.jpg":{"type":"image","variants":[{"url":"\/images\/Module_QRText.jpg","traits":["1x","light"]}],"identifier":"Module_QRText.jpg","alt":"QR Code Header"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleDelegate/handleModuleActionButton(event:module:button:completion:)":{"required":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleDelegate\/handleModuleActionButton(event:module:button:completion:)","role":"symbol","url":"\/documentation\/ticketmastertickets\/tmticketsmoduledelegate\/handlemoduleactionbutton(event:module:button:completion:)","title":"handleModuleActionButton(event:module:button:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handleModuleActionButton"},{"text":"(","kind":"text"},{"text":"event","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TMPurchasedEvent","kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV"},{"text":", ","kind":"text"},{"text":"module","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule","text":"TMTicketsModule","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"button","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TMTicketsModule","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule"},{"kind":"text","text":"."},{"preciseIdentifier":"s:19TicketmasterTickets15TMTicketsModuleC12ActionButtonC","kind":"typeIdentifier","text":"ActionButton"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"openWebpageSettings"},{"text":": ","kind":"text"},{"text":"TMTicketsModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule"},{"text":".","kind":"text"},{"text":"WebpageSettings","kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets15TMTicketsModuleC15WebpageSettingsC"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[{"type":"text","text":"Method is invoked if user has pressed a button on a custom module, and unique handling is required."}],"type":"topic"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleDelegate/addCustomModules(event:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addCustomModules"},{"kind":"text","text":"("},{"text":"event","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV","kind":"typeIdentifier","text":"TMPurchasedEvent"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"customModuleArray","kind":"internalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule","kind":"typeIdentifier","text":"TMTicketsModule"},{"text":"]?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"required":true,"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/ticketmastertickets\/tmticketsmoduledelegate\/addcustommodules(event:completion:)","title":"addCustomModules(event:completion:)","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleDelegate\/addCustomModules(event:completion:)","abstract":[{"type":"text","text":"Method is invoked when the user is viewing a specific Event. Client app needs to define an array of custom modules (if any) and return them to the Tickets SDK."}]},"Module_DefinedAspect.jpg":{"type":"image","alt":"1x1 Custom Aspect Header","identifier":"Module_DefinedAspect.jpg","variants":[{"url":"\/images\/Module_DefinedAspect.jpg","traits":["1x","light"]}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView/configure(topLabelText:topLabelTextAlignment:centerLabelText:centerLabelTextAlignment:bottomLabelText:bottomLabelTextAlignment:gradientAlpha:backgroundColor:)":{"type":"topic","title":"configure(topLabelText:topLabelTextAlignment:centerLabelText:centerLabelTextAlignment:bottomLabelText:bottomLabelTextAlignment:gradientAlpha:backgroundColor:)","url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview\/configure(toplabeltext:toplabeltextalignment:centerlabeltext:centerlabeltextalignment:bottomlabeltext:bottomlabeltextalignment:gradientalpha:backgroundcolor:)","kind":"symbol","abstract":[{"type":"text","text":"configure with background color"}],"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/configure(topLabelText:topLabelTextAlignment:centerLabelText:centerLabelTextAlignment:bottomLabelText:bottomLabelTextAlignment:gradientAlpha:backgroundColor:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"configure","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"topLabelText"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"topLabelTextAlignment","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@NSTextAlignment","kind":"typeIdentifier","text":"NSTextAlignment"},{"text":"?, ","kind":"text"},{"text":"centerLabelText","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"centerLabelTextAlignment","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@NSTextAlignment","text":"NSTextAlignment","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"bottomLabelText"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"bottomLabelTextAlignment","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@NSTextAlignment","kind":"typeIdentifier","text":"NSTextAlignment"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"gradientAlpha"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":"?, ","kind":"text"},{"text":"backgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":")"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView/configure(topLabelText:topLabelTextAlignment:centerLabelText:centerLabelTextAlignment:bottomLabelText:bottomLabelTextAlignment:gradientAlpha:mapCoordinateRegion:mapAnnotation:)":{"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/configure(topLabelText:topLabelTextAlignment:centerLabelText:centerLabelTextAlignment:bottomLabelText:bottomLabelTextAlignment:gradientAlpha:mapCoordinateRegion:mapAnnotation:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"topLabelText"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"topLabelTextAlignment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSTextAlignment","preciseIdentifier":"c:@E@NSTextAlignment"},{"text":"?, ","kind":"text"},{"text":"centerLabelText","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"centerLabelTextAlignment","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSTextAlignment","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTextAlignment"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"bottomLabelText"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"bottomLabelTextAlignment","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@NSTextAlignment","kind":"typeIdentifier","text":"NSTextAlignment"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"gradientAlpha"},{"kind":"text","text":": "},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"mapCoordinateRegion","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@SA@MKCoordinateRegion","kind":"typeIdentifier","text":"MKCoordinateRegion"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mapAnnotation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MKAnnotation","text":"MKAnnotation"},{"text":"?)","kind":"text"}],"type":"topic","title":"configure(topLabelText:topLabelTextAlignment:centerLabelText:centerLabelTextAlignment:bottomLabelText:bottomLabelTextAlignment:gradientAlpha:mapCoordinateRegion:mapAnnotation:)","url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview\/configure(toplabeltext:toplabeltextalignment:centerlabeltext:centerlabeltextalignment:bottomlabeltext:bottomlabeltextalignment:gradientalpha:mapcoordinateregion:mapannotation:)","role":"symbol","abstract":[{"text":"configure with map region and annotation","type":"text"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule/HeaderDisplay-swift.class":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HeaderDisplay","kind":"identifier"}],"title":"TMTicketsModule.HeaderDisplay","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/HeaderDisplay-swift.class","url":"\/documentation\/ticketmastertickets\/tmticketsmodule\/headerdisplay-swift.class","navigatorTitle":[{"text":"HeaderDisplay","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule/OAuthCookieSettings":{"role":"symbol","navigatorTitle":[{"text":"OAuthCookieSettings","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/OAuthCookieSettings","type":"topic","title":"TMTicketsModule.OAuthCookieSettings","url":"\/documentation\/ticketmastertickets\/tmticketsmodule\/oauthcookiesettings","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"OAuthCookieSettings","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule":{"title":"TMTicketsPrebuiltModule","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsPrebuiltModule"}],"navigatorTitle":[{"kind":"identifier","text":"TMTicketsPrebuiltModule"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule","role":"symbol","type":"topic","url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule","abstract":[{"type":"text","text":"useful pre-built "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule"},{"type":"text","text":" for the Tickets listing page"}],"kind":"symbol"},"Button_Three.jpg":{"identifier":"Button_Three.jpg","alt":"Buttons without Header","type":"image","variants":[{"url":"\/images\/Button_Three.jpg","traits":["1x","light"]}]},"Module_MapText.jpg":{"type":"image","variants":[{"url":"\/images\/Module_MapText.jpg","traits":["1x","light"]}],"alt":"Map Header","identifier":"Module_MapText.jpg"},"Module_VideoText.jpg":{"identifier":"Module_VideoText.jpg","alt":"Video Header","type":"image","variants":[{"url":"\/images\/Module_VideoText.jpg","traits":["1x","light"]}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule/ActionButton":{"role":"symbol","title":"TMTicketsModule.ActionButton","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ActionButton","kind":"identifier"}],"url":"\/documentation\/ticketmastertickets\/tmticketsmodule\/actionbutton","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ActionButton"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/ActionButton"},"Module_DefaultAspect.jpg":{"type":"image","variants":[{"url":"\/images\/Module_DefaultAspect.jpg","traits":["1x","light"]}],"alt":"Color Header","identifier":"Module_DefaultAspect.jpg"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsModuleHeaderView"}],"type":"topic","title":"TMTicketsModuleHeaderView","navigatorTitle":[{"text":"TMTicketsModuleHeaderView","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"quickly build a UIView for ","type":"text"},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView","type":"reference","isActive":true}],"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView","url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule":{"title":"TMTicketsModule","abstract":[{"text":"create a custom module to be displayed underneath the user’s list of Tickets on the Tickets listing page","type":"text"}],"url":"\/documentation\/ticketmastertickets\/tmticketsmodule","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMTicketsModule","kind":"identifier"}],"navigatorTitle":[{"text":"TMTicketsModule","kind":"identifier"}]},"Module_ImageText.jpg":{"identifier":"Module_ImageText.jpg","alt":"Image Text Gradient Header","type":"image","variants":[{"url":"\/images\/Module_ImageText.jpg","traits":["1x","light"]}]},"Module_Image.jpg":{"type":"image","variants":[{"url":"\/images\/Module_Image.jpg","traits":["1x","light"]}],"alt":"Image Header","identifier":"Module_Image.jpg"},"Button_MLBWebpage.jpg":{"identifier":"Button_MLBWebpage.jpg","alt":"MLB Webpage","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/Button_MLBWebpage.jpg"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes."}],"url":"\/documentation\/ticketmastertickets","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","title":"TicketmasterTickets","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/title","value":"TMTicketsModuleHeaderView","op":"replace"},{"value":[{"kind":"identifier","text":"TMTicketsModuleHeaderView"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/fragments"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/title","value":"TMTicketsModule","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/fragments","value":[{"kind":"identifier","text":"TMTicketsModule"}]}]}]}