{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView"},"metadata":{"symbolKind":"class","title":"TMTicketsView","navigatorTitle":[{"text":"TMTicketsView","kind":"identifier"}],"role":"symbol","externalID":"c:@M@TicketmasterTickets@objc(cs)TMTicketsView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsView"}],"roleHeading":"Class","modules":[{"name":"TicketmasterTickets"}]},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(cs)UIView"]},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)NSCoding","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)NSObject","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)CALayerDelegate","doc:\/\/com.ticketmaster.TicketmasterTickets\/s7CVarArgP","doc:\/\/com.ticketmaster.TicketmasterTickets\/s28CustomDebugStringConvertibleP","doc:\/\/com.ticketmaster.TicketmasterTickets\/s23CustomStringConvertibleP","doc:\/\/com.ticketmaster.TicketmasterTickets\/SQ","doc:\/\/com.ticketmaster.TicketmasterTickets\/SH","doc:\/\/com.ticketmaster.TicketmasterTickets\/s8SendableP","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIAppearance","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIAppearanceContainer","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UICoordinateSpace","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIDynamicItem","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIFocusEnvironment","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIFocusItem","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIFocusItemContainer","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UILargeContentViewerItem","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.ticketmaster.TicketmasterTickets\/5UIKit23UITraitChangeObservableP","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UITraitEnvironment","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To"}],"variants":[{"paths":["\/documentation\/ticketmastertickets\/tmticketsview"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ticketmastertickets\/tmticketsview"]}],"sections":[],"abstract":[{"text":"use to render Tickets SDK as a UIView embedded inside of your own UIViewController","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets"]]},"topicSections":[{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView\/init(coder:)","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView\/init(frame:)"],"title":"Initializers"},{"title":"Instance Methods","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView\/awakeFromNib()","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView\/didMoveToWindow()","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView\/reload()","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView\/willMove(toWindow:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTicketsView"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"text":"Overview","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note that this will only apply to the My Events page, as additional UI (like My Tickets) are presented modally on top of the current UIViewController."}]},{"type":"aside","style":"important","content":[{"inlineContent":[{"type":"text","text":"For most UI designs, it may be easier for you to use a "},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController","isActive":true},{"text":" instead of this class","type":"text"}],"type":"paragraph"}],"name":"Important"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsViewController":{"url":"\/documentation\/ticketmastertickets\/tmticketsviewcontroller","navigatorTitle":[{"text":"TMTicketsViewController","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"this class wraps the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView","isActive":true},{"text":" in a ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"text":" for ease of use","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController","type":"topic","title":"TMTicketsViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTicketsViewController"}]},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)NSCoding":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsView/willMove(toWindow:)":{"url":"\/documentation\/ticketmastertickets\/tmticketsview\/willmove(towindow:)","navigatorTitle":[{"text":"willMoveToWindow:","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView\/willMove(toWindow:)","type":"topic","title":"willMove(toWindow:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"willMove","kind":"identifier"},{"kind":"text","text":"("},{"text":"toWindow","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":"?)"}]},"doc://com.ticketmaster.TicketmasterTickets/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterTickets/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/SQ","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsView/init(frame:)":{"role":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView\/init(frame:)","url":"\/documentation\/ticketmastertickets\/tmticketsview\/init(frame:)","title":"init(frame:)","type":"topic","kind":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIFocusItem","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIResponderStandardEditActions","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterTickets/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIAccessibilityIdentification","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsView/didMoveToWindow()":{"url":"\/documentation\/ticketmastertickets\/tmticketsview\/didmovetowindow()","navigatorTitle":[{"kind":"identifier","text":"didMoveToWindow"}],"kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView\/didMoveToWindow()","type":"topic","title":"didMoveToWindow()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didMoveToWindow"},{"text":"()","kind":"text"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsView":{"role":"symbol","abstract":[{"type":"text","text":"use to render Tickets SDK as a UIView embedded inside of your own UIViewController"}],"url":"\/documentation\/ticketmastertickets\/tmticketsview","title":"TMTicketsView","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView","navigatorTitle":[{"text":"TMTicketsView","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TMTicketsView","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsView/awakeFromNib()":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView\/awakeFromNib()","abstract":[],"navigatorTitle":[{"text":"awakeFromNib","kind":"identifier"}],"url":"\/documentation\/ticketmastertickets\/tmticketsview\/awakefromnib()","type":"topic","kind":"symbol","role":"symbol","title":"awakeFromNib()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"awakeFromNib"},{"kind":"text","text":"()"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsView/init(coder:)":{"url":"\/documentation\/ticketmastertickets\/tmticketsview\/init(coder:)","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView\/init(coder:)","type":"topic","title":"init(coder:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"text":")","kind":"text"}]},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UITraitEnvironment"},"doc://com.ticketmaster.TicketmasterTickets/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/s7CVarArgP"},"doc://com.ticketmaster.TicketmasterTickets/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(cs)UIView"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)NSObject"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"kind":"symbol","type":"topic","url":"\/documentation\/ticketmastertickets","abstract":[{"type":"text","text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes."}],"role":"collection","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","title":"TicketmasterTickets"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsView/reload()":{"role":"symbol","url":"\/documentation\/ticketmastertickets\/tmticketsview\/reload()","title":"reload()","type":"topic","abstract":[{"type":"text","text":"reload contents of My Events page, fetch fresh orders"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reload"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView\/reload()","kind":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UICoordinateSpace"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.ticketmaster.TicketmasterTickets/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/SH"},"doc://com.ticketmaster.TicketmasterTickets/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/5UIKit23UITraitChangeObservableP"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIFocusEnvironment"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIFocusItemContainer"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UILargeContentViewerItem"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIAppearance"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIDynamicItem"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)CALayerDelegate"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIUserActivityRestoring"},"doc://com.ticketmaster.TicketmasterTickets/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/s8SendableP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"TMTicketsView"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"TMTicketsView","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"TMTicketsView","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView\/awakeFromNib()","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView\/didMoveToWindow()","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView\/init(coder:)","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView\/init(frame:)","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView\/willMove(toWindow:)"],"title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(cs)UIView"],"kind":"relationships"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"TMTicketsView","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController\/title","op":"replace","value":"TMTicketsViewController"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController\/fragments","value":[{"text":"TMTicketsViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView~1willMove(toWindow:)\/title","value":"willMoveToWindow:"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView~1willMove(toWindow:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"willMoveToWindow:","kind":"identifier"}]},{"value":"initWithFrame:","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView~1init(frame:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView~1init(frame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]},{"value":"didMoveToWindow","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView~1didMoveToWindow()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView~1didMoveToWindow()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didMoveToWindow"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/title","value":"TMTicketsView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/fragments","value":[{"kind":"identifier","text":"TMTicketsView"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView~1awakeFromNib()\/title","value":"awakeFromNib","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView~1awakeFromNib()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"awakeFromNib"}]},{"value":"initWithCoder:","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView~1init(coder:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView~1init(coder:)\/fragments","op":"replace"}]}]}