{"seeAlsoSections":[{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleDelegate"],"title":"Custom Modules","anchor":"Custom-Modules","generated":true}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsModuleHeaderView"}],"modules":[{"name":"TicketmasterTickets"}],"navigatorTitle":[{"text":"TMTicketsModuleHeaderView","kind":"identifier"}],"externalID":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModuleHeaderView","roleHeading":"Class","title":"TMTicketsModuleHeaderView","symbolKind":"class","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets"]]},"variants":[{"paths":["\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview"]}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"quickly build a UIView for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView"}],"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/MapAnnotation"],"generated":true,"anchor":"Classes"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/configure(topLabelText:topLabelTextAlignment:topLabelTextColor:centerLabelText:centerLabelTextAlignment:centerLabelTextColor:bottomLabelText:bottomLabelTextAlignment:bottomLabelTextColor:titleLabelText:titleLabelTextColor:messageLabelText:messageLabelTextColor:messageLabelDetectLinks:messageLabelLinkColor:titleMessageBackgroundColor:gradientAlpha:backgroundAspectRatio:backgroundAspectRatioForced:backgroundColor:backgroundImage:backgroundImageURL:backgroundView:mapCoordinateRegion:mapAnnotation:avContentURL:disableLoopingContent:disableAVAudio:barcode2DValue:qrCodeValue:aztecValue:pdf417Value:headerOverride:)","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/pauseAVContent()","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/playAVContent()"],"anchor":"Instance-Methods"},{"title":"Type Methods","generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/build()"]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(cs)UIView"],"kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)NSCoding","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)NSObject","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)CALayerDelegate","doc:\/\/com.ticketmaster.TicketmasterTickets\/s7CVarArgP","doc:\/\/com.ticketmaster.TicketmasterTickets\/s28CustomDebugStringConvertibleP","doc:\/\/com.ticketmaster.TicketmasterTickets\/s23CustomStringConvertibleP","doc:\/\/com.ticketmaster.TicketmasterTickets\/SQ","doc:\/\/com.ticketmaster.TicketmasterTickets\/SH","doc:\/\/com.ticketmaster.TicketmasterTickets\/s8SendableP","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIAppearance","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIAppearanceContainer","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UICoordinateSpace","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIDynamicItem","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIFocusEnvironment","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIFocusItem","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIFocusItemContainer","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UILargeContentViewerItem","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.ticketmaster.TicketmasterTickets\/5UIKit23UITraitChangeObservableP","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UITraitEnvironment","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIUserActivityRestoring"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TMTicketsModuleHeaderView","kind":"identifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Overview","anchor":"overview","level":2,"type":"heading"},{"type":"codeListing","syntax":null,"code":["\/\/ build a UIView for the header","\/\/  we have a handy method to build module UI easily, this includes:","\/\/   * text","\/\/   * images","\/\/   * maps","\/\/   * QR codes","\/\/   * 2D barcodes","\/\/   * videos","let headerView = TMTicketsModuleHeaderView.build()","","\/\/ multiple configure(...) methods are available","\/\/  we will use the one for background images","headerView.configure(backgroundImage: backgroundImage)","","\/\/ build header display","\/\/  any UIView will work here for headerView, not just a TMModuleHeaderView","let headerDisplay = TMTicketsModule.HeaderDisplay(view: headerView as UIView)","","\/\/ build action buttons that open a webpage","let webpageSettings = TMTicketsModule.WebpageSettings(","    pageTitle: \"Ball Arena\",","    urlRequest: URLRequest(url: URL(string: \"https:\/\/www.ballarena.com\/arena-policies-faq\")!))","let actionButton = TMTicketsModule.ActionButton(","    title: \"Venue Info\", \/\/ what user will see, you should localize this text","    callbackValue: \"venueInfo\", \/\/ non-localized value, for your own code\/analytics","    webpageSettings: webpageSettings)","","\/\/ modules can have:","\/\/  1. header only (no buttons)","\/\/  2. buttons only (no header)","\/\/  3. both header and buttons","","\/\/ build module","return TMTicketsModule(identifier: \"com.myDemoApp.venueInfo\", \/\/ a name unique to your app","                       headerDisplay: headerDisplay,","                       actionButtons: [actionButton]) \/\/ you can show 0 to 3 buttons"]}]}],"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView","interfaceLanguage":"swift"},"references":{"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIFocusEnvironment"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)CALayerDelegate"},"doc://com.ticketmaster.TicketmasterTickets/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(cs)UIView"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIAccessibilityIdentification"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)NSCoding"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView/pauseAVContent()":{"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/pauseAVContent()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pauseAVContent"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"pause AV content (if any)"}],"url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview\/pauseavcontent()","title":"pauseAVContent()","type":"topic","role":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UITraitEnvironment"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIUserActivityRestoring"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule":{"navigatorTitle":[{"kind":"identifier","text":"TMTicketsPrebuiltModule"}],"abstract":[{"type":"text","text":"useful pre-built "},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","isActive":true,"type":"reference"},{"type":"text","text":" for the Tickets listing page"}],"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule","url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule","title":"TMTicketsPrebuiltModule","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TMTicketsPrebuiltModule","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UICoordinateSpace"},"doc://com.ticketmaster.TicketmasterTickets/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/5UIKit23UITraitChangeObservableP"},"doc://com.ticketmaster.TicketmasterTickets/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/SH"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UILargeContentViewerItem"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleDelegate":{"title":"TMTicketsModuleDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMTicketsModuleDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleDelegate","type":"topic","navigatorTitle":[{"text":"TMTicketsModuleDelegate","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ticketmastertickets\/tmticketsmoduledelegate","abstract":[{"type":"text","text":"optional delegate to implement prebuilt and custom "},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","isActive":true},{"type":"text","text":" to be rendered on the Tickets listing page"}]},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)NSObject"},"doc://com.ticketmaster.TicketmasterTickets/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/SQ"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIFocusItem"},"doc://com.ticketmaster.TicketmasterTickets/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/s7CVarArgP"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIResponderStandardEditActions"},"doc://com.ticketmaster.TicketmasterTickets/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/s8SendableP"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView":{"title":"TMTicketsModuleHeaderView","abstract":[{"text":"quickly build a UIView for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView"}],"role":"symbol","type":"topic","url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview","navigatorTitle":[{"kind":"identifier","text":"TMTicketsModuleHeaderView"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMTicketsModuleHeaderView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIFocusItemContainer"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView/initWithCoder:":{"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview\/initwithcoder:","title":"initWithCoder:","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"role":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView/initWithFrame:":{"url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview\/initwithframe:","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/initWithFrame:","title":"initWithFrame:","type":"topic","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFrame:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}]},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://com.ticketmaster.TicketmasterTickets/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"TMTicketsModule","kind":"identifier"}],"abstract":[{"type":"text","text":"create a custom module to be displayed underneath the user’s list of Tickets on the Tickets listing page"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsModule"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","title":"TMTicketsModule","url":"\/documentation\/ticketmastertickets\/tmticketsmodule","role":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIAppearance":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIAppearance","title":"UIKit.UIAppearance"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView/MapAnnotation":{"url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview\/mapannotation","navigatorTitle":[{"text":"MapAnnotation","kind":"identifier"}],"type":"topic","title":"TMTicketsModuleHeaderView.MapAnnotation","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapAnnotation"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/MapAnnotation","abstract":[]},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIDynamicItem"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","url":"\/documentation\/ticketmastertickets","title":"TicketmasterTickets","role":"collection","kind":"symbol","type":"topic","abstract":[{"text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes.","type":"text"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView/build()":{"type":"topic","abstract":[{"type":"text","text":"create a new instance"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"build","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"TMTicketsModuleHeaderView","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModuleHeaderView"}],"title":"build()","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/build()","url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview\/build()"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView/configure(topLabelText:topLabelTextAlignment:topLabelTextColor:centerLabelText:centerLabelTextAlignment:centerLabelTextColor:bottomLabelText:bottomLabelTextAlignment:bottomLabelTextColor:titleLabelText:titleLabelTextColor:messageLabelText:messageLabelTextColor:messageLabelDetectLinks:messageLabelLinkColor:titleMessageBackgroundColor:gradientAlpha:backgroundAspectRatio:backgroundAspectRatioForced:backgroundColor:backgroundImage:backgroundImageURL:backgroundView:mapCoordinateRegion:mapAnnotation:avContentURL:disableLoopingContent:disableAVAudio:barcode2DValue:qrCodeValue:aztecValue:pdf417Value:headerOverride:)":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/configure(topLabelText:topLabelTextAlignment:topLabelTextColor:centerLabelText:centerLabelTextAlignment:centerLabelTextColor:bottomLabelText:bottomLabelTextAlignment:bottomLabelTextColor:titleLabelText:titleLabelTextColor:messageLabelText:messageLabelTextColor:messageLabelDetectLinks:messageLabelLinkColor:titleMessageBackgroundColor:gradientAlpha:backgroundAspectRatio:backgroundAspectRatioForced:backgroundColor:backgroundImage:backgroundImageURL:backgroundView:mapCoordinateRegion:mapAnnotation:avContentURL:disableLoopingContent:disableAVAudio:barcode2DValue:qrCodeValue:aztecValue:pdf417Value:headerOverride:)","role":"symbol","abstract":[{"type":"text","text":"configure header with various contents"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"configure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"topLabelText","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"topLabelTextAlignment","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSTextAlignment","preciseIdentifier":"c:@E@NSTextAlignment"},{"text":"?, ","kind":"text"},{"text":"topLabelTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"centerLabelText"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"centerLabelTextAlignment"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@NSTextAlignment","kind":"typeIdentifier","text":"NSTextAlignment"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"centerLabelTextColor"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"bottomLabelText"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"bottomLabelTextAlignment","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTextAlignment","text":"NSTextAlignment"},{"text":"?, ","kind":"text"},{"text":"bottomLabelTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"titleLabelText","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"titleLabelTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"text":"messageLabelText","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"messageLabelTextColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"messageLabelDetectLinks"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"messageLabelLinkColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"titleMessageBackgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"text":"gradientAlpha","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"backgroundAspectRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"backgroundAspectRatioForced","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"backgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"backgroundImage"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?, ","kind":"text"},{"text":"backgroundImageURL","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"text":"backgroundView","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"mapCoordinateRegion"},{"kind":"text","text":": "},{"text":"MKCoordinateRegion","preciseIdentifier":"c:@SA@MKCoordinateRegion","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"mapAnnotation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MKAnnotation","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MKAnnotation"},{"text":"?, ","kind":"text"},{"text":"avContentURL","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"?, ","kind":"text"},{"text":"disableLoopingContent","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"disableAVAudio"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"barcode2DValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"qrCodeValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"aztecValue"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"pdf417Value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"headerOverride","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV","text":"TMTicketsPrebuiltModule","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"HeaderOverride","preciseIdentifier":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV14HeaderOverrideV"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","title":"configure(topLabelText:topLabelTextAlignment:topLabelTextColor:centerLabelText:centerLabelTextAlignment:centerLabelTextColor:bottomLabelText:bottomLabelTextAlignment:bottomLabelTextColor:titleLabelText:titleLabelTextColor:messageLabelText:messageLabelTextColor:messageLabelDetectLinks:messageLabelLinkColor:titleMessageBackgroundColor:gradientAlpha:backgroundAspectRatio:backgroundAspectRatioForced:backgroundColor:backgroundImage:backgroundImageURL:backgroundView:mapCoordinateRegion:mapAnnotation:avContentURL:disableLoopingContent:disableAVAudio:barcode2DValue:qrCodeValue:aztecValue:pdf417Value:headerOverride:)","url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview\/configure(toplabeltext:toplabeltextalignment:toplabeltextcolor:centerlabeltext:centerlabeltextalignment:centerlabeltextcolor:bottomlabeltext:bottomlabeltextalignment:bottomlabeltextcolor:titlelabeltext:titlelabeltextcolor:messagelabeltext:m-5amne","kind":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.ticketmaster.TicketmasterTickets/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/s23CustomStringConvertibleP"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView/playAVContent()":{"url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview\/playavcontent()","type":"topic","title":"playAVContent()","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"playAVContent","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/playAVContent()","abstract":[{"type":"text","text":"play AV content (if any)"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"TMTicketsModuleHeaderView","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TMTicketsModuleHeaderView"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"TMTicketsModuleHeaderView","kind":"identifier"}]},{"op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/initWithCoder:","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/initWithFrame:"],"generated":true,"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","value":[{"generated":true,"anchor":"Custom-Modules","title":"Custom Modules","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule"]}],"op":"replace"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsModuleHeaderView"},{"kind":"text","text":" : "},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"}]}]}},{"op":"replace","value":"TMTicketsModuleHeaderView","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/title"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/fragments","value":[{"text":"TMTicketsModuleHeaderView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/navigatorTitle","op":"replace","value":[{"text":"TMTicketsModuleHeaderView","kind":"identifier"}]},{"value":"TMTicketsModule","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/fragments","value":[{"text":"TMTicketsModule","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/navigatorTitle","op":"replace","value":[{"text":"TMTicketsModule","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}