{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TMTicketsViewController","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"This is the recommended way to present the Tickets SDK.","type":"text"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"This class tries to add a ","type":"text"},{"type":"codeVoice","code":"Logout"},{"text":" button to the top-right of the ","type":"text"},{"code":"UINavigationBar","type":"codeVoice"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"Disable this behavior if needed by setting "},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController\/addLogoutButton","isActive":true},{"type":"text","text":" to "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}]}],"name":"Note","type":"aside","style":"note"},{"type":"paragraph","inlineContent":[{"text":"Override the default “My Tickets” title by setting the ","type":"text"},{"code":"title","type":"codeVoice"},{"type":"text","text":" property."}]},{"code":["let ticketsVC = TMTicketsViewController()","ticketsVC.addLogoutButton = false \/\/ default: true","ticketsVC.title = \"Custom Title\"  \/\/ default: \"My Tickets\"","","navigationController?.pushViewController(ticketsVC, animated: true)","\/\/ or","present(ticketsVC, animated: true)"],"type":"codeListing","syntax":null}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController"},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)ASWebAuthenticationPresentationContextProviding","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)NSCoding","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)NSObject","doc:\/\/com.ticketmaster.TicketmasterTickets\/s7CVarArgP","doc:\/\/com.ticketmaster.TicketmasterTickets\/s28CustomDebugStringConvertibleP","doc:\/\/com.ticketmaster.TicketmasterTickets\/s23CustomStringConvertibleP","doc:\/\/com.ticketmaster.TicketmasterTickets\/SQ","doc:\/\/com.ticketmaster.TicketmasterTickets\/SH","doc:\/\/com.ticketmaster.TicketmasterTickets\/s8SendableP","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIAppearanceContainer","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIContentContainer","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIFocusEnvironment","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIStateRestoring","doc:\/\/com.ticketmaster.TicketmasterTickets\/5UIKit23UITraitChangeObservableP","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UITraitEnvironment","doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets"]]},"sections":[],"kind":"symbol","metadata":{"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"TMTicketsViewController"}],"externalID":"c:@M@TicketmasterTickets@objc(cs)TMTicketsViewController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMTicketsViewController","kind":"identifier"}],"title":"TMTicketsViewController","modules":[{"name":"TicketmasterTickets"}],"roleHeading":"Class"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController\/addLogoutButton","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController\/preferredStatusBarStyle"]},{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController\/reload()","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController\/viewDidLoad()","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController\/viewWillAppear(_:)"],"title":"Instance Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmastertickets\/tmticketsviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ticketmastertickets\/tmticketsviewcontroller"]}],"abstract":[{"text":"this class wraps the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView","type":"reference"},{"text":" in a ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" for ease of use"}],"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsViewController/preferredStatusBarStyle":{"kind":"symbol","url":"\/documentation\/ticketmastertickets\/tmticketsviewcontroller\/preferredstatusbarstyle","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preferredStatusBarStyle"},{"text":": ","kind":"text"},{"text":"UIStatusBarStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIStatusBarStyle"}],"abstract":[],"title":"preferredStatusBarStyle","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"preferredStatusBarStyle"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController\/preferredStatusBarStyle"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)ASWebAuthenticationPresentationContextProviding":{"title":"AuthenticationServices.ASWebAuthenticationPresentationContextProviding","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)ASWebAuthenticationPresentationContextProviding"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsViewController/viewDidLoad()":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController\/viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"type":"topic","title":"viewDidLoad()","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/ticketmastertickets\/tmticketsviewcontroller\/viewdidload()"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterTickets/SH":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsViewController/reload()":{"abstract":[{"text":"reload contents of My Events page, fetch fresh orders","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reload"},{"kind":"text","text":"()"}],"title":"reload()","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController\/reload()","url":"\/documentation\/ticketmastertickets\/tmticketsviewcontroller\/reload()","kind":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/SQ","title":"Swift.Equatable"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://com.ticketmaster.TicketmasterTickets/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://com.ticketmaster.TicketmasterTickets/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIContentContainer":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsViewController/initWithCoder:":{"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/ticketmastertickets\/tmticketsviewcontroller\/initwithcoder:","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController\/initWithCoder:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"title":"initWithCoder:"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://com.ticketmaster.TicketmasterTickets/objc(cs)UIViewController":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(cs)UIViewController","title":"UIViewController"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsView":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTicketsView"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView","title":"TMTicketsView","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TMTicketsView"}],"url":"\/documentation\/ticketmastertickets\/tmticketsview","abstract":[{"type":"text","text":"use to render Tickets SDK as a UIView embedded inside of your own UIViewController"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsViewController/initWithNibName:bundle:":{"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/ticketmastertickets\/tmticketsviewcontroller\/initwithnibname:bundle:","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController\/initWithNibName:bundle:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithNibName:bundle:","kind":"identifier"}],"title":"initWithNibName:bundle:"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsViewController/viewWillAppear(_:)":{"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}],"url":"\/documentation\/ticketmastertickets\/tmticketsviewcontroller\/viewwillappear(_:)","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController\/viewWillAppear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewWillAppear"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"title":"viewWillAppear(_:)"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsViewController/addLogoutButton":{"kind":"symbol","abstract":[{"text":"add a ","type":"text"},{"type":"codeVoice","code":"Logout"},{"type":"text","text":" button to the top-right of the "},{"type":"codeVoice","code":"UINavigationBar"}],"role":"symbol","url":"\/documentation\/ticketmastertickets\/tmticketsviewcontroller\/addlogoutbutton","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController\/addLogoutButton","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addLogoutButton","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"addLogoutButton"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)NSObject"},"doc://com.ticketmaster.TicketmasterTickets/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/s8SendableP"},"doc://com.ticketmaster.TicketmasterTickets/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/5UIKit23UITraitChangeObservableP"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIFocusEnvironment"},"doc://com.ticketmaster.TicketmasterTickets/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsViewController":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTicketsViewController"}],"navigatorTitle":[{"text":"TMTicketsViewController","kind":"identifier"}],"type":"topic","title":"TMTicketsViewController","abstract":[{"text":"this class wraps the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView","isActive":true},{"type":"text","text":" in a "},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":" for ease of use"}],"role":"symbol","kind":"symbol","url":"\/documentation\/ticketmastertickets\/tmticketsviewcontroller"},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","url":"\/documentation\/ticketmastertickets","title":"TicketmasterTickets","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes."}]},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)NSCoding":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"TMTicketsViewController","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"TMTicketsViewController"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TMTicketsViewController"}]},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController\/preferredStatusBarStyle"]},{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController\/initWithCoder:","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController\/initWithNibName:bundle:","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController\/viewDidLoad()","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController\/viewWillAppear(_:)"],"title":"Instance Methods"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(cs)UIViewController"]}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"TMTicketsViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController~1preferredStatusBarStyle\/title","op":"replace","value":"preferredStatusBarStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController~1preferredStatusBarStyle\/fragments","value":[{"text":"preferredStatusBarStyle","kind":"identifier"}]},{"value":"viewDidLoad","op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController~1viewDidLoad()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController~1viewDidLoad()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/title","op":"replace","value":"TMTicketsView"},{"value":[{"text":"TMTicketsView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"viewWillAppear:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController~1viewWillAppear(_:)\/fragments"},{"value":"TMTicketsViewController","op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController\/fragments","value":[{"text":"TMTicketsViewController","kind":"identifier"}]}]}]}