{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule"},"topicSections":[{"anchor":"Structures","generated":true,"title":"Structures","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/HeaderOverride"]},{"anchor":"Type-Methods","title":"Type Methods","generated":true,"identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/accountManagerInvoiceAction(event:headerOverride:customIdentifier:)","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/accountManagerMoreTicketActions(event:headerOverride:customIdentifier:)","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/accountManagerSeatUpgrades(event:headerOverride:customIdentifier:)","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/currentPromotionalModules(event:appPromoKey:completion:)","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/hostSeatUpgrades(event:headerOverride:customIdentifier:)","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/venueConcessions(event:headerOverride:showWalletButton:customIdentifier:)","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/venueDirectionsViaAppleMaps(event:headerOverride:customIdentifier:)"]},{"title":"Enumerations","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/ButtonCallbackName","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/ModuleName"],"anchor":"Enumerations","generated":true}],"abstract":[{"type":"text","text":"useful pre-built "},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","type":"reference","isActive":true},{"type":"text","text":" for the Tickets listing page"}],"seeAlsoSections":[{"title":"Custom Modules","anchor":"Custom-Modules","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleDelegate"],"generated":true}],"variants":[{"paths":["\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"TMTicketsPrebuiltModule"}],"externalID":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"TMTicketsPrebuiltModule","kind":"identifier"}],"roleHeading":"Structure","symbolKind":"struct","role":"symbol","title":"TMTicketsPrebuiltModule","modules":[{"name":"TicketmasterTickets"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMTicketsPrebuiltModule","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Example usage:"}]},{"type":"codeListing","syntax":null,"code":["extension MyViewController: TMTicketsModuleDelegate {","            ","    func addCustomModules(event: TMPurchasedEvent, completion: @escaping ([TMTicketsModule]?) -> Void) {","       var modules: [TMTicketsModule] = []","","       \/\/ show an Account Manager More Ticket Actions module","       \/\/ note that this module will only render if Event is an Account Manager Event, otherwise it will not be displayed","       \/\/ this is a standard \"prebuilt\" module that we provide to all our partners","       if let module = TMTicketsPrebuiltModule.accountManagerMoreTicketActions(event: event) {","           modules.append(module)","       }","","       \/\/ show a street-map around the Venue with a Directions button that opens Apple Maps","       \/\/ this is a standard \"prebuilt\" module that we provide to all our partners","       if let module = TMTicketsPrebuiltModule.venueDirectionsViaAppleMaps(event: event) {","           modules.append(module)","       }","        ","       \/\/ show an Account Manager Seat Upgrades module","       \/\/ note that this module will only render if Event is an Account Manager Event, otherwise it will not be displayed","       \/\/ this is a standard \"prebuilt\" module that we provide to all our partners","       if let module = TMTicketsPrebuiltModule.accountManagerSeatUpgrades(event: event) {","           modules.append(module)","       }","","       \/\/ show a Venue Concessions module","       \/\/ this is a standard \"prebuilt\" module that we provide to all our partners","       if let module = TMTicketsPrebuiltModule.venueConcessions(event: event, showWalletButton: true) {","           modules.append(module)","       }","","       \/\/ return list of modules (in the order you want them displayed)","       completion(modules)","   }","}"]}]}],"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule/venueConcessions(event:headerOverride:showWalletButton:customIdentifier:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"venueConcessions","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"event"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV","kind":"typeIdentifier","text":"TMPurchasedEvent"},{"text":", ","kind":"text"},{"text":"headerOverride","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV14HeaderOverrideV","text":"HeaderOverride","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"showWalletButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"customIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"TMTicketsModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Build the Venue Concessions module"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/venueConcessions(event:headerOverride:showWalletButton:customIdentifier:)","title":"venueConcessions(event:headerOverride:showWalletButton:customIdentifier:)","type":"topic","url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule\/venueconcessions(event:headeroverride:showwalletbutton:customidentifier:)","role":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule/hostSeatUpgrades(event:headerOverride:customIdentifier:)":{"role":"symbol","abstract":[{"text":"Build the Seat Upgrades module for HOST tickets only","type":"text"}],"url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule\/hostseatupgrades(event:headeroverride:customidentifier:)","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"hostSeatUpgrades","kind":"identifier"},{"kind":"text","text":"("},{"text":"event","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TMPurchasedEvent","preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV"},{"text":", ","kind":"text"},{"text":"headerOverride","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HeaderOverride","kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV14HeaderOverrideV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"customIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?) -> ","kind":"text"},{"text":"TMTicketsModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/hostSeatUpgrades(event:headerOverride:customIdentifier:)","kind":"symbol","title":"hostSeatUpgrades(event:headerOverride:customIdentifier:)"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule/venueDirectionsViaAppleMaps(event:headerOverride:customIdentifier:)":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/venueDirectionsViaAppleMaps(event:headerOverride:customIdentifier:)","url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule\/venuedirectionsviaapplemaps(event:headeroverride:customidentifier:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"venueDirectionsViaAppleMaps"},{"text":"(","kind":"text"},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TMPurchasedEvent","kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV"},{"kind":"text","text":", "},{"text":"headerOverride","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HeaderOverride","preciseIdentifier":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV14HeaderOverrideV"},{"kind":"text","text":"?, "},{"text":"customIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule","text":"TMTicketsModule","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Build the Venue Directions via Apple Maps module"}],"type":"topic","role":"symbol","title":"venueDirectionsViaAppleMaps(event:headerOverride:customIdentifier:)","kind":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"role":"collection","abstract":[{"type":"text","text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes."}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","kind":"symbol","title":"TicketmasterTickets","type":"topic","url":"\/documentation\/ticketmastertickets"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule":{"title":"TMTicketsPrebuiltModule","role":"symbol","abstract":[{"type":"text","text":"useful pre-built "},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","isActive":true,"type":"reference"},{"type":"text","text":" for the Tickets listing page"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsPrebuiltModule"}],"navigatorTitle":[{"kind":"identifier","text":"TMTicketsPrebuiltModule"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule","url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule","type":"topic","kind":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule/currentPromotionalModules(event:appPromoKey:completion:)":{"abstract":[{"type":"text","text":"Build all current Promotional Modules defined on TM backend that apply to given Event"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"currentPromotionalModules"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV","text":"TMPurchasedEvent"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"appPromoKey"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"promotionalModules"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule","text":"TMTicketsModule","kind":"typeIdentifier"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule\/currentpromotionalmodules(event:apppromokey:completion:)","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/currentPromotionalModules(event:appPromoKey:completion:)","title":"currentPromotionalModules(event:appPromoKey:completion:)","type":"topic","role":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule/accountManagerSeatUpgrades(event:headerOverride:customIdentifier:)":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/accountManagerSeatUpgrades(event:headerOverride:customIdentifier:)","url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule\/accountmanagerseatupgrades(event:headeroverride:customidentifier:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accountManagerSeatUpgrades"},{"kind":"text","text":"("},{"text":"event","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TMPurchasedEvent","kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV"},{"text":", ","kind":"text"},{"text":"headerOverride","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV14HeaderOverrideV","text":"HeaderOverride"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"customIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule","text":"TMTicketsModule"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Build the NAM Account Manager Seat Upgrades module"}],"type":"topic","role":"symbol","title":"accountManagerSeatUpgrades(event:headerOverride:customIdentifier:)","kind":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule":{"navigatorTitle":[{"text":"TMTicketsModule","kind":"identifier"}],"kind":"symbol","title":"TMTicketsModule","role":"symbol","abstract":[{"type":"text","text":"create a custom module to be displayed underneath the user’s list of Tickets on the Tickets listing page"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsModule"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","url":"\/documentation\/ticketmastertickets\/tmticketsmodule","type":"topic"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule/ModuleName":{"url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule\/modulename","kind":"symbol","title":"TMTicketsPrebuiltModule.ModuleName","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/ModuleName","role":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ModuleName"}],"navigatorTitle":[{"kind":"identifier","text":"ModuleName"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TMTicketsModuleHeaderView"}],"abstract":[{"type":"text","text":"quickly build a UIView for "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView"}],"kind":"symbol","type":"topic","title":"TMTicketsModuleHeaderView","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTicketsModuleHeaderView"}],"url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule/accountManagerMoreTicketActions(event:headerOverride:customIdentifier:)":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/accountManagerMoreTicketActions(event:headerOverride:customIdentifier:)","abstract":[{"text":"Build the NAM Account Manager More Ticket Actions module","type":"text"}],"title":"accountManagerMoreTicketActions(event:headerOverride:customIdentifier:)","kind":"symbol","url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule\/accountmanagermoreticketactions(event:headeroverride:customidentifier:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"accountManagerMoreTicketActions","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"event"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV","text":"TMPurchasedEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"headerOverride"},{"kind":"text","text":": "},{"text":"HeaderOverride","kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV14HeaderOverrideV"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"customIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule","text":"TMTicketsModule"},{"kind":"text","text":"?"}],"role":"symbol","type":"topic"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule/ButtonCallbackName":{"navigatorTitle":[{"text":"ButtonCallbackName","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/ButtonCallbackName","title":"TMTicketsPrebuiltModule.ButtonCallbackName","abstract":[],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule\/buttoncallbackname","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ButtonCallbackName"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleDelegate":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TMTicketsModuleDelegate"}],"abstract":[{"type":"text","text":"optional delegate to implement prebuilt and custom "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule"},{"text":" to be rendered on the Tickets listing page","type":"text"}],"kind":"symbol","type":"topic","title":"TMTicketsModuleDelegate","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"TMTicketsModuleDelegate","kind":"identifier"}],"url":"\/documentation\/ticketmastertickets\/tmticketsmoduledelegate"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule/accountManagerInvoiceAction(event:headerOverride:customIdentifier:)":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"accountManagerInvoiceAction","kind":"identifier"},{"kind":"text","text":"("},{"text":"event","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV","text":"TMPurchasedEvent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"headerOverride","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV14HeaderOverrideV","text":"HeaderOverride"},{"kind":"text","text":"?, "},{"text":"customIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule","kind":"typeIdentifier","text":"TMTicketsModule"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Build the NAM Account Manager Invoice Action module"}],"url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule\/accountmanagerinvoiceaction(event:headeroverride:customidentifier:)","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/accountManagerInvoiceAction(event:headerOverride:customIdentifier:)","title":"accountManagerInvoiceAction(event:headerOverride:customIdentifier:)"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule/HeaderOverride":{"url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule\/headeroverride","type":"topic","title":"TMTicketsPrebuiltModule.HeaderOverride","abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/HeaderOverride","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeaderOverride"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HeaderOverride"}]}},"variantOverrides":[{"patch":[{"value":"TMTicketsModule","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/title","op":"replace"},{"value":[{"kind":"identifier","text":"TMTicketsModule"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/fragments"},{"value":[{"kind":"identifier","text":"TMTicketsModule"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/navigatorTitle"},{"value":"TMTicketsModuleHeaderView","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/fragments","value":[{"text":"TMTicketsModuleHeaderView","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"TMTicketsModuleHeaderView"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}