{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TMTicketsModule","kind":"identifier"}]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"overview","text":"Overview","type":"heading"},{"inlineContent":[{"text":"some useful modules have already been created for you, see ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule","type":"reference"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"headers can be easily created with ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView"}]},{"inlineContent":[{"text":"Example usage:","type":"text"}],"type":"paragraph"},{"syntax":null,"code":["\/\/ build a UIView for the header","\/\/  we have a handy method to build module UI easily, this includes:","\/\/   * text","\/\/   * images","\/\/   * maps","\/\/   * QR codes","\/\/   * 2D barcodes","\/\/   * videos","let headerView = TMModuleHeaderView.build()","","\/\/ multiple configure(...) methods are available","\/\/  we will use the one for background images","headerView.configure(backgroundImage: backgroundImage)","","\/\/ build header display","\/\/  any UIView will work here for headerView, not just a TMModuleHeaderView","let headerDisplay = TMTicketsModule.HeaderDisplay(view: headerView as UIView)","","\/\/ build action buttons that open a webpage","let webpageSettings = TMTicketsModule.WebpageSettings(","    pageTitle: \"Ball Arena\",","    urlRequest: URLRequest(url: URL(string: \"https:\/\/www.ballarena.com\/arena-policies-faq\")!))","let actionButton = TMTicketsModule.ActionButton(","    title: \"Venue Info\", \/\/ what user will see, you should localize this text","    callbackValue: \"venueInfo\", \/\/ non-localized value, for your own code\/analytics","    webpageSettings: webpageSettings)","","\/\/ modules can have:","\/\/  1. header only (no buttons)","\/\/  2. buttons only (no header)","\/\/  3. both header and buttons","","\/\/ build module","return TMTicketsModule(identifier: \"com.myDemoApp.venueInfo\", \/\/ a name unique to your app","                       headerDisplay: headerDisplay,","                       actionButtons: [actionButton]) \/\/ you can show 0 to 3 buttons"],"type":"codeListing"}],"kind":"content"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)NSObject","doc:\/\/com.ticketmaster.TicketmasterTickets\/s7CVarArgP","doc:\/\/com.ticketmaster.TicketmasterTickets\/SL","doc:\/\/com.ticketmaster.TicketmasterTickets\/s28CustomDebugStringConvertibleP","doc:\/\/com.ticketmaster.TicketmasterTickets\/s23CustomStringConvertibleP","doc:\/\/com.ticketmaster.TicketmasterTickets\/SQ","doc:\/\/com.ticketmaster.TicketmasterTickets\/SH"]}],"abstract":[{"type":"text","text":"create a custom module to be displayed underneath the user’s list of Tickets on the Tickets listing page"}],"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ticketmastertickets\/tmticketsmodule"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ticketmastertickets\/tmticketsmodule"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/ActionButton","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/HeaderDisplay-swift.class","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/OAuthCookieSettings","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/WebpageSettings"],"title":"Classes"},{"title":"Operators","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/_(_:_:)-3tm1z"]},{"title":"Initializers","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/init(identifier:headerDisplay:actionButtons:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/actionButtons","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/headerDisplay-swift.property","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/identifier"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/isEqual(_:)"]},{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/moduleArray(jsonDict:)"],"title":"Type Methods"},{"generated":true,"identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/Comparable-Implementations"],"title":"Default Implementations"}],"kind":"symbol","metadata":{"externalID":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule","role":"symbol","symbolKind":"class","title":"TMTicketsModule","modules":[{"name":"TicketmasterTickets"}],"roleHeading":"Class","navigatorTitle":[{"text":"TMTicketsModule","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TMTicketsModule","kind":"identifier"}]},"seeAlsoSections":[{"title":"Custom Modules","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleDelegate"],"generated":true}],"references":{"doc://com.ticketmaster.TicketmasterTickets/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)NSObject"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule/isEqual(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","title":"isEqual(_:)","abstract":[],"url":"\/documentation\/ticketmastertickets\/tmticketsmodule\/isequal(_:)","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/isEqual(_:)"},"doc://com.ticketmaster.TicketmasterTickets/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule/identifier":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","type":"topic","role":"symbol","title":"identifier","abstract":[{"text":"a unique module identifier (example: “com.myapp.mymodule”)","type":"text"}],"url":"\/documentation\/ticketmastertickets\/tmticketsmodule\/identifier","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/identifier"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule/_(_:_:)-3tm1z":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"<","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule","text":"TMTicketsModule"},{"kind":"text","text":", "},{"text":"TMTicketsModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","type":"topic","role":"symbol","title":"<(_:_:)","abstract":[],"url":"\/documentation\/ticketmastertickets\/tmticketsmodule\/_(_:_:)-3tm1z","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/_(_:_:)-3tm1z"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule/ActionButton":{"type":"topic","url":"\/documentation\/ticketmastertickets\/tmticketsmodule\/actionbutton","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/ActionButton","navigatorTitle":[{"kind":"identifier","text":"ActionButton"}],"abstract":[],"title":"TMTicketsModule.ActionButton","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionButton","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterTickets/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/SQ","title":"Swift.Equatable"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule/actionButtons":{"type":"topic","url":"\/documentation\/ticketmastertickets\/tmticketsmodule\/actionbuttons","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/actionButtons","abstract":[{"text":"0 to 3 action buttons to display to the user (each with their own behavior)","type":"text"}],"title":"actionButtons","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionButtons","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets15TMTicketsModuleC12ActionButtonC","text":"ActionButton"},{"text":"]?","kind":"text"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule/Comparable-Implementations":{"title":"Comparable Implementations","abstract":[],"role":"collectionGroup","kind":"article","url":"\/documentation\/ticketmastertickets\/tmticketsmodule\/comparable-implementations","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/Comparable-Implementations"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleDelegate":{"type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"TMTicketsModuleDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TMTicketsModuleDelegate"}],"kind":"symbol","abstract":[{"type":"text","text":"optional delegate to implement prebuilt and custom "},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","isActive":true,"type":"reference"},{"text":" to be rendered on the Tickets listing page","type":"text"}],"url":"\/documentation\/ticketmastertickets\/tmticketsmoduledelegate","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleDelegate","title":"TMTicketsModuleDelegate"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule/headerDisplay-swift.property":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"headerDisplay"},{"kind":"text","text":": "},{"text":"HeaderDisplay","kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets15TMTicketsModuleC13HeaderDisplayC"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","role":"symbol","title":"headerDisplay","abstract":[{"type":"text","text":"an optional header image or view to display above buttons (uses aspectFit)"}],"url":"\/documentation\/ticketmastertickets\/tmticketsmodule\/headerdisplay-swift.property","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/headerDisplay-swift.property"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule/init(identifier:headerDisplay:actionButtons:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"headerDisplay","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:19TicketmasterTickets15TMTicketsModuleC13HeaderDisplayC","kind":"typeIdentifier","text":"HeaderDisplay"},{"text":"?, ","kind":"text"},{"text":"actionButtons","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets15TMTicketsModuleC12ActionButtonC","text":"ActionButton"},{"kind":"text","text":"]?)"}],"kind":"symbol","type":"topic","role":"symbol","title":"init(identifier:headerDisplay:actionButtons:)","abstract":[{"type":"text","text":"create a module with the given identifier, header, and action buttons"}],"url":"\/documentation\/ticketmastertickets\/tmticketsmodule\/init(identifier:headerdisplay:actionbuttons:)","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/init(identifier:headerDisplay:actionButtons:)"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule/OAuthCookieSettings":{"title":"TMTicketsModule.OAuthCookieSettings","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"OAuthCookieSettings","kind":"identifier"}],"abstract":[],"url":"\/documentation\/ticketmastertickets\/tmticketsmodule\/oauthcookiesettings","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/OAuthCookieSettings","navigatorTitle":[{"text":"OAuthCookieSettings","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule":{"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsPrebuiltModule"}],"navigatorTitle":[{"kind":"identifier","text":"TMTicketsPrebuiltModule"}],"kind":"symbol","abstract":[{"text":"useful pre-built ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","isActive":true},{"text":" for the Tickets listing page","type":"text"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule","url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule","title":"TMTicketsPrebuiltModule"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule/HeaderDisplay-swift.class":{"url":"\/documentation\/ticketmastertickets\/tmticketsmodule\/headerdisplay-swift.class","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeaderDisplay"}],"navigatorTitle":[{"text":"HeaderDisplay","kind":"identifier"}],"type":"topic","title":"TMTicketsModule.HeaderDisplay","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/HeaderDisplay-swift.class"},"doc://com.ticketmaster.TicketmasterTickets/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(cs)NSObject","title":"NSObject"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/ticketmastertickets","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","abstract":[{"text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes.","type":"text"}],"title":"TicketmasterTickets"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule/moduleArray(jsonDict:)":{"title":"moduleArray(jsonDict:)","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/moduleArray(jsonDict:)","abstract":[],"role":"symbol","url":"\/documentation\/ticketmastertickets\/tmticketsmodule\/modulearray(jsondict:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moduleArray","kind":"identifier"},{"text":"(","kind":"text"},{"text":"jsonDict","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]) -> ["},{"text":"TMTicketsModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule"},{"text":"]?","kind":"text"}],"type":"topic"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"TMTicketsModule","kind":"identifier"}],"title":"TMTicketsModule","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsModule"}],"url":"\/documentation\/ticketmastertickets\/tmticketsmodule","abstract":[{"type":"text","text":"create a custom module to be displayed underneath the user’s list of Tickets on the Tickets listing page"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","role":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/SH":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/SH","title":"Swift.Hashable"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TMTicketsModuleHeaderView","kind":"identifier"}],"url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview","type":"topic","role":"symbol","abstract":[{"text":"quickly build a UIView for ","type":"text"},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView","type":"reference","isActive":true}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView","navigatorTitle":[{"kind":"identifier","text":"TMTicketsModuleHeaderView"}],"title":"TMTicketsModuleHeaderView"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule/WebpageSettings":{"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/WebpageSettings","title":"TMTicketsModule.WebpageSettings","type":"topic","url":"\/documentation\/ticketmastertickets\/tmticketsmodule\/webpagesettings","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WebpageSettings"}],"navigatorTitle":[{"text":"WebpageSettings","kind":"identifier"}],"kind":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.ticketmaster.TicketmasterTickets/SL":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/SL","title":"Swift.Comparable"},"doc://com.ticketmaster.TicketmasterTickets/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"TMTicketsModule"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"TMTicketsModule","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"TMTicketsModule","kind":"identifier"}]},{"op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/isEqual(_:)"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}]},{"op":"replace","value":[{"title":"Custom Modules","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView"],"generated":true}],"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"TMTicketsModule","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace"},{"value":"TMTicketsModule","op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/title"},{"value":[{"text":"TMTicketsModule","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/fragments","op":"replace"},{"value":"TMTicketsModuleHeaderView","op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/fragments","value":[{"text":"TMTicketsModuleHeaderView","kind":"identifier"}]}]}]}