{"sections":[],"metadata":{"roleHeading":"Protocol","modules":[{"name":"TicketmasterTickets"}],"navigatorTitle":[{"text":"TMTicketsModuleDelegate","kind":"identifier"}],"title":"TMTicketsModuleDelegate","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsModuleDelegate"}],"role":"symbol","externalID":"s:19TicketmasterTickets23TMTicketsModuleDelegateP"},"abstract":[{"type":"text","text":"optional delegate to implement prebuilt and custom "},{"isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","type":"reference"},{"type":"text","text":" to be rendered on the Tickets listing page"}],"topicSections":[{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleDelegate\/addCustomModules(event:completion:)","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleDelegate\/handleModuleActionButton(event:module:button:completion:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets"]]},"seeAlsoSections":[{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView"],"generated":true,"anchor":"Custom-Modules","title":"Custom Modules"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmastertickets\/tmticketsmoduledelegate"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsModuleDelegate"},{"text":" : AnyObject","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleDelegate"},"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView":{"type":"topic","abstract":[{"type":"text","text":"quickly build a UIView for "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView"}],"url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview","kind":"symbol","title":"TMTicketsModuleHeaderView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsModuleHeaderView"}],"role":"symbol","navigatorTitle":[{"text":"TMTicketsModuleHeaderView","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleDelegate/addCustomModules(event:completion:)":{"type":"topic","url":"\/documentation\/ticketmastertickets\/tmticketsmoduledelegate\/addcustommodules(event:completion:)","kind":"symbol","title":"addCustomModules(event:completion:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"addCustomModules","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"text":"TMPurchasedEvent","preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"customModuleArray"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule","text":"TMTicketsModule"},{"text":"]?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"abstract":[{"text":"Method is invoked when the user is viewing a specific Event. Client app needs to define an array of custom modules (if any) and return them to the Tickets SDK.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleDelegate\/addCustomModules(event:completion:)"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule":{"navigatorTitle":[{"text":"TMTicketsPrebuiltModule","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTicketsPrebuiltModule"}],"kind":"symbol","abstract":[{"text":"useful pre-built ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule"},{"text":" for the Tickets listing page","type":"text"}],"url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule","title":"TMTicketsPrebuiltModule","role":"symbol","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"url":"\/documentation\/ticketmastertickets","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","role":"collection","title":"TicketmasterTickets","kind":"symbol","abstract":[{"text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes.","type":"text"}],"type":"topic"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleDelegate/handleModuleActionButton(event:module:button:completion:)":{"type":"topic","url":"\/documentation\/ticketmastertickets\/tmticketsmoduledelegate\/handlemoduleactionbutton(event:module:button:completion:)","kind":"symbol","title":"handleModuleActionButton(event:module:button:completion:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handleModuleActionButton"},{"kind":"text","text":"("},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV","text":"TMPurchasedEvent"},{"kind":"text","text":", "},{"text":"module","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TMTicketsModule","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"button","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TMTicketsModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule"},{"text":".","kind":"text"},{"text":"ActionButton","kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets15TMTicketsModuleC12ActionButtonC"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"openWebpageSettings","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule","text":"TMTicketsModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"WebpageSettings","preciseIdentifier":"s:19TicketmasterTickets15TMTicketsModuleC15WebpageSettingsC"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method is invoked if user has pressed a button on a custom module, and unique handling is required."}],"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleDelegate\/handleModuleActionButton(event:module:button:completion:)"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleDelegate":{"url":"\/documentation\/ticketmastertickets\/tmticketsmoduledelegate","role":"symbol","abstract":[{"type":"text","text":"optional delegate to implement prebuilt and custom "},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","isActive":true},{"type":"text","text":" to be rendered on the Tickets listing page"}],"navigatorTitle":[{"text":"TMTicketsModuleDelegate","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsModuleDelegate"}],"title":"TMTicketsModuleDelegate"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsModule"}],"navigatorTitle":[{"kind":"identifier","text":"TMTicketsModule"}],"title":"TMTicketsModule","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","url":"\/documentation\/ticketmastertickets\/tmticketsmodule","abstract":[{"type":"text","text":"create a custom module to be displayed underneath the user’s list of Tickets on the Tickets listing page"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/title","value":"TMTicketsModuleHeaderView"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/fragments","value":[{"text":"TMTicketsModuleHeaderView","kind":"identifier"}],"op":"replace"},{"value":[{"text":"TMTicketsModuleHeaderView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/title","value":"TMTicketsModule"},{"value":[{"text":"TMTicketsModule","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/fragments","op":"replace"},{"value":[{"text":"TMTicketsModule","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/navigatorTitle","op":"replace"}]}]}