{"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmastertickets\/tmtickets"]},{"paths":["\/documentation\/ticketmastertickets\/tmtickets"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","topicSections":[{"title":"Structures","anchor":"Structures","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/BrandingColors","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/TicketsError"],"generated":true},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/analyticsDelegate","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/brandingColorButtonOverride","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/brandingColorNavBarOverride","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/brandingColorsOverride","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/brandingEventsPageBackgroundOverride","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/brandingTeamLogoImage","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/doNotPresentTeamLoginIfHostLoggedIn","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/moduleDelegate","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/navBarButtonTitle","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/orderDelegate","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/sdkBuildInfo","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/secureEntryVersion","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/useNewAccountsManager","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/userTrackingEnabled","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/version"],"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/configure(callSource:success:failure:)","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/display(orderOrEventId:type:action:callSource:)","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/start(ticketsView:callSource:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"generated":true,"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/shared"]},{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/ActionType","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/IdType"],"generated":true,"title":"Enumerations","anchor":"Enumerations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"roleHeading":"Class","title":"TMTickets","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TMTickets","kind":"identifier"}],"modules":[{"name":"TicketmasterTickets"}],"externalID":"c:@M@TicketmasterTickets@objc(cs)TMTickets","navigatorTitle":[{"kind":"identifier","text":"TMTickets"}],"symbolKind":"class"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)NSObject","doc:\/\/com.ticketmaster.TicketmasterTickets\/s7CVarArgP","doc:\/\/com.ticketmaster.TicketmasterTickets\/s28CustomDebugStringConvertibleP","doc:\/\/com.ticketmaster.TicketmasterTickets\/s23CustomStringConvertibleP","doc:\/\/com.ticketmaster.TicketmasterTickets\/SQ","doc:\/\/com.ticketmaster.TicketmasterTickets\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"abstract":[{"text":"main class of Tickets SDK, intended to be used as singleton","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTickets"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Overview","type":"heading","level":2,"anchor":"overview"},{"inlineContent":[{"text":"Example:","type":"text"}],"type":"paragraph"},{"code":["TMTickets.shared.configure { }"],"type":"codeListing","syntax":null}],"kind":"content"}],"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/sdkBuildInfo":{"type":"topic","title":"sdkBuildInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"sdkBuildInfo","kind":"identifier"},{"kind":"text","text":": "},{"text":"JSONDictionary","kind":"typeIdentifier","preciseIdentifier":"s:22TicketmasterFoundation14JSONDictionarya"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/sdkBuildInfo","abstract":[],"kind":"symbol","url":"\/documentation\/ticketmastertickets\/tmtickets\/sdkbuildinfo","role":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/s23CustomStringConvertibleP"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/shared":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/shared","title":"shared","kind":"symbol","url":"\/documentation\/ticketmastertickets\/tmtickets\/shared","role":"symbol","type":"topic","abstract":[{"type":"text","text":"shared singleton"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"shared","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTickets","kind":"typeIdentifier","text":"TMTickets"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/analyticsDelegate":{"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/analyticsDelegate","title":"analyticsDelegate","url":"\/documentation\/ticketmastertickets\/tmtickets\/analyticsdelegate","kind":"symbol","role":"symbol","abstract":[{"text":"optional delegate to be informed of User behavior","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"analyticsDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:19TicketmasterTickets26TMTicketsAnalyticsDelegateP","kind":"typeIdentifier","text":"TMTicketsAnalyticsDelegate"},{"text":"?","kind":"text"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/moduleDelegate":{"role":"symbol","type":"topic","url":"\/documentation\/ticketmastertickets\/tmtickets\/moduledelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"moduleDelegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets23TMTicketsModuleDelegateP","text":"TMTicketsModuleDelegate"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/moduleDelegate","abstract":[{"type":"text","text":"optional delegate to implement prebuilt and custom "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule"},{"type":"text","text":" to be rendered on the Tickets listing page"}],"title":"moduleDelegate"},"doc://com.ticketmaster.TicketmasterTickets/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/navBarButtonTitle":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/navBarButtonTitle","role":"symbol","url":"\/documentation\/ticketmastertickets\/tmtickets\/navbarbuttontitle","title":"navBarButtonTitle","abstract":[{"text":"present an button in the top-right Navbar on the Tickets page with the given localized title, ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" = no button (default)","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"navBarButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics":{"kind":"symbol","title":"TMTickets.Analytics","url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics","role":"symbol","abstract":[{"text":"analytics for User behavior","type":"text"}],"navigatorTitle":[{"text":"Analytics","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Analytics","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/doNotPresentTeamLoginIfHostLoggedIn":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/doNotPresentTeamLoginIfHostLoggedIn","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"doNotPresentTeamLoginIfHostLoggedIn","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"doNotPresentTeamLoginIfHostLoggedIn","kind":"symbol","url":"\/documentation\/ticketmastertickets\/tmtickets\/donotpresentteamloginifhostloggedin","type":"topic","abstract":[{"type":"text","text":"do not auto-present Team Login if Host is already Logged In"}]},"doc://com.ticketmaster.TicketmasterTickets/SH":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/ActionType":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ActionType","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/ActionType","title":"TMTickets.ActionType","url":"\/documentation\/ticketmastertickets\/tmtickets\/actiontype","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ActionType"}],"abstract":[{"type":"text","text":"action to perform upon completion of "},{"isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/display(orderOrEventId:type:action:callSource:)","type":"reference"}],"type":"topic"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/BrandingColors":{"type":"topic","abstract":[{"type":"text","text":"Set on "},{"isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/brandingColorsOverride","type":"reference"},{"type":"text","text":" to customize the color of UI elements by overridding their respective properties."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BrandingColors","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/BrandingColors","title":"TMTickets.BrandingColors","navigatorTitle":[{"kind":"identifier","text":"BrandingColors"}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/brandingcolors"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/secureEntryVersion":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/secureEntryVersion","url":"\/documentation\/ticketmastertickets\/tmtickets\/secureentryversion","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"secureEntryVersion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"secureEntryVersion","type":"topic","abstract":[{"type":"text","text":"version number for SecureEntry SDK"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/display(orderOrEventId:type:action:callSource:)":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/display(orderOrEventId:type:action:callSource:)","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"display"},{"kind":"text","text":"("},{"text":"orderOrEventId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"text":"IdType","kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets9TMTicketsC6IdTypeO"},{"text":", ","kind":"text"},{"text":"action","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:19TicketmasterTickets9TMTicketsC10ActionTypeO","text":"ActionType","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"callSource","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"title":"display(orderOrEventId:type:action:callSource:)","url":"\/documentation\/ticketmastertickets\/tmtickets\/display(orderoreventid:type:action:callsource:)","abstract":[{"type":"text","text":"display Tickets listing for a particular Order or Event, if not found show the My Events page"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/brandingColorButtonOverride":{"title":"brandingColorButtonOverride","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/brandingColorButtonOverride","url":"\/documentation\/ticketmastertickets\/tmtickets\/brandingcolorbuttonoverride","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"brandingColorButtonOverride","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"text":"override normal branding colors with Ticketmaster blue on certain buttons leading to Ticketmaster operations (Login, Transfer, Sell, Orders, Modules)","type":"text"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/configure(callSource:success:failure:)":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/configure(callSource:success:failure:)","type":"topic","abstract":[{"text":"configure Tickets SDK using settings from Authentication SDK","type":"text"}],"title":"configure(callSource:success:failure:)","kind":"symbol","role":"symbol","url":"\/documentation\/ticketmastertickets\/tmtickets\/configure(callsource:success:failure:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"configure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callSource","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"success","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":", "},{"text":"failure","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/TicketsError":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/TicketsError","kind":"symbol","title":"TMTickets.TicketsError","abstract":[{"text":"a collection of typical errors returned by TicketsSDK, does not include various networking errors","type":"text"}],"type":"topic","navigatorTitle":[{"text":"TicketsError","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ticketmastertickets\/tmtickets\/ticketserror","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TicketsError"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","kind":"symbol","title":"TicketmasterTickets","url":"\/documentation\/ticketmastertickets","role":"collection","type":"topic","abstract":[{"type":"text","text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes."}]},"doc://com.ticketmaster.TicketmasterTickets/SQ":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/brandingColorsOverride":{"title":"brandingColorsOverride","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brandingColorsOverride","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BrandingColors","kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets9TMTicketsC14BrandingColorsV"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"override branding colors set in Authentication SDK"}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/brandingcolorsoverride","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/brandingColorsOverride","role":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/useNewAccountsManager":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useNewAccountsManager","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ticketmastertickets\/tmtickets\/usenewaccountsmanager","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/useNewAccountsManager","title":"useNewAccountsManager","abstract":[{"text":"use new Team AccountsManager website","type":"text"}]},"doc://com.ticketmaster.TicketmasterTickets/objc(cs)NSObject":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/brandingEventsPageBackgroundOverride":{"type":"topic","abstract":[{"type":"text","text":"override default events page background"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brandingEventsPageBackgroundOverride","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","kind":"symbol","title":"brandingEventsPageBackgroundOverride","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/brandingEventsPageBackgroundOverride","url":"\/documentation\/ticketmastertickets\/tmtickets\/brandingeventspagebackgroundoverride"},"doc://com.ticketmaster.TicketmasterTickets/s7CVarArgP":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/brandingColorNavBarOverride":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/brandingColorNavBarOverride","abstract":[{"text":"do not brand navigation bar on Tickets SDK","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"brandingColorNavBarOverride","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","title":"brandingColorNavBarOverride","kind":"symbol","url":"\/documentation\/ticketmastertickets\/tmtickets\/brandingcolornavbaroverride"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/userTrackingEnabled":{"title":"userTrackingEnabled","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/userTrackingEnabled","url":"\/documentation\/ticketmastertickets\/tmtickets\/usertrackingenabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"userTrackingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[{"text":"enable or disable User Tracking","type":"text"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/brandingTeamLogoImage":{"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/brandingTeamLogoImage","title":"brandingTeamLogoImage","url":"\/documentation\/ticketmastertickets\/tmtickets\/brandingteamlogoimage","kind":"symbol","role":"symbol","abstract":[{"text":"configure Team’s logo on Account dropdown at the top of the Events listing page","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"brandingTeamLogoImage","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?"}]},"doc://com.ticketmaster.TicketmasterTickets/objc(pl)NSObject":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTickets"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets","title":"TMTickets","url":"\/documentation\/ticketmastertickets\/tmtickets","role":"symbol","navigatorTitle":[{"text":"TMTickets","kind":"identifier"}],"abstract":[{"type":"text","text":"main class of Tickets SDK, intended to be used as singleton"}],"type":"topic"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/version":{"url":"\/documentation\/ticketmastertickets\/tmtickets\/version","title":"version","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/version","type":"topic","abstract":[{"text":"version number for Tickets SDK","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"version"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsView":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TMTicketsView","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"TMTicketsView","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView","title":"TMTicketsView","url":"\/documentation\/ticketmastertickets\/tmticketsview","abstract":[{"text":"use to render Tickets SDK as a UIView embedded inside of your own UIViewController","type":"text"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/IdType":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"IdType","kind":"identifier"}],"abstract":[{"type":"text","text":"search for Event or Order on "},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/display(orderOrEventId:type:action:callSource:)","type":"reference","isActive":true}],"role":"symbol","title":"TMTickets.IdType","navigatorTitle":[{"text":"IdType","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/IdType","kind":"symbol","url":"\/documentation\/ticketmastertickets\/tmtickets\/idtype"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/start(ticketsView:callSource:)":{"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/start(ticketsView:callSource:)","title":"start(ticketsView:callSource:)","url":"\/documentation\/ticketmastertickets\/tmtickets\/start(ticketsview:callsource:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"method for connecting a "},{"isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView","type":"reference"},{"type":"text","text":" you have initialized yourself to the Tickets SDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"text":"(","kind":"text"},{"text":"ticketsView","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsView","text":"TMTicketsView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callSource"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule":{"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","navigatorTitle":[{"kind":"identifier","text":"TMTicketsModule"}],"abstract":[{"text":"create a custom module to be displayed underneath the user’s list of Tickets on the Tickets listing page","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsModule"}],"role":"symbol","kind":"symbol","title":"TMTicketsModule","url":"\/documentation\/ticketmastertickets\/tmticketsmodule"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/orderDelegate":{"url":"\/documentation\/ticketmastertickets\/tmtickets\/orderdelegate","title":"orderDelegate","abstract":[{"type":"text","text":"optional delegate to be informed of non-analytics User-actions"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"orderDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets22TMTicketsOrderDelegateP","text":"TMTicketsOrderDelegate"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/orderDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"TMTickets"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"TMTickets","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"TMTickets","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTickets"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]}},{"value":"TMTickets","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/title","op":"replace"},{"value":[{"kind":"identifier","text":"TMTickets"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TMTickets"}]},{"value":"TMTicketsView","op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/title"},{"value":[{"kind":"identifier","text":"TMTicketsView"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"TMTicketsView"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/title","op":"replace","value":"TMTicketsModule"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/fragments","value":[{"text":"TMTicketsModule","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"TMTicketsModule"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/navigatorTitle","op":"replace"}]}]}