{"kind":"symbol","variants":[{"paths":["\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/init(identifier:date:discoveryevent:eventidentifier:eventname:attractionidentifier:attractionname:venueidentifier:venuename:majorcategoryname:minorcategoryname:promoteridentifier:edptype:isresale:ticketquantity:currencycode:basepricetotal:s-4hdeh"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"date","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"discoveryEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:24TicketmasterDiscoveryAPI0B5EventV","text":"DiscoveryEvent"},{"text":"? = nil, ","kind":"text"},{"text":"eventIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"eventName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"attractionIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"attractionName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"venueIdentifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"venueName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"majorCategoryName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"minorCategoryName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"promoterIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"edpType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"isResale"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"text":"ticketQuantity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":"? = nil, ","kind":"text"},{"text":"currencyCode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"basePriceTotal"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber","text":"NSDecimalNumber"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"shippingTotal"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSDecimalNumber","text":"NSDecimalNumber","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"orderProcessingFeeTotal"},{"kind":"text","text":": "},{"text":"NSDecimalNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber"},{"text":"? = nil, ","kind":"text"},{"text":"upsellTotal","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber","text":"NSDecimalNumber"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"voucherDiscountTotal"},{"text":": ","kind":"text"},{"text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"taxTotal","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDecimalNumber","text":"NSDecimalNumber","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"grandTotal"},{"kind":"text","text":": "},{"text":"NSDecimalNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"items"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:20TicketmasterPurchase15TMPurchaseOrderC4ItemC","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/Item","text":"Item","kind":"typeIdentifier"},{"text":"]? = nil, ","kind":"text"},{"text":"billingCountry","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"billingPostalCode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"billingStateProvince","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"paymentMethod"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"shippingMethod"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"rawJSON"},{"text":": ","kind":"text"},{"text":"JSONDictionary","kind":"typeIdentifier","preciseIdentifier":"s:22TicketmasterFoundation14JSONDictionarya"},{"text":"? = nil)","kind":"text"}]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"TicketmasterPurchase"}],"symbolKind":"init","title":"init(identifier:date:discoveryEvent:eventIdentifier:eventName:attractionIdentifier:attractionName:venueIdentifier:venueName:majorCategoryName:minorCategoryName:promoterIdentifier:edpType:isResale:ticketQuantity:currencyCode:basePriceTotal:shippingTotal:orderProcessingFeeTotal:upsellTotal:voucherDiscountTotal:taxTotal:grandTotal:items:billingCountry:billingPostalCode:billingStateProvince:paymentMethod:shippingMethod:rawJSON:)","role":"symbol","externalID":"s:20TicketmasterPurchase15TMPurchaseOrderC10identifier4date14discoveryEvent15eventIdentifier0I4Name010attractionJ00lK005venueJ00mK0013majorCategoryK005minoroK008promoterJ07edpType8isResale14ticketQuantity12currencyCode14basePriceTotal13shippingTotal23orderProcessingFeeTotal11upsellTotal20voucherDiscountTotal8taxTotal10grandTotal5items14billingCountry013billingPostalY020billingStateProvince13paymentMethod14shippingMethod7rawJSONACSSSg_10Foundation4DateVSg0A12DiscoveryAPI09DiscoveryH0VSgA6_A6_A6_A6_A6_A6_A6_A6_A6_A6_SbSiSgA6_So15NSDecimalNumberCSgA18_A18_A18_A18_A18_A18_SayAC4ItemCGSgA6_A6_A6_A6_A6_SDySSypGSgtcfc","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"identifier","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"date","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?, ","kind":"text"},{"text":"discoveryEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DiscoveryEvent","kind":"typeIdentifier","preciseIdentifier":"s:24TicketmasterDiscoveryAPI0B5EventV"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"eventIdentifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"eventName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"attractionIdentifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"attractionName"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"venueIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"venueName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"majorCategoryName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"minorCategoryName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"promoterIdentifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"edpType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"isResale","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"ticketQuantity","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"currencyCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"basePriceTotal"},{"kind":"text","text":": "},{"text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"shippingTotal"},{"text":": ","kind":"text"},{"text":"NSDecimalNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber"},{"kind":"text","text":"?, "},{"text":"orderProcessingFeeTotal","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber"},{"text":"?, ","kind":"text"},{"text":"upsellTotal","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber","text":"NSDecimalNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"voucherDiscountTotal"},{"text":": ","kind":"text"},{"text":"NSDecimalNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"taxTotal"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"grandTotal"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDecimalNumber","kind":"typeIdentifier","text":"NSDecimalNumber"},{"kind":"text","text":"?, "},{"text":"items","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Item","kind":"typeIdentifier","preciseIdentifier":"s:20TicketmasterPurchase15TMPurchaseOrderC4ItemC"},{"kind":"text","text":"]?, "},{"text":"billingCountry","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"billingPostalCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"billingStateProvince","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"paymentMethod","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"shippingMethod"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"rawJSON","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"JSONDictionary","kind":"typeIdentifier","preciseIdentifier":"s:22TicketmasterFoundation14JSONDictionarya"},{"text":"?)","kind":"text"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/init(identifier:date:discoveryEvent:eventIdentifier:eventName:attractionIdentifier:attractionName:venueIdentifier:venueName:majorCategoryName:minorCategoryName:promoterIdentifier:edpType:isResale:ticketQuantity:currencyCode:basePriceTotal:shippingTotal:orderProcessingFeeTotal:upsellTotal:voucherDiscountTotal:taxTotal:grandTotal:items:billingCountry:billingPostalCode:billingStateProvince:paymentMethod:shippingMethod:rawJSON:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder"]]},"references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/init(identifier:date:discoveryEvent:eventIdentifier:eventName:attractionIdentifier:attractionName:venueIdentifier:venueName:majorCategoryName:minorCategoryName:promoterIdentifier:edpType:isResale:ticketQuantity:currencyCode:basePriceTotal:shippingTotal:orderProcessingFeeTotal:upsellTotal:voucherDiscountTotal:taxTotal:grandTotal:items:billingCountry:billingPostalCode:billingStateProvince:paymentMethod:shippingMethod:rawJSON:)":{"role":"symbol","type":"topic","title":"init(identifier:date:discoveryEvent:eventIdentifier:eventName:attractionIdentifier:attractionName:venueIdentifier:venueName:majorCategoryName:minorCategoryName:promoterIdentifier:edpType:isResale:ticketQuantity:currencyCode:basePriceTotal:shippingTotal:orderProcessingFeeTotal:upsellTotal:voucherDiscountTotal:taxTotal:grandTotal:items:billingCountry:billingPostalCode:billingStateProvince:paymentMethod:shippingMethod:rawJSON:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"date"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"text":"discoveryEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:24TicketmasterDiscoveryAPI0B5EventV","text":"DiscoveryEvent"},{"kind":"text","text":"?, "},{"text":"eventIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"eventName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"attractionIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"attractionName","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"venueIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"venueName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"majorCategoryName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"minorCategoryName"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"promoterIdentifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"edpType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"isResale","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"ticketQuantity","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"currencyCode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"basePriceTotal","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDecimalNumber","text":"NSDecimalNumber","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"shippingTotal","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSDecimalNumber","kind":"typeIdentifier","text":"NSDecimalNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"orderProcessingFeeTotal"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"upsellTotal"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber","text":"NSDecimalNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"voucherDiscountTotal"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSDecimalNumber","text":"NSDecimalNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"taxTotal"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber"},{"kind":"text","text":"?, "},{"text":"grandTotal","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDecimalNumber","text":"NSDecimalNumber","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"items","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"Item","preciseIdentifier":"s:20TicketmasterPurchase15TMPurchaseOrderC4ItemC"},{"text":"]?, ","kind":"text"},{"text":"billingCountry","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"billingPostalCode"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"billingStateProvince","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"paymentMethod"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"shippingMethod","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"rawJSON","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"JSONDictionary","preciseIdentifier":"s:22TicketmasterFoundation14JSONDictionarya"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/init(identifier:date:discoveryEvent:eventIdentifier:eventName:attractionIdentifier:attractionName:venueIdentifier:venueName:majorCategoryName:minorCategoryName:promoterIdentifier:edpType:isResale:ticketQuantity:currencyCode:basePriceTotal:shippingTotal:orderProcessingFeeTotal:upsellTotal:voucherDiscountTotal:taxTotal:grandTotal:items:billingCountry:billingPostalCode:billingStateProvince:paymentMethod:shippingMethod:rawJSON:)","abstract":[],"url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/init(identifier:date:discoveryevent:eventidentifier:eventname:attractionidentifier:attractionname:venueidentifier:venuename:majorcategoryname:minorcategoryname:promoteridentifier:edptype:isresale:ticketquantity:currencycode:basepricetotal:s-4hdeh"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMPurchaseOrder","kind":"identifier"}],"navigatorTitle":[{"text":"TMPurchaseOrder","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder","abstract":[],"title":"TMPurchaseOrder","type":"topic","role":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"role":"collection","type":"topic","title":"TicketmasterPurchase","kind":"symbol","url":"\/documentation\/ticketmasterpurchase","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","abstract":[]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/Item":{"title":"TMPurchaseOrder.Item","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/Item","role":"symbol","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Item","kind":"identifier"}],"navigatorTitle":[{"text":"Item","kind":"identifier"}],"url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/item"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseOrder\/title","value":"TMPurchaseOrder"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseOrder\/fragments","value":[{"text":"TMPurchaseOrder","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"TMPurchaseOrder"}],"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseOrder\/navigatorTitle"}]}]}