{"identifier":{"url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/paymentMethod","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentMethod","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/paymentmethod"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"s:20TicketmasterPurchase15TMPurchaseOrderC13paymentMethodSSSgvp","symbolKind":"property","title":"paymentMethod","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"modules":[{"name":"TicketmasterPurchase"}]},"kind":"symbol","references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"type":"topic","url":"\/documentation\/ticketmasterpurchase","title":"TicketmasterPurchase","abstract":[],"role":"collection","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","kind":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMPurchaseOrder","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder","kind":"symbol","navigatorTitle":[{"text":"TMPurchaseOrder","kind":"identifier"}],"title":"TMPurchaseOrder","abstract":[{"text":"A data structure that represents a purchased order","type":"text"}],"url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder","role":"symbol","type":"topic"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/paymentMethod":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/paymentMethod","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/paymentmethod","title":"paymentMethod","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethod"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseOrder\/title","value":"TMPurchaseOrder"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseOrder\/fragments","value":[{"text":"TMPurchaseOrder","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseOrder\/navigatorTitle","value":[{"text":"TMPurchaseOrder","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}