{"sections":[],"variants":[{"paths":["\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/venuename"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"TicketmasterPurchase"}],"externalID":"s:20TicketmasterPurchase15TMPurchaseOrderC9venueNameSSSgvp","role":"symbol","title":"venueName","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"venueName","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"venueName"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/venueName"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder":{"navigatorTitle":[{"kind":"identifier","text":"TMPurchaseOrder"}],"title":"TMPurchaseOrder","abstract":[{"type":"text","text":"A data structure that represents a purchased order"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TMPurchaseOrder","kind":"identifier"}],"url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder","role":"symbol","type":"topic","kind":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/venueName":{"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/venuename","title":"venueName","role":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/venueName","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"venueName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"kind":"symbol","abstract":[],"url":"\/documentation\/ticketmasterpurchase","title":"TicketmasterPurchase","role":"collection","type":"topic","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"TMPurchaseOrder","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseOrder\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseOrder\/fragments","value":[{"kind":"identifier","text":"TMPurchaseOrder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseOrder\/navigatorTitle","value":[{"kind":"identifier","text":"TMPurchaseOrder"}]}]}]}