{"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"TicketmasterAuthentication"}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"s:26TicketmasterAuthentication16TMAuthenticationC5login7backend13externalToken0D10Properties26presentationViewController9fetchRule10callSource7success7aborted7failureyAC14BackendServiceVSg_SSSgSDyS2SGSgSo06UIViewK0CSgAC05FetchM0OSgAQyAA06TMAuthG0VcyA_Sg_AOtcyA0__s5Error_pAPtctF","extendedModule":"TicketmasterAuthentication","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"login"},{"kind":"text","text":"("},{"kind":"externalParam","text":"backend"},{"text":": ","kind":"text"},{"text":"BackendService","kind":"typeIdentifier","preciseIdentifier":"s:26TicketmasterAuthentication16TMAuthenticationC14BackendServiceV"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"externalToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"loginProperties","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"presentationViewController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"fetchRule","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FetchRule","preciseIdentifier":"s:26TicketmasterAuthentication16TMAuthenticationC9FetchRuleO"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"callSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"success","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"authToken","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"TMAuthToken","kind":"typeIdentifier","preciseIdentifier":"s:26TicketmasterAuthentication11TMAuthTokenV"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"aborted","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"oldAuthToken","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TMAuthToken","preciseIdentifier":"s:26TicketmasterAuthentication11TMAuthTokenV"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"backend"},{"kind":"text","text":": "},{"preciseIdentifier":"s:26TicketmasterAuthentication16TMAuthenticationC14BackendServiceV","kind":"typeIdentifier","text":"BackendService"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":", ","kind":"text"},{"text":"failure","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"oldAuthToken"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:26TicketmasterAuthentication11TMAuthTokenV","text":"TMAuthToken","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"backend","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:26TicketmasterAuthentication16TMAuthenticationC14BackendServiceV","text":"BackendService"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"title":"login(backend:externalToken:loginProperties:presentationViewController:fetchRule:callSource:success:aborted:failure:)"},"seeAlsoSections":[{"generated":true,"title":"Login","anchor":"Login","identifiers":["doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/loginSelectionPage(backend:loginProperties:fetchRule:callSource:)"]}],"abstract":[{"text":"present login UI for given ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/BackendService","type":"reference"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/login(backend:externalToken:loginProperties:presentationViewController:fetchRule:callSource:success:aborted:failure:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"login","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"backend"},{"kind":"text","text":": "},{"preciseIdentifier":"s:26TicketmasterAuthentication16TMAuthenticationC14BackendServiceV","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/BackendService","text":"BackendService","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"externalToken"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"loginProperties","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]? = nil, ","kind":"text"},{"kind":"externalParam","text":"presentationViewController"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"fetchRule"},{"text":": ","kind":"text"},{"text":"FetchRule","preciseIdentifier":"s:26TicketmasterAuthentication16TMAuthenticationC9FetchRuleO","kind":"typeIdentifier","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/FetchRule"},{"kind":"text","text":"? = .fetchIfEmptyOrOld, "},{"text":"callSource","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"success"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"authToken","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TMAuthToken","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthToken","preciseIdentifier":"s:26TicketmasterAuthentication11TMAuthTokenV"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":", ","kind":"text"},{"text":"aborted","kind":"externalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"oldAuthToken"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthToken","text":"TMAuthToken","preciseIdentifier":"s:26TicketmasterAuthentication11TMAuthTokenV","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"backend","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/BackendService","kind":"typeIdentifier","text":"BackendService","preciseIdentifier":"s:26TicketmasterAuthentication16TMAuthenticationC14BackendServiceV"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"oldAuthToken"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthToken","preciseIdentifier":"s:26TicketmasterAuthentication11TMAuthTokenV","text":"TMAuthToken","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"backend","kind":"internalParam"},{"kind":"text","text":": "},{"text":"BackendService","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/BackendService","preciseIdentifier":"s:26TicketmasterAuthentication16TMAuthenticationC14BackendServiceV","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Login to a specific ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/BackendService","type":"reference"},{"text":", ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" = auto-determine service (simple configurations only)"}],"type":"paragraph"}],"name":"backend"},{"content":[{"inlineContent":[{"type":"text","text":"Optional external token, use to login instead of presenting a username\/password page"}],"type":"paragraph"}],"name":"externalToken"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional custom login properties"}]}],"name":"loginProperties"},{"content":[{"type":"paragraph","inlineContent":[{"text":"An optional ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" to present login on top of, "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" = auto-determine topVC (default)"}]}],"name":"presentationViewController"},{"name":"fetchRule","content":[{"inlineContent":[{"type":"text","text":"Optional "},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthToken","isActive":true},{"text":" fetching\/caching behavior rules ","type":"text"},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/FetchRule","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional name of class or process calling this method"}]}],"name":"callSource"},{"content":[{"inlineContent":[{"text":"Login success block","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"authToken: "},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthToken","isActive":true},{"type":"text","text":" (may be cached, if login not needed)"}]}]}]}],"name":"success"},{"content":[{"type":"paragraph","inlineContent":[{"text":"User aborted login block","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"authToken: ","type":"text"},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthToken","type":"reference","isActive":true},{"text":" (cached, if any, may be expired)","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"backend: "},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/BackendService","type":"reference","isActive":true},{"type":"text","text":" aborted"}]}]}]}],"name":"aborted"},{"name":"failure","content":[{"inlineContent":[{"text":"Login failure block","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"oldAuthToken: ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthToken"},{"text":" (cached, if any, may be expired)","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"error: login error","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"backend: "},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/BackendService","isActive":true,"type":"reference"},{"type":"text","text":" error source"}],"type":"paragraph"}]}],"type":"unorderedList"}]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"text":"This will be presented modally on top of your existing UI. To more precisely control the login presentation, use ","type":"text"},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/loginSelectionPage(backend:loginProperties:fetchRule:callSource:)","isActive":true,"type":"reference"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"This will also show Create Account and Forgot Password options on the login page.","type":"text"}]},{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Fetch Rules:"}]}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/FetchRule\/cachedOnly","type":"reference"},{"text":" = return cached ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthToken"},{"type":"text","text":" even if expired, if not cached do not login, return error"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/FetchRule\/fetchIfEmpty","isActive":true,"type":"reference"},{"type":"text","text":" = return cached "},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthToken","isActive":true},{"type":"text","text":" even if expired, if not cached login"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/FetchRule\/fetchIfEmptyOrOld"},{"type":"text","text":" = return cached "},{"isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthToken","type":"reference"},{"type":"text","text":" if not expired, if expired fetch, if not cached login"}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/FetchRule\/forceFetch","isActive":true},{"type":"text","text":" = ignore cached "},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthToken","isActive":true,"type":"reference"},{"text":", login always","type":"text"}],"type":"paragraph"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication","doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication"],["doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication","doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication","doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/TMAuthenticationProvider-Implementations"]]},"variants":[{"paths":["\/documentation\/ticketmasterauthentication\/tmauthentication\/login(backend:externaltoken:loginproperties:presentationviewcontroller:fetchrule:callsource:success:aborted:failure:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthentication/FetchRule/cachedOnly":{"type":"topic","abstract":[{"type":"text","text":"return locally cached values (even if old), if cache empty return error"}],"kind":"symbol","title":"TMAuthentication.FetchRule.cachedOnly","url":"\/documentation\/ticketmasterauthentication\/tmauthentication\/fetchrule\/cachedonly","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cachedOnly"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/FetchRule\/cachedOnly"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthentication/FetchRule/fetchIfEmptyOrOld":{"type":"topic","abstract":[{"type":"text","text":"return locally cached values (if not old), if cache empty (or old) fetch items off the network"}],"kind":"symbol","title":"TMAuthentication.FetchRule.fetchIfEmptyOrOld","url":"\/documentation\/ticketmasterauthentication\/tmauthentication\/fetchrule\/fetchifemptyorold","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"fetchIfEmptyOrOld","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/FetchRule\/fetchIfEmptyOrOld"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthentication":{"navigatorTitle":[{"kind":"identifier","text":"TMAuthentication"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TMAuthentication","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication","role":"symbol","abstract":[{"type":"codeVoice","code":"TMAuthentication"},{"text":" provides login UI, oauth tokens, member info, and MFA support.","type":"text"}],"url":"\/documentation\/ticketmasterauthentication\/tmauthentication","type":"topic","title":"TMAuthentication","kind":"symbol"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthentication/TMAuthenticationProvider-Implementations":{"title":"TMAuthenticationProvider Implementations","kind":"article","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/TMAuthenticationProvider-Implementations","type":"topic","role":"collectionGroup","url":"\/documentation\/ticketmasterauthentication\/tmauthentication\/tmauthenticationprovider-implementations","abstract":[]},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthentication/FetchRule":{"abstract":[{"type":"text","text":"cache and networking fetching rules"}],"type":"topic","url":"\/documentation\/ticketmasterauthentication\/tmauthentication\/fetchrule","title":"TMAuthentication.FetchRule","navigatorTitle":[{"text":"FetchRule","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/FetchRule","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FetchRule"}]},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthentication/BackendService":{"navigatorTitle":[{"text":"BackendService","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"BackendService","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/BackendService","role":"symbol","abstract":[{"type":"text","text":"backend Service providing Authentication"}],"url":"\/documentation\/ticketmasterauthentication\/tmauthentication\/backendservice","type":"topic","title":"TMAuthentication.BackendService","kind":"symbol"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication":{"kind":"symbol","title":"TicketmasterAuthentication","abstract":[{"type":"text","text":"Application Configuration and Account Operations"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication","type":"topic","role":"collection","url":"\/documentation\/ticketmasterauthentication"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthentication/FetchRule/forceFetch":{"abstract":[{"type":"text","text":"fetch items off the network, ignore any local cache"}],"type":"topic","kind":"symbol","role":"symbol","title":"TMAuthentication.FetchRule.forceFetch","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"forceFetch","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/FetchRule\/forceFetch","url":"\/documentation\/ticketmasterauthentication\/tmauthentication\/fetchrule\/forcefetch"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthentication/FetchRule/fetchIfEmpty":{"abstract":[{"type":"text","text":"return locally cached values (even if old), if cache empty fetch items off the network"}],"type":"topic","kind":"symbol","role":"symbol","title":"TMAuthentication.FetchRule.fetchIfEmpty","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"fetchIfEmpty","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/FetchRule\/fetchIfEmpty","url":"\/documentation\/ticketmasterauthentication\/tmauthentication\/fetchrule\/fetchifempty"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthToken":{"type":"topic","navigatorTitle":[{"text":"TMAuthToken","kind":"identifier"}],"abstract":[{"type":"text","text":"struct representing a user’s OAuth data"}],"kind":"symbol","title":"TMAuthToken","url":"\/documentation\/ticketmasterauthentication\/tmauthtoken","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMAuthToken"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthToken"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthentication/login(backend:externalToken:loginProperties:presentationViewController:fetchRule:callSource:success:aborted:failure:)":{"url":"\/documentation\/ticketmasterauthentication\/tmauthentication\/login(backend:externaltoken:loginproperties:presentationviewcontroller:fetchrule:callsource:success:aborted:failure:)","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/login(backend:externalToken:loginProperties:presentationViewController:fetchRule:callSource:success:aborted:failure:)","title":"login(backend:externalToken:loginProperties:presentationViewController:fetchRule:callSource:success:aborted:failure:)","type":"topic","abstract":[{"text":"present login UI for given ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/BackendService"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"login","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"backend"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BackendService","preciseIdentifier":"s:26TicketmasterAuthentication16TMAuthenticationC14BackendServiceV"},{"text":"?, ","kind":"text"},{"text":"externalToken","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"loginProperties"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"presentationViewController"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":"?, "},{"text":"fetchRule","kind":"externalParam"},{"kind":"text","text":": "},{"text":"FetchRule","preciseIdentifier":"s:26TicketmasterAuthentication16TMAuthenticationC9FetchRuleO","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"callSource"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"success","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"authToken"},{"kind":"text","text":": "},{"preciseIdentifier":"s:26TicketmasterAuthentication11TMAuthTokenV","text":"TMAuthToken","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"aborted"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"oldAuthToken"},{"kind":"text","text":": "},{"text":"TMAuthToken","preciseIdentifier":"s:26TicketmasterAuthentication11TMAuthTokenV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"backend","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"BackendService","preciseIdentifier":"s:26TicketmasterAuthentication16TMAuthenticationC14BackendServiceV"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"failure","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"oldAuthToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:26TicketmasterAuthentication11TMAuthTokenV","text":"TMAuthToken"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"backend"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:26TicketmasterAuthentication16TMAuthenticationC14BackendServiceV","text":"BackendService","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}]},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthentication/loginSelectionPage(backend:loginProperties:fetchRule:callSource:)":{"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/loginSelectionPage(backend:loginProperties:fetchRule:callSource:)","kind":"symbol","abstract":[{"type":"text","text":"create a login selection UI for configured "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/BackendService"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loginSelectionPage","kind":"identifier"},{"kind":"text","text":"("},{"text":"backend","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:26TicketmasterAuthentication16TMAuthenticationC14BackendServiceV","text":"BackendService","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"loginProperties","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]?, ","kind":"text"},{"text":"fetchRule","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FetchRule","preciseIdentifier":"s:26TicketmasterAuthentication16TMAuthenticationC9FetchRuleO"},{"kind":"text","text":"?, "},{"text":"callSource","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":"?","kind":"text"}],"title":"loginSelectionPage(backend:loginProperties:fetchRule:callSource:)","url":"\/documentation\/ticketmasterauthentication\/tmauthentication\/loginselectionpage(backend:loginproperties:fetchrule:callsource:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterAuthentication~1documentation~1TicketmasterAuthentication~1TMAuthentication\/title","value":"TMAuthentication"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterAuthentication~1documentation~1TicketmasterAuthentication~1TMAuthentication\/fragments","value":[{"kind":"identifier","text":"TMAuthentication"}]},{"value":[{"kind":"identifier","text":"TMAuthentication"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterAuthentication~1documentation~1TicketmasterAuthentication~1TMAuthentication\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}