{"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterauthentication\/tmauthentication\/sdkbuildinfo"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/sdkBuildInfo"},"abstract":[{"text":"current build details of the ","type":"text"},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication","type":"reference","isActive":true},{"text":" framework","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication","doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkBuildInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"s:22TicketmasterFoundation14JSONDictionarya","kind":"typeIdentifier","text":"JSONDictionary"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkBuildInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"s:22TicketmasterFoundation14JSONDictionarya","kind":"typeIdentifier","text":"JSONDictionary"},{"kind":"text","text":"?"}],"role":"symbol","symbolKind":"property","modules":[{"name":"TicketmasterAuthentication"}],"roleHeading":"Instance Property","title":"sdkBuildInfo","externalID":"s:26TicketmasterAuthentication16TMAuthenticationC12sdkBuildInfoSDySSypGSgvp"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthentication/sdkBuildInfo":{"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkBuildInfo","kind":"identifier"},{"text":": ","kind":"text"},{"text":"JSONDictionary","kind":"typeIdentifier","preciseIdentifier":"s:22TicketmasterFoundation14JSONDictionarya"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/sdkBuildInfo","abstract":[{"text":"current build details of the ","type":"text"},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication","type":"reference","isActive":true},{"text":" framework","type":"text"}],"title":"sdkBuildInfo","url":"\/documentation\/ticketmasterauthentication\/tmauthentication\/sdkbuildinfo"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthentication":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TMAuthentication","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TMAuthentication"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication","title":"TMAuthentication","abstract":[{"type":"codeVoice","code":"TMAuthentication"},{"text":" provides login UI, oauth tokens, member info, and MFA support.","type":"text"}],"url":"\/documentation\/ticketmasterauthentication\/tmauthentication"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication":{"kind":"symbol","role":"collection","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication","abstract":[{"type":"text","text":"Application Configuration and Account Operations"}],"title":"TicketmasterAuthentication","url":"\/documentation\/ticketmasterauthentication"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterAuthentication~1documentation~1TicketmasterAuthentication~1TMAuthentication\/title","value":"TMAuthentication"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterAuthentication~1documentation~1TicketmasterAuthentication~1TMAuthentication\/fragments","value":[{"kind":"identifier","text":"TMAuthentication"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterAuthentication~1documentation~1TicketmasterAuthentication~1TMAuthentication\/navigatorTitle","value":[{"kind":"identifier","text":"TMAuthentication"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}