{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"donateTickets"}]}]}],"variants":[{"paths":["\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule\/buttoncallbackname\/donatetickets"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/ButtonCallbackName\/donateTickets","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/ButtonCallbackName"]]},"metadata":{"title":"TMTicketsPrebuiltModule.ButtonCallbackName.donateTickets","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"donateTickets"}],"symbolKind":"case","externalID":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV18ButtonCallbackNameO06donateB0yA2EmF","modules":[{"name":"TicketmasterTickets"}],"role":"symbol","roleHeading":"Case"},"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule/ButtonCallbackName":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ButtonCallbackName"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ButtonCallbackName"}],"title":"TMTicketsPrebuiltModule.ButtonCallbackName","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/ButtonCallbackName","abstract":[{"type":"text","text":"button names for analytics"}],"url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule\/buttoncallbackname"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","title":"TicketmasterTickets","type":"topic","abstract":[{"type":"text","text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes."}],"kind":"symbol","url":"\/documentation\/ticketmastertickets","role":"collection"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule":{"role":"symbol","navigatorTitle":[{"text":"TMTicketsPrebuiltModule","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule","title":"TMTicketsPrebuiltModule","url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule","abstract":[{"text":"useful pre-built ","type":"text"},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","isActive":true,"type":"reference"},{"type":"text","text":" for the Tickets listing page"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMTicketsPrebuiltModule","kind":"identifier"}],"kind":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule":{"title":"TMTicketsModule","navigatorTitle":[{"text":"TMTicketsModule","kind":"identifier"}],"type":"topic","url":"\/documentation\/ticketmastertickets\/tmticketsmodule","abstract":[{"type":"text","text":"create a custom module to be displayed underneath the user’s list of Tickets on the Tickets listing page"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTicketsModule"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule/ButtonCallbackName/donateTickets":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"donateTickets"}],"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/ButtonCallbackName\/donateTickets","kind":"symbol","abstract":[],"type":"topic","title":"TMTicketsPrebuiltModule.ButtonCallbackName.donateTickets","url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule\/buttoncallbackname\/donatetickets"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TMTicketsModule","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/fragments","op":"replace","value":[{"kind":"identifier","text":"TMTicketsModule"}]},{"op":"replace","value":[{"kind":"identifier","text":"TMTicketsModule"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/navigatorTitle"}]}]}