{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/FetchRule\/init(rawValue:)","interfaceLanguage":"swift"},"metadata":{"title":"init(rawValue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"roleHeading":"Initializer","externalID":"s:26TicketmasterAuthentication16TMAuthenticationC9FetchRuleO8rawValueAESgSS_tcfc","symbolKind":"init","modules":[{"name":"TicketmasterAuthentication"}]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication","doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication","doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/FetchRule"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterauthentication\/tmauthentication\/fetchrule\/init(rawvalue:)"]}],"references":{"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication":{"kind":"symbol","role":"collection","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication","abstract":[{"type":"text","text":"Application Configuration and Account Operations"}],"title":"TicketmasterAuthentication","url":"\/documentation\/ticketmasterauthentication"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthentication":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TMAuthentication","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TMAuthentication"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication","title":"TMAuthentication","abstract":[{"type":"codeVoice","code":"TMAuthentication"},{"text":" provides login UI, oauth tokens, member info, and MFA support.","type":"text"}],"url":"\/documentation\/ticketmasterauthentication\/tmauthentication"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthentication/FetchRule/init(rawValue:)":{"url":"\/documentation\/ticketmasterauthentication\/tmauthentication\/fetchrule\/init(rawvalue:)","abstract":[],"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/FetchRule\/init(rawValue:)","role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"init(rawValue:)"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthentication/FetchRule":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FetchRule"}],"navigatorTitle":[{"kind":"identifier","text":"FetchRule"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/FetchRule","abstract":[{"type":"text","text":"cache and networking fetching rules"}],"title":"TMAuthentication.FetchRule","url":"\/documentation\/ticketmasterauthentication\/tmauthentication\/fetchrule"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"TMAuthentication","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterAuthentication~1documentation~1TicketmasterAuthentication~1TMAuthentication\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TMAuthentication"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterAuthentication~1documentation~1TicketmasterAuthentication~1TMAuthentication\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TMAuthentication"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterAuthentication~1documentation~1TicketmasterAuthentication~1TMAuthentication\/navigatorTitle"}]}]}