{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"text":" ","kind":"text"},{"kind":"keyword","text":"weak"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"barcodeBackgroundView","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":"!","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview\/barcodebackgroundview"]},{"paths":["\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview\/barcodebackgroundview"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView"]]},"metadata":{"symbolKind":"property","role":"symbol","externalID":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModuleHeaderView(py)barcodeBackgroundView","roleHeading":"Instance Property","title":"barcodeBackgroundView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"barcodeBackgroundView","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"barcodeBackgroundView","kind":"identifier"}],"modules":[{"name":"TicketmasterTickets"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/barcodeBackgroundView"},"kind":"symbol","references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView/barcodeBackgroundView":{"url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview\/barcodebackgroundview","role":"symbol","title":"barcodeBackgroundView","type":"topic","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/barcodeBackgroundView","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"barcodeBackgroundView","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"navigatorTitle":[{"text":"barcodeBackgroundView","kind":"identifier"}],"abstract":[]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"title":"TicketmasterTickets","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","type":"topic","role":"collection","url":"\/documentation\/ticketmastertickets","abstract":[{"type":"text","text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes."}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView","type":"topic","url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview","abstract":[{"text":"quickly build a UIView for ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView","isActive":true}],"kind":"symbol","navigatorTitle":[{"text":"TMTicketsModuleHeaderView","kind":"identifier"}],"title":"TMTicketsModuleHeaderView","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsModuleHeaderView"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"barcodeBackgroundView","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"barcodeBackgroundView","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"weak","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"barcodeBackgroundView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView~1barcodeBackgroundView\/title","op":"replace","value":"barcodeBackgroundView"},{"value":[{"text":"barcodeBackgroundView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView~1barcodeBackgroundView\/fragments"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/title","value":"TMTicketsModuleHeaderView","op":"replace"},{"value":[{"kind":"identifier","text":"TMTicketsModuleHeaderView"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}