{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"externalID":"s:19TicketmasterTickets25TMTicketsModuleHeaderViewC5buildACyFZ","roleHeading":"Type Method","title":"build()","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"build"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModuleHeaderView","text":"TMTicketsModuleHeaderView"}],"modules":[{"name":"TicketmasterTickets"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"build","kind":"identifier"},{"text":"() -> ","kind":"text"},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView","text":"TMTicketsModuleHeaderView","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModuleHeaderView","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/build()","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"create a new instance"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview\/build()"]}],"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","title":"TicketmasterTickets","abstract":[{"type":"text","text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes."}],"url":"\/documentation\/ticketmastertickets","role":"collection"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView/build()":{"title":"build()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"TMTicketsModuleHeaderView","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModuleHeaderView"}],"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/build()","kind":"symbol","abstract":[{"text":"create a new instance","type":"text"}],"type":"topic","url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview\/build()"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView":{"title":"TMTicketsModuleHeaderView","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TMTicketsModuleHeaderView","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"quickly build a UIView for ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView","isActive":true}],"navigatorTitle":[{"kind":"identifier","text":"TMTicketsModuleHeaderView"}],"url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/title","value":"TMTicketsModuleHeaderView"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/fragments","op":"replace","value":[{"kind":"identifier","text":"TMTicketsModuleHeaderView"}]},{"value":[{"kind":"identifier","text":"TMTicketsModuleHeaderView"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/navigatorTitle"}]}]}