{"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview\/centerlabel"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview\/centerlabel"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@IBOutlet","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"weak"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"centerLabel"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/centerLabel","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView"]]},"metadata":{"role":"symbol","symbolKind":"property","title":"centerLabel","navigatorTitle":[{"text":"centerLabel","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModuleHeaderView(py)centerLabel","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"centerLabel"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel"},{"kind":"text","text":"!"}],"modules":[{"name":"TicketmasterTickets"}]},"sections":[],"kind":"symbol","references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"abstract":[{"text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","title":"TicketmasterTickets","kind":"symbol","role":"collection","url":"\/documentation\/ticketmastertickets"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView/centerLabel":{"role":"symbol","navigatorTitle":[{"text":"centerLabel","kind":"identifier"}],"url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview\/centerlabel","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"centerLabel"},{"kind":"text","text":": "},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"},{"text":"!","kind":"text"}],"title":"centerLabel","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/centerLabel","abstract":[],"type":"topic"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView","title":"TMTicketsModuleHeaderView","url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview","type":"topic","abstract":[{"text":"quickly build a UIView for ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TMTicketsModuleHeaderView","kind":"identifier"}],"navigatorTitle":[{"text":"TMTicketsModuleHeaderView","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"centerLabel","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"centerLabel"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier","text":"UILabel"},{"kind":"text","text":" * "},{"text":"centerLabel","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView~1centerLabel\/title","value":"centerLabel"},{"op":"replace","value":[{"kind":"identifier","text":"centerLabel"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView~1centerLabel\/fragments"},{"value":"TMTicketsModuleHeaderView","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/fragments","value":[{"kind":"identifier","text":"TMTicketsModuleHeaderView"}],"op":"replace"}]}]}