{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView"]]},"variants":[{"paths":["\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview\/configure(toplabeltext:toplabeltextalignment:toplabeltextcolor:centerlabeltext:centerlabeltextalignment:centerlabeltextcolor:bottomlabeltext:bottomlabeltextalignment:bottomlabeltextcolor:titlelabeltext:titlelabeltextcolor:messagelabeltext:m-5gunn"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"roleHeading":"Instance Method","externalID":"s:19TicketmasterTickets25TMTicketsModuleHeaderViewC9configure12topLabelText0hiJ9Alignment0hiJ5Color06centeriJ00mijK00mijL006bottomiJ00nijK00nijL005titleiJ00oijL007messageiJ00pijL00pI11DetectLinks0pi4LinkL00o17MessageBackgroundL013gradientAlpha21backgroundAspectRatio0xyZ6Forced0xL00X5Image0X8ImageURL19mapCoordinateRegion13mapAnnotation12avContentURL21disableLoopingContent14disableAVAudio14barcode2DValue11qrCodeValue10aztecValue11pdf417Value14headerOverrideSbSSSg_So06NSTextK0VSgSo7UIColorCSgA9_A12_A15_A9_A12_A15_A9_A15_A9_A15_SbA15_A15_14CoreFoundation7CGFloatVSgA19_SbA15_So7UIImageCSg10Foundation3URLVSgSo18MKCoordinateRegionaSgSo12MKAnnotation_pSgA26_S2bA9_A9_A9_A9_AA0c8PrebuiltD0V0E8OverrideVSgtF","role":"symbol","title":"configure(topLabelText:topLabelTextAlignment:topLabelTextColor:centerLabelText:centerLabelTextAlignment:centerLabelTextColor:bottomLabelText:bottomLabelTextAlignment:bottomLabelTextColor:titleLabelText:titleLabelTextColor:messageLabelText:messageLabelTextColor:messageLabelDetectLinks:messageLabelLinkColor:titleMessageBackgroundColor:gradientAlpha:backgroundAspectRatio:backgroundAspectRatioForced:backgroundColor:backgroundImage:backgroundImageURL:mapCoordinateRegion:mapAnnotation:avContentURL:disableLoopingContent:disableAVAudio:barcode2DValue:qrCodeValue:aztecValue:pdf417Value:headerOverride:)","extendedModule":"TicketmasterTickets","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"topLabelText"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"topLabelTextAlignment","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSTextAlignment","preciseIdentifier":"c:@E@NSTextAlignment","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"topLabelTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"text":"centerLabelText","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"centerLabelTextAlignment","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSTextAlignment","preciseIdentifier":"c:@E@NSTextAlignment"},{"kind":"text","text":"?, "},{"text":"centerLabelTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"bottomLabelText"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"bottomLabelTextAlignment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTextAlignment","text":"NSTextAlignment"},{"kind":"text","text":"?, "},{"text":"bottomLabelTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"titleLabelText","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"titleLabelTextColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"messageLabelText"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"messageLabelTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?, ","kind":"text"},{"text":"messageLabelDetectLinks","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"messageLabelLinkColor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"titleMessageBackgroundColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"gradientAlpha"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"backgroundAspectRatio"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"backgroundAspectRatioForced"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"backgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"backgroundImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?, ","kind":"text"},{"text":"backgroundImageURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"mapCoordinateRegion"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@SA@MKCoordinateRegion","text":"MKCoordinateRegion","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"mapAnnotation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MKAnnotation","text":"MKAnnotation"},{"kind":"text","text":"?, "},{"text":"avContentURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"disableLoopingContent"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"disableAVAudio"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"barcode2DValue"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"qrCodeValue"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"aztecValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"pdf417Value","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"headerOverride","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV","text":"TMTicketsPrebuiltModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"HeaderOverride","preciseIdentifier":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV14HeaderOverrideV"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"modules":[{"name":"TicketmasterTickets"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/configure(topLabelText:topLabelTextAlignment:topLabelTextColor:centerLabelText:centerLabelTextAlignment:centerLabelTextColor:bottomLabelText:bottomLabelTextAlignment:bottomLabelTextColor:titleLabelText:titleLabelTextColor:messageLabelText:messageLabelTextColor:messageLabelDetectLinks:messageLabelLinkColor:titleMessageBackgroundColor:gradientAlpha:backgroundAspectRatio:backgroundAspectRatioForced:backgroundColor:backgroundImage:backgroundImageURL:mapCoordinateRegion:mapAnnotation:avContentURL:disableLoopingContent:disableAVAudio:barcode2DValue:qrCodeValue:aztecValue:pdf417Value:headerOverride:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"configure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"topLabelText","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"topLabelTextAlignment","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSTextAlignment","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTextAlignment"},{"text":"? = .left, ","kind":"text"},{"text":"topLabelTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"centerLabelText","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"centerLabelTextAlignment","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSTextAlignment","preciseIdentifier":"c:@E@NSTextAlignment","kind":"typeIdentifier"},{"kind":"text","text":"? = .center, "},{"text":"centerLabelTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"bottomLabelText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"bottomLabelTextAlignment","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSTextAlignment","preciseIdentifier":"c:@E@NSTextAlignment","kind":"typeIdentifier"},{"text":"? = .right, ","kind":"text"},{"text":"bottomLabelTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"titleLabelText"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"titleLabelTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"messageLabelText"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"messageLabelTextColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"messageLabelDetectLinks","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = true, "},{"text":"messageLabelLinkColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"titleMessageBackgroundColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"gradientAlpha"},{"kind":"text","text":": "},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"kind":"text","text":"? = 0.0, "},{"text":"backgroundAspectRatio","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":"? = nil, ","kind":"text"},{"text":"backgroundAspectRatioForced","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"text":"backgroundColor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"? = nil, ","kind":"text"},{"text":"backgroundImage","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"? = nil, "},{"text":"backgroundImageURL","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"mapCoordinateRegion"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@SA@MKCoordinateRegion","kind":"typeIdentifier","text":"MKCoordinateRegion"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"mapAnnotation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MKAnnotation","preciseIdentifier":"c:objc(pl)MKAnnotation"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"avContentURL"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"disableLoopingContent"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"text":"disableAVAudio","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"barcode2DValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"qrCodeValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"aztecValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"pdf417Value"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"headerOverride"},{"kind":"text","text":": "},{"text":"TMTicketsPrebuiltModule","preciseIdentifier":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV","kind":"typeIdentifier","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule"},{"text":".","kind":"text"},{"preciseIdentifier":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV14HeaderOverrideV","kind":"typeIdentifier","text":"HeaderOverride","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/HeaderOverride"},{"text":"? = nil) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Localized text"}],"type":"paragraph"}],"name":"topLabelText"},{"content":[{"inlineContent":[{"type":"text","text":"Nil = keep default alignment (.left)"}],"type":"paragraph"}],"name":"topLabelTextAlignment"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Text color (nil = use default)"}]}],"name":"topLabelTextColor"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Localized text","type":"text"}]}],"name":"centerLabelText"},{"name":"centerLabelTextAlignment","content":[{"type":"paragraph","inlineContent":[{"text":"Nil = keep default alignment (.center)","type":"text"}]}]},{"name":"centerLabelTextColor","content":[{"inlineContent":[{"type":"text","text":"Text color (nil = use default)"}],"type":"paragraph"}]},{"name":"bottomLabelText","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Localized text,"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Nil = keep default alignment (.right)"}],"type":"paragraph"}],"name":"bottomLabelTextAlignment"},{"name":"bottomLabelTextColor","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Text color (nil = use default)"}]}]},{"name":"titleLabelText","content":[{"inlineContent":[{"type":"text","text":"Localized title text, shown in a box below image\/map\/video\/barcode"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Text color (nil = use default)","type":"text"}]}],"name":"titleLabelTextColor"},{"name":"messageLabelText","content":[{"inlineContent":[{"type":"text","text":"Localized multi-line message text, shown in a box below image\/map\/video\/barcode"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Text color (nil = use default)"}],"type":"paragraph"}],"name":"messageLabelTextColor"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Detect and highlight URLs, Dates, Addresses, Emails, and Phone numbers in message text"}]}],"name":"messageLabelDetectLinks"},{"content":[{"inlineContent":[{"text":"Link color (nil = use default)","type":"text"}],"type":"paragraph"}],"name":"messageLabelLinkColor"},{"name":"titleMessageBackgroundColor","content":[{"inlineContent":[{"type":"text","text":"Color of text box background, shown below image\/map\/video\/barcode"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"0.0 = hide gradient, 1.0 = show gradient, nil = keep default gradient (0.0)"}]}],"name":"gradientAlpha"},{"name":"backgroundAspectRatio","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Aspect ratio (width \/ height) of background content, will be overridden by actual aspect ratio of "},{"type":"codeVoice","code":"backgroundImage"},{"type":"text","text":" or "},{"code":"backgroundImageURL","type":"codeVoice"},{"text":",","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Aspect ratio will not be overridden by "},{"type":"codeVoice","code":"backgroundImage"},{"type":"text","text":" or "},{"type":"codeVoice","code":"backgroundImageURL"}]}],"name":"backgroundAspectRatioForced"},{"name":"backgroundColor","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Background color"}]}]},{"name":"backgroundImage","content":[{"inlineContent":[{"type":"text","text":"Background image (default image, will be replaced by "},{"type":"codeVoice","code":"backgroundImageURL"},{"text":", if any)","type":"text"}],"type":"paragraph"}]},{"name":"backgroundImageURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Url of image that will be loaded to replace existing "},{"type":"codeVoice","code":"backgroundImage"},{"type":"text","text":" (if any)"}]}]},{"name":"mapCoordinateRegion","content":[{"inlineContent":[{"text":"Map region to show","type":"text"}],"type":"paragraph"}]},{"name":"mapAnnotation","content":[{"type":"paragraph","inlineContent":[{"text":"Map annotation (if any)","type":"text"}]}]},{"name":"avContentURL","content":[{"inlineContent":[{"text":"URL to AV content","type":"text"}],"type":"paragraph"}]},{"name":"disableLoopingContent","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"True = do not loop content"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"True = do not play audio"}]}],"name":"disableAVAudio"},{"content":[{"inlineContent":[{"type":"text","text":"Barcode code39 or code128 (string of letters and integers)"}],"type":"paragraph"}],"name":"barcode2DValue"},{"content":[{"type":"paragraph","inlineContent":[{"text":"QR code value (any string)","type":"text"}]}],"name":"qrCodeValue"},{"content":[{"inlineContent":[{"type":"text","text":"Aztec barcode value (any string)"}],"type":"paragraph"}],"name":"aztecValue"},{"name":"pdf417Value","content":[{"inlineContent":[{"type":"text","text":"PDF-417 code value (any string)"}],"type":"paragraph"}]},{"name":"headerOverride","content":[{"inlineContent":[{"text":"A struct that overrides any of the above values","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"text":"Bool (true = contains valid header info, false = empty view)","type":"text"}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"text":"configure header with various contents","type":"text"}],"kind":"symbol","references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule":{"navigatorTitle":[{"text":"TMTicketsPrebuiltModule","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTicketsPrebuiltModule"}],"kind":"symbol","abstract":[{"text":"useful pre-built ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule"},{"text":" for the Tickets listing page","type":"text"}],"url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule","title":"TMTicketsPrebuiltModule","role":"symbol","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsModule"}],"navigatorTitle":[{"kind":"identifier","text":"TMTicketsModule"}],"title":"TMTicketsModule","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","url":"\/documentation\/ticketmastertickets\/tmticketsmodule","abstract":[{"type":"text","text":"create a custom module to be displayed underneath the user’s list of Tickets on the Tickets listing page"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule/HeaderOverride":{"url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule\/headeroverride","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeaderOverride"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"HeaderOverride"}],"title":"TMTicketsPrebuiltModule.HeaderOverride","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/HeaderOverride","type":"topic"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView/configure(topLabelText:topLabelTextAlignment:topLabelTextColor:centerLabelText:centerLabelTextAlignment:centerLabelTextColor:bottomLabelText:bottomLabelTextAlignment:bottomLabelTextColor:titleLabelText:titleLabelTextColor:messageLabelText:messageLabelTextColor:messageLabelDetectLinks:messageLabelLinkColor:titleMessageBackgroundColor:gradientAlpha:backgroundAspectRatio:backgroundAspectRatioForced:backgroundColor:backgroundImage:backgroundImageURL:mapCoordinateRegion:mapAnnotation:avContentURL:disableLoopingContent:disableAVAudio:barcode2DValue:qrCodeValue:aztecValue:pdf417Value:headerOverride:)":{"url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview\/configure(toplabeltext:toplabeltextalignment:toplabeltextcolor:centerlabeltext:centerlabeltextalignment:centerlabeltextcolor:bottomlabeltext:bottomlabeltextalignment:bottomlabeltextcolor:titlelabeltext:titlelabeltextcolor:messagelabeltext:m-5gunn","type":"topic","abstract":[{"type":"text","text":"configure header with various contents"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"topLabelText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"topLabelTextAlignment","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@NSTextAlignment","text":"NSTextAlignment","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"topLabelTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"centerLabelText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"centerLabelTextAlignment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTextAlignment","text":"NSTextAlignment"},{"text":"?, ","kind":"text"},{"text":"centerLabelTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":"?, "},{"text":"bottomLabelText","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"bottomLabelTextAlignment"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@NSTextAlignment","text":"NSTextAlignment","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"bottomLabelTextColor"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"titleLabelText"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"titleLabelTextColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"text":"messageLabelText","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"messageLabelTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"text":"messageLabelDetectLinks","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"messageLabelLinkColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"titleMessageBackgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"gradientAlpha"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"backgroundAspectRatio"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"backgroundAspectRatioForced","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"backgroundImage"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?, ","kind":"text"},{"text":"backgroundImageURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"mapCoordinateRegion"},{"text":": ","kind":"text"},{"text":"MKCoordinateRegion","kind":"typeIdentifier","preciseIdentifier":"c:@SA@MKCoordinateRegion"},{"text":"?, ","kind":"text"},{"text":"mapAnnotation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MKAnnotation","text":"MKAnnotation"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"avContentURL"},{"kind":"text","text":": "},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"disableLoopingContent","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"disableAVAudio"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"barcode2DValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"qrCodeValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"aztecValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"pdf417Value"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"headerOverride"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV","kind":"typeIdentifier","text":"TMTicketsPrebuiltModule"},{"kind":"text","text":"."},{"text":"HeaderOverride","kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV14HeaderOverrideV"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","title":"configure(topLabelText:topLabelTextAlignment:topLabelTextColor:centerLabelText:centerLabelTextAlignment:centerLabelTextColor:bottomLabelText:bottomLabelTextAlignment:bottomLabelTextColor:titleLabelText:titleLabelTextColor:messageLabelText:messageLabelTextColor:messageLabelDetectLinks:messageLabelLinkColor:titleMessageBackgroundColor:gradientAlpha:backgroundAspectRatio:backgroundAspectRatioForced:backgroundColor:backgroundImage:backgroundImageURL:mapCoordinateRegion:mapAnnotation:avContentURL:disableLoopingContent:disableAVAudio:barcode2DValue:qrCodeValue:aztecValue:pdf417Value:headerOverride:)","role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/configure(topLabelText:topLabelTextAlignment:topLabelTextColor:centerLabelText:centerLabelTextAlignment:centerLabelTextColor:bottomLabelText:bottomLabelTextAlignment:bottomLabelTextColor:titleLabelText:titleLabelTextColor:messageLabelText:messageLabelTextColor:messageLabelDetectLinks:messageLabelLinkColor:titleMessageBackgroundColor:gradientAlpha:backgroundAspectRatio:backgroundAspectRatioForced:backgroundColor:backgroundImage:backgroundImageURL:mapCoordinateRegion:mapAnnotation:avContentURL:disableLoopingContent:disableAVAudio:barcode2DValue:qrCodeValue:aztecValue:pdf417Value:headerOverride:)"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView":{"type":"topic","abstract":[{"type":"text","text":"quickly build a UIView for "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView"}],"url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview","kind":"symbol","title":"TMTicketsModuleHeaderView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsModuleHeaderView"}],"role":"symbol","navigatorTitle":[{"text":"TMTicketsModuleHeaderView","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"url":"\/documentation\/ticketmastertickets","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","role":"collection","title":"TicketmasterTickets","kind":"symbol","abstract":[{"text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes.","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/title","op":"replace","value":"TMTicketsModule"},{"op":"replace","value":[{"kind":"identifier","text":"TMTicketsModule"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/fragments"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TMTicketsModule"}]},{"value":"TMTicketsModuleHeaderView","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/fragments","value":[{"text":"TMTicketsModuleHeaderView","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/navigatorTitle","value":[{"text":"TMTicketsModuleHeaderView","kind":"identifier"}]}]}]}