{"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/configure(topLabelText:topLabelTextAlignment:topLabelTextColor:centerLabelText:centerLabelTextAlignment:centerLabelTextColor:bottomLabelText:bottomLabelTextAlignment:bottomLabelTextColor:titleLabelText:titleLabelTextColor:messageLabelText:messageLabelTextColor:messageLabelDetectLinks:messageLabelLinkColor:titleMessageBackgroundColor:gradientAlpha:backgroundAspectRatio:backgroundAspectRatioForced:backgroundColor:backgroundImage:backgroundImageURL:backgroundView:mapCoordinateRegion:mapAnnotation:avContentURL:disableLoopingContent:disableAVAudio:barcode2DValue:qrCodeValue:aztecValue:pdf417Value:headerOverride:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","modules":[{"name":"TicketmasterTickets"}],"extendedModule":"TicketmasterTickets","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"topLabelText"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"topLabelTextAlignment","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTextAlignment","text":"NSTextAlignment"},{"text":"?, ","kind":"text"},{"text":"topLabelTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"centerLabelText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"centerLabelTextAlignment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTextAlignment","text":"NSTextAlignment"},{"kind":"text","text":"?, "},{"text":"centerLabelTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"bottomLabelText","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"bottomLabelTextAlignment","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSTextAlignment","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTextAlignment"},{"text":"?, ","kind":"text"},{"text":"bottomLabelTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"titleLabelText","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"titleLabelTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"messageLabelText","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"messageLabelTextColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":"?, ","kind":"text"},{"text":"messageLabelDetectLinks","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"messageLabelLinkColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"text":"titleMessageBackgroundColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?, ","kind":"text"},{"text":"gradientAlpha","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"backgroundAspectRatio"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"backgroundAspectRatioForced"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"backgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"backgroundImage"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"backgroundImageURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"backgroundView","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":"?, "},{"text":"mapCoordinateRegion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MKCoordinateRegion","kind":"typeIdentifier","preciseIdentifier":"c:@SA@MKCoordinateRegion"},{"text":"?, ","kind":"text"},{"text":"mapAnnotation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKAnnotation","preciseIdentifier":"c:objc(pl)MKAnnotation"},{"text":"?, ","kind":"text"},{"text":"avContentURL","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"disableLoopingContent","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"disableAVAudio","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"barcode2DValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"qrCodeValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"aztecValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"pdf417Value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"headerOverride"},{"text":": ","kind":"text"},{"text":"TMTicketsPrebuiltModule","kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV"},{"text":".","kind":"text"},{"text":"HeaderOverride","preciseIdentifier":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV14HeaderOverrideV","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Method","title":"configure(topLabelText:topLabelTextAlignment:topLabelTextColor:centerLabelText:centerLabelTextAlignment:centerLabelTextColor:bottomLabelText:bottomLabelTextAlignment:bottomLabelTextColor:titleLabelText:titleLabelTextColor:messageLabelText:messageLabelTextColor:messageLabelDetectLinks:messageLabelLinkColor:titleMessageBackgroundColor:gradientAlpha:backgroundAspectRatio:backgroundAspectRatioForced:backgroundColor:backgroundImage:backgroundImageURL:backgroundView:mapCoordinateRegion:mapAnnotation:avContentURL:disableLoopingContent:disableAVAudio:barcode2DValue:qrCodeValue:aztecValue:pdf417Value:headerOverride:)","externalID":"s:19TicketmasterTickets25TMTicketsModuleHeaderViewC9configure12topLabelText0hiJ9Alignment0hiJ5Color06centeriJ00mijK00mijL006bottomiJ00nijK00nijL005titleiJ00oijL007messageiJ00pijL00pI11DetectLinks0pi4LinkL00o17MessageBackgroundL013gradientAlpha21backgroundAspectRatio0xyZ6Forced0xL00X5Image0X8ImageURL0xF019mapCoordinateRegion13mapAnnotation12avContentURL21disableLoopingContent14disableAVAudio14barcode2DValue11qrCodeValue10aztecValue11pdf417Value14headerOverrideSbSSSg_So06NSTextK0VSgSo7UIColorCSgA10_A13_A16_A10_A13_A16_A10_A16_A10_A16_SbA16_A16_14CoreFoundation7CGFloatVSgA20_SbA16_So7UIImageCSg10Foundation3URLVSgSo6UIViewCSgSo18MKCoordinateRegionaSgSo12MKAnnotation_pSgA27_S2bA10_A10_A10_A10_AA0c8PrebuiltD0V0E8OverrideVSgtF","symbolKind":"method"},"kind":"symbol","abstract":[{"type":"text","text":"configure header with various contents"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"topLabelText","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"topLabelTextAlignment","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSTextAlignment","preciseIdentifier":"c:@E@NSTextAlignment"},{"text":"? = .left, ","kind":"text"},{"text":"topLabelTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"centerLabelText"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"centerLabelTextAlignment"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@NSTextAlignment","kind":"typeIdentifier","text":"NSTextAlignment"},{"text":"? = .center, ","kind":"text"},{"text":"centerLabelTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"bottomLabelText"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"bottomLabelTextAlignment","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@NSTextAlignment","text":"NSTextAlignment","kind":"typeIdentifier"},{"text":"? = .right, ","kind":"text"},{"text":"bottomLabelTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"titleLabelText"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"titleLabelTextColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"messageLabelText","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? = nil, ","kind":"text"},{"text":"messageLabelTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"messageLabelDetectLinks"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = true, ","kind":"text"},{"text":"messageLabelLinkColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"? = nil, "},{"text":"titleMessageBackgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"? = nil, ","kind":"text"},{"text":"gradientAlpha","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":"? = 0.0, "},{"kind":"externalParam","text":"backgroundAspectRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":"? = nil, ","kind":"text"},{"text":"backgroundAspectRatioForced","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"backgroundImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"backgroundImageURL","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":"? = nil, ","kind":"text"},{"text":"backgroundView","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"mapCoordinateRegion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@SA@MKCoordinateRegion","text":"MKCoordinateRegion","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"mapAnnotation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MKAnnotation","text":"MKAnnotation"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"avContentURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"? = nil, "},{"text":"disableLoopingContent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"text":"disableAVAudio","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"barcode2DValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"qrCodeValue"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"aztecValue"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"pdf417Value","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"headerOverride","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule","preciseIdentifier":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV","text":"TMTicketsPrebuiltModule","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"HeaderOverride","kind":"typeIdentifier","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/HeaderOverride","preciseIdentifier":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV14HeaderOverrideV"},{"text":"? = nil) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"topLabelText","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Localized text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Nil = keep default alignment (.left)"}]}],"name":"topLabelTextAlignment"},{"content":[{"inlineContent":[{"type":"text","text":"Text color (nil = use default)"}],"type":"paragraph"}],"name":"topLabelTextColor"},{"content":[{"inlineContent":[{"type":"text","text":"Localized text"}],"type":"paragraph"}],"name":"centerLabelText"},{"content":[{"inlineContent":[{"text":"Nil = keep default alignment (.center)","type":"text"}],"type":"paragraph"}],"name":"centerLabelTextAlignment"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Text color (nil = use default)","type":"text"}]}],"name":"centerLabelTextColor"},{"name":"bottomLabelText","content":[{"inlineContent":[{"text":"Localized text,","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Nil = keep default alignment (.right)","type":"text"}],"type":"paragraph"}],"name":"bottomLabelTextAlignment"},{"content":[{"inlineContent":[{"type":"text","text":"Text color (nil = use default)"}],"type":"paragraph"}],"name":"bottomLabelTextColor"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Localized title text, shown in a box below image\/map\/video\/barcode"}]}],"name":"titleLabelText"},{"name":"titleLabelTextColor","content":[{"type":"paragraph","inlineContent":[{"text":"Text color (nil = use default)","type":"text"}]}]},{"name":"messageLabelText","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Localized multi-line message text, shown in a box below image\/map\/video\/barcode"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Text color (nil = use default)"}],"type":"paragraph"}],"name":"messageLabelTextColor"},{"name":"messageLabelDetectLinks","content":[{"type":"paragraph","inlineContent":[{"text":"Detect and highlight URLs, Dates, Addresses, Emails, and Phone numbers in message text","type":"text"}]}]},{"name":"messageLabelLinkColor","content":[{"inlineContent":[{"type":"text","text":"Link color (nil = use default)"}],"type":"paragraph"}]},{"name":"titleMessageBackgroundColor","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Color of text box background, shown below image\/map\/video\/barcode"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"0.0 = hide gradient, 1.0 = show gradient, nil = keep default gradient (0.0)"}]}],"name":"gradientAlpha"},{"content":[{"inlineContent":[{"type":"text","text":"Aspect ratio (width \/ height) of background content, will be overridden by actual aspect ratio of "},{"type":"codeVoice","code":"backgroundImage"},{"type":"text","text":" or "},{"code":"backgroundImageURL","type":"codeVoice"},{"type":"text","text":","}],"type":"paragraph"}],"name":"backgroundAspectRatio"},{"content":[{"inlineContent":[{"type":"text","text":"Aspect ratio will not be overridden by "},{"type":"codeVoice","code":"backgroundImage"},{"type":"text","text":" or "},{"code":"backgroundImageURL","type":"codeVoice"}],"type":"paragraph"}],"name":"backgroundAspectRatioForced"},{"name":"backgroundColor","content":[{"inlineContent":[{"text":"Background color","type":"text"}],"type":"paragraph"}]},{"name":"backgroundImage","content":[{"inlineContent":[{"text":"Background image (default image, will be replaced by ","type":"text"},{"type":"codeVoice","code":"backgroundImageURL"},{"text":", if any)","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Url of image that will be loaded to replace existing ","type":"text"},{"type":"codeVoice","code":"backgroundImage"},{"type":"text","text":" (if any)"}],"type":"paragraph"}],"name":"backgroundImageURL"},{"content":[{"type":"paragraph","inlineContent":[{"text":"UIView to use as background, will replace ","type":"text"},{"type":"codeVoice","code":"backgroundImage"},{"text":" or ","type":"text"},{"code":"backgroundImageURL","type":"codeVoice"}]}],"name":"backgroundView"},{"content":[{"inlineContent":[{"text":"Map region to show","type":"text"}],"type":"paragraph"}],"name":"mapCoordinateRegion"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Map annotation (if any)"}]}],"name":"mapAnnotation"},{"content":[{"inlineContent":[{"text":"URL to AV content","type":"text"}],"type":"paragraph"}],"name":"avContentURL"},{"name":"disableLoopingContent","content":[{"type":"paragraph","inlineContent":[{"text":"True = do not loop content","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"True = do not play audio"}],"type":"paragraph"}],"name":"disableAVAudio"},{"name":"barcode2DValue","content":[{"inlineContent":[{"type":"text","text":"Barcode code39 or code128 (string of letters and integers)"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"QR code value (any string)"}]}],"name":"qrCodeValue"},{"content":[{"inlineContent":[{"text":"Aztec barcode value (any string)","type":"text"}],"type":"paragraph"}],"name":"aztecValue"},{"name":"pdf417Value","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"PDF-417 code value (any string)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"A struct that overrides any of the above values","type":"text"}]}],"name":"headerOverride"}]},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"text":"Bool (true = contains valid header info, false = empty view)","type":"text"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview\/configure(toplabeltext:toplabeltextalignment:toplabeltextcolor:centerlabeltext:centerlabeltextalignment:centerlabeltextcolor:bottomlabeltext:bottomlabeltextalignment:bottomlabeltextcolor:titlelabeltext:titlelabeltextcolor:messagelabeltext:m-5amne"]}],"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule":{"navigatorTitle":[{"kind":"identifier","text":"TMTicketsPrebuiltModule"}],"abstract":[{"type":"text","text":"useful pre-built "},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","isActive":true,"type":"reference"},{"type":"text","text":" for the Tickets listing page"}],"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule","url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule","title":"TMTicketsPrebuiltModule","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TMTicketsPrebuiltModule","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule/HeaderOverride":{"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule\/headeroverride","title":"TMTicketsPrebuiltModule.HeaderOverride","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"HeaderOverride","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HeaderOverride"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/HeaderOverride"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView":{"title":"TMTicketsModuleHeaderView","abstract":[{"text":"quickly build a UIView for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView"}],"role":"symbol","type":"topic","url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview","navigatorTitle":[{"kind":"identifier","text":"TMTicketsModuleHeaderView"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMTicketsModuleHeaderView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView/configure(topLabelText:topLabelTextAlignment:topLabelTextColor:centerLabelText:centerLabelTextAlignment:centerLabelTextColor:bottomLabelText:bottomLabelTextAlignment:bottomLabelTextColor:titleLabelText:titleLabelTextColor:messageLabelText:messageLabelTextColor:messageLabelDetectLinks:messageLabelLinkColor:titleMessageBackgroundColor:gradientAlpha:backgroundAspectRatio:backgroundAspectRatioForced:backgroundColor:backgroundImage:backgroundImageURL:backgroundView:mapCoordinateRegion:mapAnnotation:avContentURL:disableLoopingContent:disableAVAudio:barcode2DValue:qrCodeValue:aztecValue:pdf417Value:headerOverride:)":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/configure(topLabelText:topLabelTextAlignment:topLabelTextColor:centerLabelText:centerLabelTextAlignment:centerLabelTextColor:bottomLabelText:bottomLabelTextAlignment:bottomLabelTextColor:titleLabelText:titleLabelTextColor:messageLabelText:messageLabelTextColor:messageLabelDetectLinks:messageLabelLinkColor:titleMessageBackgroundColor:gradientAlpha:backgroundAspectRatio:backgroundAspectRatioForced:backgroundColor:backgroundImage:backgroundImageURL:backgroundView:mapCoordinateRegion:mapAnnotation:avContentURL:disableLoopingContent:disableAVAudio:barcode2DValue:qrCodeValue:aztecValue:pdf417Value:headerOverride:)","role":"symbol","abstract":[{"type":"text","text":"configure header with various contents"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"configure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"topLabelText","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"topLabelTextAlignment","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSTextAlignment","preciseIdentifier":"c:@E@NSTextAlignment"},{"text":"?, ","kind":"text"},{"text":"topLabelTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"centerLabelText"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"centerLabelTextAlignment"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@NSTextAlignment","kind":"typeIdentifier","text":"NSTextAlignment"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"centerLabelTextColor"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"bottomLabelText"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"bottomLabelTextAlignment","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTextAlignment","text":"NSTextAlignment"},{"text":"?, ","kind":"text"},{"text":"bottomLabelTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"titleLabelText","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"titleLabelTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"text":"messageLabelText","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"messageLabelTextColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"messageLabelDetectLinks"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"messageLabelLinkColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"titleMessageBackgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"text":"gradientAlpha","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"backgroundAspectRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"backgroundAspectRatioForced","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"backgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"backgroundImage"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?, ","kind":"text"},{"text":"backgroundImageURL","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"text":"backgroundView","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"mapCoordinateRegion"},{"kind":"text","text":": "},{"text":"MKCoordinateRegion","preciseIdentifier":"c:@SA@MKCoordinateRegion","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"mapAnnotation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MKAnnotation","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MKAnnotation"},{"text":"?, ","kind":"text"},{"text":"avContentURL","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"?, ","kind":"text"},{"text":"disableLoopingContent","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"disableAVAudio"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"barcode2DValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"qrCodeValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"aztecValue"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"pdf417Value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"headerOverride","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV","text":"TMTicketsPrebuiltModule","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"HeaderOverride","preciseIdentifier":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV14HeaderOverrideV"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","title":"configure(topLabelText:topLabelTextAlignment:topLabelTextColor:centerLabelText:centerLabelTextAlignment:centerLabelTextColor:bottomLabelText:bottomLabelTextAlignment:bottomLabelTextColor:titleLabelText:titleLabelTextColor:messageLabelText:messageLabelTextColor:messageLabelDetectLinks:messageLabelLinkColor:titleMessageBackgroundColor:gradientAlpha:backgroundAspectRatio:backgroundAspectRatioForced:backgroundColor:backgroundImage:backgroundImageURL:backgroundView:mapCoordinateRegion:mapAnnotation:avContentURL:disableLoopingContent:disableAVAudio:barcode2DValue:qrCodeValue:aztecValue:pdf417Value:headerOverride:)","url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview\/configure(toplabeltext:toplabeltextalignment:toplabeltextcolor:centerlabeltext:centerlabeltextalignment:centerlabeltextcolor:bottomlabeltext:bottomlabeltextalignment:bottomlabeltextcolor:titlelabeltext:titlelabeltextcolor:messagelabeltext:m-5amne","kind":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","url":"\/documentation\/ticketmastertickets","title":"TicketmasterTickets","role":"collection","kind":"symbol","type":"topic","abstract":[{"text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes.","type":"text"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"TMTicketsModule","kind":"identifier"}],"abstract":[{"type":"text","text":"create a custom module to be displayed underneath the user’s list of Tickets on the Tickets listing page"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsModule"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","title":"TMTicketsModule","url":"\/documentation\/ticketmastertickets\/tmticketsmodule","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/title","value":"TMTicketsModuleHeaderView","op":"replace"},{"value":[{"text":"TMTicketsModuleHeaderView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/fragments"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/navigatorTitle","value":[{"text":"TMTicketsModuleHeaderView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/title","value":"TMTicketsModule","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/fragments","value":[{"text":"TMTicketsModule","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"TMTicketsModule"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/navigatorTitle","op":"replace"}]}]}