{"identifier":{"url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/checkoutDidReceive(paymentNonce:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller\/checkoutdidreceive(paymentnonce:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController"]]},"abstract":[{"type":"text","text":"Update checkout cart with an external payment nonce"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkoutDidReceive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"paymentNonce","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"String"},{"text":" containing a nonce representing a selected item in the user’s external payment wallet","type":"text"}]}],"name":"paymentNonce"}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"If external payment is enabled in the Purchase SDK, the integrating App may receive a Push Notification or Deep Link containing a payment nonce for the Checkout Cart."}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This is not available yet for most of our partners"}]}],"name":"Note","style":"note","type":"aside"}]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkoutDidReceive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"paymentNonce","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"symbolKind":"method","modules":[{"name":"TicketmasterPurchase"}],"externalID":"s:20TicketmasterPurchase30TMPurchaseNavigationControllerC18checkoutDidReceive12paymentNonceySS_tF","roleHeading":"Instance Method","role":"symbol","title":"checkoutDidReceive(paymentNonce:)"},"references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"kind":"symbol","role":"collection","title":"TicketmasterPurchase","url":"\/documentation\/ticketmasterpurchase","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","type":"topic","abstract":[]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController/checkoutDidReceive(paymentNonce:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"checkoutDidReceive","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"paymentNonce"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller\/checkoutdidreceive(paymentnonce:)","title":"checkoutDidReceive(paymentNonce:)","abstract":[{"text":"Update checkout cart with an external payment nonce","type":"text"}],"type":"topic","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/checkoutDidReceive(paymentNonce:)","role":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPurchaseNavigationController"}],"navigatorTitle":[{"text":"TMPurchaseNavigationController","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A navigation controller (view controller) that allows users to select and purchase tickets to a Ticketmaster Event."}],"role":"symbol","url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller","title":"TMPurchaseNavigationController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TMPurchaseNavigationController","op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/title"},{"value":[{"text":"TMPurchaseNavigationController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/fragments"},{"op":"replace","value":[{"text":"TMPurchaseNavigationController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/navigatorTitle"}]}]}