{"identifier":{"url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/discoveryDelegate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController"]]},"abstract":[{"type":"text","text":"A delegate to call discovery methods on (optional)"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"weak"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"discoveryDelegate"},{"text":": ","kind":"text"},{"text":"TMDiscoveryDelegate","preciseIdentifier":"s:24TicketmasterDiscoveryAPI19TMDiscoveryDelegateP","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller\/discoverydelegate"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"externalID":"s:20TicketmasterPurchase30TMPurchaseNavigationControllerC17discoveryDelegate0A12DiscoveryAPI011TMDiscoveryG0_pSgvp","symbolKind":"property","title":"discoveryDelegate","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"discoveryDelegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:24TicketmasterDiscoveryAPI19TMDiscoveryDelegateP","text":"TMDiscoveryDelegate"},{"kind":"text","text":"?"}],"modules":[{"name":"TicketmasterPurchase"}]},"references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController":{"url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController","kind":"symbol","abstract":[{"type":"text","text":"A navigation controller (view controller) that allows users to select and purchase tickets to a Ticketmaster Event."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPurchaseNavigationController"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TMPurchaseNavigationController"}],"title":"TMPurchaseNavigationController"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"type":"topic","url":"\/documentation\/ticketmasterpurchase","title":"TicketmasterPurchase","abstract":[],"role":"collection","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","kind":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController/discoveryDelegate":{"url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller\/discoverydelegate","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/discoveryDelegate","title":"discoveryDelegate","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"discoveryDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:24TicketmasterDiscoveryAPI19TMDiscoveryDelegateP","kind":"typeIdentifier","text":"TMDiscoveryDelegate"},{"kind":"text","text":"?"}],"kind":"symbol","abstract":[{"type":"text","text":"A delegate to call discovery methods on (optional)"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/title","value":"TMPurchaseNavigationController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/fragments","value":[{"text":"TMPurchaseNavigationController","kind":"identifier"}]},{"value":[{"text":"TMPurchaseNavigationController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/navigatorTitle"}]}]}