{"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eventDetailsNavigationController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"eventIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"internalTestingKeys","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"marketDomain","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MarketDomain","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterFoundation@E@MarketDomain"},{"text":", ","kind":"text"},{"text":"customFont","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"},{"text":"?) -> ","kind":"text"},{"text":"TMPurchaseNavigationController","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterPurchase@objc(cs)TMPurchaseNavigationController"}],"symbolKind":"method","title":"eventDetailsNavigationController(eventIdentifier:internalTestingKeys:marketDomain:customFont:)","externalID":"s:20TicketmasterPurchase30TMPurchaseNavigationControllerC012eventDetailsdE00F10Identifier19internalTestingKeys12marketDomain10customFontACSS_SDySSypG0A10Foundation06MarketM0OSo6UIFontCSgtFZ","roleHeading":"Type Method","extendedModule":"TicketmasterPurchase","modules":[{"name":"TicketmasterPurchase"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController"]]},"identifier":{"url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/eventDetailsNavigationController(eventIdentifier:internalTestingKeys:marketDomain:customFont:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller\/eventdetailsnavigationcontroller(eventidentifier:internaltestingkeys:marketdomain:customfont:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","abstract":[{"text":"Convenience function for creating an Event Details Page with simply an identifier","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventDetailsNavigationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"eventIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"internalTestingKeys"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"] = [:], "},{"kind":"externalParam","text":"marketDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MarketDomain","preciseIdentifier":"c:@M@TicketmasterFoundation@E@MarketDomain"},{"kind":"text","text":" = .US, "},{"kind":"externalParam","text":"customFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":"? = nil) -> "},{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController","kind":"typeIdentifier","text":"TMPurchaseNavigationController","preciseIdentifier":"c:@M@TicketmasterPurchase@objc(cs)TMPurchaseNavigationController"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"eventIdentifier","content":[{"inlineContent":[{"type":"text","text":"Identifier for the Event"}],"type":"paragraph"}]},{"name":"marketDomain","content":[{"inlineContent":[{"type":"text","text":"MarketDomain for the Event, defaults to .US"}],"type":"paragraph"}]}]}],"references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController/eventDetailsNavigationController(eventIdentifier:internalTestingKeys:marketDomain:customFont:)":{"abstract":[{"type":"text","text":"Convenience function for creating an Event Details Page with simply an identifier"}],"type":"topic","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/eventDetailsNavigationController(eventIdentifier:internalTestingKeys:marketDomain:customFont:)","title":"eventDetailsNavigationController(eventIdentifier:internalTestingKeys:marketDomain:customFont:)","url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller\/eventdetailsnavigationcontroller(eventidentifier:internaltestingkeys:marketdomain:customfont:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventDetailsNavigationController"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"eventIdentifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"internalTestingKeys","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"marketDomain","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MarketDomain","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterFoundation@E@MarketDomain"},{"text":", ","kind":"text"},{"text":"customFont","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"TMPurchaseNavigationController","preciseIdentifier":"c:@M@TicketmasterPurchase@objc(cs)TMPurchaseNavigationController"}]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"kind":"symbol","role":"collection","title":"TicketmasterPurchase","url":"\/documentation\/ticketmasterpurchase","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","type":"topic","abstract":[]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPurchaseNavigationController"}],"navigatorTitle":[{"text":"TMPurchaseNavigationController","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A navigation controller (view controller) that allows users to select and purchase tickets to a Ticketmaster Event."}],"role":"symbol","url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller","title":"TMPurchaseNavigationController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"TMPurchaseNavigationController","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/title"},{"op":"replace","value":[{"text":"TMPurchaseNavigationController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/fragments"},{"op":"replace","value":[{"text":"TMPurchaseNavigationController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/navigatorTitle"}]}]}