{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"preferredStatusBarStyle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIStatusBarStyle","text":"UIStatusBarStyle","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"preferredStatusBarStyle","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","modules":[{"name":"TicketmasterPurchase"}],"externalID":"c:@M@TicketmasterPurchase@objc(cs)TMPurchaseNavigationController(py)preferredStatusBarStyle","title":"preferredStatusBarStyle"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preferredStatusBarStyle"},{"kind":"text","text":": "},{"text":"UIStatusBarStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIStatusBarStyle"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller\/preferredstatusbarstyle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller\/preferredstatusbarstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/preferredStatusBarStyle"},"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"TMPurchaseNavigationController"},{"text":"has ","type":"text"},{"type":"codeVoice","code":"lightContent"}],"references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController/preferredStatusBarStyle":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/preferredStatusBarStyle","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller\/preferredstatusbarstyle","title":"preferredStatusBarStyle","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"preferredStatusBarStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIStatusBarStyle","preciseIdentifier":"c:@E@UIStatusBarStyle","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"preferredStatusBarStyle","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"TMPurchaseNavigationController"},{"type":"text","text":"has "},{"type":"codeVoice","code":"lightContent"}],"role":"symbol","kind":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"role":"collection","title":"TicketmasterPurchase","abstract":[],"type":"topic","url":"\/documentation\/ticketmasterpurchase","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController":{"navigatorTitle":[{"kind":"identifier","text":"TMPurchaseNavigationController"}],"type":"topic","title":"TMPurchaseNavigationController","kind":"symbol","abstract":[{"text":"A navigation controller (view controller) that allows users to select and purchase tickets to a Ticketmaster Event.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMPurchaseNavigationController"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController","url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"preferredStatusBarStyle"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"preferredStatusBarStyle","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"UIStatusBarStyle","preciseIdentifier":"c:@E@UIStatusBarStyle","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredStatusBarStyle"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"preferredStatusBarStyle","op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController~1preferredStatusBarStyle\/title"},{"value":[{"text":"preferredStatusBarStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController~1preferredStatusBarStyle\/fragments","op":"replace"},{"value":"TMPurchaseNavigationController","op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/title"},{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/fragments","value":[{"kind":"identifier","text":"TMPurchaseNavigationController"}],"op":"replace"},{"value":[{"kind":"identifier","text":"TMPurchaseNavigationController"}],"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}