{"metadata":{"externalID":"c:@M@TicketmasterPurchase@objc(cs)TMPurchaseNavigationController(im)viewWillAppear:","modules":[{"name":"TicketmasterPurchase"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}],"symbolKind":"method","title":"viewWillAppear(_:)","roleHeading":"Instance Method"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/viewWillAppear(_:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"animated","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller\/viewwillappear(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller\/viewwillappear(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"role":"collection","title":"TicketmasterPurchase","abstract":[],"type":"topic","url":"\/documentation\/ticketmasterpurchase","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController/viewWillAppear(_:)":{"abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller\/viewwillappear(_:)","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/viewWillAppear(_:)","navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}],"kind":"symbol","title":"viewWillAppear(_:)"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController":{"navigatorTitle":[{"kind":"identifier","text":"TMPurchaseNavigationController"}],"type":"topic","title":"TMPurchaseNavigationController","kind":"symbol","abstract":[{"text":"A navigation controller (view controller) that allows users to select and purchase tickets to a Ticketmaster Event.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMPurchaseNavigationController"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController","url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"viewWillAppear:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewWillAppear:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"viewWillAppear:"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"animated","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController~1viewWillAppear(_:)\/title","op":"replace","value":"viewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController~1viewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewWillAppear:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/title","value":"TMPurchaseNavigationController"},{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/fragments","value":[{"text":"TMPurchaseNavigationController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/navigatorTitle","op":"replace","value":[{"text":"TMPurchaseNavigationController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}