{"abstract":[{"text":"A class that stores the global configuration for the TicketmasterDiscoveryAPI SDK","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI"]]},"metadata":{"title":"TMDiscoveryAPI","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMDiscoveryAPI","kind":"identifier"}],"navigatorTitle":[{"text":"TMDiscoveryAPI","kind":"identifier"}],"symbolKind":"class","role":"symbol","modules":[{"name":"TicketmasterDiscoveryAPI"}],"externalID":"c:@M@TicketmasterDiscoveryAPI@objc(cs)TMDiscoveryAPI","roleHeading":"Class"},"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/apiKey","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/discoveryService","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/environment","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/marketDomain","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/sdkBuildInfo","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/version"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/configure(apiKey:region:completion:)","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/configure(tmxSettings:completion:)"]},{"title":"Type Properties","anchor":"Type-Properties","generated":true,"identifiers":["doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/apiKeyError","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/shared"]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/objc(pl)NSObject","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/s7CVarArgP","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/s28CustomDebugStringConvertibleP","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/s23CustomStringConvertibleP","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/SQ","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/SH"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMDiscoveryAPI","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TMDiscoveryAPI/environment":{"kind":"symbol","abstract":[{"type":"text","text":"The Ticketmaster Host Environment marching the API key provided"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi\/environment","title":"environment","role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/environment","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"environment","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConnectionEnvironment","kind":"typeIdentifier","preciseIdentifier":"s:22TicketmasterFoundation21ConnectionEnvironmentO"}]},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TMDiscoveryAPI/discoveryService":{"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/discoveryService","type":"topic","abstract":[{"type":"text","text":"Returns a configured instance of the Discovery service (if any)"}],"kind":"symbol","title":"discoveryService","url":"\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi\/discoveryservice","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"discoveryService"},{"kind":"text","text":": "},{"preciseIdentifier":"s:24TicketmasterDiscoveryAPI0B7ServiceC","kind":"typeIdentifier","text":"DiscoveryService"},{"kind":"text","text":"?"}]},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI","kind":"symbol","title":"TicketmasterDiscoveryAPI","abstract":[],"url":"\/documentation\/ticketmasterdiscoveryapi","type":"topic","role":"collection"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/s7CVarArgP":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/SQ":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TMDiscoveryAPI":{"navigatorTitle":[{"text":"TMDiscoveryAPI","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"A class that stores the global configuration for the TicketmasterDiscoveryAPI SDK","type":"text"}],"title":"TMDiscoveryAPI","url":"\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMDiscoveryAPI","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/objc(cs)NSObject":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/objc(pl)NSObject":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TMDiscoveryAPI/apiKey":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/apiKey","deprecated":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiKey"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"title":"apiKey","abstract":[{"type":"text","text":"Your Discovery API key"}],"type":"topic","url":"\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi\/apikey"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TMDiscoveryAPI/sdkBuildInfo":{"title":"sdkBuildInfo","role":"symbol","url":"\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi\/sdkbuildinfo","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkBuildInfo","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/sdkBuildInfo"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/SH":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TMDiscoveryAPI/configure(tmxSettings:completion:)":{"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/configure(tmxSettings:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"tmxSettings","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TicketmasterAuthentication@objc(cs)TMAuthentication","text":"TMAuthentication","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:26TicketmasterAuthentication16TMAuthenticationC11TMXSettingsV","text":"TMXSettings","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"didSetMarketDomain","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"configure(tmxSettings:completion:)","kind":"symbol","url":"\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi\/configure(tmxsettings:completion:)","role":"symbol","abstract":[{"type":"text","text":"configure Discovery API with your API key"}]},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TMDiscoveryAPI/configure(apiKey:region:completion:)":{"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/configure(apiKey:region:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"apiKey"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"region"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TicketmasterAuthentication@objc(cs)TMAuthentication","kind":"typeIdentifier","text":"TMAuthentication"},{"kind":"text","text":"."},{"preciseIdentifier":"s:26TicketmasterAuthentication16TMAuthenticationC19TMXDeploymentRegionO","kind":"typeIdentifier","text":"TMXDeploymentRegion"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"didSetMarketDomain"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"title":"configure(apiKey:region:completion:)","kind":"symbol","url":"\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi\/configure(apikey:region:completion:)","role":"symbol","abstract":[{"type":"text","text":"configure Discovery API with your API key"}]},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TMDiscoveryAPI/marketDomain":{"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/marketDomain","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"marketDomain","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TicketmasterFoundation@E@MarketDomain","text":"MarketDomain","kind":"typeIdentifier"}],"title":"marketDomain","kind":"symbol","url":"\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi\/marketdomain","role":"symbol","abstract":[{"type":"text","text":"which "},{"type":"codeVoice","code":"MarketDomain"},{"type":"text","text":" to discovery Events in"}]},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TMDiscoveryAPI/shared":{"abstract":[{"text":"The shared instance","type":"text"}],"title":"shared","role":"symbol","url":"\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi\/shared","identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/shared","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TicketmasterDiscoveryAPI@objc(cs)TMDiscoveryAPI","kind":"typeIdentifier","text":"TMDiscoveryAPI"}]},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TMDiscoveryAPI/apiKeyError":{"title":"apiKeyError","role":"symbol","url":"\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi\/apikeyerror","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiKeyError"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/apiKeyError"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TMDiscoveryAPI/init":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/init","url":"\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi\/init","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","kind":"symbol","title":"init"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TMDiscoveryAPI/version":{"role":"symbol","title":"version","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"version","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[{"text":"build version of TicketmasterDiscoveryAPI","type":"text"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi\/version","identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/version","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"TMDiscoveryAPI","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"TMDiscoveryAPI","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"TMDiscoveryAPI","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/init"],"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMDiscoveryAPI","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"TMDiscoveryAPI","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterDiscoveryAPI~1documentation~1TicketmasterDiscoveryAPI~1TMDiscoveryAPI\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TMDiscoveryAPI"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterDiscoveryAPI~1documentation~1TicketmasterDiscoveryAPI~1TMDiscoveryAPI\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TMDiscoveryAPI"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterDiscoveryAPI~1documentation~1TicketmasterDiscoveryAPI~1TMDiscoveryAPI\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}