{"abstract":[{"text":"add a custom button to “No Tickets” error page","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addCustomErrorPageButton"},{"text":"(","kind":"text"},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"title","content":[{"type":"paragraph","inlineContent":[{"text":"Localized custom button title, nil = hide button (default)","type":"text"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"inlineContent":[{"text":"This button will be shown above the default ","type":"text"},{"code":"Retry","type":"codeVoice"},{"type":"text","text":" button."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Upon being pressed, "},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsOrderDelegate\/handleErrorPageCustomButton(title:)","isActive":true,"type":"reference"},{"type":"text","text":" is called on your "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsOrderDelegate"},{"text":".","type":"text"}]},{"syntax":null,"code":["TMTickets.shared.addCustomErrorPageButton(title: \"Back to Homepage\")"],"type":"codeListing"}]}],"variants":[{"paths":["\/documentation\/ticketmastertickets\/tmtickets\/addcustomerrorpagebutton(title:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/addCustomErrorPageButton(title:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets"]]},"metadata":{"extendedModule":"TicketmasterTickets","roleHeading":"Instance Method","title":"addCustomErrorPageButton(title:)","modules":[{"name":"TicketmasterTickets"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addCustomErrorPageButton","kind":"identifier"},{"text":"(","kind":"text"},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"externalID":"s:19TicketmasterTickets9TMTicketsC24addCustomErrorPageButton5titleySSSg_tF","role":"symbol"},"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets":{"title":"TMTickets","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMTickets","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets","navigatorTitle":[{"kind":"identifier","text":"TMTickets"}],"abstract":[{"type":"text","text":"main class of Tickets SDK, intended to be used as singleton"}],"url":"\/documentation\/ticketmastertickets\/tmtickets"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsOrderDelegate":{"title":"TMTicketsOrderDelegate","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsOrderDelegate","kind":"symbol","navigatorTitle":[{"text":"TMTicketsOrderDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"optional delegate to be informed of non-analytics User-actions"}],"url":"\/documentation\/ticketmastertickets\/tmticketsorderdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"TMTicketsOrderDelegate","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsOrderDelegate/handleErrorPageCustomButton(title:)":{"url":"\/documentation\/ticketmastertickets\/tmticketsorderdelegate\/handleerrorpagecustombutton(title:)","kind":"symbol","abstract":[{"text":"Method is invoked when custom button title is set by ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/addCustomErrorPageButton(title:)","isActive":true}],"role":"symbol","title":"handleErrorPageCustomButton(title:)","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsOrderDelegate\/handleErrorPageCustomButton(title:)","type":"topic","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleErrorPageCustomButton","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"title"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"url":"\/documentation\/ticketmastertickets","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes."}],"title":"TicketmasterTickets"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/addCustomErrorPageButton(title:)":{"type":"topic","title":"addCustomErrorPageButton(title:)","url":"\/documentation\/ticketmastertickets\/tmtickets\/addcustomerrorpagebutton(title:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addCustomErrorPageButton"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/addCustomErrorPageButton(title:)","abstract":[{"text":"add a custom button to “No Tickets” error page","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/title","op":"replace","value":"TMTickets"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/fragments","value":[{"text":"TMTickets","kind":"identifier"}],"op":"replace"},{"value":[{"text":"TMTickets","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/navigatorTitle"}]}]}