{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"success"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"success","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"successful configuration, Tickets SDK is ready to use (present "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController"},{"type":"text","text":")"}]}]},{"name":"failure","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"configuration error"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"this method "},{"type":"strong","inlineContent":[{"type":"text","text":"must"}]},{"type":"text","text":" be called after "},{"type":"codeVoice","code":"TMAuthentication.shared.configure()"}]}],"type":"aside","name":"Important"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Example usage:"}]},{"type":"codeListing","syntax":null,"code":["\/\/ brandedServiceSettings is a combination of branding and TMX service settings (like ApiKey)","TMAuthentication.shared.configure(brandedServiceSettings: brandedServiceSettings) { _ in","    \/\/ TMTickets inherits it's configuration from TMAuthentication","    TMTickets.shared.configure {","        \/\/ Tickets is configured and ready","        let ticketsVC = TMTicketsViewController()","        self.navigationController?.pushViewController(ticketsVC, animated: true)","        \/\/ or","        self.present(ticketsVC, animated: true)","","    } failure: { error in","        \/\/ something went wrong, probably TMAuthentication was not configured correctly","    }","} failure: { error in","    \/\/ something went wrong, probably the wrong apiKey+region combination","}"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ticketmastertickets\/tmtickets\/configure(success:failure:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/configure(success:failure:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"configure Tickets SDK using settings from Authentication SDK"}],"kind":"symbol","metadata":{"role":"symbol","title":"configure(success:failure:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"success"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:19TicketmasterTickets9TMTicketsC9configure7success7failureyyyc_ys5Error_pctF","extendedModule":"TicketmasterTickets","modules":[{"name":"TicketmasterTickets"}]},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets"]]},"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsViewController":{"role":"symbol","title":"TMTicketsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTicketsViewController"}],"abstract":[{"type":"text","text":"this class wraps the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView"},{"type":"text","text":" in a "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" for ease of use"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TMTicketsViewController"}],"url":"\/documentation\/ticketmastertickets\/tmticketsviewcontroller"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsView":{"role":"symbol","title":"TMTicketsView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTicketsView"}],"abstract":[{"type":"text","text":"use to render Tickets SDK as a UIView embedded inside of your own UIViewController"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TMTicketsView"}],"url":"\/documentation\/ticketmastertickets\/tmticketsview"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets":{"role":"symbol","title":"TMTickets","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTickets"}],"abstract":[{"type":"text","text":"main class of Tickets SDK, intended to be used as singleton"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TMTickets"}],"url":"\/documentation\/ticketmastertickets\/tmtickets"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"role":"collection","title":"TicketmasterTickets","abstract":[{"type":"text","text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes."}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","kind":"symbol","type":"topic","url":"\/documentation\/ticketmastertickets"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/configure(success:failure:)":{"role":"symbol","title":"configure(success:failure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"success"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"configure Tickets SDK using settings from Authentication SDK"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/configure(success:failure:)","kind":"symbol","type":"topic","url":"\/documentation\/ticketmastertickets\/tmtickets\/configure(success:failure:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController\/title","value":"TMTicketsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController\/fragments","value":[{"kind":"identifier","text":"TMTicketsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/title","value":"TMTicketsView"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/fragments","value":[{"kind":"identifier","text":"TMTicketsView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/title","value":"TMTickets"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/fragments","value":[{"kind":"identifier","text":"TMTickets"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}