{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configure"},{"text":"(","kind":"text"},{"text":"callSource","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"success","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" () -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"failure","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" ("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"optional name of class or process calling this method","type":"text"}]}],"name":"callSource"},{"name":"success","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"successful configuration, Tickets SDK is ready to use (present "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController"},{"type":"text","text":")"}]}]},{"name":"failure","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"configuration error"}]}]}]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"aside","name":"Important","content":[{"type":"paragraph","inlineContent":[{"text":"this method ","type":"text"},{"type":"strong","inlineContent":[{"text":"must","type":"text"}]},{"type":"text","text":" be called after "},{"code":"TMAuthentication.shared.configure()","type":"codeVoice"}]}],"style":"important"},{"inlineContent":[{"text":"Example usage:","type":"text"}],"type":"paragraph"},{"code":["\/\/ brandedServiceSettings is a combination of branding and TMX service settings (like ApiKey)","TMAuthentication.shared.configure(brandedServiceSettings: brandedServiceSettings) { _ in","    \/\/ TMTickets inherits it's configuration from TMAuthentication","    TMTickets.shared.configure {","        \/\/ Tickets is configured and ready","        let ticketsVC = TMTicketsViewController()","        self.navigationController?.pushViewController(ticketsVC, animated: true)","        \/\/ or","        self.present(ticketsVC, animated: true)","","    } failure: { error in","        \/\/ something went wrong, probably TMAuthentication was not configured correctly","    }","} failure: { error in","    \/\/ something went wrong, probably the wrong apiKey+region combination","}"],"type":"codeListing","syntax":null}],"kind":"content"}],"metadata":{"extendedModule":"TicketmasterTickets","roleHeading":"Instance Method","title":"configure(callSource:success:failure:)","symbolKind":"method","role":"symbol","modules":[{"name":"TicketmasterTickets"}],"externalID":"s:19TicketmasterTickets9TMTicketsC9configure10callSource7success7failureySSSg_yycys5Error_pctF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configure"},{"text":"(","kind":"text"},{"text":"callSource","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"success","kind":"externalParam"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"failure"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/configure(callSource:success:failure:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"configure Tickets SDK using settings from Authentication SDK"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmastertickets\/tmtickets\/configure(callsource:success:failure:)"]}],"sections":[],"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"abstract":[{"text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","url":"\/documentation\/ticketmastertickets","type":"topic","title":"TicketmasterTickets","kind":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsViewController":{"kind":"symbol","title":"TMTicketsViewController","navigatorTitle":[{"kind":"identifier","text":"TMTicketsViewController"}],"role":"symbol","url":"\/documentation\/ticketmastertickets\/tmticketsviewcontroller","abstract":[{"text":"this class wraps the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView","isActive":true},{"type":"text","text":" in a "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" for ease of use"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TMTicketsViewController","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/configure(callSource:success:failure:)":{"role":"symbol","url":"\/documentation\/ticketmastertickets\/tmtickets\/configure(callsource:success:failure:)","abstract":[{"text":"configure Tickets SDK using settings from Authentication SDK","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configure","kind":"identifier"},{"kind":"text","text":"("},{"text":"callSource","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"success"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":", ","kind":"text"},{"text":"failure","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/configure(callSource:success:failure:)","title":"configure(callSource:success:failure:)"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets":{"url":"\/documentation\/ticketmastertickets\/tmtickets","role":"symbol","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets","kind":"symbol","abstract":[{"text":"main class of Tickets SDK, intended to be used as singleton","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMTickets","kind":"identifier"}],"navigatorTitle":[{"text":"TMTickets","kind":"identifier"}],"title":"TMTickets"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsView":{"kind":"symbol","title":"TMTicketsView","navigatorTitle":[{"text":"TMTicketsView","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ticketmastertickets\/tmticketsview","abstract":[{"type":"text","text":"use to render Tickets SDK as a UIView embedded inside of your own UIViewController"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTicketsView"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController\/title","value":"TMTicketsViewController","op":"replace"},{"value":[{"kind":"identifier","text":"TMTicketsViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController\/fragments"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/title","value":"TMTickets","op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/fragments","value":[{"kind":"identifier","text":"TMTickets"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/title","value":"TMTicketsView","op":"replace"},{"value":[{"kind":"identifier","text":"TMTicketsView"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}