{"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/display(orderOrEventId:type:action:callSource:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"display Tickets listing for a particular Order or Event, if not found show the My Events page"}],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"display","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"orderOrEventId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/IdType","text":"IdType","preciseIdentifier":"s:19TicketmasterTickets9TMTicketsC6IdTypeO","kind":"typeIdentifier"},{"text":" = .any, ","kind":"text"},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"text":"ActionType","kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets9TMTicketsC10ActionTypeO","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/ActionType"},{"text":"? = nil, ","kind":"text"},{"text":"callSource","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? = nil)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"orderOrEventId","content":[{"type":"paragraph","inlineContent":[{"text":"Discovery or Legacy Order or Event identifier","type":"text"}]}]},{"name":"type","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Typically Orders and Events have different identifiers, but you can limit searching to one or the other here"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Optional action to take upon opening the correct Tickets listing page"}],"type":"paragraph"}],"name":"action"},{"name":"callSource","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional name of class or process calling this method"}]}]}]}],"metadata":{"modules":[{"name":"TicketmasterTickets"}],"extendedModule":"TicketmasterTickets","role":"symbol","externalID":"s:19TicketmasterTickets9TMTicketsC7display14orderOrEventId4type6action10callSourceySS_AC0H4TypeOAC06ActionM0OSgSSSgtF","title":"display(orderOrEventId:type:action:callSource:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"display"},{"kind":"text","text":"("},{"text":"orderOrEventId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:19TicketmasterTickets9TMTicketsC6IdTypeO","kind":"typeIdentifier","text":"IdType"},{"text":", ","kind":"text"},{"text":"action","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:19TicketmasterTickets9TMTicketsC10ActionTypeO","text":"ActionType","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"callSource","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"roleHeading":"Instance Method","symbolKind":"method"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmastertickets\/tmtickets\/display(orderoreventid:type:action:callsource:)"]}],"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/ActionType":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/ActionType","abstract":[{"text":"action to perform upon completion of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/display(orderOrEventId:type:action:callSource:)"}],"kind":"symbol","title":"TMTickets.ActionType","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ActionType","kind":"identifier"}],"navigatorTitle":[{"text":"ActionType","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ticketmastertickets\/tmtickets\/actiontype"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/display(orderOrEventId:type:action:callSource:)":{"kind":"symbol","url":"\/documentation\/ticketmastertickets\/tmtickets\/display(orderoreventid:type:action:callsource:)","title":"display(orderOrEventId:type:action:callSource:)","abstract":[{"type":"text","text":"display Tickets listing for a particular Order or Event, if not found show the My Events page"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/display(orderOrEventId:type:action:callSource:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"display","kind":"identifier"},{"kind":"text","text":"("},{"text":"orderOrEventId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets9TMTicketsC6IdTypeO","text":"IdType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"action"},{"text":": ","kind":"text"},{"text":"ActionType","kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets9TMTicketsC10ActionTypeO"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"callSource"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","title":"TicketmasterTickets","type":"topic","abstract":[{"type":"text","text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes."}],"kind":"symbol","url":"\/documentation\/ticketmastertickets","role":"collection"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets":{"navigatorTitle":[{"text":"TMTickets","kind":"identifier"}],"type":"topic","abstract":[{"text":"main class of Tickets SDK, intended to be used as singleton","type":"text"}],"url":"\/documentation\/ticketmastertickets\/tmtickets","role":"symbol","title":"TMTickets","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMTickets","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/IdType":{"url":"\/documentation\/ticketmastertickets\/tmtickets\/idtype","title":"TMTickets.IdType","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/IdType","type":"topic","kind":"symbol","abstract":[{"text":"search for Event or Order on ","type":"text"},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/display(orderOrEventId:type:action:callSource:)","isActive":true,"type":"reference"}],"navigatorTitle":[{"text":"IdType","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdType"}]}},"variantOverrides":[{"patch":[{"value":"TMTickets","op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/title"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/fragments","value":[{"text":"TMTickets","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/navigatorTitle","value":[{"text":"TMTickets","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}