{"metadata":{"modules":[{"name":"TicketmasterTickets"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"moduleDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TMTicketsModuleDelegate","kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets23TMTicketsModuleDelegateP"},{"text":"?","kind":"text"}],"title":"moduleDelegate","role":"symbol","roleHeading":"Instance Property","externalID":"s:19TicketmasterTickets9TMTicketsC14moduleDelegateAA0c6ModuleE0_pSgvp"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmastertickets\/tmtickets\/moduledelegate"]}],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"optional delegate to implement prebuilt and custom "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule"},{"type":"text","text":" to be rendered on the Tickets listing page"}],"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/moduleDelegate","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"moduleDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets23TMTicketsModuleDelegateP","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleDelegate","text":"TMTicketsModuleDelegate"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets":{"abstract":[{"type":"text","text":"main class of Tickets SDK, intended to be used as singleton"}],"url":"\/documentation\/ticketmastertickets\/tmtickets","navigatorTitle":[{"text":"TMTickets","kind":"identifier"}],"title":"TMTickets","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTickets"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets","role":"symbol","kind":"symbol","type":"topic"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleDelegate":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMTicketsModuleDelegate","kind":"identifier"}],"url":"\/documentation\/ticketmastertickets\/tmticketsmoduledelegate","navigatorTitle":[{"text":"TMTicketsModuleDelegate","kind":"identifier"}],"title":"TMTicketsModuleDelegate","abstract":[{"text":"optional delegate to implement prebuilt and custom ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","isActive":true},{"type":"text","text":" to be rendered on the Tickets listing page"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleDelegate","kind":"symbol","type":"topic"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","navigatorTitle":[{"kind":"identifier","text":"TMTicketsModule"}],"kind":"symbol","title":"TMTicketsModule","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsModule"}],"abstract":[{"text":"create a custom module to be displayed underneath the user’s list of Tickets on the Tickets listing page","type":"text"}],"url":"\/documentation\/ticketmastertickets\/tmticketsmodule"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","url":"\/documentation\/ticketmastertickets","title":"TicketmasterTickets","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes."}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/moduleDelegate":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moduleDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:19TicketmasterTickets23TMTicketsModuleDelegateP","kind":"typeIdentifier","text":"TMTicketsModuleDelegate"},{"text":"?","kind":"text"}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/moduledelegate","title":"moduleDelegate","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/moduleDelegate","kind":"symbol","abstract":[{"type":"text","text":"optional delegate to implement prebuilt and custom "},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","isActive":true},{"text":" to be rendered on the Tickets listing page","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TMTickets","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/title","op":"replace"},{"value":[{"kind":"identifier","text":"TMTickets"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/fragments"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/title","value":"TMTicketsModule","op":"replace"},{"value":[{"text":"TMTicketsModule","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/fragments"}]}]}