{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ticketsView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsView","text":"TMTicketsView"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"ticketsView","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Reference to main "},{"type":"codeVoice","code":"TMTicketsView"},{"type":"text","text":" which will display user tickets."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Calling this method is not needed if you are using the recommended "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController"},{"type":"text","text":" instead of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView"},{"type":"text","text":"."}]}],"type":"aside","name":"Important"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ticketmastertickets\/tmtickets\/start(ticketsview:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/start(ticketsView:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"method for connecting a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView"},{"type":"text","text":" you have initialized yourself to the Tickets SDK"}],"kind":"symbol","metadata":{"role":"symbol","title":"start(ticketsView:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ticketsView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TMTicketsView","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsView"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:19TicketmasterTickets9TMTicketsC5start11ticketsViewyAA0cF0C_tF","extendedModule":"TicketmasterTickets","modules":[{"name":"TicketmasterTickets"}]},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets"]]},"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsViewController":{"role":"symbol","title":"TMTicketsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTicketsViewController"}],"abstract":[{"type":"text","text":"this class wraps the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView"},{"type":"text","text":" in a "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" for ease of use"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TMTicketsViewController"}],"url":"\/documentation\/ticketmastertickets\/tmticketsviewcontroller"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"role":"collection","title":"TicketmasterTickets","abstract":[{"type":"text","text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes."}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","kind":"symbol","type":"topic","url":"\/documentation\/ticketmastertickets"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsView":{"role":"symbol","title":"TMTicketsView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTicketsView"}],"abstract":[{"type":"text","text":"use to render Tickets SDK as a UIView embedded inside of your own UIViewController"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TMTicketsView"}],"url":"\/documentation\/ticketmastertickets\/tmticketsview"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/start(ticketsView:)":{"role":"symbol","title":"start(ticketsView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ticketsView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TMTicketsView","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsView"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"method for connecting a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView"},{"type":"text","text":" you have initialized yourself to the Tickets SDK"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/start(ticketsView:)","kind":"symbol","type":"topic","url":"\/documentation\/ticketmastertickets\/tmtickets\/start(ticketsview:)"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets":{"role":"symbol","title":"TMTickets","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTickets"}],"abstract":[{"type":"text","text":"main class of Tickets SDK, intended to be used as singleton"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TMTickets"}],"url":"\/documentation\/ticketmastertickets\/tmtickets"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController\/title","value":"TMTicketsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController\/fragments","value":[{"kind":"identifier","text":"TMTicketsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/title","value":"TMTicketsView"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/fragments","value":[{"kind":"identifier","text":"TMTicketsView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/title","value":"TMTickets"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/fragments","value":[{"kind":"identifier","text":"TMTickets"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}