{"abstract":[{"type":"text","text":"method for connecting a "},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView","isActive":true},{"type":"text","text":" you have initialized yourself to the Tickets SDK"}],"metadata":{"modules":[{"name":"TicketmasterTickets"}],"externalID":"s:19TicketmasterTickets9TMTicketsC5start11ticketsView10callSourceyAA0cF0C_SSSgtF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"ticketsView"},{"text":": ","kind":"text"},{"text":"TMTicketsView","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsView"},{"text":", ","kind":"text"},{"text":"callSource","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","extendedModule":"TicketmasterTickets","title":"start(ticketsView:callSource:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ticketsView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsView","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView","kind":"typeIdentifier","text":"TMTicketsView"},{"text":", ","kind":"text"},{"text":"callSource","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil)"}]}]},{"kind":"parameters","parameters":[{"name":"ticketsView","content":[{"type":"paragraph","inlineContent":[{"text":"Reference to main ","type":"text"},{"code":"TMTicketsView","type":"codeVoice"},{"type":"text","text":" which will display user tickets."}]}]},{"name":"callSource","content":[{"inlineContent":[{"text":"optional name of class or process calling this method","type":"text"}],"type":"paragraph"}]}]},{"content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"type":"aside","content":[{"inlineContent":[{"type":"text","text":"Calling this method is not needed if you are using the recommended "},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController","isActive":true},{"text":" instead of ","type":"text"},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView","type":"reference","isActive":true},{"type":"text","text":". However, this method will not be deprecated so feel free to use it."}],"type":"paragraph"}],"style":"important","name":"Important"}],"kind":"content"}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmastertickets\/tmtickets\/start(ticketsview:callsource:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/start(ticketsView:callSource:)"},"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TMTickets","kind":"identifier"}],"url":"\/documentation\/ticketmastertickets\/tmtickets","kind":"symbol","title":"TMTickets","type":"topic","abstract":[{"type":"text","text":"main class of Tickets SDK, intended to be used as singleton"}],"navigatorTitle":[{"text":"TMTickets","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","title":"TicketmasterTickets","kind":"symbol","role":"collection","type":"topic","abstract":[{"text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes.","type":"text"}],"url":"\/documentation\/ticketmastertickets"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/start(ticketsView:callSource:)":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/start(ticketsView:callSource:)","url":"\/documentation\/ticketmastertickets\/tmtickets\/start(ticketsview:callsource:)","title":"start(ticketsView:callSource:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"text":"(","kind":"text"},{"text":"ticketsView","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TMTicketsView","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"callSource","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"abstract":[{"type":"text","text":"method for connecting a "},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView","isActive":true},{"type":"text","text":" you have initialized yourself to the Tickets SDK"}],"kind":"symbol","type":"topic"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsViewController":{"url":"\/documentation\/ticketmastertickets\/tmticketsviewcontroller","title":"TMTicketsViewController","type":"topic","role":"symbol","abstract":[{"type":"text","text":"this class wraps the "},{"isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView","type":"reference"},{"type":"text","text":" in a "},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":" for ease of use"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TMTicketsViewController","kind":"identifier"}],"navigatorTitle":[{"text":"TMTicketsViewController","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsView":{"url":"\/documentation\/ticketmastertickets\/tmticketsview","title":"TMTicketsView","type":"topic","role":"symbol","abstract":[{"type":"text","text":"use to render Tickets SDK as a UIView embedded inside of your own UIViewController"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TMTicketsView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TMTicketsView"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView"}},"variantOverrides":[{"patch":[{"value":"TMTickets","op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/title"},{"value":[{"kind":"identifier","text":"TMTickets"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/fragments"},{"value":"TMTicketsViewController","op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController\/fragments","value":[{"text":"TMTicketsViewController","kind":"identifier"}]},{"op":"replace","value":"TMTicketsView","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/fragments","value":[{"text":"TMTicketsView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}