{"abstract":[{"text":"Application Configuration and Account Operations","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication","interfaceLanguage":"swift"},"hierarchy":{"paths":[[]]},"primaryContentSections":[{"content":[{"type":"heading","level":2,"text":"Overview","anchor":"Overview"},{"inlineContent":[{"text":"The TicketmasterAuthentication framework provides:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Account Authentication operations (login, logout, refresh oauth token, get Member info, etc…)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Application Configuration (configure Ticketmaster frameworks to work with your specific App)"}]}]}],"type":"orderedList"}],"kind":"content"}],"metadata":{"title":"TicketmasterAuthentication","role":"collection","externalID":"TicketmasterAuthentication","symbolKind":"module","roleHeading":"Framework","modules":[{"name":"TicketmasterAuthentication"}]},"sections":[],"topicSections":[{"anchor":"Classes","identifiers":["doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication"],"generated":true,"title":"Classes"},{"title":"Protocols","identifiers":["doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMApigeeConfigurationProvider","doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAssertion","doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthenticationDelegate","doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthenticationExternalTokenProvider","doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthenticationProvider","doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMDeviceBindingProvider","doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMEncodableAssertion"],"generated":true,"anchor":"Protocols"},{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/AppAttestAssertion","doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMApigeeConfig","doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthToken","doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMDeviceKey","doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMMFAToken","doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMMemberInfo","doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMXNetworkServiceConfig"],"title":"Structures","generated":true,"anchor":"Structures"},{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/UIKit"],"title":"Extended Modules","generated":true,"anchor":"Extended-Modules"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterauthentication"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ticketmasterauthentication"]}],"references":{"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMApigeeConfigurationProvider":{"abstract":[{"text":"optional protocol to provide Configuration operations","type":"text"}],"navigatorTitle":[{"text":"TMApigeeConfigurationProvider","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMApigeeConfigurationProvider","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMApigeeConfigurationProvider","role":"symbol","title":"TMApigeeConfigurationProvider","url":"\/documentation\/ticketmasterauthentication\/tmapigeeconfigurationprovider"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMXNetworkServiceConfig":{"type":"topic","url":"\/documentation\/ticketmasterauthentication\/tmxnetworkserviceconfig","kind":"symbol","abstract":[{"type":"text","text":"struct representing TMX networking configuration"}],"title":"TMXNetworkServiceConfig","role":"symbol","navigatorTitle":[{"text":"TMXNetworkServiceConfig","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMXNetworkServiceConfig","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMXNetworkServiceConfig","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthToken":{"abstract":[{"text":"struct representing a user’s OAuth data","type":"text"}],"navigatorTitle":[{"text":"TMAuthToken","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMAuthToken","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthToken","role":"symbol","title":"TMAuthToken","url":"\/documentation\/ticketmasterauthentication\/tmauthtoken"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/UIKit":{"url":"\/documentation\/ticketmasterauthentication\/uikit","title":"UIKit","kind":"symbol","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/UIKit"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMMemberInfo":{"abstract":[{"type":"text","text":"struct representing a user’s Account info"}],"navigatorTitle":[{"text":"TMMemberInfo","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMMemberInfo","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMMemberInfo","role":"symbol","title":"TMMemberInfo","url":"\/documentation\/ticketmasterauthentication\/tmmemberinfo"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMMFAToken":{"role":"symbol","kind":"symbol","title":"TMMFAToken","type":"topic","url":"\/documentation\/ticketmasterauthentication\/tmmfatoken","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMMFAToken","abstract":[{"type":"text","text":"struct representing Multi-Factor Authentication Token metadata"}],"navigatorTitle":[{"kind":"identifier","text":"TMMFAToken"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMMFAToken"}]},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthenticationProvider":{"title":"TMAuthenticationProvider","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMAuthenticationProvider","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthenticationProvider","type":"topic","abstract":[{"text":"optional protocol to provide Authentication operations like login, logout, member info, etc.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"TMAuthenticationProvider","kind":"identifier"}],"url":"\/documentation\/ticketmasterauthentication\/tmauthenticationprovider"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TicketmasterAuthenticationVersionString":{"abstract":[{"text":"Project version string for TicketmasterAuthentication.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"TicketmasterAuthenticationVersionString","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TicketmasterAuthenticationVersionString","role":"symbol","title":"TicketmasterAuthenticationVersionString","url":"\/documentation\/ticketmasterauthentication\/ticketmasterauthenticationversionstring"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthenticationExternalTokenProvider":{"abstract":[{"text":"optional protocol to provide refresh\/validation functionality for external tokens","type":"text"}],"navigatorTitle":[{"text":"TMAuthenticationExternalTokenProvider","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMAuthenticationExternalTokenProvider","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthenticationExternalTokenProvider","role":"symbol","title":"TMAuthenticationExternalTokenProvider","url":"\/documentation\/ticketmasterauthentication\/tmauthenticationexternaltokenprovider"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMEncodableAssertion":{"abstract":[],"navigatorTitle":[{"text":"TMEncodableAssertion","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMEncodableAssertion","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMEncodableAssertion","role":"symbol","title":"TMEncodableAssertion","url":"\/documentation\/ticketmasterauthentication\/tmencodableassertion"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMDeviceBindingProvider":{"abstract":[{"text":"optional protocol to provide Device Binding operations.","type":"text"}],"navigatorTitle":[{"text":"TMDeviceBindingProvider","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMDeviceBindingProvider","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMDeviceBindingProvider","role":"symbol","title":"TMDeviceBindingProvider","url":"\/documentation\/ticketmasterauthentication\/tmdevicebindingprovider"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMApigeeConfig":{"role":"symbol","kind":"symbol","title":"TMApigeeConfig","type":"topic","url":"\/documentation\/ticketmasterauthentication\/tmapigeeconfig","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMApigeeConfig","abstract":[{"text":"struct representing a specific configuration’s settings","type":"text"}],"navigatorTitle":[{"text":"TMApigeeConfig","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMApigeeConfig","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAssertion":{"abstract":[],"navigatorTitle":[{"text":"TMAssertion","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMAssertion","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAssertion","role":"symbol","title":"TMAssertion","url":"\/documentation\/ticketmasterauthentication\/tmassertion"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMDeviceKey":{"abstract":[{"type":"text","text":"Attestation Bound Device Key"}],"navigatorTitle":[{"text":"TMDeviceKey","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMDeviceKey","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMDeviceKey","role":"symbol","title":"TMDeviceKey","url":"\/documentation\/ticketmasterauthentication\/tmdevicekey"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthentication":{"abstract":[{"code":"TMAuthentication","type":"codeVoice"},{"text":" provides login UI, oauth tokens, member info, and MFA support.","type":"text"}],"navigatorTitle":[{"text":"TMAuthentication","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMAuthentication","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication","role":"symbol","title":"TMAuthentication","url":"\/documentation\/ticketmasterauthentication\/tmauthentication"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TicketmasterAuthenticationVersionNumber":{"title":"TicketmasterAuthenticationVersionNumber","fragments":[{"text":"TicketmasterAuthenticationVersionNumber","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TicketmasterAuthenticationVersionNumber","type":"topic","abstract":[{"text":"Project version number for TicketmasterAuthentication.","type":"text"}],"kind":"symbol","url":"\/documentation\/ticketmasterauthentication\/ticketmasterauthenticationversionnumber"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthenticationDelegate":{"title":"TMAuthenticationDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMAuthenticationDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthenticationDelegate","type":"topic","abstract":[{"text":"optional delegate to recieve login state change information from ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication","isActive":true}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TMAuthenticationDelegate"}],"url":"\/documentation\/ticketmasterauthentication\/tmauthenticationdelegate"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication":{"type":"topic","abstract":[{"type":"text","text":"Application Configuration and Account Operations"}],"url":"\/documentation\/ticketmasterauthentication","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication","kind":"symbol","role":"collection","title":"TicketmasterAuthentication"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/AppAttestAssertion":{"abstract":[],"navigatorTitle":[{"text":"AppAttestAssertion","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AppAttestAssertion","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/AppAttestAssertion","role":"symbol","title":"AppAttestAssertion","url":"\/documentation\/ticketmasterauthentication\/appattestassertion"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication"],"title":"Classes","generated":true,"anchor":"Classes"},{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TicketmasterAuthenticationVersionNumber","doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TicketmasterAuthenticationVersionString"],"title":"Variables","generated":true,"anchor":"Variables"}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":"TMAuthentication","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterAuthentication~1documentation~1TicketmasterAuthentication~1TMAuthentication\/title"},{"op":"replace","value":[{"text":"TMAuthentication","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterAuthentication~1documentation~1TicketmasterAuthentication~1TMAuthentication\/fragments"},{"op":"replace","value":[{"text":"TMAuthentication","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterAuthentication~1documentation~1TicketmasterAuthentication~1TMAuthentication\/navigatorTitle"}]}]}