{"abstract":[{"type":"text","text":"important UI text will be colored white (default), for use with standard branding colors"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"light"}]}]}],"sections":[],"metadata":{"roleHeading":"Case","symbolKind":"case","externalID":"s:26TicketmasterAuthentication16TMAuthenticationC10ColorThemeO5lightyA2EmF","modules":[{"name":"TicketmasterAuthentication"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"light"}],"title":"TMAuthentication.ColorTheme.light","role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication","doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication","doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/ColorTheme"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/ColorTheme\/light","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterauthentication\/tmauthentication\/colortheme\/light"]}],"references":{"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthentication":{"navigatorTitle":[{"kind":"identifier","text":"TMAuthentication"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TMAuthentication","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication","role":"symbol","abstract":[{"type":"codeVoice","code":"TMAuthentication"},{"text":" provides login UI, oauth tokens, member info, and MFA support.","type":"text"}],"url":"\/documentation\/ticketmasterauthentication\/tmauthentication","type":"topic","title":"TMAuthentication","kind":"symbol"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthentication/ColorTheme":{"url":"\/documentation\/ticketmasterauthentication\/tmauthentication\/colortheme","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/ColorTheme","type":"topic","abstract":[{"text":"text color (on top of branding color), very bright colors should use a .dark theme","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ColorTheme"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ColorTheme","kind":"identifier"}],"title":"TMAuthentication.ColorTheme","role":"symbol"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication":{"kind":"symbol","title":"TicketmasterAuthentication","abstract":[{"type":"text","text":"Application Configuration and Account Operations"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication","type":"topic","role":"collection","url":"\/documentation\/ticketmasterauthentication"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthentication/ColorTheme/light":{"title":"TMAuthentication.ColorTheme.light","url":"\/documentation\/ticketmasterauthentication\/tmauthentication\/colortheme\/light","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"light"}],"abstract":[{"text":"important UI text will be colored white (default), for use with standard branding colors","type":"text"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/ColorTheme\/light","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TMAuthentication","op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterAuthentication~1documentation~1TicketmasterAuthentication~1TMAuthentication\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterAuthentication~1documentation~1TicketmasterAuthentication~1TMAuthentication\/fragments","value":[{"kind":"identifier","text":"TMAuthentication"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterAuthentication~1documentation~1TicketmasterAuthentication~1TMAuthentication\/navigatorTitle","op":"replace","value":[{"text":"TMAuthentication","kind":"identifier"}]}]}]}