{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"awakeFromNib"},{"kind":"text","text":"()"}],"languages":["swift"]}]}],"sections":[],"kind":"symbol","metadata":{"title":"awakeFromNib()","modules":[{"name":"TicketmasterTickets"}],"roleHeading":"Instance Method","externalID":"c:@M@TicketmasterTickets@objc(cs)TMTicketsView(im)awakeFromNib","role":"symbol","navigatorTitle":[{"text":"awakeFromNib","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"awakeFromNib","kind":"identifier"},{"text":"()","kind":"text"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView"]]},"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView\/awakeFromNib()","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmastertickets\/tmticketsview\/awakefromnib()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ticketmastertickets\/tmticketsview\/awakefromnib()"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsView/awakeFromNib()":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"awakeFromNib","kind":"identifier"}],"url":"\/documentation\/ticketmastertickets\/tmticketsview\/awakefromnib()","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"awakeFromNib","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","title":"awakeFromNib()","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView\/awakeFromNib()"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsView":{"title":"TMTicketsView","url":"\/documentation\/ticketmastertickets\/tmticketsview","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView","abstract":[{"text":"use to render Tickets SDK as a UIView embedded inside of your own UIViewController","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTicketsView"}],"navigatorTitle":[{"kind":"identifier","text":"TMTicketsView"}],"role":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"role":"collection","type":"topic","url":"\/documentation\/ticketmastertickets","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","kind":"symbol","title":"TicketmasterTickets","abstract":[{"type":"text","text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"awakeFromNib"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"awakeFromNib"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"awakeFromNib"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView~1awakeFromNib()\/title","value":"awakeFromNib"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView~1awakeFromNib()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"awakeFromNib","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/title","value":"TMTicketsView"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/fragments","value":[{"kind":"identifier","text":"TMTicketsView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/navigatorTitle","value":[{"text":"TMTicketsView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}