{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView\/init(frame:)"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView"]]},"metadata":{"role":"symbol","roleHeading":"Initializer","externalID":"c:@M@TicketmasterTickets@objc(cs)TMTicketsView(im)initWithFrame:","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"modules":[{"name":"TicketmasterTickets"}],"title":"init(frame:)","symbolKind":"init"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"rect"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmastertickets\/tmticketsview\/init(frame:)"]},{"paths":["\/documentation\/ticketmastertickets\/tmticketsview\/init(frame:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsView/init(frame:)":{"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView\/init(frame:)","title":"init(frame:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"frame","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/ticketmastertickets\/tmticketsview\/init(frame:)","role":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"role":"collection","abstract":[{"text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes.","type":"text"}],"title":"TicketmasterTickets","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","url":"\/documentation\/ticketmastertickets","type":"topic"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsView":{"navigatorTitle":[{"kind":"identifier","text":"TMTicketsView"}],"title":"TMTicketsView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMTicketsView","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView","kind":"symbol","url":"\/documentation\/ticketmastertickets\/tmticketsview","abstract":[{"type":"text","text":"use to render Tickets SDK as a UIView embedded inside of your own UIViewController"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"initWithFrame:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithFrame:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithFrame:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"rect"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView~1init(frame:)\/title","value":"initWithFrame:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView~1init(frame:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/title","op":"replace","value":"TMTicketsView"},{"value":[{"text":"TMTicketsView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}