{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView"]]},"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"willMove","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toWindow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIWindow","text":"UIWindow"},{"text":"?)","kind":"text"}],"externalID":"c:@M@TicketmasterTickets@objc(cs)TMTicketsView(im)willMoveToWindow:","modules":[{"name":"TicketmasterTickets"}],"role":"symbol","roleHeading":"Instance Method","title":"willMove(toWindow:)","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"willMoveToWindow:"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"willMove","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toWindow"},{"text":" ","kind":"text"},{"text":"newWindow","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIWindow","text":"UIWindow"},{"text":"?)","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView\/willMove(toWindow:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmastertickets\/tmticketsview\/willmove(towindow:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ticketmastertickets\/tmticketsview\/willmove(towindow:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsView/willMove(toWindow:)":{"title":"willMove(toWindow:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"willMoveToWindow:"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView\/willMove(toWindow:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willMove","kind":"identifier"},{"kind":"text","text":"("},{"text":"toWindow","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIWindow","text":"UIWindow","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"type":"topic","kind":"symbol","url":"\/documentation\/ticketmastertickets\/tmticketsview\/willmove(towindow:)"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsView":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TMTicketsView","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"TMTicketsView","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView","title":"TMTicketsView","url":"\/documentation\/ticketmastertickets\/tmticketsview","abstract":[{"text":"use to render Tickets SDK as a UIView embedded inside of your own UIViewController","type":"text"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","kind":"symbol","title":"TicketmasterTickets","url":"\/documentation\/ticketmastertickets","role":"collection","type":"topic","abstract":[{"type":"text","text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"willMoveToWindow:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"willMoveToWindow:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"willMoveToWindow:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIWindow","text":"UIWindow","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"newWindow"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"willMoveToWindow:","op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView~1willMove(toWindow:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView~1willMove(toWindow:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"willMoveToWindow:"}]},{"op":"replace","value":"TMTicketsView","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/title"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/fragments","value":[{"text":"TMTicketsView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/navigatorTitle","value":[{"kind":"identifier","text":"TMTicketsView"}],"op":"replace"}]}]}