{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCoder:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"coder"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ticketmastertickets\/tmticketsviewcontroller\/initwithcoder:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController\/initWithCoder:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"title":"initWithCoder:","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@TicketmasterTickets@objc(cs)TMTicketsViewController(im)initWithCoder:","modules":[{"name":"TicketmasterTickets"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}]},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController"]]},"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsViewController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/ticketmastertickets\/tmticketsviewcontroller\/initwithcoder:"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"role":"collection","title":"TicketmasterTickets","abstract":[{"type":"text","text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes."}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","kind":"symbol","type":"topic","url":"\/documentation\/ticketmastertickets"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsView":{"role":"symbol","title":"TMTicketsView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTicketsView"}],"abstract":[{"type":"text","text":"use to render Tickets SDK as a UIView embedded inside of your own UIViewController"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TMTicketsView"}],"url":"\/documentation\/ticketmastertickets\/tmticketsview"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsViewController":{"role":"symbol","title":"TMTicketsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTicketsViewController"}],"abstract":[{"type":"text","text":"this class wraps the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView"},{"type":"text","text":" in a "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" for ease of use"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TMTicketsViewController"}],"url":"\/documentation\/ticketmastertickets\/tmticketsviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/title","value":"TMTicketsView"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/fragments","value":[{"kind":"identifier","text":"TMTicketsView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController\/title","value":"TMTicketsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController\/fragments","value":[{"kind":"identifier","text":"TMTicketsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}