{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithNibName:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"nibNameOrNil"},{"text":" ","kind":"text"},{"text":"bundle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSBundle","text":"NSBundle","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"nibBundleOrNil","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController"]]},"kind":"symbol","metadata":{"externalID":"c:@M@TicketmasterTickets@objc(cs)TMTicketsViewController(im)initWithNibName:bundle:","navigatorTitle":[{"text":"initWithNibName:bundle:","kind":"identifier"}],"symbolKind":"method","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithNibName:bundle:","kind":"identifier"}],"title":"initWithNibName:bundle:","roleHeading":"Instance Method","modules":[{"name":"TicketmasterTickets"}]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ticketmastertickets\/tmticketsviewcontroller\/initwithnibname:bundle:"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController\/initWithNibName:bundle:"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","url":"\/documentation\/ticketmastertickets","title":"TicketmasterTickets","kind":"symbol","role":"collection","type":"topic","abstract":[{"type":"text","text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes."}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsViewController/initWithNibName:bundle:":{"navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"title":"initWithNibName:bundle:","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController\/initWithNibName:bundle:","url":"\/documentation\/ticketmastertickets\/tmticketsviewcontroller\/initwithnibname:bundle:"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMTicketsView","kind":"identifier"}],"navigatorTitle":[{"text":"TMTicketsView","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"use to render Tickets SDK as a UIView embedded inside of your own UIViewController"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ticketmastertickets\/tmticketsview","title":"TMTicketsView","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsViewController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMTicketsViewController","kind":"identifier"}],"navigatorTitle":[{"text":"TMTicketsViewController","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"this class wraps the "},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView","isActive":true},{"type":"text","text":" in a "},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":" for ease of use"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ticketmastertickets\/tmticketsviewcontroller","title":"TMTicketsViewController","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/title","op":"replace","value":"TMTicketsView"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/fragments","op":"replace","value":[{"kind":"identifier","text":"TMTicketsView"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TMTicketsView"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController\/title","op":"replace","value":"TMTicketsViewController"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"TMTicketsViewController"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TMTicketsViewController"}]}]}]}