{"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"s:19TicketmasterTickets23TMTicketsViewControllerC6reloadyyF","roleHeading":"Instance Method","title":"reload()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"reload"},{"kind":"text","text":"()"}],"symbolKind":"method","modules":[{"name":"TicketmasterTickets"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/ticketmastertickets\/tmticketsviewcontroller\/reload()"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reload"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"reload contents of My Events page, fetch fresh orders"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController\/reload()"},"kind":"symbol","references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsViewController":{"url":"\/documentation\/ticketmastertickets\/tmticketsviewcontroller","navigatorTitle":[{"text":"TMTicketsViewController","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"this class wraps the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView","isActive":true},{"text":" in a ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"text":" for ease of use","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController","type":"topic","title":"TMTicketsViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTicketsViewController"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"kind":"symbol","type":"topic","url":"\/documentation\/ticketmastertickets","abstract":[{"type":"text","text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes."}],"role":"collection","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","title":"TicketmasterTickets"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsViewController/reload()":{"role":"symbol","title":"reload()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reload"},{"text":"()","kind":"text"}],"type":"topic","url":"\/documentation\/ticketmastertickets\/tmticketsviewcontroller\/reload()","abstract":[{"type":"text","text":"reload contents of My Events page, fetch fresh orders"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController\/reload()"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsView":{"role":"symbol","abstract":[{"type":"text","text":"use to render Tickets SDK as a UIView embedded inside of your own UIViewController"}],"url":"\/documentation\/ticketmastertickets\/tmticketsview","title":"TMTicketsView","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView","navigatorTitle":[{"text":"TMTicketsView","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TMTicketsView","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController\/title","value":"TMTicketsViewController"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController\/fragments","op":"replace","value":[{"text":"TMTicketsViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/title","value":"TMTicketsView","op":"replace"},{"value":[{"kind":"identifier","text":"TMTicketsView"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}