{"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication","doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication","doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/AuthNotification"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterauthentication\/tmauthentication\/authnotification\/logoutstarted"]}],"metadata":{"role":"symbol","modules":[{"name":"TicketmasterAuthentication"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"logoutStarted","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation12NotificationV","kind":"typeIdentifier","text":"Notification"},{"kind":"text","text":"."},{"text":"Name","preciseIdentifier":"s:10Foundation12NotificationV4Namea","kind":"typeIdentifier"}],"symbolKind":"property","externalID":"s:26TicketmasterAuthentication16TMAuthenticationC16AuthNotificationV13logoutStartedSo18NSNotificationNameavpZ","roleHeading":"Type Property","title":"logoutStarted"},"sections":[],"abstract":[{"text":"logout process has started, ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/AuthNotification\/loggedOut","isActive":true},{"type":"text","text":" state may be called multiple times"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/AuthNotification\/logoutStarted","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logoutStarted"},{"kind":"text","text":": "},{"text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV4Namea","text":"Name"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthentication":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TMAuthentication","kind":"identifier"}],"type":"topic","abstract":[{"code":"TMAuthentication","type":"codeVoice"},{"text":" provides login UI, oauth tokens, member info, and MFA support.","type":"text"}],"role":"symbol","url":"\/documentation\/ticketmasterauthentication\/tmauthentication","title":"TMAuthentication","navigatorTitle":[{"text":"TMAuthentication","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication","kind":"symbol"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication":{"abstract":[{"type":"text","text":"Application Configuration and Account Operations"}],"title":"TicketmasterAuthentication","url":"\/documentation\/ticketmasterauthentication","role":"collection","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication","kind":"symbol","type":"topic"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthentication/AuthNotification/logoutStarted":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/AuthNotification\/logoutStarted","title":"logoutStarted","abstract":[{"type":"text","text":"logout process has started, "},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/AuthNotification\/loggedOut","isActive":true},{"type":"text","text":" state may be called multiple times"}],"url":"\/documentation\/ticketmasterauthentication\/tmauthentication\/authnotification\/logoutstarted","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"logoutStarted","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV4Namea","text":"Name"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthentication/BackendService":{"kind":"symbol","url":"\/documentation\/ticketmasterauthentication\/tmauthentication\/backendservice","role":"symbol","type":"topic","abstract":[{"text":"backend Service providing Authentication","type":"text"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/BackendService","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BackendService"}],"navigatorTitle":[{"text":"BackendService","kind":"identifier"}],"title":"TMAuthentication.BackendService"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthentication/AuthNotification/loggedOut":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/AuthNotification\/loggedOut","url":"\/documentation\/ticketmasterauthentication\/tmauthentication\/authnotification\/loggedout","abstract":[{"text":"user has logged out of given ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/BackendService"},{"text":", however logout is still processing","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"loggedOut","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV","text":"Notification"},{"text":".","kind":"text"},{"preciseIdentifier":"s:10Foundation12NotificationV4Namea","text":"Name","kind":"typeIdentifier"}],"type":"topic","role":"symbol","title":"loggedOut"},"doc://com.ticketmaster.TicketmasterAuthentication/documentation/TicketmasterAuthentication/TMAuthentication/AuthNotification":{"title":"TMAuthentication.AuthNotification","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthNotification"}],"navigatorTitle":[{"text":"AuthNotification","kind":"identifier"}],"type":"topic","url":"\/documentation\/ticketmasterauthentication\/tmauthentication\/authnotification","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"a list of state change "},{"type":"codeVoice","code":"Notifications"},{"type":"text","text":" that can be listened for"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterAuthentication\/documentation\/TicketmasterAuthentication\/TMAuthentication\/AuthNotification"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterAuthentication~1documentation~1TicketmasterAuthentication~1TMAuthentication\/title","value":"TMAuthentication","op":"replace"},{"value":[{"text":"TMAuthentication","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterAuthentication~1documentation~1TicketmasterAuthentication~1TMAuthentication\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterAuthentication~1documentation~1TicketmasterAuthentication~1TMAuthentication\/navigatorTitle","value":[{"kind":"identifier","text":"TMAuthentication"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}