{"topicSections":[{"identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge\/presentationAnchor(for:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"metadata":{"role":"collectionGroup","roleHeading":"API Collection","title":"ASWebAuthenticationPresentationContextProviding Implementations","modules":[{"name":"TicketmasterPurchase"}]},"variants":[{"paths":["\/documentation\/ticketmasterpurchase\/poppopupbridge\/aswebauthenticationpresentationcontextproviding-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ticketmasterpurchase\/poppopupbridge\/aswebauthenticationpresentationcontextproviding-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge\/ASWebAuthenticationPresentationContextProviding-Implementations"},"kind":"article","references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"role":"collection","title":"TicketmasterPurchase","abstract":[],"type":"topic","url":"\/documentation\/ticketmasterpurchase","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/POPPopupBridge":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POPPopupBridge","kind":"identifier"}],"url":"\/documentation\/ticketmasterpurchase\/poppopupbridge","navigatorTitle":[{"text":"POPPopupBridge","kind":"identifier"}],"abstract":[],"title":"POPPopupBridge"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/POPPopupBridge/presentationAnchor(for:)":{"url":"\/documentation\/ticketmasterpurchase\/poppopupbridge\/presentationanchor(for:)","role":"symbol","navigatorTitle":[{"text":"presentationAnchorForWebAuthenticationSession:","kind":"identifier"}],"type":"topic","abstract":[],"title":"presentationAnchor(for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentationAnchor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASWebAuthenticationSession","preciseIdentifier":"c:objc(cs)ASWebAuthenticationSession"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@ASPresentationAnchor","kind":"typeIdentifier","text":"ASPresentationAnchor"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge\/presentationAnchor(for:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge\/presentationAnchor(for:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":"POPPopupBridge","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge\/title","op":"replace"},{"value":[{"kind":"identifier","text":"POPPopupBridge"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"POPPopupBridge"}],"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge\/navigatorTitle"},{"value":"presentationAnchorForWebAuthenticationSession:","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge~1presentationAnchor(for:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge~1presentationAnchor(for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentationAnchorForWebAuthenticationSession:"}]}]}]}