{"metadata":{"title":"init(webView:prefersEphemeralWebBrowserSession:)","modules":[{"name":"TicketmasterPurchase"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"webView"},{"text":": ","kind":"text"},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"text":"prefersEphemeralWebBrowserSession","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","externalID":"c:@M@TicketmasterPurchase@objc(cs)POPPopupBridge(im)initWithWebView:prefersEphemeralWebBrowserSession:","roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithWebView:prefersEphemeralWebBrowserSession:"}],"symbolKind":"init"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"Initialize a Popup Bridge."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"webView","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView"},{"kind":"text","text":", "},{"text":"prefersEphemeralWebBrowserSession","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" = true)","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The web view to add a script message handler to. Do not change the web view’s configuration or user content controller after initializing Popup Bridge."}]}],"name":"webView"},{"content":[{"inlineContent":[{"text":"A Boolean that, when true, requests that the browser does not share cookies","type":"text"},{"type":"text","text":" "},{"text":"or other browsing data between the authenthication session and the user’s normal browser session.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"prefersEphemeralWebBrowserSession"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterpurchase\/poppopupbridge\/init(webview:prefersephemeralwebbrowsersession:)"]},{"paths":["\/documentation\/ticketmasterpurchase\/poppopupbridge\/init(webview:prefersephemeralwebbrowsersession:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge"]]},"identifier":{"url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge\/init(webView:prefersEphemeralWebBrowserSession:)","interfaceLanguage":"swift"},"references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/POPPopupBridge":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POPPopupBridge","kind":"identifier"}],"url":"\/documentation\/ticketmasterpurchase\/poppopupbridge","navigatorTitle":[{"text":"POPPopupBridge","kind":"identifier"}],"abstract":[],"title":"POPPopupBridge"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/POPPopupBridge/init(webView:prefersEphemeralWebBrowserSession:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"webView","kind":"externalParam"},{"kind":"text","text":": "},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"prefersEphemeralWebBrowserSession"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge\/init(webView:prefersEphemeralWebBrowserSession:)","navigatorTitle":[{"kind":"identifier","text":"initWithWebView:prefersEphemeralWebBrowserSession:"}],"type":"topic","abstract":[{"text":"Initialize a Popup Bridge.","type":"text"}],"url":"\/documentation\/ticketmasterpurchase\/poppopupbridge\/init(webview:prefersephemeralwebbrowsersession:)","role":"symbol","title":"init(webView:prefersEphemeralWebBrowserSession:)","kind":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"role":"collection","title":"TicketmasterPurchase","abstract":[],"type":"topic","url":"\/documentation\/ticketmasterpurchase","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithWebView:prefersEphemeralWebBrowserSession:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"initWithWebView:prefersEphemeralWebBrowserSession:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithWebView:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":" *) ","kind":"text"},{"text":"webView","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefersEphemeralWebBrowserSession:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"prefersEphemeralWebBrowserSession"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"webView","content":[{"type":"paragraph","inlineContent":[{"text":"The web view to add a script message handler to. Do not change the web view’s configuration or user content controller after initializing Popup Bridge.","type":"text"}]}]},{"name":"prefersEphemeralWebBrowserSession","content":[{"type":"paragraph","inlineContent":[{"text":"A Boolean that, when true, requests that the browser does not share cookies","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"or other browsing data between the authenthication session and the user’s normal browser session."},{"type":"text","text":" "},{"text":"Defaults to ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}]}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge\/title","value":"POPPopupBridge"},{"value":[{"kind":"identifier","text":"POPPopupBridge"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge\/navigatorTitle","value":[{"text":"POPPopupBridge","kind":"identifier"}]},{"value":"initWithWebView:prefersEphemeralWebBrowserSession:","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge~1init(webView:prefersEphemeralWebBrowserSession:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithWebView:prefersEphemeralWebBrowserSession:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge~1init(webView:prefersEphemeralWebBrowserSession:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}