{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge\/presentationAnchor(for:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterpurchase\/poppopupbridge\/presentationanchor(for:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ticketmasterpurchase\/poppopupbridge\/presentationanchor(for:)"]}],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge\/ASWebAuthenticationPresentationContextProviding-Implementations"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"presentationAnchorForWebAuthenticationSession:"}],"roleHeading":"Instance Method","modules":[{"name":"TicketmasterPurchase"}],"role":"symbol","externalID":"c:@CM@TicketmasterPurchase@objc(cs)POPPopupBridge(im)presentationAnchorForWebAuthenticationSession:","symbolKind":"method","extendedModule":"TicketmasterPurchase","title":"presentationAnchor(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationAnchor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASWebAuthenticationSession","preciseIdentifier":"c:objc(cs)ASWebAuthenticationSession"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ASPresentationAnchor","preciseIdentifier":"c:@T@ASPresentationAnchor"}]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"ASWebAuthenticationPresentationContextProviding.presentationAnchor(for:)"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationAnchor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"session"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)ASWebAuthenticationSession","kind":"typeIdentifier","text":"ASWebAuthenticationSession"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@T@ASPresentationAnchor","kind":"typeIdentifier","text":"ASPresentationAnchor"}]}]}],"references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/POPPopupBridge":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"POPPopupBridge"}],"url":"\/documentation\/ticketmasterpurchase\/poppopupbridge","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge","role":"symbol","title":"POPPopupBridge","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"POPPopupBridge"}]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/POPPopupBridge/presentationAnchor(for:)":{"navigatorTitle":[{"kind":"identifier","text":"presentationAnchorForWebAuthenticationSession:"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge\/presentationAnchor(for:)","url":"\/documentation\/ticketmasterpurchase\/poppopupbridge\/presentationanchor(for:)","kind":"symbol","role":"symbol","title":"presentationAnchor(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationAnchor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)ASWebAuthenticationSession","kind":"typeIdentifier","text":"ASWebAuthenticationSession"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@T@ASPresentationAnchor","kind":"typeIdentifier","text":"ASPresentationAnchor"}]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","url":"\/documentation\/ticketmasterpurchase","type":"topic","role":"collection","abstract":[],"title":"TicketmasterPurchase"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/POPPopupBridge/ASWebAuthenticationPresentationContextProviding-Implementations":{"kind":"article","url":"\/documentation\/ticketmasterpurchase\/poppopupbridge\/aswebauthenticationpresentationcontextproviding-implementations","type":"topic","title":"ASWebAuthenticationPresentationContextProviding Implementations","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge\/ASWebAuthenticationPresentationContextProviding-Implementations","role":"collectionGroup","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"presentationAnchorForWebAuthenticationSession:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"presentationAnchorForWebAuthenticationSession:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"presentationAnchorForWebAuthenticationSession:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ASWebAuthenticationSession","preciseIdentifier":"c:objc(cs)ASWebAuthenticationSession","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge\/title","value":"POPPopupBridge"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge\/fragments","value":[{"kind":"identifier","text":"POPPopupBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge\/navigatorTitle","value":[{"text":"POPPopupBridge","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge~1presentationAnchor(for:)\/title","value":"presentationAnchorForWebAuthenticationSession:"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge~1presentationAnchor(for:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"presentationAnchorForWebAuthenticationSession:","kind":"identifier"}]}]}]}