{"identifier":{"url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge\/userContentController(_:didReceive:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterpurchase\/poppopupbridge\/usercontentcontroller(_:didreceive:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ticketmasterpurchase\/poppopupbridge\/usercontentcontroller(_:didreceive:)"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge"]]},"sections":[],"abstract":[{"type":"text","text":":nodoc: This method is not covered by Semantic Versioning. Do not use."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userContentController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userContentController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKUserContentController","text":"WKUserContentController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":" "},{"kind":"internalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKScriptMessage","text":"WKScriptMessage"},{"kind":"text","text":")"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Called when the webpage sends a JavaScript message back to the native app","type":"text"}]}]}],"metadata":{"modules":[{"name":"TicketmasterPurchase"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"userContentController:didReceiveScriptMessage:"}],"externalID":"c:@M@TicketmasterPurchase@objc(cs)POPPopupBridge(im)userContentController:didReceiveScriptMessage:","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userContentController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKUserContentController","text":"WKUserContentController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKScriptMessage","text":"WKScriptMessage"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","title":"userContentController(_:didReceive:)"},"references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/POPPopupBridge":{"url":"\/documentation\/ticketmasterpurchase\/poppopupbridge","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"POPPopupBridge"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"POPPopupBridge"}],"title":"POPPopupBridge"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/POPPopupBridge/userContentController(_:didReceive:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userContentController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKUserContentController","text":"WKUserContentController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKScriptMessage","text":"WKScriptMessage"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge\/userContentController(_:didReceive:)","navigatorTitle":[{"kind":"identifier","text":"userContentController:didReceiveScriptMessage:"}],"title":"userContentController(_:didReceive:)","abstract":[{"type":"text","text":":nodoc: This method is not covered by Semantic Versioning. Do not use."}],"url":"\/documentation\/ticketmasterpurchase\/poppopupbridge\/usercontentcontroller(_:didreceive:)","role":"symbol","type":"topic"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"type":"topic","url":"\/documentation\/ticketmasterpurchase","title":"TicketmasterPurchase","abstract":[],"role":"collection","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"userContentController:didReceiveScriptMessage:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userContentController:didReceiveScriptMessage:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"userContentController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKUserContentController","text":"WKUserContentController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userContentController"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveScriptMessage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKScriptMessage","text":"WKScriptMessage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"message"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge\/title","value":"POPPopupBridge"},{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge\/fragments","value":[{"kind":"identifier","text":"POPPopupBridge"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge\/navigatorTitle","value":[{"kind":"identifier","text":"POPPopupBridge"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge~1userContentController(_:didReceive:)\/title","value":"userContentController:didReceiveScriptMessage:","op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge~1userContentController(_:didReceive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userContentController:didReceiveScriptMessage:"}],"op":"replace"}]}]}