{"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/environment-swift.property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase"]]},"abstract":[{"type":"text","text":"The Ticketmaster Host Environment marching the API key provided"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchase\/environment-swift.property"]}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"environment","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Environment","preciseIdentifier":"s:23TicketmasterPrePurchase05TMPreC0C11EnvironmentO"}],"roleHeading":"Instance Property","modules":[{"name":"TicketmasterPrePurchase"}],"title":"environment","externalID":"s:23TicketmasterPrePurchase05TMPreC0C11environmentAC11EnvironmentOvp","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"environment","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/Environment-swift.enum","text":"Environment","kind":"typeIdentifier","preciseIdentifier":"s:23TicketmasterPrePurchase05TMPreC0C11EnvironmentO"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"It is recommended to leave this as ","type":"text"},{"code":".production","type":"codeVoice"}]}],"kind":"content"}],"references":{"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchase/environment-swift.property":{"kind":"symbol","title":"environment","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/environment-swift.property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"environment","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:23TicketmasterPrePurchase05TMPreC0C11EnvironmentO","kind":"typeIdentifier","text":"Environment"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The Ticketmaster Host Environment marching the API key provided"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchase\/environment-swift.property"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchase":{"abstract":[{"type":"text","text":"A class that stores the global configuration for the TicketmasterPrePurchase SDK."}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchase","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TMPrePurchase","kind":"identifier"}],"navigatorTitle":[{"text":"TMPrePurchase","kind":"identifier"}],"role":"symbol","title":"TMPrePurchase"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase":{"title":"TicketmasterPrePurchase","url":"\/documentation\/ticketmasterprepurchase","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","abstract":[],"role":"collection","kind":"symbol"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchase/Environment-swift.enum":{"title":"TMPrePurchase.Environment","kind":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchase\/environment-swift.enum","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Environment"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/Environment-swift.enum","navigatorTitle":[{"text":"Environment","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"TMPrePurchase","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchase\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchase\/fragments","value":[{"text":"TMPrePurchase","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchase\/navigatorTitle","value":[{"text":"TMPrePurchase","kind":"identifier"}]}]}]}