{"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/MapAnnotation"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"MKAnnotation.coordinate"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/MapAnnotation\/coordinate","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview\/mapannotation\/coordinate"]}],"sections":[],"metadata":{"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","title":"coordinate","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"coordinate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"}],"externalID":"s:19TicketmasterTickets25TMTicketsModuleHeaderViewC13MapAnnotationC10coordinateSo22CLLocationCoordinate2DVvp","modules":[{"name":"TicketmasterTickets"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"coordinate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"}]}]}],"kind":"symbol","references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView/MapAnnotation/coordinate":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"coordinate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"}],"title":"coordinate","url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview\/mapannotation\/coordinate","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/MapAnnotation\/coordinate","role":"symbol","kind":"symbol","abstract":[]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView":{"type":"topic","url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsModuleHeaderView"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView","navigatorTitle":[{"kind":"identifier","text":"TMTicketsModuleHeaderView"}],"abstract":[{"type":"text","text":"quickly build a UIView for "},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView","isActive":true,"type":"reference"}],"role":"symbol","title":"TMTicketsModuleHeaderView"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView/MapAnnotation":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView\/MapAnnotation","navigatorTitle":[{"text":"MapAnnotation","kind":"identifier"}],"title":"TMTicketsModuleHeaderView.MapAnnotation","type":"topic","url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview\/mapannotation","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MapAnnotation","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"type":"topic","url":"\/documentation\/ticketmastertickets","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes."}],"title":"TicketmasterTickets"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/title","op":"replace","value":"TMTicketsModuleHeaderView"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/fragments","value":[{"text":"TMTicketsModuleHeaderView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/navigatorTitle","value":[{"text":"TMTicketsModuleHeaderView","kind":"identifier"}]}]}]}