{"kind":"symbol","identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/ActionType\/posting","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/ticketmastertickets\/tmtickets\/actiontype\/posting"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Case","modules":[{"name":"TicketmasterTickets"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"posting"}],"role":"symbol","title":"TMTickets.ActionType.posting","symbolKind":"case","externalID":"s:19TicketmasterTickets9TMTicketsC10ActionTypeO7postingyA2EmF"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"posting"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/ActionType"]]},"abstract":[{"type":"text","text":"automatically show posting flow"}],"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets":{"title":"TMTickets","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMTickets","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets","navigatorTitle":[{"kind":"identifier","text":"TMTickets"}],"abstract":[{"type":"text","text":"main class of Tickets SDK, intended to be used as singleton"}],"url":"\/documentation\/ticketmastertickets\/tmtickets"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/ActionType":{"title":"TMTickets.ActionType","kind":"symbol","role":"symbol","url":"\/documentation\/ticketmastertickets\/tmtickets\/actiontype","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ActionType","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/ActionType","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ActionType"}],"abstract":[{"text":"action to perform upon completion of ","type":"text"},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/display(orderOrEventId:type:action:callSource:)","isActive":true,"type":"reference"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/ActionType/posting":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"posting","kind":"identifier"}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/actiontype\/posting","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/ActionType\/posting","type":"topic","title":"TMTickets.ActionType.posting","abstract":[{"text":"automatically show posting flow","type":"text"}],"role":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"url":"\/documentation\/ticketmastertickets","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes."}],"title":"TicketmasterTickets"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/display(orderOrEventId:type:action:callSource:)":{"url":"\/documentation\/ticketmastertickets\/tmtickets\/display(orderoreventid:type:action:callsource:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"display"},{"text":"(","kind":"text"},{"text":"orderOrEventId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"s:19TicketmasterTickets9TMTicketsC6IdTypeO","kind":"typeIdentifier","text":"IdType"},{"kind":"text","text":", "},{"text":"action","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets9TMTicketsC10ActionTypeO","text":"ActionType"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"callSource"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"display Tickets listing for a particular Order or Event, if not found show the My Events page"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/display(orderOrEventId:type:action:callSource:)","type":"topic","title":"display(orderOrEventId:type:action:callSource:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/title","value":"TMTickets","op":"replace"},{"value":[{"kind":"identifier","text":"TMTickets"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/fragments"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/navigatorTitle","op":"replace","value":[{"text":"TMTickets","kind":"identifier"}]}]}]}