{"sections":[],"variants":[{"paths":["\/documentation\/ticketmastertickets\/tmtickets\/analytics\/action"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics"]]},"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action","interfaceLanguage":"swift"},"kind":"symbol","topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/addTicketToWalletButton","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/addTicketToWalletCanceled","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/addTicketToWalletFinished","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/barcodeScreenshot","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/customErrorButton","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/eventInfoBannerButton","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/logoutErrorButton","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/moduleActionButton","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/moduleActionButtonV2","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/navbarButtonAction","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/postingCancelButton","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/postingEditButton","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/pullToRefreshEvents","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/retryErrorButton","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/transferCancelButton","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/transferSendButton"],"generated":true},{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/init(rawValue:)"],"generated":true},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/Equatable-Implementations","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/RawRepresentable-Implementations"],"generated":true}],"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/SQ","doc:\/\/com.ticketmaster.TicketmasterTickets\/SH","doc:\/\/com.ticketmaster.TicketmasterTickets\/SY"],"type":"conformsTo"}],"metadata":{"symbolKind":"enum","modules":[{"name":"TicketmasterTickets"}],"roleHeading":"Enumeration","role":"symbol","externalID":"s:19TicketmasterTickets9TMTicketsC9AnalyticsV6ActionO","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Action"}],"navigatorTitle":[{"text":"Action","kind":"identifier"}],"title":"TMTickets.Analytics.Action"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Action"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/Action/logoutErrorButton":{"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/action\/logouterrorbutton","title":"TMTickets.Analytics.Action.logoutErrorButton","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/logoutErrorButton","abstract":[{"type":"text","text":"user did press "},{"type":"codeVoice","code":"Logout"},{"type":"text","text":" on Events listing error page"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"logoutErrorButton"}],"kind":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/Action":{"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/action","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action","navigatorTitle":[{"kind":"identifier","text":"Action"}],"abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Action"}],"title":"TMTickets.Analytics.Action"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/Action/Equatable-Implementations":{"role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/Equatable-Implementations","title":"Equatable Implementations","kind":"article","abstract":[],"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/action\/equatable-implementations"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/navBarButtonTitle":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"navBarButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/navBarButtonTitle","abstract":[{"text":"present an button in the top-right Navbar on the Tickets page with the given localized title, ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" = no button (default)","type":"text"}],"role":"symbol","title":"navBarButtonTitle","url":"\/documentation\/ticketmastertickets\/tmtickets\/navbarbuttontitle","kind":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMTickets","kind":"identifier"}],"navigatorTitle":[{"text":"TMTickets","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets","abstract":[{"type":"text","text":"main class of Tickets SDK, intended to be used as singleton"}],"role":"symbol","title":"TMTickets","url":"\/documentation\/ticketmastertickets\/tmtickets","kind":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/Action/eventInfoBannerButton":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eventInfoBannerButton","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/eventInfoBannerButton","type":"topic","title":"TMTickets.Analytics.Action.eventInfoBannerButton","kind":"symbol","abstract":[{"text":"user pressed the More Info button on the Event Info banner, shown at the top of Tickets listing page","type":"text"}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/action\/eventinfobannerbutton"},"doc://com.ticketmaster.TicketmasterTickets/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/SH"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/Action/addTicketToWalletFinished":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTicketToWalletFinished","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/addTicketToWalletFinished","type":"topic","title":"TMTickets.Analytics.Action.addTicketToWalletFinished","kind":"symbol","abstract":[{"text":"user added a ticket to the wallet","type":"text"}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/action\/addtickettowalletfinished"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/Action/transferSendButton":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transferSendButton","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/transferSendButton","type":"topic","title":"TMTickets.Analytics.Action.transferSendButton","kind":"symbol","abstract":[{"type":"text","text":"user pressed the Send Transfer button"}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/action\/transfersendbutton"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/Action/customErrorButton":{"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/action\/customerrorbutton","title":"TMTickets.Analytics.Action.customErrorButton","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/customErrorButton","abstract":[{"type":"text","text":"user did press Custom button on Events listing error page  (see "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/addCustomErrorPageButton(title:)"},{"type":"text","text":")"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"customErrorButton"}],"kind":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/Action/pullToRefreshEvents":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pullToRefreshEvents"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/pullToRefreshEvents","title":"TMTickets.Analytics.Action.pullToRefreshEvents","abstract":[{"type":"text","text":"user did pull to refresh Events listing page"}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/action\/pulltorefreshevents"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/Action/transferCancelButton":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transferCancelButton"}],"type":"topic","kind":"symbol","title":"TMTickets.Analytics.Action.transferCancelButton","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/transferCancelButton","abstract":[{"type":"text","text":"user pressed the Cancel Transfer button"}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/action\/transfercancelbutton"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/Action/postingEditButton":{"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/action\/postingeditbutton","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/postingEditButton","abstract":[{"type":"text","text":"user pressed the Edit Resale Posting button"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"postingEditButton"}],"title":"TMTickets.Analytics.Action.postingEditButton"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/Action/moduleActionButtonV2":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"moduleActionButtonV2"}],"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/moduleActionButtonV2","title":"TMTickets.Analytics.Action.moduleActionButtonV2","kind":"symbol","abstract":[{"type":"text","text":"user pressed a button on a Custom Module returned by CMS tool"}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/action\/moduleactionbuttonv2"},"doc://com.ticketmaster.TicketmasterTickets/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/SQ"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/Action/navbarButtonAction":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"navbarButtonAction"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/navbarButtonAction","title":"TMTickets.Analytics.Action.navbarButtonAction","abstract":[{"type":"text","text":"user pressed the NavBar button (see: "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/navBarButtonTitle"},{"type":"text","text":")"}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/action\/navbarbuttonaction"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","abstract":[{"type":"text","text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes."}],"url":"\/documentation\/ticketmastertickets","title":"TicketmasterTickets","type":"topic","role":"collection"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/Action/addTicketToWalletButton":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"addTicketToWalletButton"}],"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/addTicketToWalletButton","title":"TMTickets.Analytics.Action.addTicketToWalletButton","kind":"symbol","abstract":[{"type":"text","text":"user pressed Apple "},{"type":"codeVoice","code":"Add To Wallet"},{"type":"text","text":" button"}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/action\/addtickettowalletbutton"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/Action/addTicketToWalletCanceled":{"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/addTicketToWalletCanceled","abstract":[{"type":"text","text":"user cancel the process  of adding a ticket to the wallet"}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/action\/addtickettowalletcanceled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"addTicketToWalletCanceled"}],"title":"TMTickets.Analytics.Action.addTicketToWalletCanceled","type":"topic","role":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/Action/barcodeScreenshot":{"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/action\/barcodescreenshot","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/barcodeScreenshot","abstract":[{"text":"user took a screenshot of the Barcode","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeScreenshot"}],"title":"TMTickets.Analytics.Action.barcodeScreenshot"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMTicketsModule","kind":"identifier"}],"navigatorTitle":[{"text":"TMTicketsModule","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","abstract":[{"type":"text","text":"create a custom module to be displayed underneath the user’s list of Tickets on the Tickets listing page"}],"role":"symbol","title":"TMTicketsModule","url":"\/documentation\/ticketmastertickets\/tmticketsmodule","kind":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/SY"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/Action/retryErrorButton":{"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/action\/retryerrorbutton","title":"TMTickets.Analytics.Action.retryErrorButton","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/retryErrorButton","abstract":[{"type":"text","text":"user did press "},{"type":"codeVoice","code":"Retry"},{"type":"text","text":" on Events listing error page"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"retryErrorButton"}],"kind":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Analytics"}],"navigatorTitle":[{"kind":"identifier","text":"Analytics"}],"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics","abstract":[{"text":"analytics for User behavior","type":"text"}],"role":"symbol","title":"TMTickets.Analytics","url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics","kind":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/Action/RawRepresentable-Implementations":{"role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","kind":"article","abstract":[],"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/action\/rawrepresentable-implementations"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/Action/moduleActionButton":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"moduleActionButton"}],"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/moduleActionButton","title":"TMTickets.Analytics.Action.moduleActionButton","kind":"symbol","abstract":[{"type":"text","text":"user pressed a button on a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule"}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/action\/moduleactionbutton"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/addCustomErrorPageButton(title:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addCustomErrorPageButton"},{"kind":"text","text":"("},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?)"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/addCustomErrorPageButton(title:)","title":"addCustomErrorPageButton(title:)","abstract":[{"type":"text","text":"add a custom button to “No Tickets” error page"}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/addcustomerrorpagebutton(title:)"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/Action/init(rawValue:)":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/init(rawValue:)","title":"init(rawValue:)","kind":"symbol","abstract":[],"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/action\/init(rawvalue:)"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/Action/postingCancelButton":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"postingCancelButton"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/postingCancelButton","type":"topic","title":"TMTickets.Analytics.Action.postingCancelButton","kind":"symbol","abstract":[{"type":"text","text":"user pressed the Cancel Resale Posting button"}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/action\/postingcancelbutton"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/title","value":"TMTickets"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/fragments","value":[{"text":"TMTickets","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/navigatorTitle","value":[{"kind":"identifier","text":"TMTickets"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/title","value":"TMTicketsModule"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/fragments","value":[{"kind":"identifier","text":"TMTicketsModule"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/navigatorTitle","value":[{"kind":"identifier","text":"TMTicketsModule"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}