{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType","interfaceLanguage":"swift"},"sections":[],"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType\/empty","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType\/event(event:)","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType\/eventTicket(event:ticket:)","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType\/eventTickets(event:tickets:)","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType\/events(events:)","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType\/module(event:module:)","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType\/moduleButton(event:module:button:)","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType\/moduleButtonV2(event:moduleID:analyticsValue:)","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType\/moduleV2(event:moduleID:)"],"title":"Enumeration Cases"},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType\/description"],"anchor":"Instance-Properties"}],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MetadataType"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ticketmastertickets\/tmtickets\/analytics\/metadatatype"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","abstract":[{"text":"Swift enum with Associated Values of Event and Ticket metadata","type":"text"}],"metadata":{"modules":[{"name":"TicketmasterTickets"}],"symbolKind":"enum","role":"symbol","externalID":"s:19TicketmasterTickets9TMTicketsC9AnalyticsV12MetadataTypeO","title":"TMTickets.Analytics.MetadataType","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MetadataType"}],"navigatorTitle":[{"text":"MetadataType","kind":"identifier"}]},"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMPurchasedTicket":{"url":"\/documentation\/ticketmastertickets\/tmpurchasedticket","navigatorTitle":[{"kind":"identifier","text":"TMPurchasedTicket"}],"kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMPurchasedTicket"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedTicket","title":"TMPurchasedTicket","role":"symbol","abstract":[{"type":"text","text":"a single ticket (typically a single seat, unless general admission)"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/MetadataType/moduleButton(event:module:button:)":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"moduleButton","kind":"identifier"},{"text":"(","kind":"text"},{"text":"event","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TMPurchasedEvent","preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"module"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule","text":"TMTicketsModule","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"button"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule","text":"TMTicketsModule"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets15TMTicketsModuleC12ActionButtonC","text":"ActionButton"},{"kind":"text","text":")"}],"kind":"symbol","title":"TMTickets.Analytics.MetadataType.moduleButton(event:module:button:)","abstract":[{"text":"a Pre-Built or Custom Module ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule"},{"type":"text","text":" and "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/ActionButton"},{"type":"text","text":" built for a specific "},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedEvent","isActive":true,"type":"reference"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType\/moduleButton(event:module:button:)","url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/metadatatype\/modulebutton(event:module:button:)","role":"symbol","type":"topic"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/MetadataType/eventTickets(event:tickets:)":{"type":"topic","title":"TMTickets.Analytics.MetadataType.eventTickets(event:tickets:)","url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/metadatatype\/eventtickets(event:tickets:)","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"eventTickets","kind":"identifier"},{"kind":"text","text":"("},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TMPurchasedEvent","kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"tickets"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:19TicketmasterTickets17TMPurchasedTicketV","kind":"typeIdentifier","text":"TMPurchasedTicket"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"a specific "},{"isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedEvent","type":"reference"},{"type":"text","text":" and an array of all "},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedTicket","isActive":true,"type":"reference"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType\/eventTickets(event:tickets:)","kind":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/MetadataType/eventTicket(event:ticket:)":{"title":"TMTickets.Analytics.MetadataType.eventTicket(event:ticket:)","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"eventTicket","kind":"identifier"},{"kind":"text","text":"("},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TMPurchasedEvent","kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV"},{"kind":"text","text":", "},{"text":"ticket","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TMPurchasedTicket","kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets17TMPurchasedTicketV"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"text":"a specific ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedEvent"},{"type":"text","text":" and a specific "},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedTicket","isActive":true}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/metadatatype\/eventticket(event:ticket:)","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType\/eventTicket(event:ticket:)","type":"topic","role":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/MetadataType/events(events:)":{"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/metadatatype\/events(events:)","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"events","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"events"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV","text":"TMPurchasedEvent"},{"kind":"text","text":"])"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType\/events(events:)","abstract":[{"text":"an array of ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedEvent","isActive":true}],"kind":"symbol","title":"TMTickets.Analytics.MetadataType.events(events:)","type":"topic","role":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/MetadataType/moduleV2(event:moduleID:)":{"kind":"symbol","title":"TMTickets.Analytics.MetadataType.moduleV2(event:moduleID:)","type":"topic","role":"symbol","abstract":[{"text":"a Custom Module  ID driven by CMS tool built for a specific ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedEvent"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"moduleV2"},{"kind":"text","text":"("},{"kind":"externalParam","text":"event"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV","text":"TMPurchasedEvent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"moduleID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/metadatatype\/modulev2(event:moduleid:)","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType\/moduleV2(event:moduleID:)"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/MetadataType/moduleButtonV2(event:moduleID:analyticsValue:)":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"moduleButtonV2","kind":"identifier"},{"kind":"text","text":"("},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV","kind":"typeIdentifier","text":"TMPurchasedEvent"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"moduleID"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"analyticsValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","title":"TMTickets.Analytics.MetadataType.moduleButtonV2(event:moduleID:analyticsValue:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType\/moduleButtonV2(event:moduleID:analyticsValue:)","url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/metadatatype\/modulebuttonv2(event:moduleid:analyticsvalue:)","abstract":[{"type":"text","text":"A Custom Module ID driven by a CMS tool, combined with an action analytics value, designed for a specific "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedEvent"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/MetadataType/description":{"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/metadatatype\/description","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType\/description","title":"description","role":"symbol","abstract":[{"type":"text","text":"a debug description, not for end Users"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/MetadataType/event(event:)":{"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"event","kind":"identifier"},{"text":"(","kind":"text"},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TMPurchasedEvent","preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType\/event(event:)","title":"TMTickets.Analytics.MetadataType.event(event:)","abstract":[{"text":"a specific ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedEvent"}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/metadatatype\/event(event:)"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/MetadataType/empty":{"title":"TMTickets.Analytics.MetadataType.empty","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType\/empty","kind":"symbol","role":"symbol","url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/metadatatype\/empty","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"empty","kind":"identifier"}],"abstract":[{"type":"text","text":"no specific metadata available"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/MetadataType":{"title":"TMTickets.Analytics.MetadataType","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MetadataType"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MetadataType","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/metadatatype","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType","abstract":[{"type":"text","text":"Swift enum with Associated Values of Event and Ticket metadata"}],"kind":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMPurchasedEvent":{"role":"symbol","abstract":[{"type":"text","text":"an Event purchased by the User, containing Event Information, Orders, and Tickets"}],"kind":"symbol","url":"\/documentation\/ticketmastertickets\/tmpurchasedevent","navigatorTitle":[{"kind":"identifier","text":"TMPurchasedEvent"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TMPurchasedEvent","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedEvent","type":"topic","title":"TMPurchasedEvent"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule/ActionButton":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActionButton"}],"url":"\/documentation\/ticketmastertickets\/tmticketsmodule\/actionbutton","type":"topic","title":"TMTicketsModule.ActionButton","navigatorTitle":[{"kind":"identifier","text":"ActionButton"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/ActionButton","role":"symbol","abstract":[]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule":{"url":"\/documentation\/ticketmastertickets\/tmticketsmodule","type":"topic","abstract":[{"text":"create a custom module to be displayed underneath the user’s list of Tickets on the Tickets listing page","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMTicketsModule","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","navigatorTitle":[{"kind":"identifier","text":"TMTicketsModule"}],"title":"TMTicketsModule"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"url":"\/documentation\/ticketmastertickets","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","title":"TicketmasterTickets","kind":"symbol","role":"collection","type":"topic","abstract":[{"type":"text","text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes."}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics":{"navigatorTitle":[{"text":"Analytics","kind":"identifier"}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics","title":"TMTickets.Analytics","abstract":[{"type":"text","text":"analytics for User behavior"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Analytics"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/MetadataType/module(event:module:)":{"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/metadatatype\/module(event:module:)","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"module"},{"kind":"text","text":"("},{"text":"event","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV","text":"TMPurchasedEvent"},{"text":", ","kind":"text"},{"text":"module","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TMTicketsModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"a Pre-Built or Custom Module "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule"},{"text":" built for a specific ","type":"text"},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedEvent","isActive":true,"type":"reference"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType\/module(event:module:)","title":"TMTickets.Analytics.MetadataType.module(event:module:)","kind":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets","url":"\/documentation\/ticketmastertickets\/tmtickets","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMTickets","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"TMTickets","kind":"identifier"}],"abstract":[{"text":"main class of Tickets SDK, intended to be used as singleton","type":"text"}],"title":"TMTickets","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"TMTicketsModule","op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/title"},{"value":[{"text":"TMTicketsModule","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/navigatorTitle","value":[{"text":"TMTicketsModule","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/title","value":"TMTickets"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/fragments","value":[{"kind":"identifier","text":"TMTickets"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TMTickets"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}