{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/Environment-swift.enum\/custom(baseUrlString:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/Environment-swift.enum"]]},"sections":[],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"custom","kind":"identifier"},{"text":"(","kind":"text"},{"text":"baseUrlString","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"symbolKind":"case","modules":[{"name":"TicketmasterDiscoveryAPI"}],"title":"TMDiscoveryAPI.Environment.custom(baseUrlString:)","roleHeading":"Case","role":"symbol","externalID":"s:24TicketmasterDiscoveryAPI011TMDiscoveryC0C11EnvironmentO6customyAESS_tcAEmF"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"custom","kind":"identifier"},{"text":"(","kind":"text"},{"text":"baseUrlString","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi\/environment-swift.enum\/custom(baseurlstring:)"]}],"references":{"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TMDiscoveryAPI/Environment-swift.enum":{"url":"\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi\/environment-swift.enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Environment"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/Environment-swift.enum","abstract":[],"kind":"symbol","title":"TMDiscoveryAPI.Environment","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Environment"}],"type":"topic"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TMDiscoveryAPI":{"navigatorTitle":[{"kind":"identifier","text":"TMDiscoveryAPI"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI","kind":"symbol","url":"\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi","title":"TMDiscoveryAPI","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMDiscoveryAPI"}],"abstract":[{"type":"text","text":"A class that stores the global configuration for the TicketmasterDiscoveryAPI SDK"}]},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TMDiscoveryAPI/Environment-swift.enum/custom(baseUrlString:)":{"type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"custom","kind":"identifier"},{"text":"(","kind":"text"},{"text":"baseUrlString","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/Environment-swift.enum\/custom(baseUrlString:)","title":"TMDiscoveryAPI.Environment.custom(baseUrlString:)","url":"\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi\/environment-swift.enum\/custom(baseurlstring:)"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI","abstract":[],"kind":"symbol","title":"TicketmasterDiscoveryAPI","type":"topic","role":"collection","url":"\/documentation\/ticketmasterdiscoveryapi"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterDiscoveryAPI~1documentation~1TicketmasterDiscoveryAPI~1TMDiscoveryAPI\/title","value":"TMDiscoveryAPI"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterDiscoveryAPI~1documentation~1TicketmasterDiscoveryAPI~1TMDiscoveryAPI\/fragments","value":[{"kind":"identifier","text":"TMDiscoveryAPI"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterDiscoveryAPI~1documentation~1TicketmasterDiscoveryAPI~1TMDiscoveryAPI\/navigatorTitle","value":[{"text":"TMDiscoveryAPI","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}