{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/Environment-swift.enum\/Equatable-Implementations"},"kind":"article","sections":[],"metadata":{"role":"collectionGroup","title":"Equatable Implementations","roleHeading":"API Collection","modules":[{"name":"TicketmasterDiscoveryAPI"}]},"topicSections":[{"title":"Operators","generated":true,"identifiers":["doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/Environment-swift.enum\/!=(_:_:)"],"anchor":"Operators"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi\/environment-swift.enum\/equatable-implementations"]}],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/Environment-swift.enum"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI":{"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI","title":"TicketmasterDiscoveryAPI","abstract":[],"kind":"symbol","url":"\/documentation\/ticketmasterdiscoveryapi","role":"collection"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TMDiscoveryAPI":{"type":"topic","title":"TMDiscoveryAPI","identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI","abstract":[{"text":"A class that stores the global configuration for the TicketmasterDiscoveryAPI SDK","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"TMDiscoveryAPI","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMDiscoveryAPI","kind":"identifier"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi","role":"symbol"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TMDiscoveryAPI/Environment-swift.enum/!=(_:_:)":{"url":"\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi\/environment-swift.enum\/!=(_:_:)","identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/Environment-swift.enum\/!=(_:_:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","abstract":[],"title":"!=(_:_:)"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TMDiscoveryAPI/Environment-swift.enum":{"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/Environment-swift.enum","title":"TMDiscoveryAPI.Environment","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"Environment","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Environment","kind":"identifier"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi\/environment-swift.enum","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"TMDiscoveryAPI","op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterDiscoveryAPI~1documentation~1TicketmasterDiscoveryAPI~1TMDiscoveryAPI\/title"},{"value":[{"kind":"identifier","text":"TMDiscoveryAPI"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterDiscoveryAPI~1documentation~1TicketmasterDiscoveryAPI~1TMDiscoveryAPI\/fragments"},{"value":[{"kind":"identifier","text":"TMDiscoveryAPI"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterDiscoveryAPI~1documentation~1TicketmasterDiscoveryAPI~1TMDiscoveryAPI\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}