{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/Environment-swift.enum\/httpHostString(forMarketDomain:)"},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/Environment-swift.enum"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"httpHostString"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forMarketDomain"},{"kind":"text","text":" "},{"kind":"internalParam","text":"marketDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterFoundation@E@MarketDomain","text":"MarketDomain"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi\/environment-swift.enum\/httphoststring(formarketdomain:)"]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"httpHostString"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forMarketDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterFoundation@E@MarketDomain","text":"MarketDomain"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"modules":[{"name":"TicketmasterDiscoveryAPI"}],"externalID":"s:24TicketmasterDiscoveryAPI011TMDiscoveryC0C11EnvironmentO14httpHostString15forMarketDomainSS0A10Foundation0jK0O_tF","roleHeading":"Instance Method","title":"httpHostString(forMarketDomain:)","symbolKind":"method","role":"symbol"},"references":{"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TMDiscoveryAPI":{"type":"topic","title":"TMDiscoveryAPI","identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI","abstract":[{"text":"A class that stores the global configuration for the TicketmasterDiscoveryAPI SDK","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"TMDiscoveryAPI","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMDiscoveryAPI","kind":"identifier"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi","role":"symbol"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI":{"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI","title":"TicketmasterDiscoveryAPI","abstract":[],"kind":"symbol","url":"\/documentation\/ticketmasterdiscoveryapi","role":"collection"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TMDiscoveryAPI/Environment-swift.enum/httpHostString(forMarketDomain:)":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/Environment-swift.enum\/httpHostString(forMarketDomain:)","kind":"symbol","url":"\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi\/environment-swift.enum\/httphoststring(formarketdomain:)","title":"httpHostString(forMarketDomain:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"httpHostString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forMarketDomain","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MarketDomain","preciseIdentifier":"c:@M@TicketmasterFoundation@E@MarketDomain","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[]},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TMDiscoveryAPI/Environment-swift.enum":{"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/Environment-swift.enum","title":"TMDiscoveryAPI.Environment","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"Environment","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Environment","kind":"identifier"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi\/environment-swift.enum","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"TMDiscoveryAPI","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterDiscoveryAPI~1documentation~1TicketmasterDiscoveryAPI~1TMDiscoveryAPI\/title"},{"op":"replace","value":[{"text":"TMDiscoveryAPI","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterDiscoveryAPI~1documentation~1TicketmasterDiscoveryAPI~1TMDiscoveryAPI\/fragments"},{"op":"replace","value":[{"text":"TMDiscoveryAPI","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterDiscoveryAPI~1documentation~1TicketmasterDiscoveryAPI~1TMDiscoveryAPI\/navigatorTitle"}]}]}