{"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/Item"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"title":"variant","externalID":"s:20TicketmasterPurchase15TMPurchaseOrderC4ItemC7variantSSSgvp","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"variant","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"modules":[{"name":"TicketmasterPurchase"}],"role":"symbol"},"identifier":{"url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/Item\/variant","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"variant","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/item\/variant"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/Item/variant":{"url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/item\/variant","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/Item\/variant","type":"topic","title":"variant","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"variant"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"kind":"symbol","abstract":[],"url":"\/documentation\/ticketmasterpurchase","title":"TicketmasterPurchase","role":"collection","type":"topic","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder":{"navigatorTitle":[{"kind":"identifier","text":"TMPurchaseOrder"}],"title":"TMPurchaseOrder","abstract":[{"type":"text","text":"A data structure that represents a purchased order"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TMPurchaseOrder","kind":"identifier"}],"url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder","role":"symbol","type":"topic","kind":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/Item":{"abstract":[],"type":"topic","navigatorTitle":[{"text":"Item","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/Item","kind":"symbol","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/item","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Item","kind":"identifier"}],"title":"TMPurchaseOrder.Item"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseOrder\/title","op":"replace","value":"TMPurchaseOrder"},{"op":"replace","value":[{"kind":"identifier","text":"TMPurchaseOrder"}],"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseOrder\/fragments"},{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseOrder\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TMPurchaseOrder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}