{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"moduleActionButton","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/moduleActionButton","interfaceLanguage":"swift"},"abstract":[{"text":"user pressed a button on a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","isActive":true}],"sections":[],"metadata":{"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"moduleActionButton"}],"title":"TMTickets.Analytics.Action.moduleActionButton","symbolKind":"case","modules":[{"name":"TicketmasterTickets"}],"role":"symbol","externalID":"s:19TicketmasterTickets9TMTicketsC9AnalyticsV6ActionO06moduleE6ButtonyA2GmF"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmastertickets\/tmtickets\/analytics\/action\/moduleactionbutton"]}],"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/Action/moduleActionButton":{"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action\/moduleActionButton","type":"topic","abstract":[{"text":"user pressed a button on a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","isActive":true}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moduleActionButton","kind":"identifier"}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/action\/moduleactionbutton","title":"TMTickets.Analytics.Action.moduleActionButton"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule":{"type":"topic","title":"TMTicketsModule","url":"\/documentation\/ticketmastertickets\/tmticketsmodule","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsModule"}],"navigatorTitle":[{"kind":"identifier","text":"TMTicketsModule"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","role":"symbol","abstract":[{"text":"create a custom module to be displayed underneath the user’s list of Tickets on the Tickets listing page","type":"text"}],"kind":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/Action":{"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/Action","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Action","kind":"identifier"}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/action","title":"TMTickets.Analytics.Action","navigatorTitle":[{"text":"Action","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TMTickets","kind":"identifier"}],"url":"\/documentation\/ticketmastertickets\/tmtickets","navigatorTitle":[{"text":"TMTickets","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets","kind":"symbol","type":"topic","abstract":[{"text":"main class of Tickets SDK, intended to be used as singleton","type":"text"}],"title":"TMTickets"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"title":"TicketmasterTickets","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","type":"topic","role":"collection","url":"\/documentation\/ticketmastertickets","abstract":[{"type":"text","text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes."}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics":{"abstract":[{"text":"analytics for User behavior","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Analytics"}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics","navigatorTitle":[{"text":"Analytics","kind":"identifier"}],"kind":"symbol","title":"TMTickets.Analytics","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TMTicketsModule","op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TMTicketsModule"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/fragments"},{"value":"TMTickets","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/title","op":"replace"},{"op":"replace","value":[{"text":"TMTickets","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/fragments"}]}]}