{"metadata":{"title":"additionalURLParameters","modules":[{"name":"TicketmasterPurchase"}],"symbolKind":"property","externalID":"s:20TicketmasterPurchase30TMPurchaseWebsiteConfigurationC23additionalURLParametersSDyS2SGvp","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"additionalURLParameters","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"roleHeading":"Instance Property","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration\/additionalurlparameters"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/additionalURLParameters"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"additionalURLParameters","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"text":"Your own additional custom URL parameters, these string values will be URL-encoded by the Purchase SDK.","type":"text"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebsiteConfiguration/additionalURLParameters":{"title":"additionalURLParameters","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalURLParameters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"type":"topic","abstract":[{"text":"Your own additional custom URL parameters, these string values will be URL-encoded by the Purchase SDK.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/additionalURLParameters","url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration\/additionalurlparameters","role":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebsiteConfiguration":{"abstract":[{"text":"Class used to configure behavior of website Event Details Page (EDP) and Cart","type":"text"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMPurchaseWebsiteConfiguration"}],"title":"TMPurchaseWebsiteConfiguration","url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration","navigatorTitle":[{"kind":"identifier","text":"TMPurchaseWebsiteConfiguration"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"role":"collection","title":"TicketmasterPurchase","abstract":[],"type":"topic","url":"\/documentation\/ticketmasterpurchase","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"TMPurchaseWebsiteConfiguration","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseWebsiteConfiguration\/title"},{"value":[{"kind":"identifier","text":"TMPurchaseWebsiteConfiguration"}],"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseWebsiteConfiguration\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseWebsiteConfiguration\/navigatorTitle","value":[{"text":"TMPurchaseWebsiteConfiguration","kind":"identifier"}]}]}]}