{"identifier":{"url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/customTitleFont","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"TicketmasterPurchase"}],"symbolKind":"property","role":"symbol","externalID":"s:20TicketmasterPurchase30TMPurchaseWebsiteConfigurationC15customTitleFontSo6UIFontCSgvp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customTitleFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont"},{"kind":"text","text":"?"}],"title":"customTitleFont","roleHeading":"Instance Property"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration\/customtitlefont"]}],"abstract":[{"type":"text","text":"A font to use for title labels, or nil to use the default"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customTitleFont","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"},{"text":"?","kind":"text"}]}]}],"references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebsiteConfiguration/customTitleFont":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"customTitleFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont"},{"kind":"text","text":"?"}],"title":"customTitleFont","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration\/customtitlefont","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/customTitleFont","abstract":[{"type":"text","text":"A font to use for title labels, or nil to use the default"}],"role":"symbol","kind":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","url":"\/documentation\/ticketmasterpurchase","type":"topic","role":"collection","abstract":[],"title":"TicketmasterPurchase"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebsiteConfiguration":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration","navigatorTitle":[{"kind":"identifier","text":"TMPurchaseWebsiteConfiguration"}],"title":"TMPurchaseWebsiteConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPurchaseWebsiteConfiguration"}],"url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration","abstract":[{"type":"text","text":"Class used to configure behavior of website Event Details Page (EDP) and Cart"}],"kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TMPurchaseWebsiteConfiguration","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseWebsiteConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"TMPurchaseWebsiteConfiguration"}],"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseWebsiteConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"TMPurchaseWebsiteConfiguration"}],"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseWebsiteConfiguration\/navigatorTitle","op":"replace"}]}]}