{"identifier":{"url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/showNFLBranding","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration\/shownflbranding"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration"]]},"sections":[],"abstract":[{"type":"text","text":"Show special NFL branding on EDP"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showNFLBranding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}]}],"metadata":{"externalID":"s:20TicketmasterPurchase30TMPurchaseWebsiteConfigurationC15showNFLBrandingSbvp","symbolKind":"property","title":"showNFLBranding","roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showNFLBranding","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"modules":[{"name":"TicketmasterPurchase"}]},"references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"type":"topic","url":"\/documentation\/ticketmasterpurchase","title":"TicketmasterPurchase","abstract":[],"role":"collection","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","kind":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebsiteConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPurchaseWebsiteConfiguration"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TMPurchaseWebsiteConfiguration"}],"abstract":[{"type":"text","text":"Class used to configure behavior of website Event Details Page (EDP) and Cart"}],"title":"TMPurchaseWebsiteConfiguration","url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration","role":"symbol","type":"topic"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebsiteConfiguration/showNFLBranding":{"url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration\/shownflbranding","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/showNFLBranding","title":"showNFLBranding","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"showNFLBranding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","abstract":[{"text":"Show special NFL branding on EDP","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseWebsiteConfiguration\/title","value":"TMPurchaseWebsiteConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseWebsiteConfiguration\/fragments","value":[{"kind":"identifier","text":"TMPurchaseWebsiteConfiguration"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseWebsiteConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"TMPurchaseWebsiteConfiguration"}]}]}]}