{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isForProduction","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/Environment-swift.enum"]]},"sections":[],"metadata":{"modules":[{"name":"TicketmasterPurchase"}],"role":"symbol","externalID":"s:20TicketmasterPurchase10TMPurchaseC11EnvironmentO15isForProductionSbvp","symbolKind":"property","roleHeading":"Instance Property","title":"isForProduction","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isForProduction","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"variants":[{"paths":["\/documentation\/ticketmasterpurchase\/tmpurchase\/environment-swift.enum\/isforproduction"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/Environment-swift.enum\/isForProduction","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"kind":"symbol","role":"collection","title":"TicketmasterPurchase","url":"\/documentation\/ticketmasterpurchase","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","type":"topic","abstract":[]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchase":{"kind":"symbol","role":"symbol","title":"TMPurchase","url":"\/documentation\/ticketmasterpurchase\/tmpurchase","navigatorTitle":[{"kind":"identifier","text":"TMPurchase"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPurchase"}],"abstract":[{"type":"text","text":"A class that stores the global configuration for the TicketmasterPurchase SDK."}]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchase/Environment-swift.enum":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/Environment-swift.enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Environment","kind":"identifier"}],"navigatorTitle":[{"text":"Environment","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/ticketmasterpurchase\/tmpurchase\/environment-swift.enum","title":"TMPurchase.Environment"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchase/Environment-swift.enum/isForProduction":{"abstract":[],"title":"isForProduction","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/Environment-swift.enum\/isForProduction","role":"symbol","url":"\/documentation\/ticketmasterpurchase\/tmpurchase\/environment-swift.enum\/isforproduction","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isForProduction","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchase\/title","value":"TMPurchase"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchase\/fragments","value":[{"text":"TMPurchase","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchase\/navigatorTitle","value":[{"text":"TMPurchase","kind":"identifier"}]}]}]}