{"metadata":{"role":"symbol","title":"TMPurchase.Environment.testingProduction2","modules":[{"name":"TicketmasterPurchase"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"testingProduction2"}],"roleHeading":"Case","externalID":"s:20TicketmasterPurchase10TMPurchaseC11EnvironmentO18testingProduction2yA2EmF","symbolKind":"case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/Environment-swift.enum\/testingProduction2"},"kind":"symbol","variants":[{"paths":["\/documentation\/ticketmasterpurchase\/tmpurchase\/environment-swift.enum\/testingproduction2"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/Environment-swift.enum"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"testingProduction2","kind":"identifier"}],"languages":["swift"]}]}],"sections":[],"references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"role":"collection","title":"TicketmasterPurchase","abstract":[],"type":"topic","url":"\/documentation\/ticketmasterpurchase","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchase/Environment-swift.enum":{"abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Environment","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/Environment-swift.enum","title":"TMPurchase.Environment","kind":"symbol","navigatorTitle":[{"text":"Environment","kind":"identifier"}],"url":"\/documentation\/ticketmasterpurchase\/tmpurchase\/environment-swift.enum","type":"topic"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchase/Environment-swift.enum/testingProduction2":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"testingProduction2","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/ticketmasterpurchase\/tmpurchase\/environment-swift.enum\/testingproduction2","type":"topic","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/Environment-swift.enum\/testingProduction2","title":"TMPurchase.Environment.testingProduction2"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchase":{"kind":"symbol","title":"TMPurchase","role":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase","navigatorTitle":[{"kind":"identifier","text":"TMPurchase"}],"type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchase","abstract":[{"text":"A class that stores the global configuration for the TicketmasterPurchase SDK.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPurchase"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchase\/title","value":"TMPurchase"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchase\/fragments","value":[{"text":"TMPurchase","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchase\/navigatorTitle","value":[{"kind":"identifier","text":"TMPurchase"}],"op":"replace"}]}]}