{"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule"]]},"abstract":[{"type":"text","text":"Build the NAM Account Manager Addon Upsells module"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/accountManagerAddonUpsells(event:headerOverride:customIdentifier:)"},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule\/accountmanageraddonupsells(event:headeroverride:customidentifier:)"]}],"metadata":{"symbolKind":"method","title":"accountManagerAddonUpsells(event:headerOverride:customIdentifier:)","externalID":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV26accountManagerAddonUpsells5event14headerOverride16customIdentifierAA0cE0CSgAA16TMPurchasedEventV_AC06HeaderL0VSgSSSgtFZ","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accountManagerAddonUpsells","kind":"identifier"},{"text":"(","kind":"text"},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TMPurchasedEvent","kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV"},{"text":", ","kind":"text"},{"text":"headerOverride","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HeaderOverride","kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV14HeaderOverrideV"},{"text":"?, ","kind":"text"},{"text":"customIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"text":"TMTicketsModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule"},{"text":"?","kind":"text"}],"modules":[{"name":"TicketmasterTickets"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accountManagerAddonUpsells","kind":"identifier"},{"kind":"text","text":"("},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TMPurchasedEvent","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedEvent","kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV"},{"kind":"text","text":", "},{"text":"headerOverride","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/HeaderOverride","preciseIdentifier":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV14HeaderOverrideV","kind":"typeIdentifier","text":"HeaderOverride"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"customIdentifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil) -> ","kind":"text"},{"text":"TMTicketsModule","kind":"typeIdentifier","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule"},{"text":"?","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The user’s purchased Event","type":"text"}]}],"name":"event"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A struct containing any module header values to override (replacing the default module values with the provided overrides)","type":"text"}]}],"name":"headerOverride"},{"name":"customIdentifier","content":[{"type":"paragraph","inlineContent":[{"text":"Optional override identifier for prebuilt module","type":"text"}]}]}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"A module configured with the provided values (may be ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if ","type":"text"},{"type":"codeVoice","code":"event"},{"text":" are not for Account Manager)","type":"text"}]}]}],"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule/accountManagerAddonUpsells(event:headerOverride:customIdentifier:)":{"type":"topic","abstract":[{"type":"text","text":"Build the NAM Account Manager Addon Upsells module"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accountManagerAddonUpsells","kind":"identifier"},{"text":"(","kind":"text"},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TMPurchasedEvent","kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV"},{"text":", ","kind":"text"},{"text":"headerOverride","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HeaderOverride","kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV14HeaderOverrideV"},{"text":"?, ","kind":"text"},{"text":"customIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"text":"TMTicketsModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule"},{"text":"?","kind":"text"}],"kind":"symbol","title":"accountManagerAddonUpsells(event:headerOverride:customIdentifier:)","url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule\/accountmanageraddonupsells(event:headeroverride:customidentifier:)","role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/accountManagerAddonUpsells(event:headerOverride:customIdentifier:)"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"title":"TicketmasterTickets","type":"topic","url":"\/documentation\/ticketmastertickets","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","role":"collection","kind":"symbol","abstract":[{"text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes.","type":"text"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTicketsModule"}],"navigatorTitle":[{"kind":"identifier","text":"TMTicketsModule"}],"title":"TMTicketsModule","type":"topic","url":"\/documentation\/ticketmastertickets\/tmticketsmodule","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"create a custom module to be displayed underneath the user’s list of Tickets on the Tickets listing page"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMPurchasedEvent":{"abstract":[{"text":"an Event purchased by the User, containing Event Information, Orders, and Tickets","type":"text"}],"title":"TMPurchasedEvent","url":"\/documentation\/ticketmastertickets\/tmpurchasedevent","kind":"symbol","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedEvent","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPurchasedEvent"}],"navigatorTitle":[{"kind":"identifier","text":"TMPurchasedEvent"}],"role":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule":{"abstract":[{"text":"useful pre-built ","type":"text"},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","isActive":true,"type":"reference"},{"text":" for the Tickets listing page","type":"text"}],"title":"TMTicketsPrebuiltModule","url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule","kind":"symbol","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTicketsPrebuiltModule"}],"navigatorTitle":[{"kind":"identifier","text":"TMTicketsPrebuiltModule"}],"role":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule/HeaderOverride":{"abstract":[],"title":"TMTicketsPrebuiltModule.HeaderOverride","url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule\/headeroverride","kind":"symbol","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/HeaderOverride","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeaderOverride"}],"navigatorTitle":[{"kind":"identifier","text":"HeaderOverride"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/title","value":"TMTicketsModule","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/fragments","value":[{"kind":"identifier","text":"TMTicketsModule"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/navigatorTitle","value":[{"kind":"identifier","text":"TMTicketsModule"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}