{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ticketmasterdiscoveryapi"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ticketmasterdiscoveryapi"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryService","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI"]},{"title":"Structures","identifiers":["doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryAttraction","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryAttractionSearchCriteria","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryClassification","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryClassificationItem","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryClassificationSearchCriteria","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryDateRange","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryError","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryEvent","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryEventSearchCriteria","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryIdentifier","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryImageMetadata","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryPriceRange","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryProduct","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryPromoter","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoverySuggestCriteria","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoverySuggestResponse","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryVenue","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryVenueSearchCriteria","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/LegacyHostIdentifier"]},{"title":"Enumerations","identifiers":["doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryCurrency","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryEntityType","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryExclusiveBool","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryImageRatio","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryLocale","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoverySource"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"TicketmasterDiscoveryAPI","title":"TicketmasterDiscoveryAPI","symbolKind":"module","role":"collection","modules":[{"name":"TicketmasterDiscoveryAPI"}]},"hierarchy":{"paths":[[]]},"references":{"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/DiscoveryClassificationSearchCriteria":{"role":"symbol","title":"DiscoveryClassificationSearchCriteria","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscoveryClassificationSearchCriteria"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryClassificationSearchCriteria","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscoveryClassificationSearchCriteria"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/discoveryclassificationsearchcriteria"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/DiscoveryPromoter":{"role":"symbol","title":"DiscoveryPromoter","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscoveryPromoter"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryPromoter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscoveryPromoter"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/discoverypromoter"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/DiscoveryError":{"role":"symbol","title":"DiscoveryError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscoveryError"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscoveryError"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/discoveryerror"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/DiscoverySuggestResponse":{"role":"symbol","title":"DiscoverySuggestResponse","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscoverySuggestResponse"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoverySuggestResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscoverySuggestResponse"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/discoverysuggestresponse"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/DiscoveryEventSearchCriteria":{"role":"symbol","title":"DiscoveryEventSearchCriteria","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscoveryEventSearchCriteria"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryEventSearchCriteria","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscoveryEventSearchCriteria"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/discoveryeventsearchcriteria"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/DiscoveryExclusiveBool":{"role":"symbol","title":"DiscoveryExclusiveBool","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscoveryExclusiveBool"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryExclusiveBool","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscoveryExclusiveBool"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/discoveryexclusivebool"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/DiscoveryAttractionSearchCriteria":{"role":"symbol","title":"DiscoveryAttractionSearchCriteria","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscoveryAttractionSearchCriteria"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryAttractionSearchCriteria","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscoveryAttractionSearchCriteria"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/discoveryattractionsearchcriteria"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TicketmasterDiscoveryAPIVersionNumber":{"role":"symbol","title":"TicketmasterDiscoveryAPIVersionNumber","fragments":[{"kind":"identifier","text":"TicketmasterDiscoveryAPIVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for TicketmasterDiscoveryAPI."}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TicketmasterDiscoveryAPIVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterdiscoveryapi\/ticketmasterdiscoveryapiversionnumber"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/DiscoveryClassification":{"role":"symbol","title":"DiscoveryClassification","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscoveryClassification"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryClassification","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscoveryClassification"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/discoveryclassification"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TicketmasterDiscoveryAPIVersionString":{"role":"symbol","title":"TicketmasterDiscoveryAPIVersionString","fragments":[{"kind":"identifier","text":"TicketmasterDiscoveryAPIVersionString"}],"abstract":[{"type":"text","text":"Project version string for TicketmasterDiscoveryAPI."}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TicketmasterDiscoveryAPIVersionString","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterdiscoveryapi\/ticketmasterdiscoveryapiversionstring"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/DiscoveryProduct":{"role":"symbol","title":"DiscoveryProduct","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscoveryProduct"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryProduct","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscoveryProduct"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/discoveryproduct"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/DiscoveryLocale":{"role":"symbol","title":"DiscoveryLocale","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscoveryLocale"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryLocale","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscoveryLocale"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/discoverylocale"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/DiscoveryEntityType":{"role":"symbol","title":"DiscoveryEntityType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscoveryEntityType"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryEntityType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscoveryEntityType"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/discoveryentitytype"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/DiscoveryEvent":{"role":"symbol","title":"DiscoveryEvent","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscoveryEvent"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscoveryEvent"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/discoveryevent"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/DiscoveryImageRatio":{"role":"symbol","title":"DiscoveryImageRatio","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscoveryImageRatio"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryImageRatio","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscoveryImageRatio"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/discoveryimageratio"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/DiscoveryCurrency":{"role":"symbol","title":"DiscoveryCurrency","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscoveryCurrency"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryCurrency","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscoveryCurrency"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/discoverycurrency"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/DiscoverySource":{"role":"symbol","title":"DiscoverySource","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscoverySource"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoverySource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscoverySource"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/discoverysource"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/DiscoveryVenueSearchCriteria":{"role":"symbol","title":"DiscoveryVenueSearchCriteria","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscoveryVenueSearchCriteria"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryVenueSearchCriteria","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscoveryVenueSearchCriteria"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/discoveryvenuesearchcriteria"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/DiscoveryService":{"role":"symbol","title":"DiscoveryService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscoveryService"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscoveryService"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/discoveryservice"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/DiscoveryAttraction":{"role":"symbol","title":"DiscoveryAttraction","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscoveryAttraction"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryAttraction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscoveryAttraction"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/discoveryattraction"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/DiscoveryIdentifier":{"role":"symbol","title":"DiscoveryIdentifier","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscoveryIdentifier"}],"abstract":[{"type":"text","text":"a type-safe “String” to allow the compiler to help the programmer not confuse DiscoveryIDs with LegacyHostIDs"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryIdentifier","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscoveryIdentifier"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/discoveryidentifier"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI":{"role":"collection","title":"TicketmasterDiscoveryAPI","abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterdiscoveryapi"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/DiscoverySuggestCriteria":{"role":"symbol","title":"DiscoverySuggestCriteria","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscoverySuggestCriteria"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoverySuggestCriteria","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscoverySuggestCriteria"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/discoverysuggestcriteria"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/DiscoveryDateRange":{"role":"symbol","title":"DiscoveryDateRange","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscoveryDateRange"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryDateRange","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscoveryDateRange"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/discoverydaterange"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/DiscoveryPriceRange":{"role":"symbol","title":"DiscoveryPriceRange","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscoveryPriceRange"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryPriceRange","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscoveryPriceRange"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/discoverypricerange"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TMDiscoveryAPI":{"role":"symbol","title":"TMDiscoveryAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMDiscoveryAPI"}],"abstract":[{"type":"text","text":"A class that stores the global configuration for the TicketmasterDiscovery SDK."}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TMDiscoveryAPI"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/DiscoveryClassificationItem":{"role":"symbol","title":"DiscoveryClassificationItem","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscoveryClassificationItem"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryClassificationItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscoveryClassificationItem"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/discoveryclassificationitem"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/DiscoveryVenue":{"role":"symbol","title":"DiscoveryVenue","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscoveryVenue"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryVenue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscoveryVenue"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/discoveryvenue"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/LegacyHostIdentifier":{"role":"symbol","title":"LegacyHostIdentifier","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LegacyHostIdentifier"}],"abstract":[{"type":"text","text":"a type-safe “String” to allow the compiler to help the programmer not confuse DiscoveryIDs with LegacyHostIDs"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/LegacyHostIdentifier","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LegacyHostIdentifier"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/legacyhostidentifier"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/DiscoveryImageMetadata":{"role":"symbol","title":"DiscoveryImageMetadata","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscoveryImageMetadata"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/DiscoveryImageMetadata","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscoveryImageMetadata"}],"url":"\/documentation\/ticketmasterdiscoveryapi\/discoveryimagemetadata"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI"]},{"title":"Variables","identifiers":["doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TicketmasterDiscoveryAPIVersionNumber","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TicketmasterDiscoveryAPIVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterDiscoveryAPI~1documentation~1TicketmasterDiscoveryAPI~1TMDiscoveryAPI\/title","value":"TMDiscoveryAPI"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterDiscoveryAPI~1documentation~1TicketmasterDiscoveryAPI~1TMDiscoveryAPI\/fragments","value":[{"kind":"identifier","text":"TMDiscoveryAPI"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}