{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"init(keyValue:)","modules":[{"name":"TicketmasterPrePurchase"}],"externalID":"s:23TicketmasterPrePurchase05TMPreC0C11EnvironmentO8keyValueAESS_tcfc","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"keyValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"symbolKind":"init","roleHeading":"Initializer"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keyValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/Environment-swift.enum"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/Environment-swift.enum\/init(keyValue:)"},"variants":[{"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchase\/environment-swift.enum\/init(keyvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"references":{"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchase/Environment-swift.enum":{"title":"TMPrePurchase.Environment","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchase\/environment-swift.enum","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Environment"}],"navigatorTitle":[{"kind":"identifier","text":"Environment"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/Environment-swift.enum","role":"symbol","type":"topic"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchase/Environment-swift.enum/init(keyValue:)":{"abstract":[],"title":"init(keyValue:)","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keyValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchase\/environment-swift.enum\/init(keyvalue:)","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/Environment-swift.enum\/init(keyValue:)"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchase":{"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMPrePurchase","kind":"identifier"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchase","navigatorTitle":[{"text":"TMPrePurchase","kind":"identifier"}],"title":"TMPrePurchase","abstract":[{"text":"A class that stores the global configuration for the TicketmasterPrePurchase SDK.","type":"text"}]},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","url":"\/documentation\/ticketmasterprepurchase","title":"TicketmasterPrePurchase","type":"topic","role":"collection","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchase\/title","value":"TMPrePurchase","op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchase\/fragments","value":[{"text":"TMPrePurchase","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchase\/navigatorTitle","value":[{"text":"TMPrePurchase","kind":"identifier"}],"op":"replace"}]}]}