{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"purchaseNavigationController"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"purchaseNavigationController","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TicketmasterPurchase@objc(cs)TMPurchaseNavigationController","text":"TMPurchaseNavigationController","kind":"typeIdentifier","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didMakePurchaseFor"},{"kind":"text","text":" "},{"kind":"internalParam","text":"event"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:24TicketmasterDiscoveryAPI0B5EventV","kind":"typeIdentifier","text":"DiscoveryEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"order"},{"kind":"text","text":": "},{"text":"TMPurchaseOrder","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterPurchase@objc(cs)TMPurchaseOrder"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"TMPurchaseNavigationController"},{"type":"text","text":" that the user made a purchase in"}],"type":"paragraph"}],"name":"purchaseNavigationController"},{"name":"event","content":[{"inlineContent":[{"text":"The Event that tickets were sold to","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The Order for the purchase, including info like purchase total, currency code, delivery method, etc."}],"type":"paragraph"}],"name":"order"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"purchaseNavigationController(:didMakePurchaseForEvent)"},{"type":"text","text":" is immediately called upon the purchase being completed, while the user is still viewing the Order Confirmation page."},{"type":"text","text":" "},{"type":"text","text":"Once the user is finished viewing their Order Confirmation, the user presses the "},{"code":"Done","type":"codeVoice"},{"type":"text","text":" button on the navigation bar and "},{"type":"codeVoice","code":"purchaseNavigationController(:didEndCheckoutForEvent:)"},{"type":"text","text":" is called."},{"type":"text","text":" "},{"type":"text","text":"If you want to update your UI (moving the user to the Orders Listing page, for example), wait for  "},{"type":"codeVoice","code":"purchaseNavigationControllerDidFinish()"},{"text":" to be called.","type":"text"}]}],"type":"aside","name":"Note"}]}],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseUserAnalyticsDelegate"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Tells the delegate that the user made a purchase and is currently viewing the Order Confirmation page."}],"metadata":{"required":true,"roleHeading":"Instance Method","externalID":"s:20TicketmasterPurchase31TMPurchaseUserAnalyticsDelegateP28purchaseNavigationController_07didMakeB3For5orderyAA0chI0C_0A12DiscoveryAPI0N5EventVAA0C5OrderCtF","symbolKind":"method","title":"purchaseNavigationController(_:didMakePurchaseFor:order:)","modules":[{"name":"TicketmasterPurchase"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"purchaseNavigationController"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@TicketmasterPurchase@objc(cs)TMPurchaseNavigationController","kind":"typeIdentifier","text":"TMPurchaseNavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didMakePurchaseFor"},{"kind":"text","text":": "},{"preciseIdentifier":"s:24TicketmasterDiscoveryAPI0B5EventV","text":"DiscoveryEvent","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"order","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TMPurchaseOrder","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterPurchase@objc(cs)TMPurchaseOrder"},{"kind":"text","text":")"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseUserAnalyticsDelegate\/purchaseNavigationController(_:didMakePurchaseFor:order:)"},"variants":[{"paths":["\/documentation\/ticketmasterpurchase\/tmpurchaseuseranalyticsdelegate\/purchasenavigationcontroller(_:didmakepurchasefor:order:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseUserAnalyticsDelegate":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMPurchaseUserAnalyticsDelegate"}],"title":"TMPurchaseUserAnalyticsDelegate","navigatorTitle":[{"text":"TMPurchaseUserAnalyticsDelegate","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The user analytics delegate of a ","type":"text"},{"type":"codeVoice","code":"TMPurchaseNavigationController"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseUserAnalyticsDelegate","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseuseranalyticsdelegate"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseUserAnalyticsDelegate/purchaseNavigationController(_:didMakePurchaseFor:order:)":{"title":"purchaseNavigationController(_:didMakePurchaseFor:order:)","abstract":[{"type":"text","text":"Tells the delegate that the user made a purchase and is currently viewing the Order Confirmation page."}],"type":"topic","required":true,"role":"symbol","kind":"symbol","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseuseranalyticsdelegate\/purchasenavigationcontroller(_:didmakepurchasefor:order:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"purchaseNavigationController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterPurchase@objc(cs)TMPurchaseNavigationController","text":"TMPurchaseNavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didMakePurchaseFor"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:24TicketmasterDiscoveryAPI0B5EventV","text":"DiscoveryEvent","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"order"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TMPurchaseOrder","preciseIdentifier":"c:@M@TicketmasterPurchase@objc(cs)TMPurchaseOrder"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseUserAnalyticsDelegate\/purchaseNavigationController(_:didMakePurchaseFor:order:)"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"kind":"symbol","abstract":[],"url":"\/documentation\/ticketmasterpurchase","title":"TicketmasterPurchase","role":"collection","type":"topic","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMPurchaseNavigationController"}],"title":"TMPurchaseNavigationController","navigatorTitle":[{"kind":"identifier","text":"TMPurchaseNavigationController"}],"role":"symbol","abstract":[{"text":"A navigation controller (view controller) that allows users to select and purchase tickets to a Ticketmaster Event.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController","url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder":{"navigatorTitle":[{"kind":"identifier","text":"TMPurchaseOrder"}],"title":"TMPurchaseOrder","abstract":[{"type":"text","text":"A data structure that represents a purchased order"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TMPurchaseOrder","kind":"identifier"}],"url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder","role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/title","value":"TMPurchaseNavigationController"},{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/fragments","op":"replace","value":[{"text":"TMPurchaseNavigationController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/navigatorTitle","value":[{"kind":"identifier","text":"TMPurchaseNavigationController"}]},{"value":"TMPurchaseOrder","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseOrder\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseOrder\/fragments","op":"replace","value":[{"kind":"identifier","text":"TMPurchaseOrder"}]},{"op":"replace","value":[{"kind":"identifier","text":"TMPurchaseOrder"}],"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseOrder\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}