{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/adjustTrackedPageView(_:)"},"metadata":{"title":"adjustTrackedPageView(_:)","role":"symbol","symbolKind":"method","extendedModule":"TicketmasterPrePurchase","roleHeading":"Instance Method","externalID":"c:@CM@TicketmasterPrePurchase@objc(cs)TMPrePurchaseViewController(im)adjustTrackedPageView:","modules":[{"name":"TicketmasterPrePurchase"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adjustTrackedPageView"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UALPageView","preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALPageView"},{"text":") -> ","kind":"text"},{"text":"UALPageView","preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALPageView","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"adjustTrackedPageView:","kind":"identifier"}]},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UALWebViewMessageHandlerDelegate.adjustTrackedPageView(_:)"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/UALWebViewMessageHandlerDelegate-Implementations"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"adjustTrackedPageView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"pageView","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALPageView","text":"UALPageView"},{"text":") -> ","kind":"text"},{"text":"UALPageView","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALPageView"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/adjusttrackedpageview(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/adjusttrackedpageview(_:)"]}],"kind":"symbol","references":{"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/UALWebViewMessageHandlerDelegate-Implementations":{"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/ualwebviewmessagehandlerdelegate-implementations","abstract":[],"title":"UALWebViewMessageHandlerDelegate Implementations","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/UALWebViewMessageHandlerDelegate-Implementations","role":"collectionGroup","kind":"article"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/adjustTrackedPageView(_:)":{"abstract":[],"title":"adjustTrackedPageView(_:)","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/adjustTrackedPageView(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"adjustTrackedPageView","kind":"identifier"},{"kind":"text","text":"("},{"text":"UALPageView","preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALPageView","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UALPageView","preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALPageView"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"adjustTrackedPageView:","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/adjusttrackedpageview(_:)"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase":{"type":"topic","url":"\/documentation\/ticketmasterprepurchase","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","role":"collection","title":"TicketmasterPrePurchase","abstract":[]},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMPrePurchaseViewController","kind":"identifier"}],"navigatorTitle":[{"text":"TMPrePurchaseViewController","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController","abstract":[{"type":"text","text":"Class used to display UI flow for discovering attractions and venues leading up to purchase flow."}],"type":"topic","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller","title":"TMPrePurchaseViewController","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"adjustTrackedPageView:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adjustTrackedPageView:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"UALPageView","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALPageView"},{"text":" *) ","kind":"text"},{"text":"adjustTrackedPageView:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UALPageView","preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALPageView"},{"kind":"text","text":" *) "},{"text":"pageView","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"adjustTrackedPageView:","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1adjustTrackedPageView(_:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"adjustTrackedPageView:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1adjustTrackedPageView(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/title","value":"TMPrePurchaseViewController"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/fragments","value":[{"text":"TMPrePurchaseViewController","kind":"identifier"}],"op":"replace"}]}]}