{"metadata":{"navigatorTitle":[{"text":"adjustTrackedCommerceEvent:","kind":"identifier"}],"role":"symbol","title":"adjustTrackedCommerceEvent(_:)","extendedModule":"TicketmasterPrePurchase","symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@CM@TicketmasterPrePurchase@objc(cs)TMPrePurchaseViewController(im)adjustTrackedCommerceEvent:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adjustTrackedCommerceEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UALCommerceEvent","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALCommerceEvent"},{"text":") -> ","kind":"text"},{"text":"UALCommerceEvent","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALCommerceEvent"},{"text":"?","kind":"text"}],"modules":[{"name":"TicketmasterPrePurchase"}]},"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UALWebViewMessageHandlerDelegate.adjustTrackedCommerceEvent(_:)"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adjustTrackedCommerceEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"commerceEvent","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALCommerceEvent","text":"UALCommerceEvent","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALCommerceEvent","text":"UALCommerceEvent","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/adjusttrackedcommerceevent(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/adjusttrackedcommerceevent(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/UALWebViewMessageHandlerDelegate-Implementations"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/adjustTrackedCommerceEvent(_:)"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase":{"kind":"symbol","role":"collection","title":"TicketmasterPrePurchase","url":"\/documentation\/ticketmasterprepurchase","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","type":"topic","abstract":[]},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController","title":"TMPrePurchaseViewController","role":"symbol","navigatorTitle":[{"text":"TMPrePurchaseViewController","kind":"identifier"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMPrePurchaseViewController","kind":"identifier"}],"abstract":[{"text":"Class used to display UI flow for discovering attractions and venues leading up to purchase flow.","type":"text"}]},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/adjustTrackedCommerceEvent(_:)":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/adjustTrackedCommerceEvent(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adjustTrackedCommerceEvent"},{"text":"(","kind":"text"},{"text":"UALCommerceEvent","preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALCommerceEvent","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UALCommerceEvent","preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALCommerceEvent","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/adjusttrackedcommerceevent(_:)","kind":"symbol","role":"symbol","title":"adjustTrackedCommerceEvent(_:)","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"adjustTrackedCommerceEvent:"}]},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/UALWebViewMessageHandlerDelegate-Implementations":{"title":"UALWebViewMessageHandlerDelegate Implementations","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/UALWebViewMessageHandlerDelegate-Implementations","role":"collectionGroup","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/ualwebviewmessagehandlerdelegate-implementations","kind":"article","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"adjustTrackedCommerceEvent:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adjustTrackedCommerceEvent:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALCommerceEvent","text":"UALCommerceEvent"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"adjustTrackedCommerceEvent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALCommerceEvent","text":"UALCommerceEvent"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"commerceEvent"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/title","value":"TMPrePurchaseViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/fragments","value":[{"kind":"identifier","text":"TMPrePurchaseViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/navigatorTitle","value":[{"text":"TMPrePurchaseViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1adjustTrackedCommerceEvent(_:)\/title","value":"adjustTrackedCommerceEvent:"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1adjustTrackedCommerceEvent(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adjustTrackedCommerceEvent:","kind":"identifier"}]}]}]}