{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UALWebViewMessageHandlerDelegate.adjustTrackedUserAction(_:)"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"adjustTrackedUserAction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"userAction"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALUserAction","text":"UALUserAction"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UALUserAction","preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALUserAction"},{"text":"?","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/adjustTrackedUserAction(_:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:@CM@TicketmasterPrePurchase@objc(cs)TMPrePurchaseViewController(im)adjustTrackedUserAction:","role":"symbol","extendedModule":"TicketmasterPrePurchase","navigatorTitle":[{"kind":"identifier","text":"adjustTrackedUserAction:"}],"modules":[{"name":"TicketmasterPrePurchase"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adjustTrackedUserAction"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALUserAction","text":"UALUserAction","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALUserAction","text":"UALUserAction","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"symbolKind":"method","title":"adjustTrackedUserAction(_:)","roleHeading":"Instance Method"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/UALWebViewMessageHandlerDelegate-Implementations"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/adjusttrackeduseraction(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/adjusttrackeduseraction(_:)"]}],"references":{"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/UALWebViewMessageHandlerDelegate-Implementations":{"title":"UALWebViewMessageHandlerDelegate Implementations","abstract":[],"type":"topic","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/ualwebviewmessagehandlerdelegate-implementations","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/UALWebViewMessageHandlerDelegate-Implementations","role":"collectionGroup","kind":"article"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController":{"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller","abstract":[{"type":"text","text":"Class used to display UI flow for discovering attractions and venues leading up to purchase flow."}],"navigatorTitle":[{"text":"TMPrePurchaseViewController","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController","role":"symbol","kind":"symbol","title":"TMPrePurchaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPrePurchaseViewController"}],"type":"topic"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/adjustTrackedUserAction(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"adjustTrackedUserAction","kind":"identifier"},{"kind":"text","text":"("},{"text":"UALUserAction","preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALUserAction","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UALUserAction","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALUserAction"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/adjustTrackedUserAction(_:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"adjustTrackedUserAction:"}],"title":"adjustTrackedUserAction(_:)","kind":"symbol","abstract":[],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/adjusttrackeduseraction(_:)"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase":{"type":"topic","url":"\/documentation\/ticketmasterprepurchase","kind":"symbol","role":"collection","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","title":"TicketmasterPrePurchase","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"adjustTrackedUserAction:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adjustTrackedUserAction:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALUserAction","kind":"typeIdentifier","text":"UALUserAction"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"adjustTrackedUserAction:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UALUserAction","preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALUserAction"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"userAction"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/title","value":"TMPrePurchaseViewController","op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/fragments","op":"replace","value":[{"text":"TMPrePurchaseViewController","kind":"identifier"}]},{"op":"replace","value":[{"text":"TMPrePurchaseViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1adjustTrackedUserAction(_:)\/title","value":"adjustTrackedUserAction:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"adjustTrackedUserAction:"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1adjustTrackedUserAction(_:)\/fragments","op":"replace"}]}]}