{"abstract":[{"text":"A delegate to call location methods on","type":"text"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/locationdelegate"]}],"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/locationDelegate","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"locationDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TMPrePurchaseLocationDelegate","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseLocationDelegate","preciseIdentifier":"s:23TicketmasterPrePurchase05TMPreC16LocationDelegateP","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"s:23TicketmasterPrePurchase05TMPreC14ViewControllerC16locationDelegateAA0dc8LocationH0_pSgvp","roleHeading":"Instance Property","modules":[{"name":"TicketmasterPrePurchase"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"locationDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TMPrePurchaseLocationDelegate","preciseIdentifier":"s:23TicketmasterPrePurchase05TMPreC16LocationDelegateP","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property","title":"locationDelegate"},"references":{"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/locationDelegate":{"abstract":[{"text":"A delegate to call location methods on","type":"text"}],"kind":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/locationdelegate","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/locationDelegate","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"locationDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:23TicketmasterPrePurchase05TMPreC16LocationDelegateP","text":"TMPrePurchaseLocationDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"locationDelegate"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Class used to display UI flow for discovering attractions and venues leading up to purchase flow."}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller","title":"TMPrePurchaseViewController","role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TMPrePurchaseViewController","kind":"identifier"}],"navigatorTitle":[{"text":"TMPrePurchaseViewController","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase":{"abstract":[],"role":"collection","type":"topic","title":"TicketmasterPrePurchase","url":"\/documentation\/ticketmasterprepurchase","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","kind":"symbol"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseLocationDelegate":{"abstract":[{"type":"text","text":"Protocol for communicating interactions about location"}],"kind":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaselocationdelegate","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseLocationDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMPrePurchaseLocationDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"TMPrePurchaseLocationDelegate","kind":"identifier"}],"title":"TMPrePurchaseLocationDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"TMPrePurchaseViewController","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/title"},{"op":"replace","value":[{"text":"TMPrePurchaseViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/fragments"},{"op":"replace","value":[{"text":"TMPrePurchaseViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/navigatorTitle"}]}]}