{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredStatusBarStyle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIStatusBarStyle","kind":"typeIdentifier","text":"UIStatusBarStyle"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/preferredstatusbarstyle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/preferredstatusbarstyle"]}],"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"TicketmasterPrePurchase"}],"roleHeading":"Instance Property","title":"preferredStatusBarStyle","navigatorTitle":[{"text":"preferredStatusBarStyle","kind":"identifier"}],"role":"symbol","externalID":"c:@M@TicketmasterPrePurchase@objc(cs)TMPrePurchaseViewController(py)preferredStatusBarStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredStatusBarStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStatusBarStyle","preciseIdentifier":"c:@E@UIStatusBarStyle"}],"symbolKind":"property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController"]]},"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/preferredStatusBarStyle","interfaceLanguage":"swift"},"references":{"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/preferredStatusBarStyle":{"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/preferredStatusBarStyle","title":"preferredStatusBarStyle","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"preferredStatusBarStyle"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredStatusBarStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStatusBarStyle","preciseIdentifier":"c:@E@UIStatusBarStyle"}],"role":"symbol","abstract":[],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/preferredstatusbarstyle"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","url":"\/documentation\/ticketmasterprepurchase","title":"TicketmasterPrePurchase","type":"topic","role":"collection","kind":"symbol","abstract":[]},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController":{"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TMPrePurchaseViewController","kind":"identifier"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller","navigatorTitle":[{"text":"TMPrePurchaseViewController","kind":"identifier"}],"title":"TMPrePurchaseViewController","abstract":[{"type":"text","text":"Class used to display UI flow for discovering attractions and venues leading up to purchase flow."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"preferredStatusBarStyle"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"preferredStatusBarStyle"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UIStatusBarStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIStatusBarStyle"},{"text":" ","kind":"text"},{"text":"preferredStatusBarStyle","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1preferredStatusBarStyle\/title","op":"replace","value":"preferredStatusBarStyle"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1preferredStatusBarStyle\/fragments","op":"replace","value":[{"kind":"identifier","text":"preferredStatusBarStyle"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/title","op":"replace","value":"TMPrePurchaseViewController"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"TMPrePurchaseViewController"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TMPrePurchaseViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}