{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"safariViewControllerDidFinish","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"controller"},{"text":": ","kind":"text"},{"text":"SFSafariViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SFSafariViewController"},{"kind":"text","text":")"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/safariviewcontrollerdidfinish(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/safariviewcontrollerdidfinish(_:)"]}],"metadata":{"roleHeading":"Instance Method","extendedModule":"TicketmasterPrePurchase","externalID":"c:@CM@TicketmasterPrePurchase@objc(cs)TMPrePurchaseViewController(im)safariViewControllerDidFinish:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"safariViewControllerDidFinish"},{"text":"(","kind":"text"},{"text":"SFSafariViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SFSafariViewController"},{"text":")","kind":"text"}],"modules":[{"name":"TicketmasterPrePurchase"}],"role":"symbol","title":"safariViewControllerDidFinish(_:)","navigatorTitle":[{"kind":"identifier","text":"safariViewControllerDidFinish:"}]},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/SFSafariViewControllerDelegate-Implementations"]]},"kind":"symbol","sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"SFSafariViewControllerDelegate.safariViewControllerDidFinish(_:)"},{"text":".","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/safariViewControllerDidFinish(_:)"},"references":{"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController":{"kind":"symbol","navigatorTitle":[{"text":"TMPrePurchaseViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"Class used to display UI flow for discovering attractions and venues leading up to purchase flow."}],"title":"TMPrePurchaseViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMPrePurchaseViewController"}],"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController","type":"topic","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/SFSafariViewControllerDelegate-Implementations":{"type":"topic","title":"SFSafariViewControllerDelegate Implementations","role":"collectionGroup","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/sfsafariviewcontrollerdelegate-implementations","abstract":[],"kind":"article","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/SFSafariViewControllerDelegate-Implementations"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/safariViewControllerDidFinish(_:)":{"title":"safariViewControllerDidFinish(_:)","kind":"symbol","role":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/safariviewcontrollerdidfinish(_:)","type":"topic","abstract":[],"navigatorTitle":[{"text":"safariViewControllerDidFinish:","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/safariViewControllerDidFinish(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"safariViewControllerDidFinish","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SFSafariViewController","preciseIdentifier":"c:objc(cs)SFSafariViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase":{"title":"TicketmasterPrePurchase","url":"\/documentation\/ticketmasterprepurchase","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"safariViewControllerDidFinish:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"safariViewControllerDidFinish:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"safariViewControllerDidFinish:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SFSafariViewController","text":"SFSafariViewController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"TMPrePurchaseViewController","op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/fragments","value":[{"kind":"identifier","text":"TMPrePurchaseViewController"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/navigatorTitle","op":"replace","value":[{"text":"TMPrePurchaseViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1safariViewControllerDidFinish(_:)\/title","value":"safariViewControllerDidFinish:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"safariViewControllerDidFinish:"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1safariViewControllerDidFinish(_:)\/fragments"}]}]}