{"sections":[],"metadata":{"role":"collectionGroup","title":"SFSafariViewControllerDelegate Implementations","modules":[{"name":"TicketmasterPrePurchase"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/sfsafariviewcontrollerdelegate-implementations"]},{"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/sfsafariviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/safariViewControllerDidFinish(_:)"],"generated":true}],"kind":"article","identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/SFSafariViewControllerDelegate-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController"]]},"references":{"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","url":"\/documentation\/ticketmasterprepurchase","title":"TicketmasterPrePurchase","abstract":[],"type":"topic","role":"collection","kind":"symbol"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController":{"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller","title":"TMPrePurchaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPrePurchaseViewController"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"TMPrePurchaseViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"Class used to display UI flow for discovering attractions and venues leading up to purchase flow."}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/safariViewControllerDidFinish(_:)":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/safariViewControllerDidFinish(_:)","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/safariviewcontrollerdidfinish(_:)","type":"topic","navigatorTitle":[{"text":"safariViewControllerDidFinish:","kind":"identifier"}],"title":"safariViewControllerDidFinish(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"safariViewControllerDidFinish"},{"text":"(","kind":"text"},{"text":"SFSafariViewController","preciseIdentifier":"c:objc(cs)SFSafariViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/safariViewControllerDidFinish(_:)"],"generated":true}],"op":"replace","path":"\/topicSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/title","value":"TMPrePurchaseViewController","op":"replace"},{"op":"replace","value":[{"text":"TMPrePurchaseViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/fragments"},{"value":"safariViewControllerDidFinish:","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1safariViewControllerDidFinish(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"safariViewControllerDidFinish:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1safariViewControllerDidFinish(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}