{"variants":[{"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/ualwebviewmessagehandlerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/ualwebviewmessagehandlerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/UALWebViewMessageHandlerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/adjustTrackedCommerceEvent(_:)","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/adjustTrackedPageView(_:)","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/adjustTrackedUserAction(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"TicketmasterPrePurchase"}],"role":"collectionGroup","title":"UALWebViewMessageHandlerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController"]]},"references":{"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController":{"role":"symbol","title":"TMPrePurchaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPrePurchaseViewController"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TMPrePurchaseViewController"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase":{"role":"collection","title":"TicketmasterPrePurchase","abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterprepurchase"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/adjustTrackedCommerceEvent(_:)":{"role":"symbol","title":"adjustTrackedCommerceEvent(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adjustTrackedCommerceEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UALCommerceEvent","preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALCommerceEvent"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UALCommerceEvent","preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALCommerceEvent"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/adjustTrackedCommerceEvent(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adjustTrackedCommerceEvent:"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/adjusttrackedcommerceevent(_:)"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/adjustTrackedPageView(_:)":{"role":"symbol","title":"adjustTrackedPageView(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adjustTrackedPageView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UALPageView","preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALPageView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UALPageView","preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALPageView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/adjustTrackedPageView(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adjustTrackedPageView:"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/adjusttrackedpageview(_:)"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/adjustTrackedUserAction(_:)":{"role":"symbol","title":"adjustTrackedUserAction(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adjustTrackedUserAction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UALUserAction","preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALUserAction"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UALUserAction","preciseIdentifier":"c:@M@TicketmasterFoundation@objc(cs)UALUserAction"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/adjustTrackedUserAction(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adjustTrackedUserAction:"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/adjusttrackeduseraction(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/adjustTrackedCommerceEvent(_:)","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/adjustTrackedPageView(_:)","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/adjustTrackedUserAction(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/title","value":"TMPrePurchaseViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/fragments","value":[{"kind":"identifier","text":"TMPrePurchaseViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1adjustTrackedCommerceEvent(_:)\/title","value":"adjustTrackedCommerceEvent:"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1adjustTrackedCommerceEvent(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adjustTrackedCommerceEvent:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1adjustTrackedPageView(_:)\/title","value":"adjustTrackedPageView:"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1adjustTrackedPageView(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adjustTrackedPageView:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1adjustTrackedUserAction(_:)\/title","value":"adjustTrackedUserAction:"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1adjustTrackedUserAction(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adjustTrackedUserAction:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}