{"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController"]]},"metadata":{"roleHeading":"Type Method","externalID":"s:23TicketmasterPrePurchase05TMPreC14ViewControllerC012venueDetailseF00G10Identifier12marketDomain20enclosingEnvironment10customFontACSS_0A10Foundation06MarketK0OAC09EnclosingM0OSo6UIFontCSgtFZ","title":"venueDetailsViewController(venueIdentifier:marketDomain:enclosingEnvironment:customFont:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"venueDetailsViewController","kind":"identifier"},{"kind":"text","text":"("},{"text":"venueIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"marketDomain","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TicketmasterFoundation@E@MarketDomain","text":"MarketDomain","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"enclosingEnvironment","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:23TicketmasterPrePurchase05TMPreC14ViewControllerC20EnclosingEnvironmentO","text":"EnclosingEnvironment","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"customFont"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont"},{"kind":"text","text":"?) -> "},{"text":"TMPrePurchaseViewController","preciseIdentifier":"c:@M@TicketmasterPrePurchase@objc(cs)TMPrePurchaseViewController","kind":"typeIdentifier"}],"extendedModule":"TicketmasterPrePurchase","symbolKind":"method","role":"symbol","modules":[{"name":"TicketmasterPrePurchase"}]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"venueDetailsViewController"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"venueIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"marketDomain","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TicketmasterFoundation@E@MarketDomain","kind":"typeIdentifier","text":"MarketDomain"},{"kind":"text","text":" = .US, "},{"text":"enclosingEnvironment","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"EnclosingEnvironment","preciseIdentifier":"s:23TicketmasterPrePurchase05TMPreC14ViewControllerC20EnclosingEnvironmentO","kind":"typeIdentifier","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/EnclosingEnvironment"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"customFont"},{"kind":"text","text":": "},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@TicketmasterPrePurchase@objc(cs)TMPrePurchaseViewController","kind":"typeIdentifier","text":"TMPrePurchaseViewController","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Identifier for the Venue","type":"text"}]}],"name":"venueIdentifier"},{"name":"marketDomain","content":[{"type":"paragraph","inlineContent":[{"text":"General area for the page content, defaults to .US","type":"text"}]}]},{"name":"enclosingEnvironment","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"How the page is expected to be put into the view hierarchy"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/venueDetailsViewController(venueIdentifier:marketDomain:enclosingEnvironment:customFont:)","interfaceLanguage":"swift"},"abstract":[{"text":"Convenience function for creating a Venue Details Page for a specific identifier","type":"text"}],"variants":[{"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/venuedetailsviewcontroller(venueidentifier:marketdomain:enclosingenvironment:customfont:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase":{"type":"topic","url":"\/documentation\/ticketmasterprepurchase","kind":"symbol","role":"collection","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","title":"TicketmasterPrePurchase","abstract":[]},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController":{"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller","abstract":[{"type":"text","text":"Class used to display UI flow for discovering attractions and venues leading up to purchase flow."}],"navigatorTitle":[{"text":"TMPrePurchaseViewController","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController","role":"symbol","kind":"symbol","title":"TMPrePurchaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPrePurchaseViewController"}],"type":"topic"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/venueDetailsViewController(venueIdentifier:marketDomain:enclosingEnvironment:customFont:)":{"title":"venueDetailsViewController(venueIdentifier:marketDomain:enclosingEnvironment:customFont:)","abstract":[{"text":"Convenience function for creating a Venue Details Page for a specific identifier","type":"text"}],"type":"topic","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/venuedetailsviewcontroller(venueidentifier:marketdomain:enclosingenvironment:customfont:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"venueDetailsViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"venueIdentifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"marketDomain","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MarketDomain","preciseIdentifier":"c:@M@TicketmasterFoundation@E@MarketDomain","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"enclosingEnvironment","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:23TicketmasterPrePurchase05TMPreC14ViewControllerC20EnclosingEnvironmentO","text":"EnclosingEnvironment","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"customFont","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":"?) -> "},{"text":"TMPrePurchaseViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterPrePurchase@objc(cs)TMPrePurchaseViewController"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/venueDetailsViewController(venueIdentifier:marketDomain:enclosingEnvironment:customFont:)","role":"symbol","kind":"symbol"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/EnclosingEnvironment":{"type":"topic","title":"TMPrePurchaseViewController.EnclosingEnvironment","role":"symbol","abstract":[{"text":"The environment that the ","type":"text"},{"type":"codeVoice","code":"TMPrePurchaseViewController"},{"text":" is expected to be displayed in.","type":"text"}],"navigatorTitle":[{"text":"EnclosingEnvironment","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/enclosingenvironment","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/EnclosingEnvironment","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"EnclosingEnvironment","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"TMPrePurchaseViewController","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/fragments","value":[{"kind":"identifier","text":"TMPrePurchaseViewController"}]},{"value":[{"text":"TMPrePurchaseViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/navigatorTitle"}]}]}