{"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"webView:didStartProvisionalNavigation:"}],"title":"webView(_:didStartProvisionalNavigation:)","modules":[{"name":"TicketmasterPrePurchase"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"webView","kind":"identifier"},{"kind":"text","text":"("},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":", ","kind":"text"},{"text":"didStartProvisionalNavigation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigation","preciseIdentifier":"c:objc(cs)WKNavigation"},{"text":"!)","kind":"text"}],"symbolKind":"method","role":"symbol","externalID":"c:@CM@TicketmasterPrePurchase@objc(cs)TMPrePurchaseViewController(im)webView:didStartProvisionalNavigation:","extendedModule":"TicketmasterPrePurchase","roleHeading":"Instance Method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"webView"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"webView","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartProvisionalNavigation"},{"text":" ","kind":"text"},{"text":"navigation","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigation","text":"WKNavigation"},{"kind":"text","text":"!)"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"WKNavigationDelegate.webView(_:didStartProvisionalNavigation:)"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/webview(_:didstartprovisionalnavigation:)"]},{"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/webview(_:didstartprovisionalnavigation:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/WKNavigationDelegate-Implementations"]]},"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/webView(_:didStartProvisionalNavigation:)","interfaceLanguage":"swift"},"references":{"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController":{"kind":"symbol","navigatorTitle":[{"text":"TMPrePurchaseViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"Class used to display UI flow for discovering attractions and venues leading up to purchase flow."}],"title":"TMPrePurchaseViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMPrePurchaseViewController"}],"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController","type":"topic","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase":{"title":"TicketmasterPrePurchase","url":"\/documentation\/ticketmasterprepurchase","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","abstract":[],"role":"collection","kind":"symbol"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/WKNavigationDelegate-Implementations":{"kind":"article","type":"topic","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/wknavigationdelegate-implementations","title":"WKNavigationDelegate Implementations","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/WKNavigationDelegate-Implementations"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/webView(_:didStartProvisionalNavigation:)":{"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/webview(_:didstartprovisionalnavigation:)","abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/webView(_:didStartProvisionalNavigation:)","title":"webView(_:didStartProvisionalNavigation:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"text":"didStartProvisionalNavigation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigation","text":"WKNavigation"},{"kind":"text","text":"!)"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"webView:didStartProvisionalNavigation:"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"webView:didStartProvisionalNavigation:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:didStartProvisionalNavigation:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"webView:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"webView"},{"text":" ","kind":"text"},{"text":"didStartProvisionalNavigation:","kind":"identifier"},{"kind":"text","text":"("},{"text":"WKNavigation","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigation"},{"text":" *) ","kind":"text"},{"text":"navigation","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/title","value":"TMPrePurchaseViewController","op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/fragments","op":"replace","value":[{"text":"TMPrePurchaseViewController","kind":"identifier"}]},{"op":"replace","value":[{"text":"TMPrePurchaseViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/navigatorTitle"},{"op":"replace","value":"webView:didStartProvisionalNavigation:","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1webView(_:didStartProvisionalNavigation:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1webView(_:didStartProvisionalNavigation:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:didStartProvisionalNavigation:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}