{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController"]]},"variants":[{"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/webview(_:decidepolicyfor:decisionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/webview(_:decidepolicyfor:decisionhandler:)"]}],"metadata":{"externalID":"c:@CM@TicketmasterPrePurchase@objc(cs)TMPrePurchaseViewController(im)webView:decidePolicyForNavigationAction:decisionHandler:","roleHeading":"Instance Method","modules":[{"name":"TicketmasterPrePurchase"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"decidePolicyFor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigationAction","text":"WKNavigationAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decisionHandler"},{"kind":"text","text":": ("},{"text":"WKNavigationActionPolicy","preciseIdentifier":"c:@E@WKNavigationActionPolicy","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"webView:decidePolicyForNavigationAction:decisionHandler:","kind":"identifier"}],"extendedModule":"TicketmasterPrePurchase","symbolKind":"method","title":"webView(_:decidePolicyFor:decisionHandler:)"},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"code":"WKNavigationDelegate.webView(_:decidePolicyFor:decisionHandler:)","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"webView"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier","text":"WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decidePolicyFor"},{"kind":"text","text":" "},{"kind":"internalParam","text":"navigationAction"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)WKNavigationAction","text":"WKNavigationAction","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"decisionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"WKNavigationActionPolicy","preciseIdentifier":"c:@E@WKNavigationActionPolicy"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]}]}],"sections":[],"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/webView(_:decidePolicyFor:decisionHandler:)","interfaceLanguage":"swift"},"references":{"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/webView(_:decidePolicyFor:decisionHandler:)":{"role":"symbol","title":"webView(_:decidePolicyFor:decisionHandler:)","navigatorTitle":[{"kind":"identifier","text":"webView:decidePolicyForNavigationAction:decisionHandler:"}],"abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"webView"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"decidePolicyFor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKNavigationAction","text":"WKNavigationAction","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"decisionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"WKNavigationActionPolicy","preciseIdentifier":"c:@E@WKNavigationActionPolicy"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/webview(_:decidepolicyfor:decisionhandler:)","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/webView(_:decidePolicyFor:decisionHandler:)"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Class used to display UI flow for discovering attractions and venues leading up to purchase flow."}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller","title":"TMPrePurchaseViewController","role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TMPrePurchaseViewController","kind":"identifier"}],"navigatorTitle":[{"text":"TMPrePurchaseViewController","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase":{"kind":"symbol","abstract":[],"type":"topic","title":"TicketmasterPrePurchase","url":"\/documentation\/ticketmasterprepurchase","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"webView:decidePolicyForNavigationAction:decisionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:decidePolicyForNavigationAction:decisionHandler:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"webView:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier","text":"WKWebView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"webView"},{"kind":"text","text":" "},{"kind":"identifier","text":"decidePolicyForNavigationAction:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKNavigationAction","text":"WKNavigationAction","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"navigationAction","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"decisionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"preciseIdentifier":"c:@E@WKNavigationActionPolicy","text":"WKNavigationActionPolicy","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"decisionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1webView(_:decidePolicyFor:decisionHandler:)\/title","op":"replace","value":"webView:decidePolicyForNavigationAction:decisionHandler:"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1webView(_:decidePolicyFor:decisionHandler:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"webView:decidePolicyForNavigationAction:decisionHandler:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/title","op":"replace","value":"TMPrePurchaseViewController"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/fragments","op":"replace","value":[{"text":"TMPrePurchaseViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/navigatorTitle","op":"replace","value":[{"text":"TMPrePurchaseViewController","kind":"identifier"}]}]}]}