{"topicSections":[{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/webView(_:decidePolicyFor:decisionHandler:)","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/webView(_:didFail:withError:)","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/webView(_:didFailProvisionalNavigation:withError:)","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/webView(_:didFinish:)","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/webView(_:didStartProvisionalNavigation:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/WKNavigationDelegate-Implementations","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/wknavigationdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/wknavigationdelegate-implementations"]}],"metadata":{"roleHeading":"API Collection","modules":[{"name":"TicketmasterPrePurchase"}],"role":"collectionGroup","title":"WKNavigationDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController"]]},"kind":"article","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/webView(_:didFailProvisionalNavigation:withError:)":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/webView(_:didFailProvisionalNavigation:withError:)","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/webview(_:didfailprovisionalnavigation:witherror:)","title":"webView(_:didFailProvisionalNavigation:withError:)","type":"topic","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFailProvisionalNavigation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKNavigation","text":"WKNavigation","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"withError","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"webView:didFailProvisionalNavigation:withError:","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/webView(_:didFinish:)":{"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/webView(_:didFinish:)","title":"webView(_:didFinish:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"webView:didFinishNavigation:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier","text":"WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinish"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)WKNavigation","kind":"typeIdentifier","text":"WKNavigation"},{"kind":"text","text":"!)"}],"role":"symbol","abstract":[],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/webview(_:didfinish:)"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/webView(_:decidePolicyFor:decisionHandler:)":{"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/webView(_:decidePolicyFor:decisionHandler:)","title":"webView(_:decidePolicyFor:decisionHandler:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"webView:decidePolicyForNavigationAction:decisionHandler:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"decidePolicyFor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKNavigationAction","text":"WKNavigationAction","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"decisionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@E@WKNavigationActionPolicy","text":"WKNavigationActionPolicy","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","abstract":[],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/webview(_:decidepolicyfor:decisionhandler:)"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/webView(_:didStartProvisionalNavigation:)":{"abstract":[],"kind":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/webview(_:didstartprovisionalnavigation:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartProvisionalNavigation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigation","preciseIdentifier":"c:objc(cs)WKNavigation"},{"kind":"text","text":"!)"}],"title":"webView(_:didStartProvisionalNavigation:)","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/webView(_:didStartProvisionalNavigation:)","navigatorTitle":[{"kind":"identifier","text":"webView:didStartProvisionalNavigation:"}]},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/webView(_:didFail:withError:)":{"abstract":[],"title":"webView(_:didFail:withError:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"webView:didFailNavigation:withError:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFail","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WKNavigation","preciseIdentifier":"c:objc(cs)WKNavigation","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"withError","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/webview(_:didfail:witherror:)","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/webView(_:didFail:withError:)"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController":{"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TMPrePurchaseViewController","kind":"identifier"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller","navigatorTitle":[{"text":"TMPrePurchaseViewController","kind":"identifier"}],"title":"TMPrePurchaseViewController","abstract":[{"type":"text","text":"Class used to display UI flow for discovering attractions and venues leading up to purchase flow."}]},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","url":"\/documentation\/ticketmasterprepurchase","title":"TicketmasterPrePurchase","type":"topic","role":"collection","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/webView(_:decidePolicyFor:decisionHandler:)","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/webView(_:didFail:withError:)","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/webView(_:didFailProvisionalNavigation:withError:)","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/webView(_:didFinish:)","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/webView(_:didStartProvisionalNavigation:)"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1webView(_:didFailProvisionalNavigation:withError:)\/title","op":"replace","value":"webView:didFailProvisionalNavigation:withError:"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1webView(_:didFailProvisionalNavigation:withError:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:didFailProvisionalNavigation:withError:"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1webView(_:didFinish:)\/title","op":"replace","value":"webView:didFinishNavigation:"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1webView(_:didFinish:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:didFinishNavigation:"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1webView(_:decidePolicyFor:decisionHandler:)\/title","op":"replace","value":"webView:decidePolicyForNavigationAction:decisionHandler:"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1webView(_:decidePolicyFor:decisionHandler:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:decidePolicyForNavigationAction:decisionHandler:"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1webView(_:didStartProvisionalNavigation:)\/title","op":"replace","value":"webView:didStartProvisionalNavigation:"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1webView(_:didStartProvisionalNavigation:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:didStartProvisionalNavigation:"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1webView(_:didFail:withError:)\/title","op":"replace","value":"webView:didFailNavigation:withError:"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1webView(_:didFail:withError:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:didFailNavigation:withError:"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/title","op":"replace","value":"TMPrePurchaseViewController"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"TMPrePurchaseViewController"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TMPrePurchaseViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}