{"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/userContentController(_:didReceive:)"],"generated":true}],"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/WKScriptMessageHandler-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController"]]},"metadata":{"role":"collectionGroup","modules":[{"name":"TicketmasterPrePurchase"}],"title":"WKScriptMessageHandler Implementations"},"kind":"article","variants":[{"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/wkscriptmessagehandler-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/wkscriptmessagehandler-implementations"]}],"sections":[],"references":{"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/userContentController(_:didReceive:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userContentController","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)WKUserContentController","text":"WKUserContentController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didReceive","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKScriptMessage","text":"WKScriptMessage"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/userContentController(_:didReceive:)","navigatorTitle":[{"kind":"identifier","text":"userContentController:didReceiveScriptMessage:"}],"title":"userContentController(_:didReceive:)","kind":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/usercontentcontroller(_:didreceive:)","type":"topic","abstract":[]},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","title":"TicketmasterPrePurchase","type":"topic","role":"collection","url":"\/documentation\/ticketmasterprepurchase"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController","title":"TMPrePurchaseViewController","navigatorTitle":[{"text":"TMPrePurchaseViewController","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMPrePurchaseViewController"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Class used to display UI flow for discovering attractions and venues leading up to purchase flow.","type":"text"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":[{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/userContentController(_:didReceive:)"],"generated":true,"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":"userContentController:didReceiveScriptMessage:","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1userContentController(_:didReceive:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1userContentController(_:didReceive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userContentController:didReceiveScriptMessage:"}]},{"op":"replace","value":"TMPrePurchaseViewController","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/title"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/fragments","value":[{"text":"TMPrePurchaseViewController","kind":"identifier"}],"op":"replace"}]}]}