{"kind":"article","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/WKUIDelegate-Implementations"},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController"]]},"metadata":{"modules":[{"name":"TicketmasterPrePurchase"}],"title":"WKUIDelegate Implementations","role":"collectionGroup","roleHeading":"API Collection"},"topicSections":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/webView(_:createWebViewWith:for:windowFeatures:)"],"generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/wkuidelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/wkuidelegate-implementations"]}],"references":{"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMPrePurchaseViewController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller","abstract":[{"text":"Class used to display UI flow for discovering attractions and venues leading up to purchase flow.","type":"text"}],"role":"symbol","title":"TMPrePurchaseViewController","type":"topic","navigatorTitle":[{"text":"TMPrePurchaseViewController","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","title":"TicketmasterPrePurchase","kind":"symbol","role":"collection","type":"topic","abstract":[],"url":"\/documentation\/ticketmasterprepurchase"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController/webView(_:createWebViewWith:for:windowFeatures:)":{"navigatorTitle":[{"kind":"identifier","text":"webView:createWebViewWithConfiguration:forNavigationAction:windowFeatures:"}],"type":"topic","title":"webView(_:createWebViewWith:for:windowFeatures:)","abstract":[],"role":"symbol","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller\/webview(_:createwebviewwith:for:windowfeatures:)","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/webView(_:createWebViewWith:for:windowFeatures:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"createWebViewWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebViewConfiguration","text":"WKWebViewConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigationAction","text":"WKNavigationAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"windowFeatures"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWindowFeatures","text":"WKWindowFeatures"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView"},{"kind":"text","text":"?"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController\/webView(_:createWebViewWith:for:windowFeatures:)"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/title","value":"TMPrePurchaseViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/fragments","value":[{"kind":"identifier","text":"TMPrePurchaseViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/navigatorTitle","value":[{"text":"TMPrePurchaseViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1webView(_:createWebViewWith:for:windowFeatures:)\/title","value":"webView:createWebViewWithConfiguration:forNavigationAction:windowFeatures:"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController~1webView(_:createWebViewWith:for:windowFeatures:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"webView:createWebViewWithConfiguration:forNavigationAction:windowFeatures:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}