{"metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV14HeaderOverrideV19titleLabelTextColorSo7UIColorCSgvp","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"titleLabelTextColor"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"TicketmasterTickets"}],"title":"titleLabelTextColor","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/HeaderOverride\/titleLabelTextColor"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"titleLabelTextColor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule\/headeroverride\/titlelabeltextcolor"]}],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/HeaderOverride"]]},"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"type":"topic","abstract":[{"text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes.","type":"text"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","role":"collection","title":"TicketmasterTickets","kind":"symbol","url":"\/documentation\/ticketmastertickets"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","role":"symbol","kind":"symbol","type":"topic","title":"TMTicketsModule","navigatorTitle":[{"text":"TMTicketsModule","kind":"identifier"}],"abstract":[{"text":"create a custom module to be displayed underneath the user’s list of Tickets on the Tickets listing page","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTicketsModule"}],"url":"\/documentation\/ticketmastertickets\/tmticketsmodule"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule/HeaderOverride":{"role":"symbol","kind":"symbol","url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule\/headeroverride","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/HeaderOverride","navigatorTitle":[{"text":"HeaderOverride","kind":"identifier"}],"title":"TMTicketsPrebuiltModule.HeaderOverride","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeaderOverride"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule/HeaderOverride/titleLabelTextColor":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/HeaderOverride\/titleLabelTextColor","role":"symbol","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"titleLabelTextColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?","kind":"text"}],"url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule\/headeroverride\/titlelabeltextcolor","title":"titleLabelTextColor"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule":{"abstract":[{"type":"text","text":"useful pre-built "},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","isActive":true},{"text":" for the Tickets listing page","type":"text"}],"type":"topic","title":"TMTicketsPrebuiltModule","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule","url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule","navigatorTitle":[{"kind":"identifier","text":"TMTicketsPrebuiltModule"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsPrebuiltModule"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/title","value":"TMTicketsModule","op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/fragments","op":"replace","value":[{"text":"TMTicketsModule","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/navigatorTitle","value":[{"kind":"identifier","text":"TMTicketsModule"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}