{"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/ModuleName"]]},"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/ModuleName\/shareEventOnSocialMedia","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule\/modulename\/shareeventonsocialmedia"]}],"metadata":{"symbolKind":"case","title":"TMTicketsPrebuiltModule.ModuleName.shareEventOnSocialMedia","externalID":"s:19TicketmasterTickets23TMTicketsPrebuiltModuleV0E4NameO23shareEventOnSocialMediayA2EmF","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"shareEventOnSocialMedia"}],"modules":[{"name":"TicketmasterTickets"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shareEventOnSocialMedia","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule":{"abstract":[{"text":"useful pre-built ","type":"text"},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","isActive":true,"type":"reference"},{"text":" for the Tickets listing page","type":"text"}],"title":"TMTicketsPrebuiltModule","url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule","kind":"symbol","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTicketsPrebuiltModule"}],"navigatorTitle":[{"kind":"identifier","text":"TMTicketsPrebuiltModule"}],"role":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule/ModuleName/shareEventOnSocialMedia":{"type":"topic","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shareEventOnSocialMedia","kind":"identifier"}],"kind":"symbol","title":"TMTicketsPrebuiltModule.ModuleName.shareEventOnSocialMedia","url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule\/modulename\/shareeventonsocialmedia","role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/ModuleName\/shareEventOnSocialMedia"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule/ModuleName":{"abstract":[],"title":"TMTicketsPrebuiltModule.ModuleName","url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule\/modulename","kind":"symbol","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule\/ModuleName","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModuleName"}],"navigatorTitle":[{"kind":"identifier","text":"ModuleName"}],"role":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"title":"TicketmasterTickets","type":"topic","url":"\/documentation\/ticketmastertickets","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","role":"collection","kind":"symbol","abstract":[{"text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes.","type":"text"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTicketsModule"}],"navigatorTitle":[{"kind":"identifier","text":"TMTicketsModule"}],"title":"TMTicketsModule","type":"topic","url":"\/documentation\/ticketmastertickets\/tmticketsmodule","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"create a custom module to be displayed underneath the user’s list of Tickets on the Tickets listing page"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/title","value":"TMTicketsModule"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/fragments","value":[{"kind":"identifier","text":"TMTicketsModule"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/navigatorTitle","value":[{"kind":"identifier","text":"TMTicketsModule"}]}]}]}