{"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brandColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"symbolKind":"property","title":"brandColor","externalID":"s:20TicketmasterPurchase10TMPurchaseC10brandColorSo7UIColorCvp","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"TicketmasterPurchase"}]},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase"]]},"identifier":{"url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/brandColor","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/ticketmasterpurchase\/tmpurchase\/brandcolor"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","abstract":[{"type":"text","text":"The color that will be applied to UI elements in instances of "},{"type":"codeVoice","code":"TMPurchaseNavigationController"},{"type":"text","text":"."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"brandColor"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"languages":["swift"]}]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Defaults to ","type":"text"},{"type":"codeVoice","code":"0x009CDE"},{"type":"text","text":", otherwise known as “Ticketmaster blue”."},{"type":"text","text":" "},{"text":"This property only affects the color of the app navigation bars, not the web content","type":"text"}]}],"kind":"content"}],"references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"kind":"symbol","role":"collection","title":"TicketmasterPurchase","url":"\/documentation\/ticketmasterpurchase","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","type":"topic","abstract":[]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchase":{"kind":"symbol","role":"symbol","title":"TMPurchase","url":"\/documentation\/ticketmasterpurchase\/tmpurchase","navigatorTitle":[{"kind":"identifier","text":"TMPurchase"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPurchase"}],"abstract":[{"type":"text","text":"A class that stores the global configuration for the TicketmasterPurchase SDK."}]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchase/brandColor":{"url":"\/documentation\/ticketmasterpurchase\/tmpurchase\/brandcolor","title":"brandColor","type":"topic","role":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/brandColor","kind":"symbol","abstract":[{"type":"text","text":"The color that will be applied to UI elements in instances of "},{"type":"codeVoice","code":"TMPurchaseNavigationController"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"brandColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchase\/title","value":"TMPurchase","op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchase\/fragments","value":[{"kind":"identifier","text":"TMPurchase"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchase\/navigatorTitle","value":[{"kind":"identifier","text":"TMPurchase"}]}]}]}