{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"module"},{"text":"(","kind":"text"},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedEvent","text":"TMPurchasedEvent","preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"module"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule","text":"TMTicketsModule","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType\/module(event:module:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"a Pre-Built or Custom Module "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule"},{"type":"text","text":" built for a specific "},{"isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedEvent","type":"reference"}],"metadata":{"modules":[{"name":"TicketmasterTickets"}],"title":"TMTickets.Analytics.MetadataType.module(event:module:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:19TicketmasterTickets9TMTicketsC9AnalyticsV12MetadataTypeO6moduleyAgA16TMPurchasedEventV_AA0C6ModuleCtcAGmF","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"module","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TMPurchasedEvent","preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV"},{"text":", ","kind":"text"},{"text":"module","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule","text":"TMTicketsModule"},{"text":")","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType"]]},"variants":[{"paths":["\/documentation\/ticketmastertickets\/tmtickets\/analytics\/metadatatype\/module(event:module:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"kind":"symbol","type":"topic","abstract":[{"text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes.","type":"text"}],"title":"TicketmasterTickets","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","url":"\/documentation\/ticketmastertickets","role":"collection"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/MetadataType/module(event:module:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"module"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"text":"TMPurchasedEvent","kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV"},{"text":", ","kind":"text"},{"text":"module","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule","text":"TMTicketsModule"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType\/module(event:module:)","type":"topic","abstract":[{"type":"text","text":"a Pre-Built or Custom Module "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule"},{"type":"text","text":" built for a specific "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedEvent"}],"title":"TMTickets.Analytics.MetadataType.module(event:module:)","kind":"symbol","url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/metadatatype\/module(event:module:)"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule":{"navigatorTitle":[{"text":"TMTicketsModule","kind":"identifier"}],"url":"\/documentation\/ticketmastertickets\/tmticketsmodule","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTicketsModule"}],"title":"TMTicketsModule","abstract":[{"type":"text","text":"create a custom module to be displayed underneath the user’s list of Tickets on the Tickets listing page"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets":{"title":"TMTickets","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets","abstract":[{"type":"text","text":"main class of Tickets SDK, intended to be used as singleton"}],"navigatorTitle":[{"kind":"identifier","text":"TMTickets"}],"role":"symbol","kind":"symbol","url":"\/documentation\/ticketmastertickets\/tmtickets","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMTickets","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics":{"kind":"symbol","navigatorTitle":[{"text":"Analytics","kind":"identifier"}],"role":"symbol","abstract":[{"text":"analytics for User behavior","type":"text"}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics","type":"topic","title":"TMTickets.Analytics","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Analytics","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMPurchasedEvent":{"url":"\/documentation\/ticketmastertickets\/tmpurchasedevent","abstract":[{"text":"an Event purchased by the User, containing Event Information, Orders, and Tickets","type":"text"}],"title":"TMPurchasedEvent","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TMPurchasedEvent"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedEvent","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"TMPurchasedEvent","kind":"identifier"}],"kind":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/MetadataType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MetadataType"}],"kind":"symbol","navigatorTitle":[{"text":"MetadataType","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType","title":"TMTickets.Analytics.MetadataType","role":"symbol","url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/metadatatype","abstract":[{"type":"text","text":"Swift enum with Associated Values of Event and Ticket metadata"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/title","value":"TMTicketsModule"},{"value":[{"text":"TMTicketsModule","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"TMTicketsModule"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/navigatorTitle"},{"op":"replace","value":"TMTickets","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/title"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/fragments","value":[{"text":"TMTickets","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TMTickets"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}