{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"moduleButton","kind":"identifier"},{"kind":"text","text":"("},{"text":"event","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedEvent","preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV","kind":"typeIdentifier","text":"TMPurchasedEvent"},{"kind":"text","text":", "},{"text":"module","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","kind":"typeIdentifier","text":"TMTicketsModule"},{"kind":"text","text":", "},{"kind":"externalParam","text":"button"},{"kind":"text","text":": "},{"text":"TMTicketsModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule"},{"kind":"text","text":"."},{"text":"ActionButton","preciseIdentifier":"s:19TicketmasterTickets15TMTicketsModuleC12ActionButtonC","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/ActionButton","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"modules":[{"name":"TicketmasterTickets"}],"externalID":"s:19TicketmasterTickets9TMTicketsC9AnalyticsV12MetadataTypeO12moduleButtonyAgA16TMPurchasedEventV_AA0C6ModuleCAL06ActionH0CtcAGmF","title":"TMTickets.Analytics.MetadataType.moduleButton(event:module:button:)","role":"symbol","roleHeading":"Case","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"moduleButton"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"event"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV","kind":"typeIdentifier","text":"TMPurchasedEvent"},{"text":", ","kind":"text"},{"text":"module","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule","kind":"typeIdentifier","text":"TMTicketsModule"},{"text":", ","kind":"text"},{"text":"button","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule","text":"TMTicketsModule","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"ActionButton","preciseIdentifier":"s:19TicketmasterTickets15TMTicketsModuleC12ActionButtonC","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmastertickets\/tmtickets\/analytics\/metadatatype\/modulebutton(event:module:button:)"]}],"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType\/moduleButton(event:module:button:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"a Pre-Built or Custom Module "},{"isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","type":"reference"},{"text":" and ","type":"text"},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/ActionButton","type":"reference","isActive":true},{"type":"text","text":" built for a specific "},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedEvent","isActive":true,"type":"reference"}],"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule/ActionButton":{"role":"symbol","title":"TMTicketsModule.ActionButton","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ActionButton","kind":"identifier"}],"url":"\/documentation\/ticketmastertickets\/tmticketsmodule\/actionbutton","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ActionButton"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/ActionButton"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics":{"kind":"symbol","title":"TMTickets.Analytics","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Analytics"}],"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics","abstract":[{"text":"analytics for User behavior","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Analytics"}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMPurchasedEvent":{"kind":"symbol","abstract":[{"type":"text","text":"an Event purchased by the User, containing Event Information, Orders, and Tickets"}],"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedEvent","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPurchasedEvent"}],"type":"topic","title":"TMPurchasedEvent","navigatorTitle":[{"text":"TMPurchasedEvent","kind":"identifier"}],"url":"\/documentation\/ticketmastertickets\/tmpurchasedevent"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule":{"title":"TMTicketsModule","abstract":[{"text":"create a custom module to be displayed underneath the user’s list of Tickets on the Tickets listing page","type":"text"}],"url":"\/documentation\/ticketmastertickets\/tmticketsmodule","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMTicketsModule","kind":"identifier"}],"navigatorTitle":[{"text":"TMTicketsModule","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/MetadataType/moduleButton(event:module:button:)":{"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType\/moduleButton(event:module:button:)","title":"TMTickets.Analytics.MetadataType.moduleButton(event:module:button:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moduleButton","kind":"identifier"},{"kind":"text","text":"("},{"text":"event","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:19TicketmasterTickets16TMPurchasedEventV","text":"TMPurchasedEvent"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"module"},{"kind":"text","text":": "},{"text":"TMTicketsModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule"},{"text":", ","kind":"text"},{"text":"button","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TMTicketsModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterTickets@objc(cs)TMTicketsModule"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"ActionButton","preciseIdentifier":"s:19TicketmasterTickets15TMTicketsModuleC12ActionButtonC"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"a Pre-Built or Custom Module "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule"},{"text":" and ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule\/ActionButton"},{"type":"text","text":" built for a specific "},{"isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedEvent","type":"reference"}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/metadatatype\/modulebutton(event:module:button:)"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes."}],"url":"\/documentation\/ticketmastertickets","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","title":"TicketmasterTickets","role":"collection"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/Analytics/MetadataType":{"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/Analytics\/MetadataType","title":"TMTickets.Analytics.MetadataType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MetadataType","kind":"identifier"}],"navigatorTitle":[{"text":"MetadataType","kind":"identifier"}],"abstract":[{"type":"text","text":"Swift enum with Associated Values of Event and Ticket metadata"}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/analytics\/metadatatype"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets":{"abstract":[{"text":"main class of Tickets SDK, intended to be used as singleton","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMTickets","kind":"identifier"}],"title":"TMTickets","kind":"symbol","url":"\/documentation\/ticketmastertickets\/tmtickets","role":"symbol","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets","navigatorTitle":[{"kind":"identifier","text":"TMTickets"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"TMTicketsModule","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/title"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/fragments","value":[{"text":"TMTicketsModule","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"TMTickets","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/fragments","value":[{"kind":"identifier","text":"TMTickets"}]}]}]}