{"abstract":[{"text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","interfaceLanguage":"swift"},"primaryContentSections":[{"content":[{"text":"Overview","type":"heading","level":2,"anchor":"Overview"},{"inlineContent":[{"text":"See ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets","isActive":true}],"type":"paragraph"}],"kind":"content"}],"metadata":{"externalID":"TicketmasterTickets","title":"TicketmasterTickets","symbolKind":"module","role":"collection","modules":[{"name":"TicketmasterTickets"}],"roleHeading":"Framework"},"hierarchy":{"paths":[[]]},"topicSections":[{"anchor":"Custom-Modules","title":"Custom Modules","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleDelegate"]},{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/CustomModules"],"generated":true,"anchor":"Articles","title":"Articles"},{"generated":true,"identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController"],"title":"Classes","anchor":"Classes"},{"anchor":"Protocols","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsAnalyticsDelegate","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsOrderDelegate"],"title":"Protocols","generated":true},{"anchor":"Structures","title":"Structures","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedEvent","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedEventInfo","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedOrder","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedTicket"],"generated":true},{"generated":true,"anchor":"Extended-Modules","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/UIKit"],"title":"Extended Modules"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmastertickets"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ticketmastertickets"]}],"kind":"symbol","references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsViewController":{"abstract":[{"text":"this class wraps the ","type":"text"},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView","type":"reference","isActive":true},{"type":"text","text":" in a "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" for ease of use"}],"title":"TMTicketsViewController","url":"\/documentation\/ticketmastertickets\/tmticketsviewcontroller","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsViewController"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"TMTicketsViewController","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsView"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView","title":"TMTicketsView","url":"\/documentation\/ticketmastertickets\/tmticketsview","type":"topic","role":"symbol","navigatorTitle":[{"text":"TMTicketsView","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"use to render Tickets SDK as a UIView embedded inside of your own UIViewController","type":"text"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"type":"topic","url":"\/documentation\/ticketmastertickets","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes."}],"title":"TicketmasterTickets"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleDelegate":{"title":"TMTicketsModuleDelegate","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleDelegate","type":"topic","navigatorTitle":[{"text":"TMTicketsModuleDelegate","kind":"identifier"}],"url":"\/documentation\/ticketmastertickets\/tmticketsmoduledelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"TMTicketsModuleDelegate","kind":"identifier"}],"role":"symbol","abstract":[{"text":"optional delegate to implement prebuilt and custom ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","isActive":true},{"type":"text","text":" to be rendered on the Tickets listing page"}],"kind":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMPurchasedEventInfo":{"abstract":[{"text":"information about Event purchased by the User","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"TMPurchasedEventInfo","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedEventInfo","title":"TMPurchasedEventInfo","kind":"symbol","url":"\/documentation\/ticketmastertickets\/tmpurchasedeventinfo","role":"symbol","navigatorTitle":[{"text":"TMPurchasedEventInfo","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMPurchasedOrder":{"kind":"symbol","abstract":[{"text":"a specific order for an Event containing one or more Tickets","type":"text"}],"url":"\/documentation\/ticketmastertickets\/tmpurchasedorder","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedOrder","title":"TMPurchasedOrder","role":"symbol","type":"topic","navigatorTitle":[{"text":"TMPurchasedOrder","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TMPurchasedOrder","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMPurchasedTicket":{"abstract":[{"type":"text","text":"a single ticket (typically a single seat, unless general admission)"}],"navigatorTitle":[{"text":"TMPurchasedTicket","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedTicket","role":"symbol","url":"\/documentation\/ticketmastertickets\/tmpurchasedticket","title":"TMPurchasedTicket","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPurchasedTicket"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModuleHeaderView":{"type":"topic","url":"\/documentation\/ticketmastertickets\/tmticketsmoduleheaderview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsModuleHeaderView"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView","navigatorTitle":[{"kind":"identifier","text":"TMTicketsModuleHeaderView"}],"abstract":[{"type":"text","text":"quickly build a UIView for "},{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView","isActive":true,"type":"reference"}],"role":"symbol","title":"TMTicketsModuleHeaderView"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsModule":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMTicketsModule"}],"navigatorTitle":[{"kind":"identifier","text":"TMTicketsModule"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","type":"topic","title":"TMTicketsModule","url":"\/documentation\/ticketmastertickets\/tmticketsmodule","abstract":[{"text":"create a custom module to be displayed underneath the user’s list of Tickets on the Tickets listing page","type":"text"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMPurchasedEvent":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TMPurchasedEvent"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPurchasedEvent"}],"title":"TMPurchasedEvent","url":"\/documentation\/ticketmastertickets\/tmpurchasedevent","abstract":[{"type":"text","text":"an Event purchased by the User, containing Event Information, Orders, and Tickets"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMPurchasedEvent","type":"topic","kind":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsAnalyticsDelegate":{"title":"TMTicketsAnalyticsDelegate","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsAnalyticsDelegate","role":"symbol","abstract":[{"type":"text","text":"optional delegate to be informed of User behavior"}],"url":"\/documentation\/ticketmastertickets\/tmticketsanalyticsdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMTicketsAnalyticsDelegate","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TMTicketsAnalyticsDelegate"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/UIKit":{"url":"\/documentation\/ticketmastertickets\/uikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/UIKit","title":"UIKit","type":"topic","role":"collection"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TicketmasterTicketsVersionNumber":{"title":"TicketmasterTicketsVersionNumber","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TicketmasterTicketsVersionNumber","role":"symbol","abstract":[{"type":"text","text":"Project version number for TicketmasterTickets."}],"url":"\/documentation\/ticketmastertickets\/ticketmasterticketsversionnumber","fragments":[{"kind":"identifier","text":"TicketmasterTicketsVersionNumber"}],"type":"topic"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets":{"title":"TMTickets","navigatorTitle":[{"text":"TMTickets","kind":"identifier"}],"url":"\/documentation\/ticketmastertickets\/tmtickets","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TMTickets","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets","type":"topic","role":"symbol","abstract":[{"type":"text","text":"main class of Tickets SDK, intended to be used as singleton"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsPrebuiltModule":{"abstract":[{"text":"useful pre-built ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","type":"reference"},{"text":" for the Tickets listing page","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMTicketsPrebuiltModule","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsPrebuiltModule","title":"TMTicketsPrebuiltModule","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TMTicketsPrebuiltModule"}],"url":"\/documentation\/ticketmastertickets\/tmticketsprebuiltmodule"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTicketsOrderDelegate":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMTicketsOrderDelegate"}],"url":"\/documentation\/ticketmastertickets\/tmticketsorderdelegate","role":"symbol","abstract":[{"type":"text","text":"optional delegate to be informed of non-analytics User-actions"}],"title":"TMTicketsOrderDelegate","navigatorTitle":[{"text":"TMTicketsOrderDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsOrderDelegate","kind":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/CustomModules":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/CustomModules","kind":"article","url":"\/documentation\/ticketmastertickets\/custommodules","abstract":[{"text":"A ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","isActive":true},{"type":"text","text":" is defined by three values:"}],"title":"Custom Module","type":"topic","role":"article"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TicketmasterTicketsVersionString":{"abstract":[{"text":"Project version string for TicketmasterTickets.","type":"text"}],"kind":"symbol","title":"TicketmasterTicketsVersionString","role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TicketmasterTicketsVersionString","type":"topic","url":"\/documentation\/ticketmastertickets\/ticketmasterticketsversionstring","fragments":[{"text":"TicketmasterTicketsVersionString","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Custom-Modules","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModule","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsModuleHeaderView"],"title":"Custom Modules"},{"title":"Articles","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/CustomModules"],"generated":true,"anchor":"Articles"},{"generated":true,"title":"Classes","identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsView","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTicketsViewController"],"anchor":"Classes"},{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TicketmasterTicketsVersionNumber","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TicketmasterTicketsVersionString"],"anchor":"Variables","title":"Variables","generated":true}]},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController\/title","value":"TMTicketsViewController","op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController\/fragments","value":[{"text":"TMTicketsViewController","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"TMTicketsViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsViewController\/navigatorTitle"},{"op":"replace","value":"TMTicketsView","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/title"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/fragments","value":[{"text":"TMTicketsView","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsView\/navigatorTitle","value":[{"kind":"identifier","text":"TMTicketsView"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/title","value":"TMTicketsModuleHeaderView","op":"replace"},{"value":[{"text":"TMTicketsModuleHeaderView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/fragments"},{"value":[{"text":"TMTicketsModuleHeaderView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModuleHeaderView\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/title","value":"TMTicketsModule"},{"op":"replace","value":[{"text":"TMTicketsModule","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/fragments"},{"value":[{"text":"TMTicketsModule","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTicketsModule\/navigatorTitle","op":"replace"},{"value":"TMTickets","op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/title"},{"op":"replace","value":[{"text":"TMTickets","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/navigatorTitle","value":[{"text":"TMTickets","kind":"identifier"}]}]}]}