{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmastertickets\/tmtickets\/namwebsiteenvironment\/init(keyvalue:)"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keyValue"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Initializer","symbolKind":"init","role":"symbol","title":"init(keyValue:)","externalID":"s:19TicketmasterTickets9TMTicketsC21NAMWebsiteEnvironmentO8keyValueAESS_tcfc","modules":[{"name":"TicketmasterTickets"}]},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets","doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/NAMWebsiteEnvironment"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"keyValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/NAMWebsiteEnvironment\/init(keyValue:)"},"references":{"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets":{"type":"topic","abstract":[{"type":"text","text":"main class of Tickets SDK, intended to be used as singleton"}],"title":"TMTickets","navigatorTitle":[{"text":"TMTickets","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets","url":"\/documentation\/ticketmastertickets\/tmtickets","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TMTickets","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/NAMWebsiteEnvironment":{"navigatorTitle":[{"kind":"identifier","text":"NAMWebsiteEnvironment"}],"url":"\/documentation\/ticketmastertickets\/tmtickets\/namwebsiteenvironment","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"NAMWebsiteEnvironment","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/NAMWebsiteEnvironment","kind":"symbol","abstract":[{"type":"text","text":"Ticketmaster NAM Website Environment (for web-based Archtics Transfer, Resale, Upgrade, etc…)"}],"title":"TMTickets.NAMWebsiteEnvironment","type":"topic"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets/TMTickets/NAMWebsiteEnvironment/init(keyValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"keyValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[],"type":"topic","title":"init(keyValue:)","kind":"symbol","url":"\/documentation\/ticketmastertickets\/tmtickets\/namwebsiteenvironment\/init(keyvalue:)","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets\/TMTickets\/NAMWebsiteEnvironment\/init(keyValue:)","role":"symbol"},"doc://com.ticketmaster.TicketmasterTickets/documentation/TicketmasterTickets":{"url":"\/documentation\/ticketmastertickets","kind":"symbol","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterTickets\/documentation\/TicketmasterTickets","title":"TicketmasterTickets","role":"collection","abstract":[{"text":"Implementation of Ticketmaster post-purchase functionality such as viewing purchased Events, Tickets, and Barcodes.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"TMTickets","op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/fragments","value":[{"kind":"identifier","text":"TMTickets"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterTickets~1documentation~1TicketmasterTickets~1TMTickets\/navigatorTitle","value":[{"kind":"identifier","text":"TMTickets"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}