{"hierarchy":{"paths":[[]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"metadata":{"roleHeading":"Framework","title":"TicketmasterPrePurchase","role":"collection","externalID":"TicketmasterPrePurchase","symbolKind":"module","modules":[{"name":"TicketmasterPrePurchase"}]},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController"]},{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseAnalyticsDelegate","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseLocationDelegate","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseNavigationDelegate"],"title":"Protocols"},{"title":"Extended Modules","identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/Foundation","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TicketmasterFoundation"]}],"variants":[{"paths":["\/documentation\/ticketmasterprepurchase"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ticketmasterprepurchase"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"content","content":[{"text":"Overview","anchor":"Overview","level":2,"type":"heading"}]}],"references":{"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TicketmasterFoundation":{"abstract":[],"kind":"symbol","url":"\/documentation\/ticketmasterprepurchase\/ticketmasterfoundation","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TicketmasterFoundation","role":"collection","title":"TicketmasterFoundation","type":"topic"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TicketmasterPrePurchaseVersionNumber":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TicketmasterPrePurchaseVersionNumber","url":"\/documentation\/ticketmasterprepurchase\/ticketmasterprepurchaseversionnumber","title":"TicketmasterPrePurchaseVersionNumber","kind":"symbol","abstract":[{"text":"Project version number for TicketmasterPrePurchase.","type":"text"}],"fragments":[{"text":"TicketmasterPrePurchaseVersionNumber","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/Foundation":{"abstract":[],"title":"Foundation","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/Foundation","type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/ticketmasterprepurchase\/foundation"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseAnalyticsDelegate":{"abstract":[{"text":"Protocol for communicating analytics-related information","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPrePurchaseAnalyticsDelegate"}],"type":"topic","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseanalyticsdelegate","navigatorTitle":[{"text":"TMPrePurchaseAnalyticsDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseAnalyticsDelegate","title":"TMPrePurchaseAnalyticsDelegate","kind":"symbol","role":"symbol"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TicketmasterPrePurchaseVersionString":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TicketmasterPrePurchaseVersionString","title":"TicketmasterPrePurchaseVersionString","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/ticketmasterprepurchase\/ticketmasterprepurchaseversionstring","abstract":[{"type":"text","text":"Project version string for TicketmasterPrePurchase."}],"fragments":[{"text":"TicketmasterPrePurchaseVersionString","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchase":{"type":"topic","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchase","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPrePurchase"}],"abstract":[{"text":"A class that stores the global configuration for the TicketmasterPrePurchase SDK.","type":"text"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase","navigatorTitle":[{"text":"TMPrePurchase","kind":"identifier"}],"title":"TMPrePurchase","kind":"symbol"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseNavigationDelegate":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseNavigationDelegate","title":"TMPrePurchaseNavigationDelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TMPrePurchaseNavigationDelegate"}],"kind":"symbol","abstract":[{"type":"text","text":"Protocol for communicating navigations happening in PrePurchase pages"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMPrePurchaseNavigationDelegate","kind":"identifier"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchasenavigationdelegate"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseLocationDelegate":{"navigatorTitle":[{"text":"TMPrePurchaseLocationDelegate","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseLocationDelegate","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaselocationdelegate","title":"TMPrePurchaseLocationDelegate","abstract":[{"text":"Protocol for communicating interactions about location","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMPrePurchaseLocationDelegate","kind":"identifier"}]},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchaseViewController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMPrePurchaseViewController","kind":"identifier"}],"navigatorTitle":[{"text":"TMPrePurchaseViewController","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController","abstract":[{"type":"text","text":"Class used to display UI flow for discovering attractions and venues leading up to purchase flow."}],"type":"topic","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchaseviewcontroller","title":"TMPrePurchaseViewController","kind":"symbol"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase":{"type":"topic","url":"\/documentation\/ticketmasterprepurchase","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","role":"collection","title":"TicketmasterPrePurchase","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchaseViewController"],"title":"Classes"},{"title":"Variables","identifiers":["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TicketmasterPrePurchaseVersionNumber","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TicketmasterPrePurchaseVersionString"]}],"op":"replace"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchase\/title","value":"TMPrePurchase"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchase\/fragments","value":[{"text":"TMPrePurchase","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/title","op":"replace","value":"TMPrePurchaseViewController"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchaseViewController\/fragments","value":[{"text":"TMPrePurchaseViewController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}