{"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration"],"title":"Classes","anchor":"Classes","generated":true},{"identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationDelegate","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseSharingDelegate","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseUserAnalyticsDelegate","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebAnalyticsDelegate","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TipDecorating"],"generated":true,"anchor":"Protocols","title":"Protocols"},{"title":"Structures","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/CheckoutConfirmationHandler","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/HeadlineTipViewStyle"],"generated":true,"anchor":"Structures"},{"title":"Enumerations","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMEndCheckoutReason","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMEndTicketSelectionReason","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseComponent","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseDecision","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavBarButton","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseSubPage"],"generated":true,"anchor":"Enumerations"}],"metadata":{"title":"TicketmasterPurchase","role":"collection","roleHeading":"Framework","externalID":"TicketmasterPurchase","modules":[{"name":"TicketmasterPurchase"}],"symbolKind":"module"},"identifier":{"url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","interfaceLanguage":"swift"},"hierarchy":{"paths":[[]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterpurchase"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ticketmasterpurchase"]}],"references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TipDecorating":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TipDecorating","url":"\/documentation\/ticketmasterpurchase\/tipdecorating","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TipDecorating"}],"navigatorTitle":[{"kind":"identifier","text":"TipDecorating"}],"abstract":[],"title":"TipDecorating","type":"topic"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/HeadlineTipViewStyle":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeadlineTipViewStyle"}],"navigatorTitle":[{"kind":"identifier","text":"HeadlineTipViewStyle"}],"abstract":[],"title":"HeadlineTipViewStyle","type":"topic","url":"\/documentation\/ticketmasterpurchase\/headlinetipviewstyle","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/HeadlineTipViewStyle"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchase":{"url":"\/documentation\/ticketmasterpurchase\/tmpurchase","role":"symbol","kind":"symbol","abstract":[{"text":"A class that stores the global configuration for the TicketmasterPurchase SDK.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMPurchase","kind":"identifier"}],"type":"topic","title":"TMPurchase","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase","navigatorTitle":[{"text":"TMPurchase","kind":"identifier"}]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMPurchaseNavigationController"}],"title":"TMPurchaseNavigationController","navigatorTitle":[{"kind":"identifier","text":"TMPurchaseNavigationController"}],"role":"symbol","abstract":[{"text":"A navigation controller (view controller) that allows users to select and purchase tickets to a Ticketmaster Event.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController","url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationDelegate":{"title":"TMPurchaseNavigationDelegate","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationDelegate","role":"symbol","url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPurchaseNavigationDelegate"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The navigation delegate of a "},{"type":"codeVoice","code":"TMPurchaseNavigationController"}],"navigatorTitle":[{"text":"TMPurchaseNavigationDelegate","kind":"identifier"}]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseDecision":{"url":"\/documentation\/ticketmasterpurchase\/tmpurchasedecision","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseDecision","navigatorTitle":[{"text":"TMPurchaseDecision","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMPurchaseDecision"}],"title":"TMPurchaseDecision","abstract":[{"text":"The decisions that user can make","type":"text"}],"type":"topic"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebsiteConfiguration":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration","abstract":[{"text":"Class used to configure behavior of website Event Details Page (EDP) and Cart","type":"text"}],"title":"TMPurchaseWebsiteConfiguration","navigatorTitle":[{"text":"TMPurchaseWebsiteConfiguration","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TMPurchaseWebsiteConfiguration","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration","type":"topic"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder":{"navigatorTitle":[{"kind":"identifier","text":"TMPurchaseOrder"}],"title":"TMPurchaseOrder","abstract":[{"type":"text","text":"A data structure that represents a purchased order"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TMPurchaseOrder","kind":"identifier"}],"url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder","role":"symbol","type":"topic","kind":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TicketmasterPurchaseVersionNumber":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TicketmasterPurchaseVersionNumber","abstract":[{"type":"text","text":"Project version number for TicketmasterPurchase."}],"title":"TicketmasterPurchaseVersionNumber","url":"\/documentation\/ticketmasterpurchase\/ticketmasterpurchaseversionnumber","kind":"symbol","type":"topic","fragments":[{"text":"TicketmasterPurchaseVersionNumber","kind":"identifier"}],"role":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseSharingDelegate":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TMPurchaseSharingDelegate"}],"title":"TMPurchaseSharingDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"TMPurchaseSharingDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseSharingDelegate","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The sharing delegate of a "},{"type":"codeVoice","code":"TMPurchaseNavigationController"},{"type":"text","text":"."}],"url":"\/documentation\/ticketmasterpurchase\/tmpurchasesharingdelegate"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/CheckoutConfirmationHandler":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/CheckoutConfirmationHandler","type":"topic","title":"CheckoutConfirmationHandler","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutConfirmationHandler"}],"navigatorTitle":[{"text":"CheckoutConfirmationHandler","kind":"identifier"}],"url":"\/documentation\/ticketmasterpurchase\/checkoutconfirmationhandler"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebAnalyticsDelegate":{"title":"TMPurchaseWebAnalyticsDelegate","url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebanalyticsdelegate","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebAnalyticsDelegate","abstract":[{"type":"text","text":"The detailed anayltics delegate of a "},{"type":"codeVoice","code":"TMPurchaseNavigationController"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"TMPurchaseWebAnalyticsDelegate","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMPurchaseWebAnalyticsDelegate"}]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseComponent":{"url":"\/documentation\/ticketmasterpurchase\/tmpurchasecomponent","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseComponent","navigatorTitle":[{"text":"TMPurchaseComponent","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPurchaseComponent"}],"title":"TMPurchaseComponent","abstract":[{"type":"text","text":"The component that user interacted with"}],"type":"topic"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TicketmasterPurchaseVersionString":{"title":"TicketmasterPurchaseVersionString","abstract":[{"text":"Project version string for TicketmasterPurchase.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TicketmasterPurchaseVersionString","url":"\/documentation\/ticketmasterpurchase\/ticketmasterpurchaseversionstring","type":"topic","role":"symbol","fragments":[{"text":"TicketmasterPurchaseVersionString","kind":"identifier"}]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavBarButton":{"role":"symbol","title":"TMPurchaseNavBarButton","type":"topic","abstract":[{"text":"The navigation bar header button that the user has pressed","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavBarButton","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TMPurchaseNavBarButton","kind":"identifier"}],"navigatorTitle":[{"text":"TMPurchaseNavBarButton","kind":"identifier"}],"url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavbarbutton"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/POPPopupBridge":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"POPPopupBridge","kind":"identifier"}],"url":"\/documentation\/ticketmasterpurchase\/poppopupbridge","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge","role":"symbol","title":"POPPopupBridge","kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"POPPopupBridge"}]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMEndCheckoutReason":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"TMEndCheckoutReason","kind":"identifier"}],"url":"\/documentation\/ticketmasterpurchase\/tmendcheckoutreason","type":"topic","abstract":[{"type":"text","text":"The reason that the checkout portion of the purchase process ended"}],"title":"TMEndCheckoutReason","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMEndCheckoutReason","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"TMEndCheckoutReason","kind":"identifier"}]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseUserAnalyticsDelegate":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMPurchaseUserAnalyticsDelegate"}],"title":"TMPurchaseUserAnalyticsDelegate","navigatorTitle":[{"text":"TMPurchaseUserAnalyticsDelegate","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The user analytics delegate of a ","type":"text"},{"type":"codeVoice","code":"TMPurchaseNavigationController"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseUserAnalyticsDelegate","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseuseranalyticsdelegate"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseSubPage":{"url":"\/documentation\/ticketmasterpurchase\/tmpurchasesubpage","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The subpages of Event Details Page and Checkout Cart"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMPurchaseSubPage","kind":"identifier"}],"type":"topic","title":"TMPurchaseSubPage","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseSubPage","navigatorTitle":[{"kind":"identifier","text":"TMPurchaseSubPage"}]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMEndTicketSelectionReason":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TMEndTicketSelectionReason","kind":"identifier"}],"url":"\/documentation\/ticketmasterpurchase\/tmendticketselectionreason","type":"topic","abstract":[{"text":"The reason that the ticket selection portion of the purchase process ended","type":"text"}],"title":"TMEndTicketSelectionReason","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMEndTicketSelectionReason","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TMEndTicketSelectionReason"}]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"kind":"symbol","abstract":[],"url":"\/documentation\/ticketmasterpurchase","title":"TicketmasterPurchase","role":"collection","type":"topic","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"title":"Classes","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration"],"generated":true,"anchor":"Classes"},{"title":"Variables","anchor":"Variables","generated":true,"identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TicketmasterPurchaseVersionNumber","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TicketmasterPurchaseVersionString"]}],"op":"replace","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchase\/title","value":"TMPurchase"},{"value":[{"text":"TMPurchase","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchase\/fragments"},{"value":[{"text":"TMPurchase","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchase\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/title","value":"TMPurchaseNavigationController","op":"replace"},{"op":"replace","value":[{"text":"TMPurchaseNavigationController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/fragments"},{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/navigatorTitle","op":"replace","value":[{"text":"TMPurchaseNavigationController","kind":"identifier"}]},{"op":"replace","value":"TMPurchaseWebsiteConfiguration","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseWebsiteConfiguration\/title"},{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseWebsiteConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"TMPurchaseWebsiteConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseWebsiteConfiguration\/navigatorTitle","value":[{"text":"TMPurchaseWebsiteConfiguration","kind":"identifier"}]},{"op":"replace","value":"TMPurchaseOrder","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseOrder\/title"},{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseOrder\/fragments","value":[{"kind":"identifier","text":"TMPurchaseOrder"}],"op":"replace"},{"value":[{"kind":"identifier","text":"TMPurchaseOrder"}],"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseOrder\/navigatorTitle","op":"replace"},{"value":"POPPopupBridge","op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge\/fragments","value":[{"text":"POPPopupBridge","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"POPPopupBridge"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}