{"variants":[{"paths":["\/documentation\/ticketmasterpurchase\/poppopupbridge"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ticketmasterpurchase\/poppopupbridge"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","title":"POPPopupBridge","modules":[{"name":"TicketmasterPurchase"}],"symbolKind":"class","roleHeading":"Class","navigatorTitle":[{"text":"POPPopupBridge","kind":"identifier"}],"externalID":"c:@M@TicketmasterPurchase@objc(cs)POPPopupBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"POPPopupBridge"}]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)ASWebAuthenticationPresentationContextProviding","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)NSObject","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s7CVarArgP","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s8CopyableP","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s28CustomDebugStringConvertibleP","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s23CustomStringConvertibleP","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/SQ","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/SH","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s8SendableP","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)WKScriptMessageHandler"],"type":"conformsTo"}],"sections":[],"topicSections":[{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge\/init(webView:prefersEphemeralWebBrowserSession:)"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge\/userContentController(_:didReceive:)"],"generated":true},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge\/ASWebAuthenticationPresentationContextProviding-Implementations"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"POPPopupBridge"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)NSObject"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/POPPopupBridge/init(webView:prefersEphemeralWebBrowserSession:)":{"url":"\/documentation\/ticketmasterpurchase\/poppopupbridge\/init(webview:prefersephemeralwebbrowsersession:)","title":"init(webView:prefersEphemeralWebBrowserSession:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge\/init(webView:prefersEphemeralWebBrowserSession:)","navigatorTitle":[{"text":"initWithWebView:prefersEphemeralWebBrowserSession:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Initialize a Popup Bridge."}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"webView","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"prefersEphemeralWebBrowserSession","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.ticketmaster.ios.TicketmasterPurchase/s8CopyableP":{"title":"Swift.Copyable","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s8CopyableP"},"doc://com.ticketmaster.ios.TicketmasterPurchase/objc(pl)ASWebAuthenticationPresentationContextProviding":{"title":"ASWebAuthenticationPresentationContextProviding","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)ASWebAuthenticationPresentationContextProviding"},"doc://com.ticketmaster.ios.TicketmasterPurchase/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/SH"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/POPPopupBridge":{"url":"\/documentation\/ticketmasterpurchase\/poppopupbridge","title":"POPPopupBridge","type":"topic","role":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge","navigatorTitle":[{"text":"POPPopupBridge","kind":"identifier"}],"kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POPPopupBridge","kind":"identifier"}]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/POPPopupBridge/userContentController(_:didReceive:)":{"url":"\/documentation\/ticketmasterpurchase\/poppopupbridge\/usercontentcontroller(_:didreceive:)","title":"userContentController(_:didReceive:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge\/userContentController(_:didReceive:)","navigatorTitle":[{"kind":"identifier","text":"userContentController:didReceiveScriptMessage:"}],"kind":"symbol","abstract":[{"text":":nodoc: This method is not covered by Semantic Versioning. Do not use.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userContentController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKUserContentController","text":"WKUserContentController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKScriptMessage","text":"WKScriptMessage"},{"kind":"text","text":")"}]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"kind":"symbol","role":"collection","title":"TicketmasterPurchase","url":"\/documentation\/ticketmasterpurchase","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","type":"topic","abstract":[]},"doc://com.ticketmaster.ios.TicketmasterPurchase/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/SQ"},"doc://com.ticketmaster.ios.TicketmasterPurchase/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s23CustomStringConvertibleP"},"doc://com.ticketmaster.ios.TicketmasterPurchase/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(cs)NSObject"},"doc://com.ticketmaster.ios.TicketmasterPurchase/objc(pl)WKScriptMessageHandler":{"title":"WKScriptMessageHandler","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)WKScriptMessageHandler"},"doc://com.ticketmaster.ios.TicketmasterPurchase/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s8SendableP"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/POPPopupBridge/ASWebAuthenticationPresentationContextProviding-Implementations":{"url":"\/documentation\/ticketmasterpurchase\/poppopupbridge\/aswebauthenticationpresentationcontextproviding-implementations","title":"ASWebAuthenticationPresentationContextProviding Implementations","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge\/ASWebAuthenticationPresentationContextProviding-Implementations","kind":"article","abstract":[]},"doc://com.ticketmaster.ios.TicketmasterPurchase/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s7CVarArgP"},"doc://com.ticketmaster.ios.TicketmasterPurchase/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"POPPopupBridge"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"POPPopupBridge"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"POPPopupBridge"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge\/init(webView:prefersEphemeralWebBrowserSession:)","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge\/userContentController(_:didReceive:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/POPPopupBridge\/ASWebAuthenticationPresentationContextProviding-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)ASWebAuthenticationPresentationContextProviding","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)WKScriptMessageHandler"],"type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"POPPopupBridge","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge~1init(webView:prefersEphemeralWebBrowserSession:)\/title","value":"initWithWebView:prefersEphemeralWebBrowserSession:"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge~1init(webView:prefersEphemeralWebBrowserSession:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithWebView:prefersEphemeralWebBrowserSession:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge\/title","value":"POPPopupBridge"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge\/fragments","value":[{"kind":"identifier","text":"POPPopupBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge\/navigatorTitle","value":[{"kind":"identifier","text":"POPPopupBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge~1userContentController(_:didReceive:)\/title","value":"userContentController:didReceiveScriptMessage:"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1POPPopupBridge~1userContentController(_:didReceive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userContentController:didReceiveScriptMessage:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}