{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPurchaseWebsiteConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)NSObject","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s7CVarArgP","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s28CustomDebugStringConvertibleP","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s23CustomStringConvertibleP","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/SQ","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"class used to configure behavior of website Event Details Page (EDP) and Cart"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPurchaseWebsiteConfiguration"}],"title":"TMPurchaseWebsiteConfiguration","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@TicketmasterPurchase@objc(cs)TMPurchaseWebsiteConfiguration","modules":[{"name":"TicketmasterPurchase"}],"navigatorTitle":[{"kind":"identifier","text":"TMPurchaseWebsiteConfiguration"}]},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/init(eventID:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/additionalURLParameters","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/attractionID","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/brandName","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/cameFromCode","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/discreteID","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/eventID","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/internalTestingKeys","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/marketDomain","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/showCalendarToolbarButton","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/showFavoriteToolbarButton","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/showInfoToolbarButton","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/showNFLBranding","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/showResaleMessageBanner","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/showResaleSoftLanding","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/showShareToolbarButton"]}],"references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s28CustomDebugStringConvertibleP"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebsiteConfiguration/internalTestingKeys":{"role":"symbol","title":"internalTestingKeys","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalTestingKeys"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"internal keys used by Ticketmaster, should not be modified by your App"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/internalTestingKeys","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration\/internaltestingkeys"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"role":"collection","title":"TicketmasterPurchase","abstract":[],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebsiteConfiguration/showNFLBranding":{"role":"symbol","title":"showNFLBranding","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showNFLBranding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"show special NFL branding on EDP"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/showNFLBranding","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration\/shownflbranding"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebsiteConfiguration/eventID":{"role":"symbol","title":"eventID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Discovery or Host Event Identifier (required)"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/eventID","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration\/eventid"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebsiteConfiguration/cameFromCode":{"role":"symbol","title":"cameFromCode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameFromCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"marketing campaign code used for tracking"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/cameFromCode","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration\/camefromcode"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebsiteConfiguration/showCalendarToolbarButton":{"role":"symbol","title":"showCalendarToolbarButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showCalendarToolbarButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"show Event “Calendar” button in NavBar, button will only appear if Event has other performances at the same Venue"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/showCalendarToolbarButton","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration\/showcalendartoolbarbutton"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebsiteConfiguration/discreteID":{"role":"symbol","title":"discreteID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"discreteID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"a special “password” used to expose hidden ticket types on the EDP"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/discreteID","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration\/discreteid"},"doc://com.ticketmaster.ios.TicketmasterPurchase/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(cs)NSObject"},"doc://com.ticketmaster.ios.TicketmasterPurchase/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/SH"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebsiteConfiguration/brandName":{"role":"symbol","title":"brandName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"brandName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The brand name (a special branding id) used to style web page content"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/brandName","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration\/brandname"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebsiteConfiguration/marketDomain":{"role":"symbol","title":"marketDomain","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"marketDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MarketDomain","preciseIdentifier":"c:@M@TicketmasterFoundation@E@MarketDomain"}],"abstract":[{"type":"text","text":"geographical area the event is in"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/marketDomain","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration\/marketdomain"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebsiteConfiguration":{"role":"symbol","title":"TMPurchaseWebsiteConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPurchaseWebsiteConfiguration"}],"abstract":[{"type":"text","text":"class used to configure behavior of website Event Details Page (EDP) and Cart"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TMPurchaseWebsiteConfiguration"}],"url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebsiteConfiguration/showInfoToolbarButton":{"role":"symbol","title":"showInfoToolbarButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showInfoToolbarButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"show Event “Info” button in NavBar, enables presentADP and presentVDP User Navigation delegate methods"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/showInfoToolbarButton","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration\/showinfotoolbarbutton"},"doc://com.ticketmaster.ios.TicketmasterPurchase/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s7CVarArgP"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebsiteConfiguration/additionalURLParameters":{"role":"symbol","title":"additionalURLParameters","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalURLParameters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"your own additional custom URL parameters, these string values will be URL-encoded by the Purchase SDK."}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/additionalURLParameters","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration\/additionalurlparameters"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebsiteConfiguration/showResaleMessageBanner":{"role":"symbol","title":"showResaleMessageBanner","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showResaleMessageBanner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"show resale message banner at the top of EDP"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/showResaleMessageBanner","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration\/showresalemessagebanner"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebsiteConfiguration/showResaleSoftLanding":{"role":"symbol","title":"showResaleSoftLanding","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showResaleSoftLanding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"hide resale ticket offerings of EDP behind a toggle\/button"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/showResaleSoftLanding","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration\/showresalesoftlanding"},"doc://com.ticketmaster.ios.TicketmasterPurchase/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/SQ"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebsiteConfiguration/showFavoriteToolbarButton":{"role":"symbol","title":"showFavoriteToolbarButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showFavoriteToolbarButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"show Event Favoriting “Heart” button in NavBar, enables Favorites delegate methods"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/showFavoriteToolbarButton","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration\/showfavoritetoolbarbutton"},"doc://com.ticketmaster.ios.TicketmasterPurchase/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s23CustomStringConvertibleP"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebsiteConfiguration/showShareToolbarButton":{"role":"symbol","title":"showShareToolbarButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showShareToolbarButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"show Event Social “Share” button in EDP NavBar enables Sharing delegate methods"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/showShareToolbarButton","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration\/showsharetoolbarbutton"},"doc://com.ticketmaster.ios.TicketmasterPurchase/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)NSObject"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebsiteConfiguration/attractionID":{"role":"symbol","title":"attractionID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"attractionID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Discovery or Host Attraction\/Attraction Identifier, used for branding"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/attractionID","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration\/attractionid"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebsiteConfiguration/init(eventID:)":{"role":"symbol","title":"init(eventID:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"eventID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Create a new Website Configuration with default settings"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration\/init(eventID:)","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration\/init(eventid:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"TMPurchaseWebsiteConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TMPurchaseWebsiteConfiguration"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TMPurchaseWebsiteConfiguration"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPurchaseWebsiteConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseWebsiteConfiguration\/title","value":"TMPurchaseWebsiteConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseWebsiteConfiguration\/fragments","value":[{"kind":"identifier","text":"TMPurchaseWebsiteConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}