{"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)NSObject","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s7CVarArgP","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s28CustomDebugStringConvertibleP","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s23CustomStringConvertibleP","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/SQ","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/SH"]}],"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/Item"]},{"title":"Initializers","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/init(identifier:date:discoveryEvent:eventIdentifier:eventName:attractionIdentifier:attractionName:venueIdentifier:venueName:majorCategoryName:minorCategoryName:promoterIdentifier:edpType:isResale:ticketQuantity:currencyCode:basePriceTotal:shippingTotal:orderProcessingFeeTotal:upsellTotal:voucherDiscountTotal:taxTotal:grandTotal:items:billingCountry:billingPostalCode:billingStateProvince:paymentMethod:shippingMethod:rawJSON:)","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/init(jsonDictionary:discoveryEvent:)","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/init(jsonString:discoveryEvent:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/attractionIdentifier","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/attractionName","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/basePriceTotal","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/billingCountry","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/billingPostalCode","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/billingStateProvince","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/convenienceFeeTotal","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/currencyCode","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/date","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/discoveryEvent","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/edpType","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/eventIdentifier","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/eventName","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/grandTotal","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/identifier","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/isResale","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/items","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/majorCategoryName","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/minorCategoryName","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/orderProcessingFeeTotal","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/otherFeeTotal","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/paymentMethod","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/promoterIdentifier","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/rawJSON","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/shippingMethod","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/shippingTotal","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/taxTotal","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/ticketQuantity","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/upsellTotal","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/venueIdentifier","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/venueName","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/voucherDiscountTotal"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/isEqual(_:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterpurchase\/tmpurchaseorder"]},{"paths":["\/documentation\/ticketmasterpurchase\/tmpurchaseorder"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMPurchaseOrder","kind":"identifier"}],"modules":[{"name":"TicketmasterPurchase"}],"navigatorTitle":[{"kind":"identifier","text":"TMPurchaseOrder"}],"title":"TMPurchaseOrder","symbolKind":"class","externalID":"c:@M@TicketmasterPurchase@objc(cs)TMPurchaseOrder","role":"symbol","roleHeading":"Class"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMPurchaseOrder","kind":"identifier"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder"},"kind":"symbol","references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/shippingTotal":{"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shippingTotal"},{"kind":"text","text":": "},{"text":"NSDecimalNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber"}],"role":"symbol","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/shippingtotal","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/shippingTotal","type":"topic","abstract":[],"title":"shippingTotal"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/currencyCode":{"title":"currencyCode","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currencyCode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/currencycode","abstract":[],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/currencyCode"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/majorCategoryName":{"role":"symbol","type":"topic","kind":"symbol","title":"majorCategoryName","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/majorCategoryName","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"majorCategoryName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/majorcategoryname","abstract":[]},"doc://com.ticketmaster.ios.TicketmasterPurchase/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s7CVarArgP","type":"unresolvable"},"doc://com.ticketmaster.ios.TicketmasterPurchase/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/SQ","type":"unresolvable"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","url":"\/documentation\/ticketmasterpurchase","abstract":[],"title":"TicketmasterPurchase"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/convenienceFeeTotal":{"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"convenienceFeeTotal","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/convenienceFeeTotal","type":"topic","title":"convenienceFeeTotal","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/conveniencefeetotal","kind":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/SH","type":"unresolvable"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/voucherDiscountTotal":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/voucherDiscountTotal","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/voucherdiscounttotal","role":"symbol","kind":"symbol","title":"voucherDiscountTotal","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"voucherDiscountTotal"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber","text":"NSDecimalNumber"}],"abstract":[]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/eventName":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/eventName","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/eventname","role":"symbol","kind":"symbol","title":"eventName","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"abstract":[]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/venueName":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"venueName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"venueName","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/venuename","role":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/venueName","type":"topic","abstract":[],"kind":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/otherFeeTotal":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"otherFeeTotal"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDecimalNumber","kind":"typeIdentifier","text":"NSDecimalNumber"}],"role":"symbol","type":"topic","title":"otherFeeTotal","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/otherfeetotal","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/otherFeeTotal","kind":"symbol","abstract":[]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/attractionIdentifier":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/attractionIdentifier","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"attractionIdentifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[],"title":"attractionIdentifier","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/attractionidentifier","role":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/discoveryEvent":{"type":"topic","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/discoveryEvent","abstract":[],"role":"symbol","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/discoveryevent","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"discoveryEvent"},{"kind":"text","text":": "},{"text":"DiscoveryEvent","preciseIdentifier":"s:24TicketmasterDiscoveryAPI0B5EventV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","title":"discoveryEvent"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/eventIdentifier":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/eventIdentifier","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/eventidentifier","type":"topic","kind":"symbol","role":"symbol","title":"eventIdentifier","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"eventIdentifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/basePriceTotal":{"kind":"symbol","role":"symbol","abstract":[],"title":"basePriceTotal","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/basepricetotal","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/basePriceTotal","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"basePriceTotal"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber","text":"NSDecimalNumber"}],"type":"topic"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/attractionName":{"abstract":[],"title":"attractionName","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/attractionName","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/attractionname","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"attractionName","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/isResale":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/isResale","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"isResale","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isResale","role":"symbol","kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/isresale"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/init(identifier:date:discoveryEvent:eventIdentifier:eventName:attractionIdentifier:attractionName:venueIdentifier:venueName:majorCategoryName:minorCategoryName:promoterIdentifier:edpType:isResale:ticketQuantity:currencyCode:basePriceTotal:shippingTotal:orderProcessingFeeTotal:upsellTotal:voucherDiscountTotal:taxTotal:grandTotal:items:billingCountry:billingPostalCode:billingStateProvince:paymentMethod:shippingMethod:rawJSON:)":{"abstract":[],"kind":"symbol","title":"init(identifier:date:discoveryEvent:eventIdentifier:eventName:attractionIdentifier:attractionName:venueIdentifier:venueName:majorCategoryName:minorCategoryName:promoterIdentifier:edpType:isResale:ticketQuantity:currencyCode:basePriceTotal:shippingTotal:orderProcessingFeeTotal:upsellTotal:voucherDiscountTotal:taxTotal:grandTotal:items:billingCountry:billingPostalCode:billingStateProvince:paymentMethod:shippingMethod:rawJSON:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"date"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"discoveryEvent"},{"kind":"text","text":": "},{"text":"DiscoveryEvent","kind":"typeIdentifier","preciseIdentifier":"s:24TicketmasterDiscoveryAPI0B5EventV"},{"kind":"text","text":"?, "},{"text":"eventIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"eventName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"attractionIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"attractionName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"venueIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"venueName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"majorCategoryName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"minorCategoryName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"promoterIdentifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"edpType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"isResale","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"ticketQuantity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":"?, ","kind":"text"},{"text":"currencyCode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"basePriceTotal"},{"text":": ","kind":"text"},{"text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"shippingTotal"},{"text":": ","kind":"text"},{"text":"NSDecimalNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"orderProcessingFeeTotal"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber","text":"NSDecimalNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"upsellTotal"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"voucherDiscountTotal"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber"},{"kind":"text","text":"?, "},{"text":"taxTotal","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"grandTotal"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSDecimalNumber","text":"NSDecimalNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"items","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Item","kind":"typeIdentifier","preciseIdentifier":"s:20TicketmasterPurchase15TMPurchaseOrderC4ItemC"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"billingCountry"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"billingPostalCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"billingStateProvince","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"paymentMethod"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"shippingMethod","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"rawJSON"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:22TicketmasterFoundation14JSONDictionarya","kind":"typeIdentifier","text":"JSONDictionary"},{"text":"?)","kind":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/init(identifier:date:discoveryEvent:eventIdentifier:eventName:attractionIdentifier:attractionName:venueIdentifier:venueName:majorCategoryName:minorCategoryName:promoterIdentifier:edpType:isResale:ticketQuantity:currencyCode:basePriceTotal:shippingTotal:orderProcessingFeeTotal:upsellTotal:voucherDiscountTotal:taxTotal:grandTotal:items:billingCountry:billingPostalCode:billingStateProvince:paymentMethod:shippingMethod:rawJSON:)","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/init(identifier:date:discoveryevent:eventidentifier:eventname:attractionidentifier:attractionname:venueidentifier:venuename:majorcategoryname:minorcategoryname:promoteridentifier:edptype:isresale:ticketquantity:currencycode:basepricetotal:s-4hdeh"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/upsellTotal":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/upsellTotal","type":"topic","title":"upsellTotal","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"upsellTotal"},{"kind":"text","text":": "},{"text":"NSDecimalNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber"}],"url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/upselltotal","abstract":[]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/init(jsonDictionary:discoveryEvent:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"jsonDictionary"},{"kind":"text","text":": "},{"preciseIdentifier":"s:22TicketmasterFoundation14JSONDictionarya","kind":"typeIdentifier","text":"JSONDictionary"},{"kind":"text","text":", "},{"text":"discoveryEvent","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DiscoveryEvent","kind":"typeIdentifier","preciseIdentifier":"s:24TicketmasterDiscoveryAPI0B5EventV"},{"text":"?)","kind":"text"}],"kind":"symbol","title":"init(jsonDictionary:discoveryEvent:)","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/init(jsonDictionary:discoveryEvent:)","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/init(jsondictionary:discoveryevent:)"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/minorCategoryName":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/minorCategoryName","abstract":[],"role":"symbol","kind":"symbol","title":"minorCategoryName","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/minorcategoryname","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minorCategoryName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder":{"url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder","navigatorTitle":[{"text":"TMPurchaseOrder","kind":"identifier"}],"abstract":[],"role":"symbol","title":"TMPurchaseOrder","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPurchaseOrder"}],"kind":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/promoterIdentifier":{"url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/promoteridentifier","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/promoterIdentifier","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"promoterIdentifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"title":"promoterIdentifier","type":"topic","kind":"symbol","role":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/taxTotal":{"type":"topic","abstract":[],"title":"taxTotal","kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"taxTotal","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/taxTotal","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/taxtotal"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/date":{"abstract":[],"title":"date","role":"symbol","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/date","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/date","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"date"},{"kind":"text","text":": "},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"}],"kind":"symbol","type":"topic"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/orderProcessingFeeTotal":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/orderProcessingFeeTotal","type":"topic","role":"symbol","title":"orderProcessingFeeTotal","abstract":[],"kind":"symbol","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/orderprocessingfeetotal","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"orderProcessingFeeTotal","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSDecimalNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber"}]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/ticketQuantity":{"abstract":[],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/ticketQuantity","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/ticketquantity","title":"ticketQuantity","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ticketQuantity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/paymentMethod":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethod"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/paymentMethod","title":"paymentMethod","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/paymentmethod","type":"topic","abstract":[],"kind":"symbol","role":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/items":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"items"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"Item","preciseIdentifier":"s:20TicketmasterPurchase15TMPurchaseOrderC4ItemC"},{"kind":"text","text":"]"}],"kind":"symbol","title":"items","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/items","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/items"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/isEqual(_:)":{"role":"symbol","type":"topic","kind":"symbol","title":"isEqual(_:)","abstract":[],"url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/isequal(_:)","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/shippingMethod":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"shippingMethod","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","title":"shippingMethod","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/shippingMethod","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/shippingmethod"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/grandTotal":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/grandTotal","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/grandtotal","kind":"symbol","title":"grandTotal","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"grandTotal","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber","text":"NSDecimalNumber"}],"abstract":[],"type":"topic","role":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/billingStateProvince":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"billingStateProvince"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"billingStateProvince","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/billingStateProvince","type":"topic","abstract":[],"url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/billingstateprovince","role":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/billingCountry":{"kind":"symbol","title":"billingCountry","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/billingcountry","abstract":[],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/billingCountry","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"billingCountry","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/billingPostalCode":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"billingPostalCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/billingPostalCode","title":"billingPostalCode","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/billingpostalcode","abstract":[],"role":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/objc(cs)NSObject":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.ticketmaster.ios.TicketmasterPurchase/objc(pl)NSObject":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/init(jsonString:discoveryEvent:)":{"kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"jsonString","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"discoveryEvent"},{"kind":"text","text":": "},{"text":"DiscoveryEvent","kind":"typeIdentifier","preciseIdentifier":"s:24TicketmasterDiscoveryAPI0B5EventV"},{"kind":"text","text":"?)"}],"abstract":[],"role":"symbol","title":"init(jsonString:discoveryEvent:)","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/init(jsonString:discoveryEvent:)","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/init(jsonstring:discoveryevent:)"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/venueIdentifier":{"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"venueIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"venueIdentifier","kind":"symbol","type":"topic","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/venueIdentifier","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/venueidentifier"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/Item":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Item","kind":"identifier"}],"url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/item","role":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/Item","navigatorTitle":[{"text":"Item","kind":"identifier"}],"abstract":[],"type":"topic","title":"TMPurchaseOrder.Item"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/edpType":{"url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/edptype","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/edpType","abstract":[],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"edpType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"edpType","type":"topic","kind":"symbol","role":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/rawJSON":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rawJSON"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"JSONDictionary","preciseIdentifier":"s:22TicketmasterFoundation14JSONDictionarya"},{"kind":"text","text":"?"}],"kind":"symbol","title":"rawJSON","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/rawJSON","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/rawjson"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/identifier":{"title":"identifier","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/identifier","abstract":[],"role":"symbol","url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/identifier","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"TMPurchaseOrder","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"text":"TMPurchaseOrder","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TMPurchaseOrder"}],"op":"replace"},{"op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/isEqual(_:)"]}],"path":"\/topicSections"},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPurchaseOrder"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"TMPurchaseOrder","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseOrder\/title"},{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseOrder\/fragments","op":"replace","value":[{"kind":"identifier","text":"TMPurchaseOrder"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseOrder~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseOrder~1isEqual(_:)\/fragments","op":"replace"}]}]}