{"abstract":[{"type":"text","text":"A navigation controller (view controller) that allows users to select and purchase tickets to a Ticketmaster Event."}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/init(coder:)","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/init(configuration:discoveryEvent:)","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/init(nibName:bundle:)"],"anchor":"Initializers","generated":true},{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/navigationDelegate","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/preferredStatusBarStyle","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/sharingDelegate","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/userAnalyticsDelegate","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/webAnalyticsDelegate"]},{"identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/checkoutDidReceive(paymentError:)","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/checkoutDidReceive(paymentNonce:)","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/viewWillAppear(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/eventDetailsNavigationController(eventIdentifier:internalTestingKeys:marketDomain:customFont:)"],"anchor":"Type-Methods"}],"variants":[{"paths":["\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase"]]},"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(cs)UINavigationController"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)ASWebAuthenticationPresentationContextProviding","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)NSCoding","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)NSObject","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s7CVarArgP","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s28CustomDebugStringConvertibleP","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s23CustomStringConvertibleP","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/SQ","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/SH","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)UIAppearanceContainer","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)UIContentContainer","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)UIFocusEnvironment","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)UIStateRestoring","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/5UIKit23UITraitChangeObservableP","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)UITraitEnvironment","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMPurchaseNavigationController","kind":"identifier"}]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"type":"aside","name":"Important","style":"important","content":[{"inlineContent":[{"text":"Do not dismiss instances of ","type":"text"},{"code":"TMPurchaseNavigationController","type":"codeVoice"},{"type":"text","text":". Doing so will result in memory leaks caused by retain cycles. Instances of "},{"code":"TMPurchaseNavigationController","type":"codeVoice"},{"text":" will dismiss themselves when instructed by users.","type":"text"}],"type":"paragraph"}]}],"kind":"content"}],"metadata":{"title":"TMPurchaseNavigationController","externalID":"c:@M@TicketmasterPurchase@objc(cs)TMPurchaseNavigationController","roleHeading":"Class","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMPurchaseNavigationController","kind":"identifier"}],"navigatorTitle":[{"text":"TMPurchaseNavigationController","kind":"identifier"}],"modules":[{"name":"TicketmasterPurchase"}],"role":"symbol"},"sections":[],"references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController/preferredStatusBarStyle":{"type":"topic","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"TMPurchaseNavigationController"},{"text":"has ","type":"text"},{"code":"lightContent","type":"codeVoice"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"preferredStatusBarStyle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIStatusBarStyle","preciseIdentifier":"c:@E@UIStatusBarStyle"}],"kind":"symbol","url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller\/preferredstatusbarstyle","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/preferredStatusBarStyle","navigatorTitle":[{"text":"preferredStatusBarStyle","kind":"identifier"}],"title":"preferredStatusBarStyle"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController/viewWillAppear(_:)":{"abstract":[],"url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller\/viewwillappear(_:)","role":"symbol","title":"viewWillAppear(_:)","navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/viewWillAppear(_:)","type":"topic"},"doc://com.ticketmaster.ios.TicketmasterPurchase/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)UIUserActivityRestoring"},"doc://com.ticketmaster.ios.TicketmasterPurchase/objc(pl)ASWebAuthenticationPresentationContextProviding":{"type":"unresolvable","title":"AuthenticationServices.ASWebAuthenticationPresentationContextProviding","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)ASWebAuthenticationPresentationContextProviding"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController/checkoutDidReceive(paymentNonce:)":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/checkoutDidReceive(paymentNonce:)","abstract":[{"type":"text","text":"Update checkout cart with an external payment nonce"}],"title":"checkoutDidReceive(paymentNonce:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkoutDidReceive"},{"text":"(","kind":"text"},{"text":"paymentNonce","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller\/checkoutdidreceive(paymentnonce:)","kind":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController/init(configuration:discoveryEvent:)":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/init(configuration:discoveryEvent:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TMPurchaseWebsiteConfiguration","preciseIdentifier":"c:@M@TicketmasterPurchase@objc(cs)TMPurchaseWebsiteConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"discoveryEvent"},{"kind":"text","text":": "},{"preciseIdentifier":"s:24TicketmasterDiscoveryAPI0B5EventV","text":"DiscoveryEvent","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[{"text":"A UIViewController that allows Ticketmaster Checkout","type":"text"}],"title":"init(configuration:discoveryEvent:)","url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller\/init(configuration:discoveryevent:)","kind":"symbol","role":"symbol","type":"topic"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController/init(nibName:bundle:)":{"type":"topic","abstract":[{"type":"text","text":"The "},{"code":"TMPurchaseNavigationController","type":"codeVoice"},{"text":" is designed to be created at runtime once the Event information is known (as part of the ","type":"text"},{"code":"TMPurchaseWebsiteConfiguration","type":"codeVoice"},{"type":"text","text":")"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"nibName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"bundle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSBundle","text":"Bundle","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller\/init(nibname:bundle:)","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/init(nibName:bundle:)","navigatorTitle":[{"text":"initWithNibName:bundle:","kind":"identifier"}],"title":"init(nibName:bundle:)"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController/sharingDelegate":{"abstract":[{"text":"Customized social sharing message","type":"text"}],"url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller\/sharingdelegate","role":"symbol","title":"sharingDelegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sharingDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TMPurchaseSharingDelegate","preciseIdentifier":"s:20TicketmasterPurchase25TMPurchaseSharingDelegateP"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/sharingDelegate","type":"topic"},"doc://com.ticketmaster.ios.TicketmasterPurchase/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)UIResponderStandardEditActions"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController/userAnalyticsDelegate":{"abstract":[{"text":"User behavior analytics","type":"text"}],"url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller\/useranalyticsdelegate","role":"symbol","title":"userAnalyticsDelegate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"userAnalyticsDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:20TicketmasterPurchase31TMPurchaseUserAnalyticsDelegateP","text":"TMPurchaseUserAnalyticsDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/userAnalyticsDelegate","type":"topic"},"doc://com.ticketmaster.ios.TicketmasterPurchase/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/SQ","title":"Swift.Equatable"},"doc://com.ticketmaster.ios.TicketmasterPurchase/objc(pl)UIStateRestoring":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring"},"doc://com.ticketmaster.ios.TicketmasterPurchase/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://com.ticketmaster.ios.TicketmasterPurchase/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://com.ticketmaster.ios.TicketmasterPurchase/objc(cs)UINavigationController":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(cs)UINavigationController","title":"UINavigationController"},"doc://com.ticketmaster.ios.TicketmasterPurchase/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://com.ticketmaster.ios.TicketmasterPurchase/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController":{"abstract":[{"type":"text","text":"A navigation controller (view controller) that allows users to select and purchase tickets to a Ticketmaster Event."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TMPurchaseNavigationController"}],"url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller","title":"TMPurchaseNavigationController","navigatorTitle":[{"kind":"identifier","text":"TMPurchaseNavigationController"}]},"doc://com.ticketmaster.ios.TicketmasterPurchase/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.ticketmaster.ios.TicketmasterPurchase/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController/checkoutDidReceive(paymentError:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkoutDidReceive","kind":"identifier"},{"kind":"text","text":"("},{"text":"paymentError","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"type":"topic","title":"checkoutDidReceive(paymentError:)","url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller\/checkoutdidreceive(paymenterror:)","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/checkoutDidReceive(paymentError:)","abstract":[{"type":"text","text":"Update checkout cart with an external payment error"}],"kind":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController/webAnalyticsDelegate":{"abstract":[{"text":"Server\/website performance analytics","type":"text"}],"url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller\/webanalyticsdelegate","role":"symbol","title":"webAnalyticsDelegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webAnalyticsDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TMPurchaseWebAnalyticsDelegate","preciseIdentifier":"s:20TicketmasterPurchase30TMPurchaseWebAnalyticsDelegateP"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/webAnalyticsDelegate","type":"topic"},"doc://com.ticketmaster.ios.TicketmasterPurchase/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)NSObject"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController/init(coder:)":{"abstract":[{"text":"The ","type":"text"},{"code":"TMPurchaseNavigationController","type":"codeVoice"},{"text":" is designed to be created at runtime once the Event information is known (as part of the ","type":"text"},{"code":"TMPurchaseWebsiteConfiguration","type":"codeVoice"},{"text":")","type":"text"}],"url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller\/init(coder:)","role":"symbol","title":"init(coder:)","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/init(coder:)","type":"topic"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController/eventDetailsNavigationController(eventIdentifier:internalTestingKeys:marketDomain:customFont:)":{"type":"topic","abstract":[{"text":"Convenience function for creating an Event Details Page with simply an identifier","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eventDetailsNavigationController","kind":"identifier"},{"kind":"text","text":"("},{"text":"eventIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"internalTestingKeys","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"marketDomain"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TicketmasterFoundation@E@MarketDomain","kind":"typeIdentifier","text":"MarketDomain"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"customFont"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterPurchase@objc(cs)TMPurchaseNavigationController","text":"TMPurchaseNavigationController"}],"kind":"symbol","url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller\/eventdetailsnavigationcontroller(eventidentifier:internaltestingkeys:marketdomain:customfont:)","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/eventDetailsNavigationController(eventIdentifier:internalTestingKeys:marketDomain:customFont:)","title":"eventDetailsNavigationController(eventIdentifier:internalTestingKeys:marketDomain:customFont:)"},"doc://com.ticketmaster.ios.TicketmasterPurchase/objc(pl)UIContentContainer":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer","type":"unresolvable"},"doc://com.ticketmaster.ios.TicketmasterPurchase/s7CVarArgP":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.ticketmaster.ios.TicketmasterPurchase/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://com.ticketmaster.ios.TicketmasterPurchase/SH":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"role":"collection","type":"topic","title":"TicketmasterPurchase","kind":"symbol","url":"\/documentation\/ticketmasterpurchase","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","abstract":[]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController/navigationDelegate":{"abstract":[{"text":"User navigation outside of the TicketmasterPurchase SDK","type":"text"}],"url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller\/navigationdelegate","role":"symbol","title":"navigationDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"navigationDelegate","kind":"identifier"},{"kind":"text","text":": "},{"text":"TMPurchaseNavigationDelegate","kind":"typeIdentifier","preciseIdentifier":"s:20TicketmasterPurchase28TMPurchaseNavigationDelegateP"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/navigationDelegate","type":"topic"},"doc://com.ticketmaster.ios.TicketmasterPurchase/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://com.ticketmaster.ios.TicketmasterPurchase/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://com.ticketmaster.ios.TicketmasterPurchase/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"TMPurchaseNavigationController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"TMPurchaseNavigationController","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"TMPurchaseNavigationController","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/preferredStatusBarStyle"],"title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/init(coder:)","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/init(nibName:bundle:)","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/viewWillAppear(_:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(cs)UINavigationController"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPurchaseNavigationController"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UINavigationController","kind":"typeIdentifier","text":"UINavigationController"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController~1preferredStatusBarStyle\/title","value":"preferredStatusBarStyle","op":"replace"},{"value":[{"text":"preferredStatusBarStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController~1preferredStatusBarStyle\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"viewWillAppear:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController~1viewWillAppear(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController~1init(nibName:bundle:)\/title","value":"initWithNibName:bundle:"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController~1init(nibName:bundle:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithNibName:bundle:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/title","op":"replace","value":"TMPurchaseNavigationController"},{"value":[{"kind":"identifier","text":"TMPurchaseNavigationController"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/fragments"},{"value":[{"kind":"identifier","text":"TMPurchaseNavigationController"}],"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController~1init(coder:)\/title","value":"initWithCoder:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController~1init(coder:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}