{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPurchase"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ticketmasterpurchase\/tmpurchase"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ticketmasterpurchase\/tmpurchase"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)NSObject","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s7CVarArgP","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s28CustomDebugStringConvertibleP","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s23CustomStringConvertibleP","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/SQ","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A class that stores the global configuration for the TicketmasterPurchase SDK."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPurchase"}],"title":"TMPurchase","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@TicketmasterPurchase@objc(cs)TMPurchase","modules":[{"name":"TicketmasterPurchase"}],"navigatorTitle":[{"kind":"identifier","text":"TMPurchase"}]},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/apiKey","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/brandColor","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/disableUFCLoginManagement","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/dismissUponCompletion","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/environment","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/useDebugAnalytics","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/version"]},{"title":"Type Properties","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/shared"]}],"references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/SQ"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchase/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/ticketmasterpurchase\/tmpurchase\/init"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchase/environment":{"role":"symbol","title":"environment","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"environment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConnectionEnvironment","preciseIdentifier":"s:22TicketmasterFoundation21ConnectionEnvironmentO"}],"abstract":[{"type":"text","text":"The Ticketmaster Host Environment marching the API key provided"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/environment","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchase\/environment"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchase/disableUFCLoginManagement":{"role":"symbol","title":"disableUFCLoginManagement","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableUFCLoginManagement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Disable UFC login management within the "},{"type":"codeVoice","code":"Purchase SDK"},{"type":"text","text":", the integrating App will handle UFC calls made by the website"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/disableUFCLoginManagement","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchase\/disableufcloginmanagement"},"doc://com.ticketmaster.ios.TicketmasterPurchase/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/SH"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchase/dismissUponCompletion":{"role":"symbol","title":"dismissUponCompletion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissUponCompletion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Automatically dismiss "},{"type":"codeVoice","code":"TMPurchaseNavigationController"},{"type":"text","text":" upon completion of purchase operations (purchase, cancel, etc)"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/dismissUponCompletion","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchase\/dismissuponcompletion"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchase":{"role":"symbol","title":"TMPurchase","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPurchase"}],"abstract":[{"type":"text","text":"A class that stores the global configuration for the TicketmasterPurchase SDK."}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TMPurchase"}],"url":"\/documentation\/ticketmasterpurchase\/tmpurchase"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchase/brandColor":{"role":"symbol","title":"brandColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"brandColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"The color that will be applied to UI elements in instances of "},{"type":"codeVoice","code":"TMPurchaseNavigationController"},{"type":"text","text":". Defaults to "},{"type":"codeVoice","code":"0x009CDE"},{"type":"text","text":", otherwise known as “Ticketmaster blue”."}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/brandColor","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchase\/brandcolor"},"doc://com.ticketmaster.ios.TicketmasterPurchase/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s7CVarArgP"},"doc://com.ticketmaster.ios.TicketmasterPurchase/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(pl)NSObject"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchase/apiKey":{"role":"symbol","title":"apiKey","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The API key to use with Ticketmaster’s Discovery API. Defaults to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/apiKey","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchase\/apikey"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchase/useDebugAnalytics":{"role":"symbol","title":"useDebugAnalytics","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"useDebugAnalytics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A flag that indicates whether the Purchase SDK should put analytics into a debug bucket"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/useDebugAnalytics","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchase\/usedebuganalytics"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"role":"collection","title":"TicketmasterPurchase","abstract":[],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase"},"doc://com.ticketmaster.ios.TicketmasterPurchase/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(cs)NSObject"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchase/shared":{"role":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TMPurchase","preciseIdentifier":"c:@M@TicketmasterPurchase@objc(cs)TMPurchase"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/shared","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchase\/shared"},"doc://com.ticketmaster.ios.TicketmasterPurchase/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s28CustomDebugStringConvertibleP"},"doc://com.ticketmaster.ios.TicketmasterPurchase/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/s23CustomStringConvertibleP"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchase/version":{"role":"symbol","title":"version","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"version"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/version","kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchase\/version"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"TMPurchase"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TMPurchase"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TMPurchase"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/init"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPurchase"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchase\/title","value":"TMPurchase"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchase\/fragments","value":[{"kind":"identifier","text":"TMPurchase"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}